### ISSUE TITLE
RuntimeException: Already decorating

### ISSUE THREAD

**Issue by Dominance** [micdoodle8/Galacticraft#1249]
http://pastebin.com/LQ6EcaUR 

Using version 1.7-3.0.6.232

**Comment by DraksterAU** [comment]
Hi @radfast 
Sorry to bother you man, but if I'm using 1.7-3.0.12.404 will this occur? I'm setting this crash after Gregtech is installed whenever I try to rocket between dimensions:

I know this is not your problem - just asking for some advice, as I use More Planets mod and am stuck on that version :(

Time: 1/16/16 11:52 PM
Description: Ticking entity

java.lang.RuntimeException: Already decorating!!
        at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:24)
        at stevekung.mods.moreplanets.planets.siriusb.worldgen.ChunkProviderSiriusB.decoratePlanet(ChunkProviderSiriusB.java:268)
        at stevekung.mods.moreplanets.planets.siriusb.worldgen.ChunkProviderSiriusB.func_73153_a(ChunkProviderSiriusB.java:284)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:408)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1197)
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:293)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:199)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:167)
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:304)
        at net.minecraft.world.World.func_72964_e(World.java:751)
        at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:234)
        at stevekung.mods.moreplanets.planets.kapteynb.entities.EntityTier8Rocket.func_70071_h_(EntityTier8Rocket.java:89)
        at net.minecraft.world.World.func_72866_a(World.java:2658)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
        at net.minecraft.world.World.func_72870_g(World.java:2607)
        at net.minecraft.world.World.func_72939_s(World.java:2423)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:24)
        at stevekung.mods.moreplanets.planets.siriusb.worldgen.ChunkProviderSiriusB.decoratePlanet(ChunkProviderSiriusB.java:268)
        at stevekung.mods.moreplanets.planets.siriusb.worldgen.ChunkProviderSiriusB.func_73153_a(ChunkProviderSiriusB.java:284)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:408)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1197)
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:293)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:199)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:167)
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:304)
        at net.minecraft.world.World.func_72964_e(World.java:751)
        at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:234)
        at stevekung.mods.moreplanets.planets.kapteynb.entities.EntityTier8Rocket.func_70071_h_(EntityTier8Rocket.java:89)
        at net.minecraft.world.World.func_72866_a(World.java:2658)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
        at net.minecraft.world.World.func_72870_g(World.java:2607)

-- Entity being ticked --
Details:
        Entity Type: MorePlanet.Tier8Rocket (stevekung.mods.moreplanets.planets.kapteynb.entities.EntityTier8Rocket)
        Entity ID: 113
        Entity Name: entity.MorePlanet.Tier8Rocket.name
        Entity's Exact location: -241.50, 68.00, -251.50
        Entity's Block location: World: (-242,68,-252), Chunk: (at 14,4,4 in -16,-16; contains blocks -256,0,-256 to -241,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
        Entity's Momentum: 0.00, 0.00, 0.00

**Comment by SteveKunG** [comment]
What? I already fix that! Maybe you should be re-create new chunk in your map.

**Comment by DraksterAU** [comment]
Thanks for the advice Steve, lucky we can - no one has rockets yet!! :)

Will report back when I try

**Comment by radfast** [comment]
Hi @DraksterAU - seems like this is a **More Planets** worldgen issue on SiriusB.

I'm totally happy for you + @SteveKunG to use this thread as a place to discuss it, that's OK.

If you find something in Galacticraft core or API needs fixing, then please re-open this issue.

**Comment by denwd** [comment]
Good evening, a solution was found?
Fashion latest versions (More Planet + Galacticraft)

**Comment by SteveKunG** [comment]
@denwd Nibiru world gen was fixed in 1.3.0 Pre-7

**Comment by vadimyer** [comment]
@SteveKunG Mars satellites (Phobos, Deimos) suffer from the same "already decorating" issue. And Sirius B on Pre-7, too.

**Comment by DraksterAU** [comment]
@SteveKunG I tried Pre7, it didn't improve anything for me.

Also ... with GC + More Planets installed my server slows down by ...90% or so..... I get timeouts loading dimensions regardless of whether or not they are GC.

Had to kill GC + more planets entirely... but we did a server reset so I'm all good w/o it for now.

**Comment by SteveKunG** [comment]
@vadimyer @DraksterAU Mars moon issue was fixed in 1.3.0 (Full Release).

@DraksterAU Your server issue I think its cause by all space dimension already loaded.
