### ISSUE TITLE
Crashes when opening minecraft world with G.C

### ISSUE THREAD

**Issue by spikeydude** [micdoodle8/Galacticraft#1254]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 16/11/14 8:22 PM
Description: Ticking block entity

io.netty.handler.codec.EncoderException: java.lang.NullPointerException
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
    at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
    at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
    at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.sendToAllAround(GalacticraftChannelHandler.java:93)
    at micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced.func_145845_h(TileEntityAdvanced.java:61)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NullPointerException
    at micdoodle8.mods.galacticraft.core.network.NetworkUtil.encodeData(NetworkUtil.java:173)
    at micdoodle8.mods.galacticraft.core.network.PacketDynamic.encodeInto(PacketDynamic.java:70)
    at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.encodeInto(GalacticraftChannelHandler.java:39)
    at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.encodeInto(GalacticraftChannelHandler.java:15)
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51)
    at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
    ... 17 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
    at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
    at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
    at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.sendToAllAround(GalacticraftChannelHandler.java:93)
    at micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced.func_145845_h(TileEntityAdvanced.java:61)

-- Block entity being ticked --
Details:
    Name: Dummy Block // micdoodle8.mods.galacticraft.core.tile.TileEntityMulti
    Block type: ID #195 (tile.dummyblock // micdoodle8.mods.galacticraft.core.blocks.BlockMulti)
    Block data value: 2 / 0x2 / 0b0010
    Block location: World: (-2,96,171), Chunk: (at 14,6,11 in -1,10; contains blocks -16,0,160 to -1,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #195 (tile.dummyblock // micdoodle8.mods.galacticraft.core.blocks.BlockMulti)
    Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: Space
    All players: 1 total; [GCEntityPlayerMP['nath1015'/332, l='Space', x=3.95, y=66.00, z=154.54]]
    Chunk stats: ServerChunkCache: 714 Drop: 0
    Level seed: 6567073259393987990
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-1,64,260), Chunk: (at 15,4,4 in -1,16; contains blocks -16,0,256 to -1,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 414301 game time, 231950 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 25983 (now: false), thunder time: 32243 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 164953656 bytes (157 MB) / 404348928 bytes (385 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 13, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 6 mods loaded, 6 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1236} [Forge Mod Loader](forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1236} [Minecraft Forge](forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftCore{3.0.6} [Galacticraft Core](GalacticraftCore-1.7-3.0.6.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftMars{3.0.6} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.6.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [GCEntityPlayerMP['nath1015'/332, l='Space', x=3.95, y=66.00, z=154.54]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Caasin** [comment]
I keep getting this every time I try and create a new world. And When i join a world that is already created it works until i try and go into space. Once i crash from trying to go int space i can never go o that world again. Idk whats going on, im not a programmar so i dnt knw anything about what this thing is saying. I have the lastest versions of galacticraft core, galaticraft planeets and micdoodlecore all from the dev website.
Crash report:
Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 04/03/16 10:29 PM
Description: Exception getting block type in world

java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.util.WorldUtil.otherModGenerate(IILnet/minecraft/world/World;Lnet/minecraft/world/chunk/IChunkProvider;Lnet/minecraft/world/chunk/IChunkProvider;)V
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.getTopBlockCoord(WorldProviderSurfaceBOP.java:41)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.func_76566_a(WorldProviderSurfaceBOP.java:14)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at WorldServerOF.func_72963_a(WorldServerOF.java:80)
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at WorldServerOF.<init>(WorldServerOF.java:69)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-181,64,2), Chunk: (at 11,4,2 in -12,0; contains blocks -192,0,0 to -177,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.getTopBlockCoord(WorldProviderSurfaceBOP.java:41)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.func_76566_a(WorldProviderSurfaceBOP.java:14)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at WorldServerOF.func_72963_a(WorldServerOF.java:80)

-- Affected level --
Details:
	Level name: LOL
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 55 Drop: 0
	Level seed: -3153527735134308186
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at WorldServerOF.<init>(WorldServerOF.java:69)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2857350064 bytes (2724 MB) / 3207856128 bytes (3059 MB) up to 3207856128 bytes (3059 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.2.0
	LaunchWrapper: 40 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx3G -Xms3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_C1 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
	UCHIJAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAA	BuildMod{v1.0} [Build Mod] (CoroUtil-1.7.10.jar) 
	UCHIJAA	CoroAI{v1.0} [CoroAI] (CoroUtil-1.7.10.jar) 
	UCHIJAA	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.7.10.jar) 
	UCHIJAA	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.7.10.jar) 
	UCHIJAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAA	EnderStorage{1.4.7.32} [EnderStorage] (EnderStorage-1.7.10-1.4.7.32-universal.jar) 
	UCHIJAA	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
	UCHIJAA	ExtraUtilities{1.1.0k} [Extra Utilities] (Extra-Utilities-Mod-1.7.10(1).jar) 
	UCHIJAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.446.jar) 
	UCHIJAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.446.jar) 
	UCHIJAA	GraveStone{2.9.0} [GraveStone] (Gravestone-Mod-1.7.10.jar) 
	UCHIJAA	iChunUtil{4.1.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHIJAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	UCHIJAA	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAA	Morph{0.9.2} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHIJAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UCHIJAA	telepads{1.6.4 v5} [Teleportation Pads] (TelePads-Mod-1.7.10.jar) 
	UCHIJAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (Thermal-Expansion-Mod-1.7.10(1).jar) 
	UCHIJAA	weather2{v2.3.11} [Localized Weather & Storms] (weather2-1.7.10-2.3.10.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.3-112
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by radfast** [comment]
> I have the lastest versions of core, GC planets and micdoodlecore all from the dev website.

Not sure what you mean by "the dev website".

Please say the actual filenames of the mods you are using.

Please also provide a complete listing / screenshot of your ```/mods``` folder.

**Comment by Caasin** [comment]
It's OK. I needed a micdoodle update so im good to go now. And for the
first time in forever, I know where and how to ask for mod help. Thanks!
