### ISSUE TITLE
Galacticraft Planets 1.7.10 Crash Report

### ISSUE THREAD

**Issue by RyanNut123321** [micdoodle8/Galacticraft#1285]
Here is my crash report, I do not know what happened.
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 11/28/14 9:15 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/planets/asteroids/tile/TileEntityShortRangeTelepad
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/planets/asteroids/tile/TileEntityShortRangeTelepad
    at micdoodle8.mods.galacticraft.planets.asteroids.blocks.AsteroidBlocks.initBlocks(AsteroidBlocks.java:38)
    at micdoodle8.mods.galacticraft.planets.asteroids.AsteroidsModule.preInit(AsteroidsModule.java:99)
    at micdoodle8.mods.galacticraft.planets.PlanetsProxy.preInit(PlanetsProxy.java:18)
    at micdoodle8.mods.galacticraft.planets.PlanetsProxyClient.preInit(PlanetsProxyClient.java:18)
    at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.preInit(GalacticraftPlanets.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityShortRangeTelepad
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 42 more
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/tile/TileEntityElectricBlock
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:180)
    ... 44 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.core.tile.TileEntityElectricBlock
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:99)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 48 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 142479392 bytes (135 MB) / 427208704 bytes (407 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.18.1180 Minecraft Forge 10.13.0.1180 9 mods loaded, 9 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.18.1180} [Forge Mod Loader](forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.0.1180} [Minecraft Forge](forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    camping{2.1} [The Camping Mod 2](Camping-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    flansmod{4.7.0} [Flan's Mod](Flans Mod-1.7.10-4.7.0.jar) Unloaded->Constructed->Pre-initialized
    GalacticraftCore{3.0.5} [Galacticraft Core](Galacticraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    GalacticraftMars{3.0.0} [Galacticraft Planets](Galacticraft-Planets-Mod-1.7.10.jar) Unloaded->Constructed->Errored
    ReiMinimap{1.7.10} [Rei's Minimap](ReiMinimap-1.7.10-3.6.jar) Unloaded->Constructed->Pre-initialized

**Comment by xXEnglishXx** [comment]
please help me, i am with the same versions of galacticraftcore 1.7-3.0.12.464 and galacticraft planets 1.7-3.0.12.464. look:

UCE	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.464.jar) U= Unloaded. C= Constructed, E=Errored

**Comment by dj3520** [comment]
@xXEnglishXx please make a new issue and read [the posting new issues guidelines](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md#posting-new-issues---guidelines)
