### ISSUE TITLE
JPEG library broken

### ISSUE THREAD

**Issue by Baughn** [micdoodle8/Galacticraft#1321]
It's not your fault, but I'm seeing crashes when initializing GalactiCraftCore::jpgWriter due to broken OpenJDK builds:

cpw.mods.fml.common.LoaderException: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Ljava/lang/Class;Ljava/lang/Class;)V
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
        at cpw.mods.fml.common.Loader.serverStarted(Loader.java:753)
        at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Ljava/lang/Class;Ljava/lang/Class;)V
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.<clinit>(JPEGImageWriter.java:186)
        at com.sun.imageio.plugins.jpeg.JPEGImageWriterSpi.createWriterInstance(JPEGImageWriterSpi.java:96)
        at javax.imageio.spi.ImageWriterSpi.createWriterInstance(ImageWriterSpi.java:351)
        at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:843)
        at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:827)
        at micdoodle8.mods.galacticraft.core.GalacticraftCore.serverInit(GalacticraftCore.java:324)

Can you use PNG instead? Alternately, can you make that a config option?

**Comment by radfast** [comment]
OK thanks we can take a look at that library, as it seems this is potentially an issue for any Linux-based server running Galacticraft

**Comment by halvors** [comment]
When will this be done?

**Comment by EzerArch** [comment]
> When will this be done?

I think the classical "When it's done" applies here. :)

**Comment by radfast** [comment]
I've discussed this with micdoodle8 and we don't have a good solution right now:
* we ideally do not want to distribute a third party library with Galacticraft
* as far as we can see, none of the libraries used by vanilla Minecraft offers any alternative JPG encoding solution
* as it's a known bug in the OpenJDK, our assumption is that people are currently working on fixing it
* it's also an issue which AFAIAA servers can workaround simply by using the Sun / Oracle JRE

We will keep an eye on the situation, if it becomes clear that a category of servers has no good solution for this and it's affecting a large number of servers then we will think again.

**Comment by Baughn** [comment]
It's easy to fix server-side, as you say; use a non-broken version of Java.

It's more of a concern for me client-side, since not all players are equally capable at running their systems. They may have a broken OpenJDK install; they will blame me, Galacticraft or both, but will at any rate not be able to fix their system without serious hand-holding.

I don't have a good solution either, if distributing the library is out. Maybe some code change such that GC at least doesn't crash? But how playable is it without the JPEGs?

**Comment by radfast** [comment]
OK we can probably catch the crash and play without the JPEGs.  If the server does not send the JPEG to the client then the client will use the default Overworld image, so Display screens and rocket takeoff will look a bit sucky, that's all.

I'll look at this next time I update that code, which will be soon - there are other open issues with it as well.

**Comment by Baughn** [comment]
How large are these images, really? How often are they sent? Could they be cached?

I ask because another option would be to send them uncompressed, as bitmaps. It's not my preference... but it's an option.

**Comment by radfast** [comment]
Again that's asking for substantial code changes in the mod, including the networking code - so servers/clients would not be compatible before and after the change - to fix a problem which is really not our problem in the first place.  Given that OpenJDK is open source, it would probably take less time for me just to go fix the bug in its JPEG library (but I assume other people are already working on that?)

For now, I am happy to include code in Galacticraft to trap the error so there is no crash, that's totally reasonable.
