### ISSUE TITLE
NPE in onPlayerClicked when using new TC 4.2.2.0

### ISSUE THREAD

**Issue by christianvdstap** [micdoodle8/Galacticraft#1339]
Hello

I was upgrading the kirara servers and it seems that the new Thaumcraft makes the onPlayerClickedd handler sad and it now throws a nullpointer exception. Reporting the issue here as the NPE is occuring inside galacticraft code.

Galacticraft build 248
Thaumcraft 4.2.2.0
Forge build 1272

Exception:

[09:51:25] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@5902e061:
java.lang.NullPointerException
        at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.onPlayerClicked(EventHandlerGC.java:167) ~[EventHandlerGC.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_75_EventHandlerGC_onPlayerClicked_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) [ForgeEventFactory.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:140) [mx.class:?]
        at thaumcraft.common.entities.ai.interact.AIUseItem.click(AIUseItem.java:156) [AIUseItem.class:?]
        at thaumcraft.common.entities.ai.interact.AIUseItem.func_75246_d(AIUseItem.java:99) [AIUseItem.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103) [uj.class:?]
        at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540) [sw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) [sw.class:?]
        at thaumcraft.common.entities.golems.EntityGolemBase.func_70636_d(EntityGolemBase.java:349) [EntityGolemBase.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) [sw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2070) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2034) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1887) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by radfast** [comment]
It's a bug in Thaumcraft code.  They are triggering Forge player events with a null player, from the part of the Golem code which simulates player left-clicking.  In my opinion they should not be doing that, it's likely to crash quite a few other mods - they should either use a fake player or not trigger the Forge player events at all, that's their choice.

But anyhow it's easy enough to add a workaround for it in Galacticraft, so I have done that: this crash should be fixed in GC 3.0.6.251.
