### ISSUE TITLE
Galacticraft Crash 

### ISSUE THREAD

**Issue by dariusc93** [micdoodle8/Galacticraft#1369]
There is a crash related to https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java#L325 when attempting to run GC on a server. This is likely due to client code running. Possibly add a check to see if it is a server or remove that line(s) of code (if its not needed)?

Version: 3.0.6.248

Stacktrace:

Caused by: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Ljava/lang/Class;Ljava/lang/Class;)V
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.<clinit>(JPEGImageWriter.java:186)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriterSpi.createWriterInstance(JPEGImageWriterSpi.java:96)
	at javax.imageio.spi.ImageWriterSpi.createWriterInstance(ImageWriterSpi.java:351)
	at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:843)
	at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:827)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.serverInit(GalacticraftCore.java:325)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:752)
	... 3 more

**Comment by dariusc93** [comment]
@radfast It was done with openjdk (jre 8) and yea youre right, it looks like it is because its not using oracle jre.

**Comment by radfast** [comment]
Thanks for coming back, as suspected it's due to a bug in OpenJDK, see #1321 
Is there any way you can use the Oracle JRE?

**Comment by Baughn** [comment]
Due to licensing issues, the Oracle JRE is not included in the package repositories for a lot of Linux distributions. Installing it would be an extra step.

**Comment by dariusc93** [comment]
It is not a problem to use Oracle JRE. Normally for quick deployment I rely on openjdk but for ubuntu, there is a ppa to install oracle jre.
