### ISSUE TITLE
Sealed Kinesis Pipes (from Buildcraft)

### ISSUE THREAD

**Issue by Cracks777** [micdoodle8/Galacticraft#1393]
when i place down a golden or stone kinesis sealer it boots me off the server and when i reconnect the sealer is there but it is invisible to other players? not sure what is going on.

**Comment by radfast** [comment]
Please post:
* screenshot
* fml-client-latest.log
* server log for the time when you got booted

Also check you are using the latest version of Galacticraft

**Comment by Cracks777** [comment]
[07:29:59] [Server thread/ERROR] [FML/]: A TileEntity type buildcraft.transport.TileGenericPipe has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class buildcraft.transport.TileGenericPipe is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:84) ~[aor.class:?]
	at buildcraft.transport.TileGenericPipe.func_145841_b(TileGenericPipe.java:263) ~[TileGenericPipe.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:391) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:218) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:418) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1052) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]

**Comment by Cracks777** [comment]
there is the part of the server log, nothing shows on my client, i can find a way to post complete log if needed but it wouldnt let me paste it to pastebin as its too large. the block shows its from galacticraft but the error is coming from buildcraft? should i post this there?

**Comment by radfast** [comment]
oh!  you are using a Sealed Kinesis Pipe?  OK, that's a Galacticraft bug not a Buildcraft issue.  We'll look at this.

Please tell me which exact versions of Galacticraft and Buildcraft you are using, so I can test the same as you.

**Comment by Cracks777** [comment]
BuildCraft 6.3.1 
buildcraft-compat-6.3.1

GalacticraftCore-1.7-3.0.7.255
Galacticraft-Planets-1.7-3.0.7.255
MicdoodleCore-1.7-3.0.7.255

**Comment by Cracks777** [comment]
![before](https://cloud.githubusercontent.com/assets/10608111/5822722/f133acca-a09b-11e4-9cb8-b830f16f256d.jpg)


![after](https://cloud.githubusercontent.com/assets/10608111/5822724/f88b88a8-a09b-11e4-95fc-bb8a94b21b9c.jpg)

![after rejoin](https://cloud.githubusercontent.com/assets/10608111/5822725/fb2d11b2-a09b-11e4-9325-1320b7e84057.jpg)


![other player](https://cloud.githubusercontent.com/assets/10608111/5822729/037c23a8-a09c-11e4-8eb9-758618c3394d.jpg)

**Comment by radfast** [comment]
Plenty of info, thank you.  We will look at this and I hope find a solution in the next couple of days, I'll post any update here.

**Comment by Cracks777** [comment]
ok thanks

**Comment by Cracks777** [comment]
any news on a fix for this?

**Comment by Cracks777** [comment]
Any Fix for this?

**Comment by micdoodle8** [comment]
Hey, can you test with the latest build of Galacticraft and Buildcraft? Seems as though I'm able to place them without issue:

![](http://i.imgur.com/d7pT9Q5.png)

**Comment by micdoodle8** [comment]
Until more information comes up, this will be closed.

**Comment by radfast** [comment]
(Note to Cracks777: an invisibility issue happens when a 'smart' block - so here, a Buildcraft pipe - did not finish loading its tile entity.  So ... the invisibility you were seeing is a normal consequence of the issue in the log.)

**Comment by radfast** [comment]
See also:   https://github.com/BuildCraft/BuildCraft/issues/2399   where asiekierka says this was fixed in Buildcraft, so seems like it may have been a BC bug all along.

We have not recently changed the Galacticraft part of a Sealed Kinesis Pipe.
