### ISSUE TITLE
Non Fatal Tile Entity Exception with BC 6.3.1

### ISSUE THREAD

**Issue by ianc1215** [micdoodle8/Galacticraft#1414]
I have no idea what is causing this but my FML client-latest.log 87MB and full of this error repeating.

```
[06:08:01] [Server thread/ERROR] [FML/]: A TileEntity type buildcraft.transport.TileGenericPipe has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class buildcraft.transport.TileGenericPipe is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
	at buildcraft.transport.TileGenericPipe.func_145841_b(TileGenericPipe.java:263) ~[TileGenericPipe.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:181) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[06:08:01] [Server thread/INFO] [OpenEye/]: openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write, skipping java.lang.RuntimeException: class buildcraft.transport.TileGenericPipe is missing a mapping! This is a bug!
```

My guess is its an issue with the recent changes to the BC API. Can you please investigate this?

Oh, yeah also this only happens when I am in a Galacticraft dimension, overworld and everywhere else is fine. No errors.

**Comment by radfast** [comment]
It could be related to #1393.  In your Galacticraft dimension, are you using any Sealed versions of Buildcraft item pipes or Kinesis pipes?

If it's not that, then my guess is it's not a Galacticraft issue at all - it's just a coincidence that you have the block causing the issue in your space base but not in the Overworld - so have a think about any blocks which it could be.  (If possible, use Creative mode to build a copy of your space base, or the machines in it, on the Overworld until the problem comes up.)

Note: it could be a block from Buildcraft or a block from any other mod which interacts with Buildcraft, most likely another tech mod for example EnderIO.

**Comment by ianc1215** [comment]
Here are the versions of the mods that apply.

Forge 10.13.2.1291

BuildCraft 6.3.3 
buildcraft-compat-6.3.1

GalacticraftCore-1.7-3.0.8.257
Galacticraft-Planets-1.7-3.0.8.257
MicdoodleCore-1.7-3.0.8.257

**Comment by ianc1215** [comment]
No I am in creative mode just walking around.

**Comment by ianc1215** [comment]
No machines, no bases, heck not even a space suit. Just me and lunar surface.

**Comment by radfast** [comment]
hmm, maybe in that case the problem is because you, the player, are __not__ on the Overworld.  So something in your Overworld base works OK if you are there, but not if you go away.

And I notice it says transportpipe, so it will be an item pipe not power.  As well as Buildcraft pipes, look also at any other mods which have things like Buildcraft pipes.

**Comment by ianc1215** [comment]
I will try placing BC + GC in a separate runtime and see if I can duplicate the issue.

**Comment by radfast** [comment]
OK, sounds like you know what you are doing!  Anything you can do to narrow down the cause or show me exactly how to duplicate it, will be helpful.

**Comment by ianc1215** [comment]
<<< Is IT guy and Tech Support

**Comment by ianc1215** [comment]
Also picking though the log files I found these.

```
[06:58:21] [Client thread/WARN] [BuildCraft/]: Detected pipe with unknown key (null). Did you remove a buildcraft addon?
[06:58:21] [Client thread/WARN] [BuildCraft/]: Pipe failed to initialize at {0},{1},{2}, deleting
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.transport.TileGenericPipe.afterStateUpdated(TileGenericPipe.java:1023)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.core.network.PacketTileState.applyStates(PacketTileState.java:62)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.core.network.PacketHandler.channelRead0(PacketHandler.java:72)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.core.network.PacketHandler.channelRead0(PacketHandler.java:27)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

and this...

```
[06:58:21] [Client thread/WARN] [BuildCraft/]: Detected pipe with unknown key (null). Did you remove a buildcraft addon?
[06:58:21] [Client thread/WARN] [BuildCraft/]: Pipe failed to initialize at {0},{1},{2}, deleting
[06:58:21] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
```

There has to be hundreds of them in the log file. Just from my test the log file is 124617 lines.

**Comment by radfast** [comment]
Do you have the issue without BuildcraftCompat?
Do you have the issue without Galacticraft (!) ?

**Comment by ianc1215** [comment]
I have not tried removing BC compat. I am pretty sure unless GC specific hooks into it nothing happens with that mod. At the moment MFR and NEI integration are the 2 big ones it hooks into.

**Comment by radfast** [comment]
and was this a newly generated Overworld, or only on the Moon again?

Please also post up your ```core.conf``` (or extracts) - I'm interested in the ore generation code, wondering if you have set it to generate Buildcraft pipes in place of ore on the Moon...

**Comment by ianc1215** [comment]
Yes every thing was brand new everything, i was testing out some worldgen in all dims.

I do have a lot of stuff set to generate on the moon. But each ID was hand entered after verifying with NEI. Its all ores.

**core.conf**

```
   # Enter IDs of other mods' ores here for Galacticraft to generate them on the Moon and other planets. Format is BlockName or BlockName:metadata. Use optional parameters at end of each line: /RARE /UNCOMMON or /COMMON for rarity in a chunk; /DEEP /SHALLOW or /BOTH for height; /SINGLE /STANDARD or /LARGE for clump size; /XTRARANDOM for ores sometimes there sometimes not at all.  /ONLYMOON or /ONLYMARS if wanted on one planet only.  If nothing specified, defaults are /COMMON, /BOTH and /STANDARD.  Repeat lines to generate a huge quantity of ores.
    S:"Other mods ores for GC to generate on the Moon and planets" <
	 166
	 167
	 168 /UNCOMMON /DEEP /SINGLE
	 169
	 233
	 234 /UNCOMMON /DEEP /SINGLE /XTRARANDOM
	 445 /UNCOMMON /BOTH /SINGLE
	 445:1 /UNCOMMON /BOTH /SINGLE
	 445:2 /UNCOMMON /BOTH /SINGLE
	 445:3 /UNCOMMON /BOTH /SINGLE
	 445:4 /UNCOMMON /BOTH /SINGLE
	 445:5 /UNCOMMON /BOTH /SINGLE
	 445:6 /UNCOMMON /BOTH /SINGLE
	 768 /COMMON /BOTH /LARGE
	 768:1
	 768:2
	 877
	 877:1
	 877:2 /UNCOMMON /BOTH /STANDARD
	 877:3
	 877:4 /UNCOMMON /DEEP /STANDARD
	 877:5 /RARE /DEEP /SINGLE
	 877:6 /RARE /DEEP /SINGLE
	 887 /UNCOMMON /DEEP /STANDARD
	 1109:7
	 1109:8
	 1109:9
	 1109:10
	 1109:11
	 1387:3
	 1387:4
	 1387:5
	 1447
	 1447:1
	 1447:2
	 1499:1 /UNCOMMON /BOTH /STANDARD
	 1507
	 1507:1
	 1507:2
	 1507:3
	 1507:4
	 1507:5
	 1535:7
	 1538:8
	 2218
	 2218:1
	 2218:2
	 7441 /RARE /DEEP /SINGLE /XTRARANDOM
     >
```

Legend;
166 - 196 = IC2 ores
233 - 234 = AE2 certus
445 - 445:6 = TC4 Shards and Ores
768 - 768:2 = Forestry Ores
877 - 877:6 = Therm Found Ores (CoFH stuff)
887 = Big Reactors Ore
1109:7 - 1109:11 = Railcraft Poor Ores
1387:3 - 1387:5 = Tinkers Construct Ores (no Gravel)
1447 - 1507:5 = Metalurgy 4 Ores

**Comment by radfast** [comment]
Does the problem happen without that oregen config, in a new world?

I strongly suspect the problem here is your ore IDs have changed since you first entered them.  That will happen in Minecraft 1.7 if you change any of the mods in your modpack (even maybe with a version update).

http://wiki.micdoodle8.com/wiki/SealableIDs#Seems_complicated.2C_why_do_I_have_to_do_this

**Comment by ianc1215** [comment]
That does not seem to be the case. I just verified all of them. All was accounted for.

**Comment by radfast** [comment]
Like I say, try a new world with out that oregen config, and I'm willing to bet that you won't see the issue.

**Comment by ianc1215** [comment]
I tried no oregen and the error did not show up. I added my oregen using qualified names instead of IDs and the errors is still not showing back up. Looks like that was the issue.

**Comment by radfast** [comment]
ok great you've fixed it, thanks for confirming
