### ISSUE TITLE
ClassCastException when building Galacticraft machines in a Logistics Pipes request table.

### ISSUE THREAD

**Issue by StarkRG** [micdoodle8/Galacticraft#1423]
This error happened as I attempted to craft a compressor in the request table, but it happens with any Galacticraft machines. Only the client crashes, the server doesn't seem to be affected.

Versions: Logistics Pipes 0.8.3.94 and Galacticraft 3.0.8.257

```
java.lang.ClassCastException: logisticspipes.blocks.crafting.FakePlayer cannot be cast to net.minecraft.client.entity.EntityPlayerSP
    at micdoodle8.mods.galacticraft.core.items.ItemBlockMachine.func_77622_d(ItemBlockMachine.java:101)
    at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:387)
    at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
    at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:110)
    at logisticspipes.pipes.PipeBlockRequestTable.getOutput(PipeBlockRequestTable.java:275)
    at logisticspipes.pipes.PipeBlockRequestTable.getResultForClick(PipeBlockRequestTable.java:300)
    at logisticspipes.gui.orderer.GuiRequestTable$1.getResultForClick(GuiRequestTable.java:108)
    at logisticspipes.utils.gui.HandelableSlot.getProvidedStack(HandelableSlot.java:23)
    at logisticspipes.utils.gui.DummyContainer.func_75144_a(DummyContainer.java:509)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
    at logisticspipes.utils.gui.LogisticsBaseGuiScreen.func_73864_a(LogisticsBaseGuiScreen.java:303)
    at logisticspipes.gui.orderer.GuiRequestTable.func_73864_a(GuiRequestTable.java:551)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at logisticspipes.utils.gui.LogisticsBaseGuiScreen.handleMouseInputSub(LogisticsBaseGuiScreen.java:241)
    at logisticspipes.gui.orderer.GuiRequestTable.handleMouseInputSub(GuiRequestTable.java:557)
    at logisticspipes.utils.gui.LogisticsBaseGuiScreen.func_146274_d(LogisticsBaseGuiScreen.java:236)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by radfast** [comment]
Thank you for raising, this will be fixed in next version.

You might want to also raise the issue with the LogisticsPipes guys, as can probably affect other mods as well.  The real problem here is that LogisticsPipes makes a "fake player", and clientside it ought to be an instance of a clientside player.  (Maybe they already thought about that and there's a reason for doing it they way they do, I do not know full details of their mod.)

**Comment by StarkRG** [comment]
I did, actually: https://github.com/RS485/LogisticsPipes/issues/566#issuecomment-72361830

**Comment by radfast** [comment]
Version 3.0.8.262 with this fix is now available at the usual place.
