### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by simonappleton** [micdoodle8/Galacticraft#1444]
Not sure if this is cause or symptom:

```04:29:12 java.lang.OutOfMemoryError: Java heap space
04:29:12 at micdoodle8.mods.galacticraft.core.wrappers.FlagData.saveFlagData(FlagData.java:114) ~[FlagData.class:?]
04:29:12 at micdoodle8.mods.galacticraft.core.dimension.SpaceRace.saveToNBT(SpaceRace.java:87) ~[SpaceRace.class:?]
04:29:12 at micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager.saveSpaceRaces(SpaceRaceManager.java:104) ~[SpaceRaceManager.class:?]
04:29:12 at micdoodle8.mods.galacticraft.core.dimension.WorldDataSpaceRaces.func_76187_b(WorldDataSpaceRaces.java:26) ~[WorldDataSpaceRaces.class:?]
04:29:12 at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:87) ~[azq.class:?]
04:29:12 at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:75) ~[azq.class:?]
04:29:12 at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:837) ~[mt.class:?]
04:29:12 at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:801) ~[mt.class:?]
04:29:12 at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) ~[MinecraftServer.class:?]
04:29:12 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) ~[MinecraftServer.class:?]
04:29:12 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
04:29:12 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
04:29:12  [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/./crash-reports/crash-2015-02-11_04.29.12-server.txt
04:29:12  [Server thread/INFO]: Stopping server
04:29:12  [Server thread/INFO]: Saving players
04:29:12  [Server thread/INFO]: Saving worlds
04:29:12  [Server thread/INFO]: Saving chunks for level 'world'/Overworld
04:30:08  [Server thread/ERROR]: Exception stopping the server
04:30:08 java.lang.OutOfMemoryError: Java heap space
04:30:08 at java.util.HashMap.newNode(HashMap.java:1734) ~[?:1.8.0_05]
04:30:08 at java.util.HashMap.putVal(HashMap.java:641) ~[?:1.8.0_05]
04:30:08 at java.util.HashMap.put(HashMap.java:611) ~[?:1.8.0_05]
04:30:08 at net.minecraft.nbt.NBTTagCompound.func_74774_a(SourceFile:60) ~[dh.class:?]
04:30:08 at micdoodle8.mods.galacticraft.core.wrappers.FlagData.saveFlagData(FlagData.java:113) ~[FlagData.class:?]
04:30:08 at micdoodle8.mods.galacticraft.core.dimension.SpaceRace.saveToNBT(SpaceRace.java:87) ~[SpaceRace.class:?]
04:30:08 at micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager.saveSpaceRaces(SpaceRaceManager.java:104) ~[SpaceRaceManager.class:?]
04:30:08 at micdoodle8.mods.galacticraft.core.dimension.WorldDataSpaceRaces.func_76187_b(WorldDataSpaceRaces.java:26) ~[WorldDataSpaceRaces.class:?]
04:30:08 at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:87) ~[azq.class:?]
04:30:08 at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:75) ~[azq.class:?]
04:30:08 at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:837) ~[mt.class:?]
04:30:08 at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:801) ~[mt.class:?]
04:30:08 at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) ~[MinecraftServer.class:?]
04:30:08 at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:350) ~[MinecraftServer.class:?]
04:30:08 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:480) [MinecraftServer.class:?]
04:30:08 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]```

**Comment by radfast** [comment]
Please give more details, like:
* is this on a server?
* how many players, how many SpaceRace teams?
* what are your JVM memory settings, can you fix this by giving Java more memory?
* does this happen every time or is it a one-off?

**Comment by simonappleton** [comment]
Hi

Apologies for lack of details!

Yes, on server. One player online, no SpaceRace teams (we haven't used it yet).

Memory allowance is adaptive (Creeperhost), so not sure.

So far a one-off, but there is a niggling memory leak on the server, so I posted this in case it is an issue.

I realise we're a version behind on Galacticraft, so I'll update. Probably best to ignore this issue unless it reoccurs!

thanks

**Comment by radfast** [comment]
Please try new build 3.0.8.264.  I've redone the flag data to make it use less memory when it's saving, so this out of memory error you had probably can't happen now (fingers crossed).  I'm hoping this might also help with the flag data save issue which several server owners have had.

If you get the out of memory again, please do let us know.
