### ISSUE TITLE
Automated Cargo Rocket Telemetry Display Crash

### ISSUE THREAD

**Issue by jgabello** [micdoodle8/Galacticraft#1466]
After linking an automated cargo rocket to a telemetry unit and display screen, I launched the rocket.  When it hit the height that would indicate it had left the dimension, the server crashed.

This was reproduced in Bevo Tech Pack 11 and 12

Client log BTP 12: 
24/2/15 13:29:01 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[24/2/15 13:29:01 PM] // There are four lights!
[24/2/15 13:29:01 PM] 
[24/2/15 13:29:01 PM] Time: 2/24/15 1:29 PM
[24/2/15 13:29:01 PM] Description: Ticking entity
[24/2/15 13:29:01 PM] 
[24/2/15 13:29:01 PM] java.util.ConcurrentModificationException
[24/2/15 13:29:01 PM] 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
[24/2/15 13:29:01 PM] 	at java.util.ArrayList$Itr.next(ArrayList.java:831)
[24/2/15 13:29:01 PM] 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntitySpaceshipBase.func_70071_h_(EntitySpaceshipBase.java:198)
[24/2/15 13:29:01 PM] 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:326)
[24/2/15 13:29:01 PM] 	at micdoodle8.mods.galacticraft.planets.mars.entities.EntityCargoRocket.func_70071_h_(EntityCargoRocket.java:113)
[24/2/15 13:29:01 PM] 	at net.minecraft.world.World.func_72866_a(World.java:2070)
[24/2/15 13:29:01 PM] 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
[24/2/15 13:29:01 PM] 	at net.minecraft.world.World.func_72870_g(World.java:2034)
[24/2/15 13:29:01 PM] 	at net.minecraft.world.World.func_72939_s(World.java:1887)
[24/2/15 13:29:01 PM] 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[24/2/15 13:29:01 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[24/2/15 13:29:01 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[24/2/15 13:29:01 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[24/2/15 13:29:01 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[24/2/15 13:29:01 PM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[24/2/15 13:29:01 PM] 
[24/2/15 13:29:01 PM] 
[24/2/15 13:29:01 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[24/2/15 13:29:01 PM] ---------------------------------------------------------------------------------------
[24/2/15 13:29:01 PM] 
[24/2/15 13:29:01 PM] -- Head --
[24/2/15 13:29:01 PM] Stacktrace:
[24/2/15 13:29:01 PM] 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
[24/2/15 13:29:01 PM] 	at java.util.ArrayList$Itr.next(ArrayList.java:831)
[24/2/15 13:29:01 PM] 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntitySpaceshipBase.func_70071_h_(EntitySpaceshipBase.java:198)
[24/2/15 13:29:01 PM] 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:326)
[24/2/15 13:29:01 PM] 	at micdoodle8.mods.galacticraft.planets.mars.entities.EntityCargoRocket.func_70071_h_(EntityCargoRocket.java:113)
[24/2/15 13:29:01 PM] 	at net.minecraft.world.World.func_72866_a(World.java:2070)
[24/2/15 13:29:01 PM] 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
[24/2/15 13:29:01 PM] 	at net.minecraft.world.World.func_72870_g(World.java:2034)
[24/2/15 13:29:01 PM] 
[24/2/15 13:29:01 PM] -- Entity being ticked --
[24/2/15 13:29:01 PM] Details:
[24/2/15 13:29:01 PM] 	Entity Type: GalacticraftMars.CargoRocket (micdoodle8.mods.galacticraft.planets.mars.entities.EntityCargoRocket)
[24/2/15 13:29:01 PM] 	Entity ID: 446594
[24/2/15 13:29:01 PM] 	Entity Name: Cargo Rocket
[24/2/15 13:29:01 PM] 	Entity's Exact location: -255.50, 864.00, 205.50
[24/2/15 13:29:01 PM] 	Entity's Block location: World: (-256,864,205), Chunk: (at 0,54,13 in -16,12; contains blocks -256,0,192 to -241,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
[24/2/15 13:29:01 PM] 	Entity's Momentum: -0.00, 5.00, -0.00
[24/2/15 13:29:01 PM] Stacktrace:
[24/2/15 13:29:01 PM] 	at net.minecraft.world.World.func_72939_s(World.java:1887)
[24/2/15 13:29:01 PM] 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[24/2/15 13:29:01 PM] 
[24/2/15 13:29:01 PM] -- Affected level --
[24/2/15 13:29:01 PM] Details:
[24/2/15 13:29:01 PM] 	Level name: New World
[24/2/15 13:29:01 PM] 	All players: 0 total; []
[24/2/15 13:29:01 PM] 	Chunk stats: ServerChunkCache: 259 Drop: 0
[24/2/15 13:29:01 PM] 	Level seed: -3985815874921706338
[24/2/15 13:29:01 PM] 	Level generator: ID 00 - default, ver 1. Features enabled: false
[24/2/15 13:29:01 PM] 	Level generator options: 
[24/2/15 13:29:01 PM] 	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[24/2/15 13:29:01 PM] 	Level time: 0 game time, 0 day time
[24/2/15 13:29:01 PM] 	Level dimension: 0
[24/2/15 13:29:01 PM] 	Level storage version: 0x00000 - Unknown?
[24/2/15 13:29:01 PM] 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[24/2/15 13:29:01 PM] 	Level game mode: ~~ERROR~~ NullPointerException: null
[24/2/15 13:29:01 PM] Stacktrace:
[24/2/15 13:29:01 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[24/2/15 13:29:01 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[24/2/15 13:29:01 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[24/2/15 13:29:01 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[24/2/15 13:29:01 PM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[24/2/15 13:29:01 PM] 
[24/2/15 13:29:01 PM] -- System Details --
[24/2/15 13:29:01 PM] Details:
[24/2/15 13:29:01 PM] 	Minecraft Version: 1.7.10
[24/2/15 13:29:01 PM] 	Operating System: Mac OS X (x86_64) version 10.10.2
[24/2/15 13:29:01 PM] 	Java Version: 1.7.0_71, Oracle Corporation
[24/2/15 13:29:01 PM] 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[24/2/15 13:29:01 PM] 	Memory: 655192408 bytes (624 MB) / 1967910912 bytes (1876 MB) up to 4260102144 bytes (4062 MB)
[24/2/15 13:29:01 PM] 	JVM Flags: 7 total; -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx4096M -XX:PermSize=256M
[24/2/15 13:29:01 PM] 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[24/2/15 13:29:01 PM] 	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 97
[24/2/15 13:29:01 PM] 	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 168 mods loaded, 167 mods active

--
Server and Client are running Bevo Tech Pack 11 
See log:
[08:09:04] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:960) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[?:1.7.0_71]
        at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[?:1.7.0_71]
        at micdoodle8.mods.galacticraft.api.prefab.entity.EntitySpaceshipBase.func_70071_h_(EntitySpaceshipBase.java:199) ~[EntitySpaceshipBase.class:?]
        at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:326) ~[EntityAutoRocket.class:?]
        at micdoodle8.mods.galacticraft.planets.mars.entities.EntityCargoRocket.func_70071_h_(EntityCargoRocket.java:114) ~[EntityCargoRocket.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2647) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2600) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2412) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) ~[MinecraftServer.class:?]
        ... 4 more
[08:09:04] [Server thread/ERROR]:       Cause of unexpected exception was
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[?:1.7.0_71]
        at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[?:1.7.0_71]
        at micdoodle8.mods.galacticraft.api.prefab.entity.EntitySpaceshipBase.func_70071_h_(EntitySpaceshipBase.java:199) ~[EntitySpaceshipBase.class:?]
        at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:326) ~[EntityAutoRocket.class:?]
        at micdoodle8.mods.galacticraft.planets.mars.entities.EntityCargoRocket.func_70071_h_(EntityCargoRocket.java:114) ~[EntityCargoRocket.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2647) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2600) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2412) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
[08:09:04] [Server thread/ERROR]: This crash report has been saved to: /games/btp/./crash-reports/crash-2015-02-24_08.09.04-server.txt
[08:09:04] [Server thread/INFO]: Stopping server

**Comment by radfast** [comment]
Thank you for reporting, we'll need to fix this.
Can you tell me which exact version of Galacticraft is in that pack?

**Comment by jgabello** [comment]
Apologies for not including it in the original post:
I duplicated it in Bevo Tech Pack 12 and 11
BTP 12
Galacticraft-Planets-1.7-3.0.8.266.jar
GalacticraftCore-1.7-3.0.8.266.jar
 http://bevolj.com/?p=5618 for list of included mods

BTP 11
Galacticraft-Planets-1.7-3.0.6.245.jar
GalacticraftCore-1.7-3.0.6.245.jar
http://bevolj.com/?p=5615 for list of included mods

**Comment by radfast** [comment]
Fixed next version, thank you for reporting this.
