### ISSUE TITLE
Updated tutorial on use of API

### ISSUE THREAD

**Issue by Alex-the-666** [micdoodle8/Galacticraft#1486]
before we begin, I would just like to know what forge version would be the best to match the latest download of galacticraft?

OK. so I've been trying to figure out how to create an addon for galacticraft for a while now. even setting up he workspace correctly would be good. currently there are no updated tutorials for how to create an addon for GC, and I have only gotten this far:
[spoiler]
[08:32:59] [main/INFO] [GradleStart]: Extra: []
[08:32:59] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/alexr_000/.gradle/caches/minecraft/assets, --assetIndex, 1.7.10, --accessToken, {REDACTED}, --version, 1.7.10, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.GradleStartCommon$GradleStartTweaker]
[08:32:59] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:32:59] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:32:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.GradleStartCommon$GradleStartTweaker
[08:32:59] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[08:32:59] [main/INFO] [FML]: Forge Mod Loader version 7.10.18.1180 for Minecraft 1.7.10 loading
[08:32:59] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_05, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre8
[08:32:59] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[08:33:00] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:33:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.GradleStartCommon$GradleStartTweaker
[08:33:00] [main/INFO] [GradleStart]: Injecting location in coremod cpw.mods.fml.relauncher.FMLCorePlugin
[08:33:00] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[08:33:00] [main/INFO] [GradleStart]: Injecting location in coremod micdoodle8.mods.miccore.MicdoodlePlugin
[08:33:00] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:33:00] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[08:33:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:33:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:33:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:33:00] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[08:33:03] [main/ERROR] [FML]: The minecraft jar file:/C:/Users/alexr_000/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.0.1180/forgeSrc-1.7.10-10.13.0.1180.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
[08:33:03] [main/ERROR] [FML]: FML has been ordered to ignore the invalid or missing minecraft certificate. This is very likely to cause a problem!
[08:33:03] [main/ERROR] [FML]: Technical information: ClientBrandRetriever was at jar:file:/C:/Users/alexr_000/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.0.1180/forgeSrc-1.7.10-10.13.0.1180.jar!/net/minecraft/client/ClientBrandRetriever.class, there were 0 certificates for it
[08:33:03] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[08:33:03] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:33:03] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
Successfully Registered Transformer
[Micdoodle8Core]: Patching game...
[Micdoodle8Core]: Patching game...
[08:33:03] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[08:33:03] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
Galacticraft successfully injected bytecode into: net/minecraft/entity/EntityLivingBase (1 / 1)
Galacticraft successfully injected bytecode into: net/minecraft/entity/Entity (1 / 1)
Galacticraft successfully injected bytecode into: net/minecraft/client/gui/GuiSleepMP (1 / 1)
[08:33:04] [main/INFO]: Setting user: Player171
Galacticraft successfully injected bytecode into: net/minecraft/entity/item/EntityItem (1 / 1)
[08:33:06] [Client thread/INFO]: LWJGL Version: 2.9.1
Galacticraft successfully injected bytecode into: net/minecraftforge/client/ForgeHooksClient (1 / 1)
[08:33:07] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[08:33:07] [Client thread/INFO] [FML]: MinecraftForge v10.13.0.1180 Initialized
[08:33:07] [Client thread/INFO] [FML]: Replaced 182 ore recipies
[08:33:07] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[08:33:07] [Client thread/INFO] [FML]: Searching C:\Users\alexr_000\Desktop\Mod Dev Workspace\BeyondSol\eclipse\mods for mods
[08:33:07] [Client thread/INFO] [FML]: Also searching C:\Users\alexr_000\Desktop\Mod Dev Workspace\BeyondSol\eclipse\mods\1.7.10 for mods
[08:33:08] [Client thread/ERROR] [FML]: FML has detected a mod that is using a package name based on 'net.minecraft.src' : net.minecraft.src.FMLRenderAccessLibrary. This is generally a severe programming error.  There should be no mod code in the minecraft namespace. MOVE YOUR MOD! If you're in eclipse, select your source code and 'refactor' it into a new package. Go on. DO IT NOW!
[08:33:12] [Client thread/INFO] [FML]: Forge Mod Loader has identified 7 mods to load
[08:33:13] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Example Mod, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:Galacticraft Planets
[08:33:13] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[08:33:13] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[08:33:13] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[08:33:13] [Client thread/ERROR] [examplemod]: Skipping event FMLPreInitializationEvent and marking errored mod examplemod since required dependency GalacticraftCore has errored
[08:33:13] [Client thread/ERROR] [GalacticraftMars]: Skipping event FMLPreInitializationEvent and marking errored mod GalacticraftMars since required dependency GalacticraftCore has errored
[08:33:13] [Client thread/INFO] [FML]: Applying holder lookups
[08:33:13] [Client thread/INFO] [FML]: Holder lookups applied
[08:33:13] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[08:33:13] [Client thread/ERROR] [FML]: 
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.18.1180} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.0.1180} [Minecraft Forge] (forgeSrc-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.271.jar) Unloaded->Constructed->Errored
	examplemod{1.0} [Example Mod] (bin) Unloaded->Constructed->Errored
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.271.jar) Unloaded->Constructed->Errored
[08:33:13] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[08:33:13] [Client thread/ERROR] [FML]: Caught exception from GalacticraftCore
java.lang.NoSuchFieldError: field_150410_aZ
	at micdoodle8.mods.galacticraft.core.util.ConfigManagerCore.syncConfig(ConfigManagerCore.java:338) ~[GalacticraftCore-1.7-3.0.8.271.jar:?]
	at micdoodle8.mods.galacticraft.core.util.ConfigManagerCore.initialize(ConfigManagerCore.java:88) ~[GalacticraftCore-1.7-3.0.8.271.jar:?]
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:129) ~[GalacticraftCore-1.7-3.0.8.271.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[forgeSrc-1.7.10-10.13.0.1180.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[forgeSrc-1.7.10-10.13.0.1180.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[forgeSrc-1.7.10-10.13.0.1180.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:532) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:941) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:164) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85) [start/:?]
	at GradleStart.main(GradleStart.java:45) [start/:?]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 3/7/15 8:33 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: field_150410_aZ
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:532)
	at net.minecraft.client.Minecraft.run(Minecraft.java:941)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85)
	at GradleStart.main(GradleStart.java:45)
Caused by: java.lang.NoSuchFieldError: field_150410_aZ
	at micdoodle8.mods.galacticraft.core.util.ConfigManagerCore.syncConfig(ConfigManagerCore.java:338)
	at micdoodle8.mods.galacticraft.core.util.ConfigManagerCore.initialize(ConfigManagerCore.java:88)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 839136760 bytes (800 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.18.1180 Minecraft Forge 10.13.0.1180 7 mods loaded, 7 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.18.1180} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.0.1180} [Minecraft Forge] (forgeSrc-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.271.jar) Unloaded->Constructed->Errored
	examplemod{1.0} [Example Mod] (bin) Unloaded->Constructed->Errored
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.271.jar) Unloaded->Constructed->Errored
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\alexr_000\Desktop\Mod Dev Workspace\BeyondSol\eclipse\.\crash-reports\crash-2015-03-07_08.33.13-client.txt
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[/spoiler]

My forge version is 1.7.10-10.13.0.1180.

**Comment by radfast** [comment]
This is not a suitable topic for the Github issues list.
+ there is ample information on the Galacticraft forum and the wiki.

**Comment by DeinoRaptor** [comment]
Radfast, if your not going to help, then die
