### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Flukethoughts** [micdoodle8/Galacticraft#1499]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 3/13/15 11:53 AM
Description: Ticking block entity

java.lang.RuntimeException: DISPATCHER expects a NetworkDispatcher
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$2.validateArgs(FMLOutboundHandler.java:58)
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:262)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.sendToAllAround(GalacticraftChannelHandler.java:94)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced.func_145845_h(TileEntityAdvanced.java:61)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenPipe.func_145845_h(TileEntityOxygenPipe.java:51)
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$2.validateArgs(FMLOutboundHandler.java:58)
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:262)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.sendToAllAround(GalacticraftChannelHandler.java:94)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced.func_145845_h(TileEntityAdvanced.java:61)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenPipe.func_145845_h(TileEntityOxygenPipe.java:51)

-- Block entity being ticked --
Details:
	Name: Oxygen Pipe // micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenPipe
	Block type: ID #1419 (tile.oxygenPipe // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenPipe)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (2,96,-4), Chunk: (at 2,6,12 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #1419 (tile.oxygenPipe // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenPipe)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

**Comment by radfast** [comment]
That crash is happening deep within the Forge network code which is used by all mods.

I've looked at this and Galacticraft is not doing anything strange at this point, just sending a standard tile entity update to clients which is something the mod does hundreds of times every tick, without erroring.  (It's also not anything we have changed recently, at all.)

Please can you comment on:

* Do you have a non-vanilla server setup (for example Cauldron, Spigot, BungeeCord, FastCraft, or anything similar?)

* Did this error occur at a strange time, like server startup or server shutdown (I mean when the server was already shutting down for a different reason, prior to the crash) or is it mid-game?

* Any prior error messages or warnings relating to networking?  Like was it already going wrong?

It would help me if you can provide your complete ```fml-server-latest.log``` for the server run when this happened.  Upload it to Mediafire or Dropbox or Google Drive or similar.

**Comment by radfast** [comment]
Also is this a one-off, or does it happen every time the chunk loads?

**Comment by Flukethoughts** [comment]
cauldron happens randomly just a weird little issue. Plus server always crashes when someone uses a digital miner on a planet.

**Comment by radfast** [comment]
Full log would help me to see if there is anything going wrong in Galacticraft.

Please also post the crash report from the [Mekanism] digital miner.

**Comment by radfast** [comment]
Any update please?  We want to fix this type of thing.
