### ISSUE TITLE
Server Crash when making launchpad

### ISSUE THREAD

**Issue by Cracks777** [micdoodle8/Galacticraft#1508]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/19/15 9:25 PM
Description: Ticking block entity

java.lang.NoSuchFieldError: field_73244_f
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvancedTile.func_149749_a(BlockAdvancedTile.java:53)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:644)
	at net.minecraft.world.World.func_147465_d(World.java:793)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityLandingPadSingle.func_145845_h(TileEntityLandingPadSingle.java:37)
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvancedTile.func_149749_a(BlockAdvancedTile.java:53)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:644)
	at net.minecraft.world.World.func_147465_d(World.java:793)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityLandingPadSingle.func_145845_h(TileEntityLandingPadSingle.java:37)

-- Block entity being ticked --
Details:
	Name: Landing Pad // micdoodle8.mods.galacticraft.core.tile.TileEntityLandingPadSingle
	Block type: ID #182 (tile.landingPad // micdoodle8.mods.galacticraft.core.blocks.BlockLandingPad)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (8852,138,-467), Chunk: (at 4,8,13 in 553,-30; contains blocks 8848,0,-480 to 8863,255,-465), Region: (17,-1; contains chunks 544,-32 to 575,-1, blocks 8704,0,-512 to 9215,255,-1)
	Actual block type: ID #182 (tile.landingPad // micdoodle8.mods.galacticraft.core.blocks.BlockLandingPad)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [GCEntityPlayerMP['Eclipse'/725, l='world', x=8852.05, y=138.00, z=-468.70](Eclipse at 8852.046506089298,138.0,-468.69999998807907)]
	Chunk stats: ServerChunkCache: 912 Drop: 0
	Level seed: 712362433643191817
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (242,66,74), Chunk: (at 2,4,10 in 15,4; contains blocks 240,0,64 to 255,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 36086168 game time, 28170029 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 64419 (now: false), thunder time: 12942 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_76, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1567459304 bytes (1494 MB) / 2591031296 bytes (2471 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -XX:PermSize=256m -XX:MaxPermSize=512m -Xmx6144M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 104
	FML: MCP v9.05 FML v7.10.88.1307 git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1307 96 mods loaded, 95 mods active

**Comment by radfast** [comment]
This is a known bug in Cauldron, unfortunately.  http://bt.industrial-craft.net/view.php?id=1323

We will look at what we can do to workaround it.

**Comment by radfast** [comment]
Please use Galacticraft versions 295 or 297 on a Cauldron server.

**Comment by Cracks777** [comment]
ok thank you.

**Comment by radfast** [comment]
Direct link to download GC version 297 __for servers__.  (This is 100% compatible with players who are on version 296).
http://ci.micdoodle8.com/job/Galacticraft-1.7/297/
