### ISSUE TITLE
mekanism v8 compatibility problem

### ISSUE THREAD

**Issue by Suikju** [micdoodle8/Galacticraft#1515]
Maybe you are working on it. I got a crash when i try to connect any Oxygen depended machine with mekanismengines like electric seperator. I already wrote an issue for the author of mekanism, but he said you have to date your api up. 
I hope you can fix it soon.

**Comment by radfast** [comment]
Already fixed, use the correct Galacticraft version:
http://wiki.micdoodle8.com/wiki/Compatibility#Mekanism

**Comment by Suikju** [comment]
ah ok, thank you ^^

**Comment by Suikju** [comment]
uhm i use both mods the latest version.
Galacticraft-wiki said 3.0.10.298 works with v8 currently better than v7. I still get crashes, when i try to connect any oxygen machines with mekanism machines.
Actually there is mekanism 8.0.2.199 installed.

So i tried to locate the problem and use only mekanism v8 (8.02.199) and galacticraft (3.0.10.298) and i found that the connection with electric seperator from mekanism and any oxygen machines works. But when i start the machine, it crashes. Using gc-machines with the pressure tube doesnt work. 
Maybe it helps for analyzing the problem?

![unbenannt](https://cloud.githubusercontent.com/assets/11639581/6823014/7706a09e-d2e4-11e4-99ed-7850366a8acf.PNG)

**Comment by radfast** [comment]
thank you we'll look at this urgently - hope to have it fixed within 24 hours

**Comment by Suikju** [comment]
i tried to connect electric seperator with oxygen tube (galactricraft). Crashes again but another crashreport. Maybe its important for you. 

---- Minecraft Crash Report ----
// Don't do that.

Time: 25.03.15 12:09
Description: Ticking block entity

java.lang.AbstractMethodError: micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenPipe.receiveGas(Lnet/minecraftforge/common/util/ForgeDirection;Lmekanism/api/gas/GasStack;Z)I
	at mekanism.common.tile.TileEntityElectrolyticSeparator.onUpdate(TileEntityElectrolyticSeparator.java:223)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by radfast** [comment]
OK I see what's going on here.  Please try Mekanism 8.0.2.201, I think that has already fixed this.

**Comment by Suikju** [comment]
ok i try it

**Comment by Suikju** [comment]
nope it doesnt. 

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 25.03.15 12:21
Description: Exception in server tick loop

java.lang.AbstractMethodError: micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenStorageModule.receiveGas(Lnet/minecraftforge/common/util/ForgeDirection;Lmekanism/api/gas/GasStack;Z)I
	at mekanism.api.gas.GasNetwork.tickEmit(GasNetwork.java:177)
	at mekanism.api.gas.GasNetwork.onUpdate(GasNetwork.java:259)
	at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:280)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:85)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:73)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_92_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by radfast** [comment]
ok - thanks for the new crash report, I will look at this some more and try to find a fix, I hope in next 24 hours.

Please play without connecting Mekanism pipes to Galacticraft machines, for now.

**Comment by Suikju** [comment]
i think its only the oxygen compatibilty problem, because the new function to produce deuterium and oxygen. i downgraded mekanism to v7 and there are good compatibilties. No crashes. 
Energy pipes in mekanism v8 with galactricraft works fine. No crashes.

**Comment by Suikju** [comment]
ok i wait. ^^.

**Comment by radfast** [comment]
This is fixed in new build 3.0.10.299.  Thank you for waiting.

**Comment by Suikju** [comment]
Thank you for your hard work. But the game doesnt want to start now ^^. I redownloaded it serveral times and let only galacticraft starting. Maybe there are some compatibility problems i thought. But no solving. I know you sit a long time to fix it. I hope you can do it one more time :+1: 

--- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 26.03.15 10:39
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at micdoodle8.mods.galacticraft.planets.asteroids.blocks.AsteroidBlocks.registerBlocks(AsteroidBlocks.java:67)
	at micdoodle8.mods.galacticraft.planets.asteroids.AsteroidsModule.preInit(AsteroidsModule.java:109)
	at micdoodle8.mods.galacticraft.planets.PlanetsProxy.preInit(PlanetsProxy.java:18)
	at micdoodle8.mods.galacticraft.planets.PlanetsProxyClient.preInit(PlanetsProxyClient.java:18)
	at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.preInit(GalacticraftPlanets.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Suikju** [comment]
Maybe you tried it on your own starting a game with this mod. Maybe its my problem, i dont know. :I. 
I downgraded forge on an older version and removed every other mods. Im not good at reading such crash reports.

**Comment by radfast** [comment]
You're doing everything right.  It was my mistake, trying to get a build out too late at night.
Please try new build 300 just up, it should fix everything and be stable for you.
Direct link: http://ci.micdoodle8.com/job/Galacticraft-1.7/300/

**Comment by Suikju** [comment]
wow it works now. thank you very much. :+1:

**Comment by radfast** [comment]
Nice, thanks for confirming.
