### ISSUE TITLE
Galacticraft Tab crash on click

### ISSUE THREAD

**Issue by Glued2Computer** [micdoodle8/Galacticraft#1526]
When opening the galacticraft tab from inventory, crashes to desktop.
crashlog: http://pastebin.com/VE5mZDSx

**Comment by Playaah** [comment]
I have the same issue. I added Galacticraft to the FTB Infinity pack, and when i try to open the inventory tab the game crashes. http://pastebin.com/w8vpeYGt

**Comment by radfast** [comment]
Please roll back to version 3.0.10.301 until this is fixed.
Download link: http://ci.micdoodle8.com/job/Galacticraft-1.7/301/

**Comment by EzerArch** [comment]
Thanks for reporting. I was writing an issue already. But in my case, Galacticraft Tab crashes only if CustomNPC is installed.

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 28/03/15 16:35
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at net.minecraft.client.gui.inventory.GuiContainer.func_73876_c(GuiContainer.java:698)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by micdoodle8** [comment]
Fixes via ee0a227f6d76513b7c56583064fa4e5810834595 . Use the development build on the download site. Thanks for the reports.

**Comment by radfast** [comment]
@EzerArch do you have ExtraTIC installed?  That seems to be the conflict causing mod with the other two crash reports above (FTB Infinity).

**Comment by radfast** [comment]
Everyone affected by this: please now use latest Galacticraft build 3.0.11.306.
(Everything should be fixed - any more problems, please post.)

**Comment by EzerArch** [comment]
> do you have ExtraTIC installed? Or any other Tinker's Construct extensions?

I don't. I tested r306, the crash is gone.

**Comment by radfast** [comment]
Awesome.
