### ISSUE TITLE
Minecraft Server Crash

### ISSUE THREAD

**Issue by Nilsteichert** [micdoodle8/Galacticraft#1609]
Crash Report:
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 4/25/15 1:46 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.storage.SaveHandler.func_75754_f(SaveHandler.java:349)
	at net.minecraft.server.management.ServerConfigurationManager.func_72373_m(ServerConfigurationManager.java:1577)
	at net.minecraft.server.MinecraftServer.func_70000_a(MinecraftServer.java:1311)
	at net.minecraft.server.dedicated.DedicatedServer.func_70000_a(DedicatedServer.java:441)
	at net.minecraft.profiler.PlayerUsageSnooper.func_76471_b(SourceFile:97)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:845)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.14.33-nitradoV3-MC-300-nH-dP-i
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 282846000 bytes (269 MB) / 580911104 bytes (554 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -Xmx2048M -Xms256M -XX:MaxPermSize=128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1272 git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1272 3 mods loaded, 3 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1272} [Forge Mod Loader] (minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1272} [Minecraft Forge] (minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 4; []
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

Console by Start:
[20:44:55] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[20:44:56] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1692]: Potential problem: Galacticraft did not complete injection of bytecode into: oi (4 / 6)
[20:44:56] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.getMethod0(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.getMethod(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 6 more
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 12 more
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/EntityLivingBase
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 14 more
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.EntityLivingBase
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 18 more
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/Entity
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 20 more
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.Entity
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 24 more
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.RuntimeException: asm error net.minecraft.entity.Entity 0b915cc9 dr 0d5875a3 0 1
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.asm.FastCraftTransformer.transform(F:251)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 26 more

**Comment by radfast** [comment]
This looks to be a FastCraft error:

> [20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.RuntimeException: asm error net.minecraft.entity.Entity 0b915cc9 dr 0d5875a3 0 1
[20:44:57] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at fastcraft.asm.FastCraftTransformer.transform(F:251)

Why do you think it's Galacticraft?

**Comment by radfast** [comment]
Though Galacticraft doesn't look to be the cause of this, I can also see you are using an out of date Galacticraft - it's generally a good idea to be running the latest

**Comment by Nilsteichert** [comment]
Hm its a Modpack which is only for 1.6
And i asked my server hoster who told me its from galacticraft. But if its
a compatibily Problem ill try to fix it myself
Am 26.04.2015 03:06 schrieb "Co-developer of Galacticraft" <
notifications@github.com>:

**Comment by radfast** [comment]
> i asked my server hoster who told me its from galacticraft. 

Your server hoster sounds like an idiot, then.

It's __not__ a compatibility problem in Galacticraft.  Which part of what I wrote above do you not understand?  I already told you, this is not a Galacticraft problem at all.

This part of your log is correct for Galacticraft in MC1.6.4.  The log lines show that Galacticraft is working __correctly__.  (The oi (4/6) message is normal, a check of any log from a time when the game started normally will show you that.)
> [20:44:56] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1692]: Potential problem: Galacticraft did not complete injection of bytecode into: oi (4 / 6)
[20:44:56] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: sv (1 / 1)

**Comment by Nilsteichert** [comment]
Ok it works now anyways but Thanks for your Support :)
Am 26.04.2015 19:23 schrieb "Co-developer of Galacticraft" <
notifications@github.com>:
