### ISSUE TITLE
Tile Entity Miner

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1619]
[22:08:55] [Server thread/ERROR] [FML]: A TileEntity type micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityMinerBase has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityMinerBase.writeToNBT(TileEntityMinerBase.java:218) ~[TileEntityMinerBase.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeChunkToNBT(AnvilChunkLoader.java:395) [AnvilChunkLoader.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.saveChunk(AnvilChunkLoader.java:204) [AnvilChunkLoader.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.safeSaveChunk(ChunkProviderServer.java:287) [ChunkProviderServer.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java:340) [ChunkProviderServer.class:?]
	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:863) [WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:370) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]

This is bug. Not crashes.

**Comment by radfast** [comment]
Thank you for reporting.  This issue will cause the dock which had the error to look "transparent" when reloaded, you will need to break it and re-build it before it can work properly.
