### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lightning02** [micdoodle8/Galacticraft#1685]
Problem with world in chunk generation in the log in.

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 01/06/15 11.07
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at grim3212.mc.ttmultra.metalworks.BlockDerrick.func_149749_a(BlockDerrick.java:132)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
	at net.minecraft.world.World.func_147465_d(World.java:800)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:456)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_108_EventHandlerGC_populate_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1170)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
	at net.minecraft.world.World.func_72964_e(World.java:739)
	at net.minecraft.world.World.func_147439_a(World.java:665)
	at drzhark.mocreatures.entity.passive.MoCEntityBird.FindTreeTop(MoCEntityBird.java:121)
	at drzhark.mocreatures.entity.passive.MoCEntityBird.FlyToNextTree(MoCEntityBird.java:199)
	at drzhark.mocreatures.entity.passive.MoCEntityBird.func_70636_d(MoCEntityBird.java:398)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1890)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
	at net.minecraft.world.World.func_72866_a(World.java:2643)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:2596)
	at net.minecraft.world.World.func_72939_s(World.java:2409)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

-- Head --
Stacktrace:
	at grim3212.mc.ttmultra.metalworks.BlockDerrick.func_149749_a(BlockDerrick.java:132)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
	at net.minecraft.world.World.func_147465_d(World.java:800)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:456)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_108_EventHandlerGC_populate_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1170)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
	at net.minecraft.world.World.func_72964_e(World.java:739)

+++++  The same at different coordinates.

---- Minecraft Crash Report ----
// Don't do that.

Time: 01/06/15 14.17
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at grim3212.mc.ttmultra.metalworks.BlockDerrick.func_149749_a(BlockDerrick.java:132)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
	at net.minecraft.world.World.func_147465_d(World.java:800)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:456)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_108_EventHandlerGC_populate_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:165)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:341)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
	at net.minecraft.world.World.func_72964_e(World.java:739)
	at net.minecraft.world.World.func_147439_a(World.java:665)
	at net.minecraft.world.World.func_147460_e(World.java:1068)
	at net.minecraft.world.World.func_147459_d(World.java:1027)
	at net.minecraft.world.World.func_147444_c(World.java:988)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:844)
	at net.minecraft.world.World.func_147465_d(World.java:822)
	at net.minecraft.world.gen.feature.WorldGenerator.func_150516_a(SourceFile:33)
	at com.pam.harvestcraft.WorldGenPamFruitPalmTree.func_76484_a(WorldGenPamFruitPalmTree.java:116)
	at com.pam.harvestcraft.PamTreeGenerator.generateSurface(PamTreeGenerator.java:226)
	at com.pam.harvestcraft.PamTreeGenerator.generate(PamTreeGenerator.java:22)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:394)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at grim3212.mc.ttmultra.metalworks.BlockDerrick.func_149749_a(BlockDerrick.java:132)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
	at net.minecraft.world.World.func_147465_d(World.java:800)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:456)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_108_EventHandlerGC_populate_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:165)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:341)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
	at net.minecraft.world.World.func_72964_e(World.java:739)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-268,90,79), Chunk: (at 4,5,15 in -17,4; contains blocks -272,0,64 to -257,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:665)
	at net.minecraft.world.World.func_147460_e(World.java:1068)
	at net.minecraft.world.World.func_147459_d(World.java:1027)
	at net.minecraft.world.World.func_147444_c(World.java:988)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:844)
	at net.minecraft.world.World.func_147465_d(World.java:822)
	at net.minecraft.world.gen.feature.WorldGenerator.func_150516_a(SourceFile:33)
	at com.pam.harvestcraft.WorldGenPamFruitPalmTree.func_76484_a(WorldGenPamFruitPalmTree.java:116)
	at com.pam.harvestcraft.PamTreeGenerator.generateSurface(PamTreeGenerator.java:226)
	at com.pam.harvestcraft.PamTreeGenerator.generate(PamTreeGenerator.java:22)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:394)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

**Comment by radfast** [comment]
And this is a Galacticraft issue because ... ?

**Comment by lightning02** [comment]
I'm not sure is a issue but something like, an id call from gala? I'm not very able to read crash report but there say "at micdolcore"

**Comment by radfast** [comment]
This is the crash:
> at grim3212.mc.ttmultra.metalworks.BlockDerrick.func_149749_a(BlockDerrick.java:132)

How to read a crash report: it's always the first line in the crash report which is the actual crash.  (At least, if that line is from a mod then it's that, sometimes there can be other kinds of crash involving network code like NettyIO but you don't need to worry about that's not ...

The micdoodle8 ... generateOil part lower down just tells you how it got there.  So yes, this happened while Galacticraft was generating oil, but there's also some vanilla Minecraft code in between so it's not likely to be a Galacticraft crash.  The relevant Galacticraft code called world.setBlock().  Here's a link to it, which you can show to the grim3212 guys if it helps them:
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/event/EventHandlerGC.java

If you can't get in to your world while this crash is happening, you might need to uninstall the grim3212 mod - but warning, uninstalling it and then loading the map will delete all of its blocks and items in the world.

There's nothing more we can do to help you here.

**Comment by lightning02** [comment]
Thanks alot for the clarification, it helps me a lot!
Btw just for curiosity, how i act when happen a crash not showing the offending mod?

**Comment by radfast** [comment]
>  how i act when happen a crash not showing the offending mod?

That's hard to answer.  It really doesn't happen too often, and if it does happen in network code (e.g. a crash in NettyIO) it can be hard even for mod authors to figure out the reason.

As well as what I said already, I recommend:

* Search Google for the 10-20 words at the top of the crash report, sometimes you can find a person pasted the same crash on a Minecraft forum somewhere
* Try to figure out which mod crashed based on what you were doing when the crash happened - then ask for help in the Support forum for that mod, someone will help you.
*  You can try removing mods from your modpack until the crash stops happening.  For example if you can't load your world at all, maybe you will have to do this.  Then you will know which mod is crashing.  (Warning: removing mods will cause block and item loss in your world.  Especially be careful if removing a storage or chests mod, you can lose everything in the storage!!!)
*  Ask a friend who knows Java...

**Comment by lightning02** [comment]
Oh, I get it.
I thank you again very much for your time! :)
