### ISSUE TITLE
Issue When Loading

### ISSUE THREAD

**Issue by ean521** [micdoodle8/Galacticraft#1713]
When I load Minecraft, I get the following crash report:

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/14/15 8:10 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/api/recipes/BuildcraftRecipes
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/recipes/BuildcraftRecipes
	at micdoodle8.mods.galacticraft.core.recipe.RecipeManagerGC.addBuildCraftCraftingRecipes(RecipeManagerGC.java:573)
	at micdoodle8.mods.galacticraft.core.recipe.RecipeManagerGC.loadRecipes(RecipeManagerGC.java:43)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.postInit(GalacticraftCore.java:399)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.recipes.BuildcraftRecipes
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 122007392 bytes (116 MB) / 387936256 bytes (369 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJ	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJ	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJ	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJ	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-2.jar) 
	UCHIJ	BuildCraft|Core{7.0.9} [BuildCraft] buildcraft-7.0.9.jar) 
	UCHIJ	BuildCraft|Silicon{7.0.9} [BC Silicon] buildcraft-7.0.9.jar) 
	UCHIJ	BuildCraft|Transport{7.0.9} [BC Transport] buildcraft-7.0.9.jar) 
	UCHIJ	BuildCraft|Builders{7.0.9} [BC Builders] buildcraft-7.0.9.jar) 
	UCHIJ	BuildCraft|Robotics{7.0.9} [BC Robotics] buildcraft-7.0.9.jar) 
	UCHIJ	BuildCraft|Energy{7.0.9} [BC Energy] buildcraft-7.0.9.jar) 
	UCHIJ	BuildCraft|Factory{7.0.9} [BC Factory] buildcraft-7.0.9.jar) 
	UCHIJ	ComputerCraft{1.73} [ComputerCraft] ComputerCraft1.73.jar) 
	UCHIJ	SlimevoidLib{2.0.4.7} [Slimevoid Library] SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJ	DynamicTransport{0.1.2.0} [Dynamic Transport] DynamicTransport-0.1.2.0.jar) 
	UCHIE	GalacticraftCore{3.0.12} [Galacticraft Core] GalacticraftCore-1.7-3.0.12.343.jar) 
	UCHIE	GalacticraftMars{3.0.12} [Galacticraft Planets] Galacticraft-Planets-1.7-3.0.12.343.jar) 
	UCHIJ	LittleBlocks{2.2.4.4} [Little Blocks] LittleBlocks-2.2.4.4.jar) 
	UCHIJ	ReiMinimap{1.7.10} [Rei's Minimap] Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJ	Baubles{1.0.1.10} [Baubles] Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJ	Thaumcraft{4.2.3.5} [Thaumcraft] Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJ	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] ThaumicTinkerer-2.5-1.7.10-164.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.52' Renderer: 'GeForce GTX 960/PCIe/SSE2'

**Comment by Tsyklop** [comment]
https://github.com/micdoodle8/Galacticraft/issues/1711

**Comment by Tsyklop** [comment]
Yes! I agree! 343 crash, the error is the same!

**Comment by Dream-Master** [comment]
I have this crash too.

**Comment by radfast** [comment]
OK roll back to 341 for now please.

**Comment by radfast** [comment]
This is now fixed in [344](http://ci.micdoodle8.com/job/Galacticraft-1.7/344/) I hope.  It was a simple typing error (I forgot to delete a line of code I moved).  Sorry 'bout that!

**Comment by Tsyklop** [comment]
344 work fine. No Crash

**Comment by radfast** [comment]
Thanks for confirming.  I hope not too many people downloaded 342 and 343 in the short time while they were the 'latest'.
