### ISSUE TITLE
Crash when I land on a newly created Space Station

### ISSUE THREAD

**Issue by chezpaul** [micdoodle8/Galacticraft#1855]
I'm trying to create a space station and it keeps crashing.
Running a KCauldron server with Forge Mod Loader version 7.99.4.1492 and latest Galacticraft 1.7-3.0.12.357

Here's the full server log. http://pastebin.com/T48Jx3UY
(Forgot to check client log)
And just the crash log:

[17:37:05 INFO]: Loading dimension 15 (DIM_SPACESTATION15) (net.minecraft.server.dedicated.DedicatedServer@4330d3b6)

[17:37:05 INFO]: [WorldGuard] Default configuration file written: /Users/bwayserver/Desktop/KCauldron/plugins/WorldGuard/worlds/DIM_SPACESTATION15/config.yml

[17:37:05 INFO]: [WorldGuard] Default configuration file written: /Users/bwayserver/Desktop/KCauldron/plugins/WorldGuard/worlds/DIM_SPACESTATION15/blacklist.txt

[17:37:05 INFO]: [WorldGuard] (DIM_SPACESTATION15) TNT ignition is blocked.

[17:37:05 INFO]: [WorldGuard] (DIM_SPACESTATION15) Lighters are PERMITTED.

[17:37:05 INFO]: [WorldGuard] (DIM_SPACESTATION15) Lava fire is blocked.

[17:37:05 INFO]: [WorldGuard] (DIM_SPACESTATION15) Fire spread is UNRESTRICTED.

[17:37:05 INFO]: [WorldGuard] Loaded configuration for world 'DIM_SPACESTATION15'

[17:37:05 INFO]: [Prism]: Registering new world to the database/cache: DIM_SPACESTATION15 31

[17:37:05 INFO]: [Dynmap] Loaded 3 maps of world 'DIM_SPACESTATION15'.

[17:37:22 INFO]: Found matching world (15) for name: Space Station 15

[17:37:22 INFO]: Server attempting to transfer player chezboutin to dimension 15

[17:37:22 INFO]: chezboutin issued server command: /we cui

[17:37:23 ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$WorldTickEvent@353fae6:

java.lang.IndexOutOfBoundsException

at kcauldron.wrapper.LinkedHelper.get(LinkedHelper.java:27) ~[LinkedHelper.class:1.7.10-1492.155]

at kcauldron.wrapper.QueueToList.get(QueueToList.java:30) ~[QueueToList.class:1.7.10-1492.155]

at drzhark.customspawner.CustomSpawner.countEntities(CustomSpawner.java:205) ~[CustomSpawner.class:?]

at drzhark.customspawner.CustomSpawner.doCustomSpawning(CustomSpawner.java:273) ~[CustomSpawner.class:?]

at drzhark.customspawner.handlers.SpawnTickHandler.worldTick(SpawnTickHandler.java:36) ~[SpawnTickHandler.class:?]

at cpw.mods.fml.common.eventhandler.ASMEventHandler_362_SpawnTickHandler_worldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]

at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1492.155]

at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1492.155]

at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:272) [FMLCommonHandler.class:1.7.10-1492.155]

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:925) [MinecraftServer.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

[17:37:23 ERROR]: Index: 9 Listeners:

[17:37:23 ERROR]: 0: NORMAL

[17:37:23 ERROR]: 1: ASM: am2.proxy.tick.ServerTickHandler@2b29c939 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 2: ASM: thaumcraft.common.lib.events.ServerTickEventsFML@8e8a28a serverWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 3: ASM: vazkii.botania.common.item.ItemGrassSeeds@53e4dbf8 onTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 4: ASM: vazkii.botania.common.item.equipment.tool.terrasteel.ItemTerraAxe@7da79980 onTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 5: ASM: noppes.npcs.ServerTickHandler@4fd33e5b onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 6: ASM: ic2.core.TickHandler@6ae4cba3 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 7: ASM: codechicken.nei.ServerHandler@2b582f7d tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 8: ASM: vazkii.botania.common.core.handler.CommonTickHandler@2b8af8b2 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 9: ASM: drzhark.customspawner.handlers.SpawnTickHandler@534c17ac worldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 10: ASM: mekanism.common.CommonWorldTickHandler@4b9eaa40 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 11: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@7244acdd serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 12: ASM: micdoodle8.mods.galacticraft.core.tick.TickHandlerServer@13c34310 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 13: ASM: buildcraft.transport.stripes.PipeExtensionListener@842242c tick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 14: ASM: buildcraft.robotics.map.MapManager@2404274 tickDelayedWorlds(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

[17:37:23 ERROR]: 15: ASM: vazkii.botania.common.block.BlockPistonRelay@7929566c tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V

[17:37:23 ERROR]: 16: ASM: lumien.randomthings.Handler.RTTickHandler@2c75fde tick(Lcpw/mods/fml/common/gameevent/TickEvent;)V

[17:37:23 ERROR]: Encountered an unexpected exception

java.lang.IndexOutOfBoundsException

at kcauldron.wrapper.LinkedHelper.get(LinkedHelper.java:27) ~[LinkedHelper.class:1.7.10-1492.155]

at kcauldron.wrapper.QueueToList.get(QueueToList.java:30) ~[QueueToList.class:1.7.10-1492.155]

at drzhark.customspawner.CustomSpawner.countEntities(CustomSpawner.java:205) ~[CustomSpawner.class:?]

at drzhark.customspawner.CustomSpawner.doCustomSpawning(CustomSpawner.java:273) ~[CustomSpawner.class:?]

at drzhark.customspawner.handlers.SpawnTickHandler.worldTick(SpawnTickHandler.java:36) ~[SpawnTickHandler.class:?]

at cpw.mods.fml.common.eventhandler.ASMEventHandler_362_SpawnTickHandler_worldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]

at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1492.155]

at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:1.7.10-1492.155]

at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:272) ~[FMLCommonHandler.class:1.7.10-1492.155]

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:925) ~[MinecraftServer.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) ~[MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

[17:37:23 ERROR]: This crash report has been saved to: /Users/bwayserver/Desktop/KCauldron/./crash-reports/crash-2015-09-29_17.37.23-server.txt

[17:37:23 INFO]: Stopping server

**Comment by micdoodle8** [comment]
This appears to be a drzhark's CustomSpawners mod issue. Although it is triggered by creating a space station, the last problematic line in the crash report is:

    at drzhark.customspawner.CustomSpawner.countEntities(CustomSpawner.java:205) ~[CustomSpawner.class:?]

**Comment by chezpaul** [comment]
Yes, when I turn off CustomNPC, it works fine.
Thanks

**Comment by chezpaul** [comment]
So is it Custom NPC's only in a Galacticraft dimension?

**Comment by micdoodle8** [comment]
Okay, good to know. Glad you got it working.
