### ISSUE TITLE
Couldn't render entity ClassCastException

### ISSUE THREAD

**Issue by plaguewolf** [micdoodle8/Galacticraft#1857]
ive also posted this to mekanism, @ https://github.com/aidancbrady/Mekanism/issues/2981

im running quite a few mods, 256 at last count, but i believe ive narrowed down the source of a bug that has been persisting for the last few days since i updated/changed things.

heres the relevant error thrown, or rather one of them, as my log was simply spammed to hell by practically every entity over a 30 minute period.

its important to note, this didnt initially cause a cash, and in fact doesnt start happening until some time into a new world, about long enough for mystcraft to finish instability profiling.

i think, and im no expert, that its a problem with all of, or one or the other, galacticraft/mekanism, in regards to being used alongside PlayerAPI/RenderPlayerAPI/RenderPlayerAPIEnhancer.

[09:34:38] [Client thread/ERROR]: Couldn't render entity
java.lang.ClassCastException: net.minecraft.entity.monster.EntitySkeleton cannot be cast to net.minecraft.entity.player.EntityPlayer
at micdoodle8.mods.galacticraft.core.client.model.ModelPlayerBaseGC.afterSetRotationAngles(ModelPlayerBaseGC.java:283) ~[ModelPlayerBaseGC.class:?]
at api.player.model.ModelPlayerAPI.setRotationAngles(Unknown Source) ~[ModelPlayerAPI.class:?]
at api.player.model.ModelPlayerAPI.setRotationAngles(Unknown Source) ~[ModelPlayerAPI.class:?]
at api.player.model.ModelPlayer.func_78087_a(Unknown Source) ~[ModelPlayer.class:?]
at mekanism.client.render.ModelCustomArmor$GlowArmor.func_78088_a(ModelCustomArmor.java:256) ~[ModelCustomArmor$GlowArmor.class:?]
at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:162) [boh.class:?]
at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23) [bok.class:?]
at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:164) [bnw.class:?]
at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:361) [bnw.class:?]
at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271) [bnn.class:?]
at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244) [bnn.class:?]
at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471) [bma.class:?]
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224) [blt.class:?]
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) [blt.class:?]
at net.minecraft.client.Minecraft.func_71411_J(Unknown Source) [bao.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

**Comment by micdoodle8** [comment]
Hmm, strange error. I'll commit a quick fix to stop the crash, but Mekanism glow armor *appears* to be calling something it shouldn't.

**Comment by SvEgiiVEteR** [comment]
similar problem ..
when you look down all the good
sometimes when you look into the distance
It begins the hard spamming of this error in the log
http://hastebin.com/dobepibaku.hs
galacticraft/mekanism
PlayerAPI/RenderPlayerAPI/RenderPlayerAPIEnhancer.
exists a solution?
Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10
OF C1
Mekanism-1.7.10-8.1.7.255
GalacticraftCore-1.7-3.0.12.407

**Comment by radfast** [comment]
Thanks @SvEgiiVEteR - I can fix this tomorrow I think, it needs a similar fix to the one micdoodle8 made already.  Again, the reason this happens is that Glow Armor is doing something strange, I guess those mobs you listed are all able to spawn wearing Glow Armor.

I'll post again when this is fixed.

**Comment by plaguewolf** [comment]
from what i under stood, it was actually PlayerAPIEnhancer causing the derp. PAE was taking anything and everything that modified armour, and casting it in its own instance to try and mitigate inter-mod derps with things like custom hitboxes, smart moving, things that alter the way the player model, etc, works.

**Comment by SvEgiiVEteR** [comment]
@radfast 
not sure but it seems
exclude
-mekanism.client.renderer.ModelCustomArmor
in render_player_api_Enhancer_classnames.txt
help

PS
I was just one crash with the class
micdoodle8.mods.galacticraft.core.client.model.ModelPlayerBaseGC
can not reproduce..

**Comment by plaguewolf** [comment]
yeah, it never caused a crash for me, but whenever i got near a skeleton wearing the glowstone armor, my logs would get spammed with errors. some 100 lines or so of errors

**Comment by dj3520** [comment]
Have you read the contributing guidelines? I believe it explains why GC
appears in the crash.

**Comment by radfast** [comment]
No no, @dj3520.  This one is a valid issue report, and @SvEgiiVEteR and @plaguewolf are making valuable contributions.

**Comment by dj3520** [comment]
Ah sorry then, false alarm
