### ISSUE TITLE
getFluidID [Errors]

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1871]
Console clogged errors:
Version: GalacticraftCore-Dev-1.7-3.0.12.178.jar (363)

```
[03:35:24] [Server thread/ERROR] [Galacticraft]: Forge error when sending network packet to nearby players - this is not a Galacticraft bug, does another mod make fake players?
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.sendToAllAround(GalacticraftChannelHandler.java:96)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced.updateEntity(TileEntityAdvanced.java:61)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.tile.TileEntityParaChest.updateEntity(TileEntityParaChest.java:232)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.World.updateEntities(World.java:2160)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:515)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:703)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.network.NetworkUtil.writeFluidTank(NetworkUtil.java:474)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.network.NetworkUtil.encodeData(NetworkUtil.java:81)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.network.PacketDynamic.encodeInto(PacketDynamic.java:70)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.encodeInto(GalacticraftChannelHandler.java:41)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.encodeInto(GalacticraftChannelHandler.java:17)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
[03:35:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 18 more
```

**Comment by dj3520** [comment]
List of other mods?

**Comment by BlesseNtumble** [comment]
GC3
GalaxySpace
IC2

**Comment by micdoodle8** [comment]
Forge version?

**Comment by BlesseNtumble** [comment]
version = "1.7.10-10.13.4.1448-1.7.10"

**Comment by micdoodle8** [comment]
Hmm that's strange. Did this just come up recently? Do you know which change triggered it?

**Comment by BlesseNtumble** [comment]
Well, probably the last build, where there were changes to oil and fuel.
