### ISSUE TITLE
The fuel Loader causes minecraft to crash when buildcraft is installed

### ISSUE THREAD

**Issue by LucidityZero** [micdoodle8/Galacticraft#1902]
Buildcraft version 7.0.23 conflicts with galacticraft version 1.7-3.0.6.232

**Comment by LucidityZero** [comment]
I will try to add the crash report as soon as possible

**Comment by LucidityZero** [comment]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 9/27/15 2:59 AM
Description: Ticking block entity

io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.sendToAllAround(GalacticraftChannelHandler.java:93)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced.func_145845_h(TileEntityAdvanced.java:61)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.core.network.NetworkUtil.encodeData(NetworkUtil.java:173)
	at micdoodle8.mods.galacticraft.core.network.PacketDynamic.encodeInto(PacketDynamic.java:70)
	at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.encodeInto(GalacticraftChannelHandler.java:39)
	at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.encodeInto(GalacticraftChannelHandler.java:15)
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at micdoodle8.mods.galacticraft.core.network.GalacticraftChannelHandler.sendToAllAround(GalacticraftChannelHandler.java:93)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced.func_145845_h(TileEntityAdvanced.java:61)

-- Block entity being ticked --
Details:
	Name: Dummy Block // micdoodle8.mods.galacticraft.core.tile.TileEntityMulti
	Block type: ID #693 (tile.dummyblock // micdoodle8.mods.galacticraft.core.blocks.BlockMulti)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (41,69,-2922), Chunk: (at 9,4,6 in 2,-183; contains blocks 32,0,-2928 to 47,255,-2913), Region: (0,-6; contains chunks 0,-192 to 31,-161, blocks 0,0,-3072 to 511,255,-2561)
	Actual block type: ID #693 (tile.dummyblock // micdoodle8.mods.galacticraft.core.blocks.BlockMulti)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New Worldttrttet
	All players: 1 total; [GCEntityPlayerMP['LucidityZero'/138, l='New Worldttrttet', x=38.19, y=69.00, z=-2921.21]]
	Chunk stats: ServerChunkCache: 545 Drop: 0
	Level seed: 1960619828128133831
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-4,64,-164), Chunk: (at 12,4,12 in -1,-11; contains blocks -16,0,-176 to -1,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 114678 game time, 174973 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 57741 (now: false), thunder time: 149815 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_10-ea, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 194146632 bytes (185 MB) / 777773056 bytes (741 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 Optifine OptiFine_1.7.10_HD_C1 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	bdlib{1.9.2.104} [BD Lib] (bdlib-1.9.2.104-mc1.7.10.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.23} [BuildCraft] (buildcraft-7.0.23-core.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.23} [Buildcraft Transport] (buildcraft-7.0.23-transport.jar) 
	UCHIJAAAA	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
	UCHIJAAAA	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	electrometrics{0.1.1} [Electrometrics] (Electrometrics-1.7.10-0.1.1.jar) 
	UCHIJAAAA	EE3{0.3.507} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.507.jar) 
	UCHIJAAAA	exnihilo{1.38-46} [Ex Nihilo] (Ex-Nihilo-1.38-46.jar) 
	UCHIJAAAA	IC2{2.2.657-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.6} [Galacticraft Core] (GalacticraftCore-1.7-3.0.6.232.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.6} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.6.232.jar) 
	UCHIJAAAA	advgenerators{0.9.18.113} [Advanced Generators] (generators-0.9.18.113-mc1.7.10.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAAAA	SSR{Alpha 0.9a} [Soul Shards: Reborn] (Soul-Shards-Reborn-Mod-1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity] (Universal-Electricity-Mod-1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|blueprints (1.4) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|core (1.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|events (1.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.0.23-core.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.0.23-core.jar
		* CoFHAPI (1.7.10R1.1.0) from Electrometrics-1.7.10-0.1.1.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from buildcraft-7.0.23-core.jar
		* CoFHAPI|item (1.7.10R1.1.0) from Electrometrics-1.7.10-0.1.1.jar
		* EE3-API|array (1.2) from EquivalentExchange3-1.7.10-0.3.507.jar
		* EE3-API|core (1.2) from EquivalentExchange3-1.7.10-0.3.507.jar
		* EE3-API|event (1.2) from EquivalentExchange3-1.7.10-0.3.507.jar
		* EE3-API|exchange (1.2) from EquivalentExchange3-1.7.10-0.3.507.jar
		* EE3-API|knowledge (1.2) from EquivalentExchange3-1.7.10-0.3.507.jar
		* EE3-API|recipe (1.2) from EquivalentExchange3-1.7.10-0.3.507.jar
		* EE3-API|util (1.2) from EquivalentExchange3-1.7.10-0.3.507.jar
		* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.6.232.jar
		* IC2API (1.0) from Industrial-Craft-2-Mod-Experimental-1.7.10.jar
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['LucidityZero'/138, l='New Worldttrttet', x=38.19, y=69.00, z=-2921.21]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by dj3520** [comment]
232? Try 375

**Comment by micdoodle8** [comment]
Please re-open if the issue persists with GC build 375.

**Comment by LucidityZero** [comment]
It still persists and has the exact same crash report

**Comment by micdoodle8** [comment]
I need the new crash report, it's impossible that it's the exact same crash report because the point in the code that the crash report is pointing to has been changed.

**Comment by Youjust** [comment]
Buildcraft is loaded on my game, as well as the latest (375) version of GC. Fuel loaders don't crash me.

**Comment by coolmodi** [comment]
Maybe try a current BC version? I haven't had any problems with 7.0.26 or the current 7.1.12 together with GC 344 and now 400/402.

**Comment by Youjust** [comment]
Well, yes, but now I'm running the *latest* latest version and still no crashes.

**Comment by micdoodle8** [comment]
Okay, please re-open this issue if the problem re-occurs with the latest version @LucidityZero
