### ISSUE TITLE
Doesn't Even Load crashes on launcher load

### ISSUE THREAD

**Issue by Bowen2404** [micdoodle8/Galacticraft#1908]
crash report:
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[07:42:30] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[07:42:30] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[07:42:30] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[07:42:30] [main/INFO] [FML]: Forge Mod Loader version 7.99.32.1517 for Minecraft 1.7.10 loading
[07:42:30] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Mac OS X:x86_64:10.11, installed at /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
[07:42:30] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07:42:30] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.DepLoader$DepLoadInst:<init>:333]: MicdoodleCore searching for dependencies in mods file: /Users/Bowen/Library/Application Support/minecraft/mods
[07:42:31] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07:42:31] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[07:42:31] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[07:42:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[07:42:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[07:42:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[07:42:32] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[07:42:32] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[07:42:32] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[07:42:32] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[07:42:32] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[07:42:33] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[07:42:33] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[07:42:33] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[07:42:33] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[07:42:33] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[07:42:33] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[07:42:33] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[07:42:33] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[07:42:33] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[07:42:33] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[07:42:33] [main/INFO] [STDERR]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1777]: Potential problem: Galacticraft did not complete injection of bytecode into: sv (0 / 1)
[07:42:34] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: sa (1 / 1)
[07:42:34] [main/INFO] [STDERR]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1777]: Potential problem: Galacticraft did not complete injection of bytecode into: sa (0 / 1)
[07:42:34] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: bdi (1 / 1)
[07:42:34] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: bdi (1 / 1)
[07:42:34] [main/INFO]: Setting user: Bowen2404
[07:42:34] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: xk (1 / 1)
[07:42:34] [main/INFO] [STDERR]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1777]: Potential problem: Galacticraft did not complete injection of bytecode into: xk (0 / 1)
[07:42:35] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/monster/EntitySnowman
	at net.minecraft.block.Block.func_149671_p(Block.java:293) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.monster.EntitySnowman
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
	at net.minecraft.block.Block.func_149671_p(Block.java:293) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/monster/EntityGolem
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_31]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
	at net.minecraft.block.Block.func_149671_p(Block.java:293) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.monster.EntityGolem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_31]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
	at net.minecraft.block.Block.func_149671_p(Block.java:293) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file net/minecraft/entity/monster/EntityGolem
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_31]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_31]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
	at net.minecraft.block.Block.func_149671_p(Block.java:293) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Exception in thread "main" [07:42:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[07:42:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[07:42:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[07:42:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[07:42:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:968)
[07:42:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[07:42:35] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Bowen2404** [comment]
I'm not really good at coding but I tried looking at the crash report and i think the problem is The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft. Though I have no idea what to do :-1:

**Comment by micdoodle8** [comment]
You're running two versions of MicdoodleCore in your client.

**Comment by Bowen2404** [comment]
thanks

**Comment by Bowen2404** [comment]
whoops

**Comment by felipe15y** [comment]
thanks
