### ISSUE TITLE
[1.6.4] [Out-dated Forge version] Crash on start

### ISSUE THREAD

**Issue by DeezBlocks** [micdoodle8/Galacticraft#1950]
I install forge 1.6.2 then play, it works, I follow a vid on how to install galacticraft, finished.
I go to the launcher make the version forge.1.6.4yadayadayada
Whtn i hit play the game is starting with the mojang screen, then it crashes.
it says there was a mod error and I've reinstalled the mod & forge many times.
it keeps crashing.
ReportVVVVV

---- Minecraft Crash Report ----
// There are four lights!

Time: 11/22/15 2:32 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/ZombieEvent$SummonAidEvent
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:149)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:521)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:181)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:471)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:806)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/ZombieEvent$SummonAidEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetPublicMethods(Class.java:2894)
	at java.lang.Class.getMethods(Class.java:1607)
	at net.minecraftforge.event.EventBus.register(EventBus.java:33)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:540)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:194)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:105)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:520)
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.ZombieEvent$SummonAidEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:171)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 124897976 bytes (119 MB) / 228229120 bytes (217 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.3.883 Minecraft Forge 9.11.0.883 6 mods loaded, 6 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{6.4.3.883} [Forge Mod Loader] (minecraftforge-9.11.0.883.jar) Unloaded->Constructed->Pre-initialized
	Forge{9.11.0.883} [Minecraft Forge] (minecraftforge-9.11.0.883.jar) Unloaded->Constructed->Pre-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{2.0.14} [Galacticraft Core] (Galacticraft-1.6.4-2.0.14.1098.jar) Unloaded->Constructed->Errored
	GalacticraftMars{2.0.14} [Galacticraft Mars] (Galacticraft-Planets-1.6.4-2.0.14.1098.jar) Unloaded->Constructed->Errored

**Comment by p9n6ce** [comment]
having same problem please help :-(

**Comment by radfast** [comment]
Try a more recent version of Forge for Minecraft 1.6.4
http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.6.4.html
and let us know if you still have this problem.

It's hard to imagine where you found such an old version of Forge - are you using a modpack?

**Comment by p9n6ce** [comment]
I found out that it was a compatibility error with windows 10 on the
internet and my friend was having the same problem and was using
Galacticraft on its own

**Comment by radfast** [comment]
Thanks @p9n6ce 

@DeezBlocks I hope that helps you - maybe you can find versions of the Minecraft launcher and Forge which are compatible with Windows 10.
