### ISSUE TITLE
Missing dimension provider crash

### ISSUE THREAD

**Issue by BionicFelps** [micdoodle8/Galacticraft#1962]
Happens intermittently upon loading into world, works fine most of the time, but randomly get this.

Various warnings:
~~Optifine.
~~Tons of mods
The error is also not reliable, so it's hard to say if I just remove Optifine or other "unfriendly" mods such as chickenbones (also mentioned in the error) whether or not it's still occurring...

Full log:
http://minimatech.bionicsquirrels.com/files/fullForgeLogGalacticraftError.tar.bz2 (May need something like winrar to open that if you're on windows. The log was too big for a pastebin site)

Crash-Report:

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 12/11/15 2:52 AM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Could not get provider type for dimension -19, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.shouldLoadSpawn(DimensionManager.java:268)
	at codechicken.chunkloader.ChunkLoaderManager.cleanChunks(ChunkLoaderManager.java:745)
	at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:755)
	at codechicken.chunkloader.ChunkLoaderEventHandler.worldTick(ChunkLoaderEventHandler.java:32)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_710_ChunkLoaderEventHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.19.0-39-generic
	Java Version: 1.8.0_45-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 800420496 bytes (763 MB) / 2736783360 bytes (2610 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms1024m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 51, tcache: 77, allocated: 1, tallocated: 17
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_C1 146 mods loaded, 146 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.20.38} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	dynamicswordskills{1.7.10-1.6.5} [Dynamic Sword Skills] (1.7.10-dynamicswordskills-1.6.5.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	Automagy{0.27} [Automagy] (Automagy-1.7.10-0.27.jar) 
	UCHIJAAAA	BetterFoliage{1.0.15} [Better Foliage] (BetterFoliage-mc1.7-1.0.15.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	BiomesOPlenty{2.0.2} [Biomes O' Plenty] (BiomesOPlenty-1.7.2-2.0.2.932-universal.jar) 
	UCHIJAAAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAAAA	Forestry{4.2.1.48} [Forestry for Minecraft] (forestry_1.7.10-4.2.1.48.jar) 
	UCHIJAAAA	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHIJAAAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	Botania{r1.7-237} [Botania] (Botania r1.7-237.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	OpenComputers{1.5.20.38} [OpenComputers] (OpenComputers-MC1.7.10-1.5.20.38-universal.jar) 
	UCHIJAAAA	CompactMachines{1.7.10-1.21} [Compact Machines] (compactmachines-1.7.10-1.21.jar) 
	UCHIJAAAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
	UCHIJAAAA	decorativemarble{Beta 1.1710.3} [Decorative Marble] (decorativemarble-1.1710.3.jar) 
	UCHIJAAAA	decorativechimney{Beta 1.1710.3} [Decorative Chimney] (decorativechimney-1.1710.3.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.6.2} [Immersive Engineering] (ImmersiveEngineering-0.6.2.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	MagicBees{1.7.10-2.4.0} [Magic Bees] (magicbees-1.7.10-2.4.0.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V9b.jar) 
	UCHIJAAAA	Eln{50} [Electrical Age] (ElectricalAge_BETA-1.10_r50.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.421_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.421_beta.jar) 
	UCHIJAAAA	EnderZoo{1.7.10-1.0.15.32} [Ender Zoo] (EnderZoo-1.7.10-1.0.15.32.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	TSteelworks{1.7.10-1.1.2} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.2-19.jar) 
	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAA	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.3.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.571} [Forbidden Magic] (Forbidden Magic-1.7.10-0.571.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375.jar) 
	UCHIJAAAA	GalaxySpace{2.6} [GalaxySpace] (GalaxySpace-2.6 BETA.jar) 
	UCHIJAAAA	gravestonemod{1.7.10} [Gravestones] (GraveStones 1.7.10 -3.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UCHIJAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar) 
	UCHIJAAAA	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	MekanismTools{8.1.7} [MekanismTools] (MekanismTools-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
	UCHIJAAAA	Morpheus{1.7.10-1.6.19} [Morpheus] (Morpheus-1.7.10-1.6.19.jar) 
	UCHIJAAAA	neiintegration{1.0.13} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.13.jar) 
	UCHIJAAAA	OmnisCore{0.1.0} [Omnis Core] (OmnisCore-1.7.10 - 0.0.6-universal.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	rftools{4.13} [RFTools] (rftools-4.13.jar) 
	UCHIJAAAA	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
	UCHIJAAAA	RouterReborn{1.2.0.35} [Router Reborn] (RouterReborn-1.7.10-1.2.0.35-universal.jar) 
	UCHIJAAAA	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UCHIJAAAA	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAA	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.7.5} [Storage Drawers] (StorageDrawers-1.7.10-1.7.5.jar) 
	UCHIJAAAA	TaintedMagic{1.1.6.4} [Tainted Magic] (TaintedMagic-1.1.6.4.jar) 
	UCHIJAAAA	benway_knowledge{0.1.5.1} [Thaumaturgical Knowledge] (Thaumaturgical Knowledge-0.1.5.1.jar) 
	UCHIJAAAA	TU{1.0} [Thaumic Upholstry] (Thaumic_Upholstery-1.2_1.7.10.jar) 
	UCHIJAAAA	thaumicenergistics{0.8.10.10} [Thaumic Energistics] (thaumicenergistics-0.8.10.10.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCHIJAAAA	thaumicinfusion{4.32} [Thaumic Infusion] (ThaumicInfusion-4.32.jar) 
	UCHIJAAAA	ThaumicPipes{1.2.00} [Thaumic Pipes] (ThaumicPipes-1.7.10 - 1.2.1b-universal.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	ThermalSmeltery{1.7.10-1.2.1} [Thermal Smeltery] (ThermalSmeltery-1.7.10-1.2.1.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAA	tinker_io{beta 1.4.2} [Tinker I/O] (tinker_io-1.7.10-beta 1.4.2.jar) 
	UCHIJAAAA	Torched{4.0.0} [Torched] (Torched-Mod-1.7.10.jar) 
	UCHIJAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	RedstoneArsenal: -[1.7.10]1.1.1-89
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.1.0-161
	EnderIO: Found the following problem(s) with your installation: "Optifine is installed. This is NOT supported." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['cooksters'/1323, l='New World', x=85.14, y=68.88, z=111.25]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by dj3520** [comment]
Try again without ChickenChunks

**Comment by BionicFelps** [comment]
I'll try to reproduce without ChickenChunks, but like I said I don't have a reliable way to initiate the crash...

**Comment by micdoodle8** [comment]
Curious to what makes you believe this is a Galacticraft issue. Unless you changed it in the config dimension id -19 isn't being used in this mod.

**Comment by BionicFelps** [comment]
-19 is from GalaxySpace (an addon, I realize unaffiliated officially with GalactiCraft), one of my friends who's usually in the know on this sort of thing when I mentioned the bug told me that I should report it to GalactiCraft dev... I asked him why and he seemed to believe that GalactiCraft overrides some of the dimension code...

So far I've not been able to reproduce without ChickenChunks btw... Which of course leads me to believe that this is somehow Chickenbones' fault, although I don't know why a chunkloading mod would be touching a dimension that's never been loaded yet >.> Maybe that's the problem, it goes there looking for chunkloaders and it freaks out cause something isn't initialized...

**Comment by dj3520** [comment]
Can you post a log without chickenchunks? Use pastebin or gist if it's too
big to put here

**Comment by BionicFelps** [comment]
https://gist.github.com/BionicFelps/75908d681a264e68379c

Loaded up, and entered a world, then took that snapshot of the log.

I've been working on the pack, changes you should know about:
*Added fastcraft (for testing purposes, not sure if I want to check back every three weeks when I release this, so I'll probably not have it in the final version (I plan on adhering to all mod licenses ofc))
*Removed gravestones (OpenBlocks already adds the functionality and seems to interfere with it)
*Some unrelated config changes mostly to work around other inter-mod issues.

**Comment by BionicFelps** [comment]
Don't want to make a new issue of it since it's on ichun to fix it (closed source mod), but thought I'd also point you to:
https://github.com/iChun/IssueTracker-Mods/issues/34

**Comment by radfast** [comment]
Thanks for reporting the RPT/Torch Rocket thing, I've commented on the iChun issue tracker.

With the dimension -19 issue, this is something that will have to be taken up with the GalaxySpace addon author.  It is not Galacticraft itself causing the problem, and this issue tracker is not for addons.  It is maybe just a question of configuring the addon properly to work with your other mods (i.e. not to use dimension -19).  I noticed this line in the startup log:

> Could not register dimension -19 - does it clash with another mod?  Change the ID in config.

**Comment by radfast** [comment]
In some cases these dimension ID conflict issues are caused by AE2's **Spatial Storage Cells**.  AE2 creates a new dimension for _every new storage cell_.  There may be a way to configure it to switch that off or to control which dimensions AE2 is allowed to use, but I am not an AE2 expert.
