### ISSUE TITLE
Oxygen Sealer NPE Crash

### ISSUE THREAD

**Issue by SirWilli** [micdoodle8/Galacticraft#2018]
hey,

the reported crash at https://github.com/micdoodle8/Galacticraft/issues/1803#issuecomment-170791948
just happened again with build 414a.

```
java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:359)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:92)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:47)
	at micdoodle8.mods.galacticraft.core.oxygen.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:64)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer.func_145845_h(TileEntityOxygenSealer.java:163)
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:359)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:92)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:47)
	at micdoodle8.mods.galacticraft.core.oxygen.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:64)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer.func_145845_h(TileEntityOxygenSealer.java:163)

-- Block entity being ticked --
Details:
	Name: Air Sealer // micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer
	Block type: ID #183 (tile.sealer // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenSealer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-10721,62,-11796), Chunk: (at 15,3,12 in -671,-738; contains blocks -10736,0,-11808 to -10721,255,-11793), Region: (-21,-24; contains chunks -672,-768 to -641,-737, blocks -10752,0,-12288 to -10241,255,-11777)
	Actual block type: ID #183 (tile.sealer // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenSealer)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
```

**Comment by radfast** [comment]
Oh sorry, looks like I accidentally rolled back that fix in https://github.com/micdoodle8/Galacticraft/commit/12d9143af49bc71b0c14e71ebb85048df1908605.

This will be fixed properly in new version 419 ... should be about 5 minutes :)

**Comment by radfast** [comment]
New version 419 is now available - you can download all three files with no ads from [here](http://ci.micdoodle8.com/job/Galacticraft-1.7/419/).

Sorry about recent changes causing crashes, I know how frustrating it is if your server keeps on crashing for players.  That should be the last of it, I hope.

**Comment by SirWilli** [comment]
Thanks. Probably need to push another update to FTB. (Already 3 updates in 2 days :/)
