### ISSUE TITLE
[Add-on + Dev] Custom Space Station not working?

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2021]
I attempt to teleport to Mars Space Station. Game not getting crash but it print an error log.
Sorry if this issue is a my mod problem. I'm not sure.

> [20:46:37] [Server thread/INFO] [Galacticraft]: Failed to find matching world for 'Mars Space Station 2'
[20:46:37] [Server thread/ERROR] [Galacticraft]: Error occurred when attempting to transfer entity to dimension: Mars Space Station 2
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.network.PacketSimple.handleServerSide(PacketSimple.java:870)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.channelRead0(GalacticraftPacketHandler.java:27)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.channelRead0(GalacticraftPacketHandler.java:1)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.processPacket(FMLProxyPacket.java:86)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
[20:46:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

**Comment by BlesseNtumble** [comment]
Hmm, My space station is functioning normally with the latest Dev build...
![1](http://6.firepic.org/6/images/2016-01/15/xoqcyikh5elv.png)

Build 231 Dev.

**Comment by radfast** [comment]
@SteveKung:
* To be reachable now, all dimensions must have their name registered in WorldUtil.dimNames.
* The registered name must be == ```worldProvider.getDimensionName()```.
* For Galacticraft core space stations the [```worldProviderOrbit.getDimensionName()```](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/dimension/WorldProviderOrbit.java#L483) is always "Space Station #".  Therefore [WorldUtil creates a string like that and registers it](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L622).  WorldUtil does not call ```worldProviderOrbit.getDimensionName()```.
* The reason not to call ```worldProviderOrbit.getDimensionName()``` is we do not want to create an instance of the WorldProvider, because to create the WorldProvider means the dimension must be loaded.

To fix this: change [WorldProviderOrbitMars](https://github.com/SteveKunG/More-Planets/blob/1.8/src/main/java/stevekung/mods/moreplanets/spacestation/mars/WorldProviderMarsOrbit.java#L60) to this: ``` return "Space Station " + this.spaceStationDimensionID;```

**Comment by SteveKunG** [comment]
Thank you very much. I will not change anything from WorldProviderOrbit O_o
