### ISSUE TITLE
[Doh!] Server crash with GC421 

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#2029]
[Full log pastebin](http://pastebin.com/uAmNqkUk)
The interesting bit (a friend of mine says this is client code crashing on a server)

java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at net.minecraft.world.World.func_72867_j(World.java:4369) ~[ahb.class:?]
	at net.minecraft.world.World.getSunBrightnessFactor(World.java:2054) ~[ahb.class:?]
	at net.minecraft.world.WorldProvider.getSunBrightnessFactor(WorldProvider.java:383) ~[aqo.class:?]
	at net.minecraft.world.World.func_72967_a(World.java:2026) ~[ahb.class:?]
	at net.minecraft.world.World.func_72966_v(World.java:3240) ~[ahb.class:?]
	at net.minecraft.world.World.<init>(World.java:489) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
	... 11 more
Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51) ~[KCauldron-1.7.10-1492.152.jar:1.7.10-1492.152]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
	... 11 more
[11:50:12] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
	at net.minecraft.world.World.func_72867_j(World.java:4369) ~[ahb.class:?]
	at net.minecraft.world.World.getSunBrightnessFactor(World.java:2054) ~[ahb.class:?]
	at net.minecraft.world.WorldProvider.getSunBrightnessFactor(WorldProvider.java:383) ~[aqo.class:?]
	at net.minecraft.world.World.func_72967_a(World.java:2026) ~[ahb.class:?]
	at net.minecraft.world.World.func_72966_v(World.java:3240) ~[ahb.class:?]
	at net.minecraft.world.World.<init>(World.java:489) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51) ~[KCauldron-1.7.10-1492.152.jar:1.7.10-1492.152]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 13 more

**Comment by dj3520** [comment]
GC419 is OK
GC420 is not OK
suspecting 11e243c9f1d1fd29ff86dd0e08c994e89020a94c

**Comment by radfast** [comment]
Please try 422, should fix this.   I apologise for making a new crash, I was testing all my recent changes in SSP only because that's where the Cargo Rocket problems were.

**Comment by dj3520** [comment]
No problem. Everyone does something like this at least once in their
lifetime, probably more.
