### ISSUE TITLE
Client Hang on creation of Singleplayer world (Latest GC)

### ISSUE THREAD

**Issue by DraksterAU** [micdoodle8/Galacticraft#2097]
Hi All

Getting the below 'error' in singleplayer using Forge 1566 for 1.7.10...

Not sure what it means, so I'm logging it here.... but it prevents me from creation of an SP world.

```
> 
> > [10:45:44] [Server thread/DEBUG] [FML/]: The fluid GalacticraftMars:bacterialsludge has been selected as the default fluid for bacterialsludge
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IllegalArgumentException: value already present: null
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fluids.FluidRegistry.loadFluidDefaults(FluidRegistry.java:113)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fluids.FluidRegistry.loadFluidDefaults(FluidRegistry.java:318)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.common.ForgeModContainer.readData(ForgeModContainer.java:323)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:124)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.World.<init>(World.java:220)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at WorldServerOF.<init>(WorldServerOF.java:69)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
> > [10:45:44] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> > 
```

**Comment by DraksterAU** [comment]
Client/idiot user issie.
