### ISSUE TITLE
Random Crash after installation of Latest GC

### ISSUE THREAD

**Issue by DraksterAU** [micdoodle8/Galacticraft#2099]
Hi All,

I use KCauldron and have seen this once so far.... but its the first crash we have ever had in this server install (more than a month)... and happened 5 minutes after installing GC.

Running KCauldron B185... there are issues in higher versions that haven't been resolved yet.

```
> Time: 19/02/16 20:10
> Description: Exception in server tick loop
> 
> java.lang.NullPointerException: Exception in server tick loop
>         at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:460)
>         at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1009)
>         at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:530)
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
>         at java.lang.Thread.run(Thread.java:745)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
>         Minecraft Version: 1.7.10
>         KCauldron Version: pw.prok:KCauldron:1.7.10-1614.185
>         Plugins: Craftconomy3, Buycraft, BanManager, MultiWorld, RewardVoting, DeathMessages, IslandCraft, TimeLock, ItemRestrict, AsyncWorldEditInjector, dynmap, WorldEdit, Nordic, Essentials, ClearLag, BukkitCompat, WorldBorder, Votifier, HothGenerator, MultiCommand, Multiverse-Core, ProtocolLib, AsyncWorldEdit, DiscordSRV, WeatherLock, PermissionsEx, SQLibrary, Whitelist, Vault, MassiveCore, UltimateArena, StockMarket, Herochat, WorldGuard, Factions, EssentialsGeoIP, EssentialsAntiBuild, FactionsPlus, BungeeChatClient, AutorunCommands, Prism, EssentialsSpawn, boosCooldowns, Inquisitor, LegendQuest, MCBans, HeroBounty, Autorank, Jobs, Citizens, AdvancedAchievements, Dynmap-HeroChat, GlobalMarket, BukkitSpeak, Transporter
>         Disabled Plugins:
>         Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
>         Java Version: 1.8.0_66, Oracle Corporation
>         Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>         Memory: 2710401056 bytes (2584 MB) / 11598299136 bytes (11061 MB) up to 27962376192 bytes (26667 MB)
>         JVM Flags: 2 total; -XX:MaxPermSize=512M -Xmx30000M
>         AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>         IntCache: cache: 1, tcache: 0, allocated: 12, tallocated: 96
>         FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 99 mods loaded, 99 mods active
>         States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>         UCHIJAAAA       mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
>         UCHIJAAAA       FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.185.jar)
>         UCHIJAAAA       Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.185.jar)
>         UCHIJAAAA       kimagine{0.2} [KImagine] (minecraft.jar)
>         UCHIJAAAA       appliedenergistics2-core{rv2-beta-28} [AppliedEnergistics2 Core] (minecraft.jar)
>         UCHIJAAAA       CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
>         UCHIJAAAA       Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar)
>         UCHIJAAAA       NotEnoughItems{1.0.5.118} [Not Enough Items] (nei-1.0.5.118.jar)
>         UCHIJAAAA       OpenComputers|Core{1.5.22.46} [OpenComputers (Core)] (minecraft.jar)
>         UCHIJAAAA       OpenEye{0.6} [OpenEye] (openeye-0.6.jar)
>         UCHIJAAAA       OpenModsCore{0.6} [OpenModsCore] (minecraft.jar)
>         UCHIJAAAA       <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
>         UCHIJAAAA       IC2{2.2.807-experimental} [IndustrialCraft 2] (ic2-2.2.807.jar)
>         UCHIJAAAA       ImmibisCore{59.0.8} [Immibis Core] (immibiscore-59.0.8.jar)
>         UCHIJAAAA       AdvancedMachines{59.0.2} [Advanced Machines] (advancedmachines-59.0.2.jar)
>         UCHIJAAAA       AdvancedRepulsionSystems{59.0.2} [Advanced Repulsion Systems] (advancedrepulsionsystems-59.0.2.jar)
>         UCHIJAAAA       AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (advancedsolarpanels-3.5.1.jar)
>         UCHIJAAAA       appliedenergistics2{rv2-beta-28} [Applied Energistics 2] (appliedenergistics-2b28.jar)
>         UCHIJAAAA       CoFHCore{1.7.10R3.0.3} [CoFH Core] (cofhcore-3.0.3.jar)
>         UCHIJAAAA       BuildCraft|Core{7.1.14} [BuildCraft] (bc-7.1.14.jar)
>         UCHIJAAAA       BuildCraft|Builders{7.1.14} [BC Builders] (bc-7.1.14.jar)
>         UCHIJAAAA       BuildCraft|Transport{7.1.14} [BC Transport] (bc-7.1.14.jar)
>         UCHIJAAAA       BuildCraft|Energy{7.1.14} [BC Energy] (bc-7.1.14.jar)
>         UCHIJAAAA       BuildCraft|Silicon{7.1.14} [BC Silicon] (bc-7.1.14.jar)
>         UCHIJAAAA       BuildCraft|Robotics{7.1.14} [BC Robotics] (bc-7.1.14.jar)
>         UCHIJAAAA       BuildCraft|Factory{7.1.14} [BC Factory] (bc-7.1.14.jar)
>         UCHIJAAAA       Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (mantle-0.3.2b.jar)
>         UCHIJAAAA       Natura{2.2.0} [Natura] (natura-2.2.0.1.jar)
>         UCHIJAAAA       Forestry{4.1.1.46} [Forestry for Minecraft] (forestry-4.1.1.46.jar)
>         UCHIJAAAA       ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (thermalfoundation-1.2.0.102.jar)
>         UCHIJAAAA       ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (thermalexpansion-4.0.3.218.jar)
>         UCHIJAAAA       BuildCraft|Compat{7.1.3} [BuildCraft Compat] (bc-compat-7.1.3.jar)
>         UCHIJAAAA       BiblioCraft{1.9.2} [BiblioCraft] (bibliocraft-1.9.2.jar)
>         UCHIJAAAA       CarpentersBlocks{3.3.7} [Carpenter's Blocks] (carpenters-3.3.7.jar)
>         UCHIJAAAA       Railcraft{9.8.0.0} [Railcraft] (railcraft-9.8.0.0.jar)
>         UCHIJAAAA       ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
>         UCHIJAAAA       chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar)
>         UCHIJAAAA       CompactSolars{4.4.39.315} [Compact Solar Arrays] (compactsolars-4.4.39.315.jar)
>         UCHIJAAAA       ComputerCraft{1.75} [ComputerCraft] (computercraft-1.7.5.jar)
>         UCHIJAAAA       customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar)
>         UCHIJAAAA       desertcraft{1.7.2b} [Pam's DesertCraft] (desertcraft-1.7.10a.jar)
>         UCHIJAAAA       dlr{2.4.0} [Don's Lightning Rod] (donslightningrodmod.jar)
>         UCHIJAAAA       Dynmap{2.1-104} [Dynmap] (dynmap.jar)
>         UCHIJAAAA       ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar)
>         UCHIJAAAA       flansmod{4.9.0} [Flan's Mod] (flansmod-4.9.0.jar)
>         UCHIJAAAA       cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (furnituremod-3.4.7.jar)
>         UCHIJAAAA       GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.442.jar)
>         UCHIJAAAA       GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.442.jar)
>         UCHIJAAAA       GraviSuite{1.7.10-2.0.3} [Graviation Suite] (gravisuite-2.0.3.jar)
>         UCHIJAAAA       GregsBlocks{1.5.2} [Greg's Blocks] (GregsBlocks-1.5.2-mc1.7.10.jar)
>         UCHIJAAAA       GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar)
>         UCHIJAAAA       HoloInventory{1.8.3.86} [HoloInventory] (holoinventory-1.8.3.86.jar)
>         UCHIJAAAA       LLadders{0.5.0} [Luppii's Ladders] (lupisladders-0.5.0.jar)
>         UCHIJAAAA       MarketCompanion{2.0.0} [MarketCompanion] (marketcompanion-2.0.1.jar)
>         UCHIJAAAA       RadixCore{2.1.1} [RadixCore] (radix-core-2.1.1.jar)
>         UCHIJAAAA       MCA{1.7.10-5.1.1.0} [Minecraft Comes Alive] (mca-5.1.1.0.jar)
>         UCHIJAAAA       mcheli{0.9.3} [MC Helicopter] (mcheli)
>         UCHIJAAAA       mediccraft{1.0.1 - 1.7.2} [MedicCraft] (mediccraft-1.0.1.jar)
>         UCHIJAAAA       Mekanism{8.1.7} [Mekanism] (mekanism-8.1.7.255.jar)
>         UCHIJAAAA       MekanismGenerators{8.1.7} [MekanismGenerators] (mekanismgenerators-8.1.7.255.jar)
>         UCHIJAAAA       MekanismTools{8.1.7} [MekanismTools] (mekanismtools-8.1.7.255.jar)
>         UCHIJAAAA       numina{0.4.0.119} [Numina] (numina-0.4.0.119.jar)
>         UCHIJAAAA       MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar)
>         UCHIJAAAA       ProjRed|Core{4.5.12.64} [ProjectRed] (projectredbase-4.5.12.64.jar)
>         UCHIJAAAA       powersuits{0.11.0.290} [MachineMuse's Modular Powersuits] (mps-0.11.0.290.jar)
>         UCHIJAAAA       NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40.jar)
>         UCHIJAAAA       NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40.jar)
>         UCHIJAAAA       NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40.jar)
>         UCHIJAAAA       NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40.jar)
>         UCHIJAAAA       NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40.jar)
>         UCHIJAAAA       NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40.jar)
>         UCHIJAAAA       NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40.jar)
>         UCHIJAAAA       Oceancraft{1.4.1} [Oceancraft] (oceancraft-1.4.1.jar)
>         UCHIJAAAA       OpenMods{0.6} [OpenMods] (openmodslib-0.6.jar)
>         UCHIJAAAA       OpenBlocks{1.3} [OpenBlocks] (openblocks-1.3.jar)
>         UCHIJAAAA       ProjRed|Transmission{4.5.12.64} [ProjectRed-Transmission] (projectredintegration-4.5.12.64.jar)
>         UCHIJAAAA       StargateTech2{0.7.7-Alpha} [StargateTech 2] (stargatetech-0.7.8.jar)
>         UCHIJAAAA       OpenComputers{1.5.22.46} [OpenComputers] (OpenComputers-1.5.22.46.jar)
>         UCHIJAAAA       openmodularturrets{2.1.8-199} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.8-199.jar)
>         UCHIJAAAA       opensecurity{1.0.90} [OpenSecurity] (OpenSecurity-1.0.90.jar)
>         UCHIJAAAA       ProjectBlue{1.1.4} [Project Blue] (ProjectBlue-1.1.4-mc1.7.10.jar)
>         UCHIJAAAA       ProjRed|Integration{4.5.12.64} [ProjectRed-Integration] (projectredintegration-4.5.12.64.jar)
>         UCHIJAAAA       ProjRed|Illumination{4.5.12.64} [ProjectRed-Illumination] (projectredlighting-4.5.12.64.jar)
>         UCHIJAAAA       ProjRed|Expansion{4.5.12.64} [ProjectRed-Expansion] (projectredmechanical-4.5.12.64.jar)
>         UCHIJAAAA       ProjRed|Transportation{4.5.12.64} [ProjectRed-Transportation] (projectredmechanical-4.5.12.64.jar)
>         UCHIJAAAA       ProjRed|Exploration{4.5.12.64} [ProjectRed-Exploration] (projectredworld-4.5.12.64.jar)
>         UCHIJAAAA       securitycraft{v1.8.1} [SecurityCraft] (securitycraft-1.8.1.jar)
>         UCHIJAAAA       SGCraft{1.9.4} [Greg's SG Craft] (SGCraft-StargateMC.jar)
>         UCHIJAAAA       Waila{1.5.10} [Waila] (waila-1.5.10.jar)
>         UCHIJAAAA       TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (tinkersconstruct-1.8.8.jar)
>         UCHIJAAAA       bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar)
>         UCHIJAAAA       Treecapitator{1.7.10} [Treecapitator] (treecapitator-2.0.4.jar)
>         UCHIJAAAA       Tubestuff{59.0.3} [Tubestuff] (tubestuff-59.0.3.jar)
>         UCHIJAAAA       WR-CBE|Core{1.4.1.9} [WR-CBE Core] (wr-cbe-1.4.1.9.jar)
>         UCHIJAAAA       WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (wr-cbe-1.4.1.9.jar)
>         UCHIJAAAA       WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (wr-cbe-1.4.1.9.jar)
>         UCHIJAAAA       McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
>         UCHIJAAAA       xan_personalizedRecipes{beta_1.7.10-2.1.0} [Personalized Recipes] (Personalized-Recipes-2.3.0.jar)
>         UCHIJAAAA       ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
>         OpenModsLib crash transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
>         AE2 Version: beta rv2-beta-28 for Forge 10.13.2.1291
>         CoFHCore: -[1.7.10]3.0.3-303
>         Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
>         ThermalFoundation: -[1.7.10]1.2.0-102
>         ThermalExpansion: -[1.7.10]4.0.3B1-218
>         TConstruct Environment: Environment healthy.
>         Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
> Bukkit, Cauldron, or other Bukkit replacement
> These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
>         AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
>         Profiler Position: N/A (disabled)
>         Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>         Player Count: 3 / 1024; [EntityPlayerMP['mainesi'/305, l='P2Y-321', x=-427.10, y=66.56, z=1068.50](mainesi at -427.1000061035156,66.5625,1068.5), EntityPlayerMP['Bysokar'/197, l='P2Y-321', x=-383.93, y=31.00, z=526.80](Bysokar at -383.92690686901597,31.0,526.7956355317816), GCEntityPlayerMP['random09'/65292, l='random09-homeworld-MilkyWay', x=178.77, y=57.00, z=240.57](random09 at 178.7680772363761,57.0,240.56603004386776)]
>         Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
> 
```

**Comment by radfast** [comment]
I don't see anything in the crash report with any connection with Galacticraft.

func_73151_a is not something we are interacting with - it's the server's saveChunks() method.

Just because this happened after you installed Galacticraft (and you had no other crashes for a month?!) does not mean Galacticraft is the cause - I'm not saying 100% Galacticraft is **not** the cause, but there's nothing here I can work with.

If it happens again, and further testing shows it happens only when Galacticraft is installed, then I can take another look at this but right now I don't see anything for me to investigate / fix.
