### ISSUE TITLE
Space Station Fail? Build 451

### ISSUE THREAD

**Issue by Cracks777** [micdoodle8/Galacticraft#2145]
[12:18:38] [Server thread/INFO] [Galacticraft/]: Failed to find matching world for 'satellite.spaceStation.overworld'
[12:18:38] [Server thread/ERROR] [Galacticraft/]: Error occurred when attempting to transfer entity to dimension: satellite.spaceStation.overworld
[12:18:38] [Server thread/WARN] [/]: java.lang.NullPointerException
[12:18:38] [Server thread/WARN] [/]: 	at micdoodle8.mods.galacticraft.core.network.PacketSimple.handleServerSide(PacketSimple.java:853)
[12:18:38] [Server thread/WARN] [/]: 	at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.channelRead0(GalacticraftPacketHandler.java:27)
[12:18:38] [Server thread/WARN] [/]: 	at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.channelRead0(GalacticraftPacketHandler.java:12)
[12:18:38] [Server thread/WARN] [/]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[12:18:38] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[12:18:38] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[12:18:38] [Server thread/WARN] [/]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:18:38] [Server thread/WARN] [/]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[12:18:38] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[12:18:38] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[12:18:38] [Server thread/WARN] [/]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[12:18:38] [Server thread/WARN] [/]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[12:18:38] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[12:18:38] [Server thread/WARN] [/]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[12:18:38] [Server thread/WARN] [/]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[12:18:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013)
[12:18:38] [Server thread/WARN] [/]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[12:18:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
[12:18:38] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
[12:18:38] [Server thread/WARN] [/]: 	at java.lang.Thread.run(Unknown Source)

**Comment by radfast** [comment]
Thank you for reporting.  Fixed in 452.

@SteveKunG @BlesseNtumble please check build 452 works OK with your mods - especially the space stations but check your planets also.  (Use **/dimensiontp** and check all destinations can be reached.)

**Comment by Cracks777** [comment]
thank you so much, Keep up the good work
