### ISSUE TITLE
More planets addon server launch error MC 1.7.10

### ISSUE THREAD

**Issue by iallexe** [micdoodle8/Galacticraft#2203]
Now I have dealt with other problems when it comes to servers such as conflicting IDs but this I have no clue how to fix. I believe this is a bug if I think about it since the problem seems to involve thermal padding. Anybody got any ideas?
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 5/29/16 1:11 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: stevekung/mods/moreplanets/core/items/ItemTier2ThermalPadding
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: stevekung/mods/moreplanets/core/items/ItemTier2ThermalPadding
	at stevekung.mods.moreplanets.core.MorePlanetsCore.preInit(MorePlanetsCore.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more
Caused by: java.lang.ClassNotFoundException: stevekung.mods.moreplanets.core.items.ItemTier2ThermalPadding
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 32 more
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/item/IItemThermal
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 34 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.api.item.IItemThermal
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at micdoodle8.mods.miccore.MicdoodleTransformer.startInjection(MicdoodleTransformer.java:1854)
	at micdoodle8.mods.miccore.MicdoodleTransformer.transformCustomAnnotations(MicdoodleTransformer.java:953)
	at micdoodle8.mods.miccore.MicdoodleTransformer.transform(MicdoodleTransformer.java:337)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 40 more

**Comment by dj3520** [comment]
Issues with More Planets should be posted there, not here.

**Comment by MJRLegends** [comment]
@iallexe update your version of galacticraft to latest version

**Comment by iallexe** [comment]
@dj3520 I am sorry for posting this here then. However I can't seem to find a More Planets thread on GitHub that doesn't direct me to micdoodle8/Galacticraft. Could you give me a link please?

**Comment by iallexe** [comment]
@MJRLegends It is the latest version.

**Comment by MJRLegends** [comment]
What version are you running of galacticraft

**Comment by iallexe** [comment]
@MJRLegends 1.7-3.0.12.375

**Comment by MJRLegends** [comment]
Thats not the latest version

**Comment by iallexe** [comment]
0_o as of when?

**Comment by iallexe** [comment]
Nvm sry it's a stupid question to ask. I'll search for a newer version then thank you.

**Comment by MJRLegends** [comment]
Your version was released on Oct 16, 2015, you should be getting versions from here https://ci.micdoodle8.com/job/Galacticraft-1.7/

**Comment by iallexe** [comment]
Once again thank you.

**Comment by iallexe** [comment]
@MJRLegends It works now thank you.
