### ISSUE TITLE
Ore dictionary Broken entrys

### ISSUE THREAD

**Issue by Matachusets** [micdoodle8/Galacticraft#2231]
Hello, from some ago i noticed in console this bug and search then on the log, here they are

[19:21:25] [Client thread/INFO] [FML/GalacticraftCore]: InvTweaks: net.minecraft.inventory.ContainerMerchant
[19:21:25] [Client thread/INFO] [FML/GalacticraftCore]: InvTweaks: net.minecraft.inventory.ContainerHopper
[19:21:25] [Client thread/INFO] [FML/GalacticraftCore]: InvTweaks: net.minecraft.inventory.ContainerEnchantment
[19:21:25] [Client thread/INFO] [FML/GalacticraftCore]: InvTweaks: net.minecraft.inventory.ContainerBrewingStand
[19:21:25] [Client thread/INFO] [FML/GalacticraftCore]: InvTweaks: net.minecraft.inventory.ContainerBeacon
[19:21:25] [Client thread/INFO] [battlegear2/GalacticraftCore]: M&B - Patching Class ItemInWorldManager (mx)
[19:21:25] [Client thread/INFO] [battlegear2/GalacticraftCore]:     Patching method tryUseItem in ItemInWorldManager
[19:21:25] [Client thread/INFO] [battlegear2/GalacticraftCore]: M&B - Patching Class ItemInWorldManager done
[19:21:25] [Client thread/INFO] [STDOUT/GalacticraftCore]: [api.player.server.ServerPlayerAPI:log:37]: Server Player 1.4 Created
[19:21:25] [Client thread/INFO] [STDOUT/GalacticraftCore]: [api.player.server.ServerPlayerAPI:register:792]: Server Player: registered GalacticraftCore
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name ingotCopper has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name ingotTin has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name ingotAluminum has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name compressedCopper has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name compressedTin has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name compressedAluminum has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name compressedSteel has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name compressedBronze has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name compressedIron has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name waferSolar has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name waferBasic has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name waferAdvanced has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name compressedMeteoricIron has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemMoon) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:244)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \* A broken ore dictionary registration with name ingotMeteoricIron has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemMoon) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:245)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[19:21:25] [Client thread/WARN] [FML/GalacticraftCore]: ****************************************
[19:21:25] [Client thread/TRACE] [GalacticraftCore/GalacticraftCore]: Sent event FMLPreInitializationEvent to mod GalacticraftCore

I m using GalactiCraft 3.012, right now dont know if this is the last stable version, also this bug is weird because, I have accesd to blocks mentioned, and can change then whit they variant of other mod using Ore dictioray converter mod, copper, tin, and alumium, ore blocks and ingots.

Great mod, keep up the good work!

**Comment by Yogs-antiCreeper** [comment]
This is happening to me too. I'm not sure how bad the bug (e.g. if it makes the game crash) as my modpack using it is broken for another reason (or maybe not, tbh I have no clue what I'm doing most of the time). I hope this gets fixed soon.

**Comment by radfast** [comment]
Fixed ever since Galacticraft version 3.0.12.404.  That was in November 2015.

https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md guideline 4
