### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Finermeerkat137** [micdoodle8/Galacticraft#2281]
does anyone know what caused this crash?

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 10/8/16 4:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:700)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:249)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ExceptionInInitializerError
	at micdoodle8.mods.galacticraft.core.client.ClientProxyCore.registerHandlers(ClientProxyCore.java:262)
	at micdoodle8.mods.galacticraft.core.client.ClientProxyCore.init(ClientProxyCore.java:213)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.init(GalacticraftCore.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:699)
	... 10 more
Caused by: java.lang.NumberFormatException: For input string: "minecraft"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at micdoodle8.mods.galacticraft.core.tick.GCCoreTickHandlerClient.<clinit>(GCCoreTickHandlerClient.java:94)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 96972880 bytes (92 MB) / 248446976 bytes (236 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.50.1,345 Minecraft Forge 9.11.1.1345 6 mods loaded, 6 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{6.4.50.1,345} [Forge Mod Loader] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{9.11.1.1345} [Minecraft Forge] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	GalacticraftCore{2.0.14} [Galacticraft Core] (Galacticraft-1.6.4-2.0.14.1084.jar) Unloaded->Constructed->Pre-initialized->Errored
	GalacticraftMars{2.0.14} [Galacticraft Mars] (Galacticraft-Planets-1.6.4-2.0.14.1084.jar) Unloaded->Constructed->Pre-initialized->Errored

**Comment by micdoodle8** [comment]
Sorry, the 1.6.4 version of Galacticraft isn't supported anymore.
