### ISSUE TITLE
[1.8.9] Requires Java 8 - crash when using Java 7 or earlier

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#2285]
```
java.lang.UnsupportedClassVersionError: micdoodle8/mods/miccore/MicdoodlePlugin : Unsupported major.minor version 52.0
>   at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_72]
>   at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
>   at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
>   at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
>   at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_72]
>   at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
>   at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
>   at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
>   at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_72]
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
>   at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
>   at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
>   at java.lang.Class.forName0(Native Method) ~[?:1.7.0_72]
>   at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_72]
>   at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:536) ~[forge-1.8.9-11.15.1.1902-1.8.9.jar:?]
>   at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:416) ~[forge-1.8.9-11.15.1.1902-1.8.9.jar:?]
>   at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246) ~[forge-1.8.9-11.15.1.1902-1.8.9.jar:?]
>   at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95) [forge-1.8.9-11.15.1.1902-1.8.9.jar:?]
>   at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72) [forge-1.8.9-11.15.1.1902-1.8.9.jar:?]
>   at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.8.9-11.15.1.1902-1.8.9.jar:?]
>   at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119) [forge-1.8.9-11.15.1.1902-1.8.9.jar:?]
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by micdoodle8** [comment]
What version of java are you using to run minecraft?

**Comment by BlesseNtumble** [comment]
7

**Comment by micdoodle8** [comment]
Updating to Java 8 is the quick-fix for this problem. I'll try to get Java 1.7 support working again.

**Comment by micdoodle8** [comment]
Going to close this, there's too much of a reliance on java 8+ in the current codebase. 

Since a lot of other mods require java 8+, we are definitely not alone in dropping java 7 support. 

P.S. For security reasons, java should be kept updated. For those who land here from google, you can find the latest version of java here: https://java.com/en/download/
