### ISSUE TITLE
Crash on the server

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2303]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.30-BETA.jar)
  MorePlanetsPlugin (bin)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 24/10/2559, 14:07 น.
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.block.Block.getCreativeTabToDisplayOn()Lnet/minecraft/creativetab/CreativeTabs;
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
    at net.minecraft.server.dedicated.DedicatedServer.startServer(DedicatedServer.java:115)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:508)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.getCreativeTabToDisplayOn()Lnet/minecraft/creativetab/CreativeTabs;
    at micdoodle8.mods.galacticraft.core.blocks.GCBlocks.registerSorted(GCBlocks.java:286)
    at micdoodle8.mods.galacticraft.core.blocks.GCBlocks.registerBlock(GCBlocks.java:267)
    at micdoodle8.mods.galacticraft.core.GalacticraftCore.registerOilandFuel(GalacticraftCore.java:465)
    at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:260)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 5 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 961886456 bytes (917 MB) / 1056309248 bytes (1007 MB) up to 1056309248 bytes (1007 MB)
    JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1902 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forgeSrc-1.8.9-11.15.1.1902-1.8.9.jar) 
    UCH Forge{11.15.1.1902} [Minecraft Forge](forgeSrc-1.8.9-11.15.1.1902-1.8.9.jar) 
    UCH Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCH nei{1.0} [nei](bin) 
    UCH NBTEdit{1.8.9-1.0} [In-game NBTEdit](bin) 
    UCE GalacticraftCore{4.0.0} [Galacticraft Core](bin) 
    UCE GalacticraftPlanets{4.0.0} [Galacticraft Planets](bin) 
    UCE MorePlanets{2.0.0} [More Planets](bin) 
    Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.30-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MorePlanetsPlugin (bin)
  stevekung.mods.moreplanets.core.asm.MorePlanetsTransformer
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by micdoodle8** [comment]
I'm assuming this was a crash in your workspace. If you add a new Block/Item to the galacticraft tab you need to implement ISortableBlock or ISortableItem

**Comment by SteveKunG** [comment]
Still getting crash without my mod loaded. And I didn't adding a new block or item into Galacticraft tabs.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.30-BETA.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 31/10/2559, 3:58 น.
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.block.Block.getCreativeTabToDisplayOn()Lnet/minecraft/creativetab/CreativeTabs;
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.startServer(DedicatedServer.java:115)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:508)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.getCreativeTabToDisplayOn()Lnet/minecraft/creativetab/CreativeTabs;
	at micdoodle8.mods.galacticraft.core.blocks.GCBlocks.registerSorted(GCBlocks.java:286)
	at micdoodle8.mods.galacticraft.core.blocks.GCBlocks.registerBlock(GCBlocks.java:267)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.registerOilandFuel(GalacticraftCore.java:465)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 916154032 bytes (873 MB) / 1056309248 bytes (1007 MB) up to 1056309248 bytes (1007 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCH	Forge{11.15.1.1902} [Minecraft Forge] (forgeSrc-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCH	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCH	nei{1.0} [nei] (bin) 
	UCH	NBTEdit{1.8.9-1.0} [In-game NBTEdit] (bin) 
	UCE	GalacticraftCore{4.0.0} [Galacticraft Core] (bin) 
	UCE	GalacticraftPlanets{4.0.0} [Galacticraft Planets] (bin) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.30-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by dj3520** [comment]
Seeing this with only GC 32beta
http://pastebin.com/CXhau3Fw

**Comment by micdoodle8** [comment]
Ah, indeed this was on Galacticraft's end. I misunderstood your report, thinking you meant a crash on the server thread, but you meant this only occurs on a dedicated server.

All dedicated server startup crashes should be fixed now. Thanks.
