### ISSUE TITLE
Server crashes (Dimension -22) (huge mod list)

### ISSUE THREAD

**Issue by scrouthtv** [micdoodle8/Galacticraft#2312]
This issue just happens when using GalacfticCraft, I have a few other mods installed, but they work properly. Here's the error:

`java.lang.IllegalArgumentException: Could not get provider type for dimension -22, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.shouldLoadSpawn(DimensionManager.java:268)
	at net.minecraft.world.gen.ChunkProviderServer.func_73241_b(ChunkProviderServer.java:70)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:820)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

**Comment by dj3520** [comment]
If you could upload the full log to gist/pastebin/etc that would be helpful. We'll also need the list of other mods installed in case they're causing an conflict with Galacticraft. Finally what Minecraft version, if this is singleplayer or on a server, and if you're using cauldron/thermos/etc.

**Comment by scrouthtv** [comment]
[Crash Report](https://gist.github.com/964087b7eefdcda46434508cfd0e11a2.git)

[Mod List](https://gist.github.com/d33f002fe7cb8cbf5315ae4c18e7f866.git)

Minecraft Version: 1.7.10
Forge Version: 10.13.14.1614-1.7.10
Game Mode: Singleplayer

I tried it without MineFactory Reloaded, and it doesn't work either. 
When I try without GalacticCraft, the error is ongoing.
But when I delete MicDoodleCore, it loads (also with MineFactory Reloaded).

**Comment by radfast** [comment]
Dimension -22 is not a Galacticraft dimension, and Galacticraft is not mentioned in that crash report.

It could maybe be an issue with [GalaxySpace](https://github.com/BlesseNtumble/GalaxySpace), does your server start if GalaxySpace is removed?

> when I delete MicDoodleCore, it loads

Did you change anything else?  Note that deleting MicDoodleCore will also disable GalaxySpace and other mods which depend on Galacticraft.

**Comment by radfast** [comment]
See also #2236, could be a dimension ID conflict between other mods

**Comment by radfast** [comment]
Could also be a Multiverse issue. See also #2242 and #2243

**Comment by radfast** [comment]
In some cases these dimension ID conflict issues are caused by AE2's **Spatial Storage Cells**.  AE2 creates a new dimension for _every new storage cell_.  There may be a way to configure it to switch that off or to control which dimensions AE2 is allowed to use, but I am not an AE2 expert.
