### ISSUE TITLE
GuiCelestialSelection Crash

### ISSUE THREAD

**Issue by confol1** [micdoodle8/Galacticraft#2329]
EDIT:This is the lastest version

When I open the GUI map of the planets or go into space, it crashes. Here is the crash report.

---- Minecraft Crash Report ----
// You're mean.

Time: 12/4/16 4:49 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1165)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.drawCelestialBodies(GuiCelestialSelection.java:1283)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73863_a(GuiCelestialSelection.java:1048)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1165)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.drawCelestialBodies(GuiCelestialSelection.java:1283)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73863_a(GuiCelestialSelection.java:1048)

-- Screen render details --
Details:
	Screen name: micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection
	Mouse location: Scaled: (213, 119). Absolute: (427, 240)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

**Comment by micdoodle8** [comment]
By latest you mean 3.0.12.464, right? 

I'm asking because the code this points to doesn't really have any obvious reason to throw a NullPointerException.

**Comment by micdoodle8** [comment]
Are you using any Galacticraft addons?
