### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by GDVE** [micdoodle8/Galacticraft#2345]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 10/12/16 17:26
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 9
	at micdoodle8.mods.galacticraft.core.inventory.PersistantInventoryCrafting.func_70299_a(PersistantInventoryCrafting.java:161)
	at galaxyspace.SolarSystem.planets.overworld.tile.TileEntityAssemblyMachine.func_70299_a(TileEntityAssemblyMachine.java:317)
	at appeng.util.inv.WrapperInventoryRange.func_70299_a(WrapperInventoryRange.java:103)
	at appeng.util.inv.AdaptorIInventory.addItems(AdaptorIInventory.java:287)
	at appeng.util.inv.AdaptorIInventory.addItems(AdaptorIInventory.java:226)
	at appeng.helpers.DualityInterface.pushPattern(DualityInterface.java:927)
	at appeng.me.cluster.implementations.CraftingCPUCluster.executeCrafting(CraftingCPUCluster.java:707)
	at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:577)
	at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:165)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:280)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:238)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_192_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:894)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

================

	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.463.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.463.jar) 
	UCHIJAAAA	GalaxySpace{1.1.3} [GalaxySpace] (GalaxySpace-1.1.3.jar)

**Comment by dj3520** [comment]
Please include all mods.
Paging @BlesseNtumble

**Comment by radfast** [comment]
This is a GalaxySpace bug, please talk to @BlesseNtumble or report it over there.
Not a Galacticraft bug as such.
