### ISSUE TITLE
Broken ore registry 1.7.10

### ISSUE THREAD

**Issue by APersonnn** [micdoodle8/Galacticraft#2358]
[crash-2016-12-21_17.07.22-server.txt](https://github.com/micdoodle8/Galacticraft/files/667696/crash-2016-12-21_17.07.22-server.txt)
[crash-2016-12-21_17.21.19-server.txt](https://github.com/micdoodle8/Galacticraft/files/667697/crash-2016-12-21_17.21.19-server.txt)
[crash-2016-12-21_17.40.34-server.txt](https://github.com/micdoodle8/Galacticraft/files/667698/crash-2016-12-21_17.40.34-server.txt)
[crash-2016-12-21_16.49.03-server.txt](https://github.com/micdoodle8/Galacticraft/files/667695/crash-2016-12-21_16.49.03-server.txt)
Bug in modded forge server:
17:29:14] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name waferSolar has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!

**Comment by MJRLegends** [comment]
No other mod uses waferSolar ore dictionary anyways....

**Comment by APersonnn** [comment]
then whats the problem?

**Comment by MJRLegends** [comment]
Well there isnt really a problem, its just the fact there is a error in your console which is no big deal, it will only become a problem if a recipe or something breaks due to it. You can even fix it yourself in a mod pack with MineTweaker

**Comment by APersonnn** [comment]
everytime i open a block, the server crashes, and is minetweaker a mod?

**Comment by APersonnn** [comment]
i figured out abt minetweaker, but theres more broken stuff:

[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name ingotCopper has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name ingotTin has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name ingotAluminum has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name compressedCopper has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name compressedTin has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name compressedAluminum has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name compressedSteel has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name compressedBronze has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name compressedIron has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name waferSolar has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name waferBasic has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name waferAdvanced has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name compressedMeteoricIron has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemMoon) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:12] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:244)
[18:06:12] [Server thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:06:12] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: ****************************************
[18:06:12] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name ingotMeteoricIron has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemMoon) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!

**Comment by APersonnn** [comment]
also if you could help me do the minetweaker code, that would be nice

**Comment by radfast** [comment]
Please update to the latest Galacticraft 1.7.10 version.  Not version 375, that is very old.
This issue is **probably** fixed in the latest version.

See also: https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md
(point number 4)
