### ISSUE TITLE
[1.8.9] Shield Controller - java.lang.NullPointerException log spam

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2375]
`Caused by: java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.checkShield(GCPlayerHandler.java:675) ~[GCPlayerHandler.class:?]
	at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1367) ~[GCPlayerHandler.class:?]
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:293) ~[EventHandlerGC.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:461) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:1773) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:323) ~[EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:366) ~[EntityPlayerMP.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:347) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:36) ~[C03PacketPlayer.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.processPacket(C03PacketPlayer.java:140) ~[C03PacketPlayer$C05PacketPlayerLook.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_112]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 5 more`

**Comment by SteveKunG** [comment]
Fixed.
