### ISSUE TITLE
[1.8.9] Crash when using pick block on Cryogenic Chamber

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2382]
`// Ouch. That hurt :(

Time: 25/1/2560, 12:26 น.
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockState{block=galacticraftcore:block_multi, properties=[renderType, type]}
	at net.minecraft.block.state.BlockState$StateImplementation.getValue(BlockState.java:137)
	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.getMetaFromState(BlockMachineMars.java:380)
	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.damageDropped(BlockMachineMars.java:297)
	at net.minecraft.block.Block.getDamageValue(Block.java:1157)
	at net.minecraft.block.Block.getPickBlock(Block.java:1908)
	at net.minecraft.block.Block.getPickBlock(Block.java:1895)
	at micdoodle8.mods.galacticraft.core.blocks.BlockMulti.getPickBlock(BlockMulti.java:266)
	at net.minecraftforge.common.ForgeHooks.onPickBlock(ForgeHooks.java:394)
	at net.minecraft.client.Minecraft.middleClickMouse(Minecraft.java:2506)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2128)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1080)
	at net.minecraft.client.Minecraft.run(Minecraft.java:380)
	at net.minecraft.client.main.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.getValue(BlockState.java:137)
	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.getMetaFromState(BlockMachineMars.java:380)
	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.damageDropped(BlockMachineMars.java:297)
	at net.minecraft.block.Block.getDamageValue(Block.java:1157)
	at net.minecraft.block.Block.getPickBlock(Block.java:1908)
	at net.minecraft.block.Block.getPickBlock(Block.java:1895)
	at micdoodle8.mods.galacticraft.core.blocks.BlockMulti.getPickBlock(BlockMulti.java:266)
	at net.minecraftforge.common.ForgeHooks.onPickBlock(ForgeHooks.java:394)
	at net.minecraft.client.Minecraft.middleClickMouse(Minecraft.java:2506)`

**Comment by EzerArch** [comment]
If I recall right, this crash also happens with Launch Pads.

**Comment by micdoodle8** [comment]
This should fix both, and any other multiblocks with the crash. Re-open/re-create if not.
