### ISSUE TITLE
[1.7.10] Error in console, java.lang.ClassCastException: MFRSpawnHandlerSlimeling

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2439]
Getting this error in the console on mod pack load...

MFR Version: 2.8.1-174
Forge: Latest
Galacticraft: Build 470

```
[12:11:54] [Client thread/ERROR]: ************************************************
[12:11:54] [Client thread/ERROR]: ************************************************
[12:11:54] [Client thread/ERROR]: Bad IMC message (registerSpawnHandler)
[12:11:54] [Client thread/ERROR]: from GalacticraftMars
[12:11:54] [Client thread/ERROR]: ************************************************
[12:11:54] [Client thread/ERROR]: ************************************************
[12:11:54] [Client thread/ERROR]: catching
java.lang.ClassCastException: micdoodle8.mods.galacticraft.planets.mars.entities.MFRSpawnHandlerSlimeling cannot be cast to powercrystals.minefactoryreloaded.api.IMobSpawnHandler
	at powercrystals.minefactoryreloaded.IMCHandler.processIMC(IMCHandler.java:213) [IMCHandler.class:?]
	at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.loadComplete(MineFactoryReloadedCore.java:817) [MineFactoryReloadedCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:745) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[12:11:54] [Client thread/INFO]: Load Complete.
```

**Comment by radfast** [comment]
Thank you, I will look at this as a priority.

Which exact version of MFR (and also which version of CofH libraries)?

**Comment by MJRLegends** [comment]
MFR Version is said above, and

Cofh Core Version: 3.1.3-327

I dont have Cofh Lib in the mod pack

**Comment by radfast** [comment]
Thank you!  Should be fixed in new build 3.0.12.471, which will be available moments after I post this.
This error was introduced in a recent update to Galacticraft, earlier this week, so I'm happy we caught it so fast, I don't think too many people should be affected.

The recent update fixed Slimeling duping possibilities - where a player could fill a Slimeling's inventory with items, catch it in a Safari Net, and duplicate it in a Grinder in exact mode.  If anybody **blacklisted** spawning or grinding of Slimelings before, they probably will not have to now.  Slimelings now work the same way as vanilla horses and donkeys in MFR: if you spawn an exact copy, you will have the same colour creature but the spawned in one will not have any inventory bag.

**Comment by MJRLegends** [comment]
Sweet thanks :P

**Comment by MJRLegends** [comment]
I can confirm the error has gone from the console on mod pack start :D

**Comment by radfast** [comment]
Thank you!  Your bug reports are always welcomed, helps us fix problems quickly.
