### ISSUE TITLE
Spongeforge not working with Galacticraft 1.8.9

### ISSUE THREAD

**Issue by ModForge** [micdoodle8/Galacticraft#2473]

**Comment by radfast** [comment]
1.  Can you be more specific about **what** is not working

2.  The problem could be on Sponge API's side, please provide a link to the issue reporting this to Sponge developers

**Comment by ModForge** [comment]
I tried to create a issue on spongeforge github, but it was closed with the message "1.8 is not supported". My forge version is the latest one "forge-1.8.9-11.15.1.1902-1.8.9-universal". And I am using build 45. I will also try to install playerapi later.

**Comment by ModForge** [comment]
[18:29:28] [Client thread/INFO]: Setting user: candeniz
[18:29:30] [Client thread/INFO]: LWJGL Version: 2.9.4
[18:29:35] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:SpongeForge, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core
[18:29:37] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:29:37] [Thread-9/INFO]: Initializing LWJGL OpenAL
[18:29:37] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:29:37] [Thread-9/INFO]: OpenAL initialized.
[18:29:38] [Sound Library Loader/INFO]: Sound engine started
[18:29:39] [Client thread/INFO]: Created: 16x16 textures-atlas
[18:29:41] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:SpongeForge, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core
[18:29:41] [Client thread/INFO]: SoundSystem shutting down...
[18:29:41] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[18:29:41] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:29:42] [Thread-11/INFO]: Initializing LWJGL OpenAL
[18:29:42] [Thread-11/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:29:42] [Thread-11/INFO]: OpenAL initialized.
[18:29:42] [Sound Library Loader/INFO]: Sound engine started
[18:29:43] [Client thread/WARN]: Texture galacticraftplanets:textures/items/orionDrive.png with size 28x28 limits mip level from 4 to 2
[18:29:43] [Client thread/WARN]: textures: dropping miplevel from 4 to 2, because of minimum power of two: 4
[18:29:46] [Client thread/INFO]: Created: 4096x4096 textures-atlas
[18:29:47] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:30:57] [Server thread/INFO]: Starting integrated minecraft server version 1.8.9
[18:30:57] [Server thread/INFO]: Generating keypair
[18:30:57] [Server thread/INFO]: Converting map!
[18:30:57] [Server thread/INFO]: Scanning folders...
[18:30:57] [Server thread/INFO]: Total conversion count is 0
[18:30:57] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:30:57] [Server thread/INFO]: Preparing start region for level 0 (Yeni Dünyass)
[18:30:58] [Server thread/INFO]: Preparing start region for level -1 (DIM-1)
[18:30:59] [Server thread/INFO]: Preparing spawn area: 28%
[18:31:00] [Server thread/INFO]: Preparing spawn area: 68%
[18:31:01] [Server thread/INFO]: Preparing start region for level 1 (DIM1)
[18:31:02] [Server thread/INFO]: Preparing spawn area: 66%
[18:31:03] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:31:55] [Server thread/INFO]: Starting integrated minecraft server version 1.8.9
[18:31:55] [Server thread/INFO]: Generating keypair
[18:31:55] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:31:58] [Client thread/INFO]: Deleting level Yeni Dünyass
[18:31:58] [Client thread/INFO]: Attempt 1...
[18:31:59] [Client thread/INFO]: Stopping!
[18:31:59] [Client thread/INFO]: SoundSystem shutting down...
[18:31:59] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by radfast** [comment]
This is what I wanted to see:

> [15:49:25] [Server thread/ERROR] [FML]: Caught exception from GalacticraftCore
java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.core.util.WorldUtil.registerPlanet(WorldUtil.java:551) ~[WorldUtil.class:?]
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.onServerStarting(GalacticraftCore.java:400) ~[GalacticraftCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.8.9-11.15.1.1902-1.8.9.jar:?]
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:787) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:284) [FMLCommonHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:125) [bpo.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

from https://github.com/SpongePowered/SpongeForge/issues/1360

**Comment by radfast** [comment]
I've looked into this some more, seems like this is absolutely a SpongeForge issue.

SpongeForge developers were aware of issues with mods creating dimensions, and looks to me like they fixed it in https://github.com/SpongePowered/SpongeForge/commit/f07f8a4b1e36c2c2039f6ee790b0752e9864c929  (maybe one or two commits earlier or later than that as well, I am not completely familiar with their code).

But it looks like they made that fix in MC1.10.2 or later versions of SpongeForge only - what they call "bleeding" - and not 1.8.9.  I don't really understand their policy on that, as that means that they are aware of a fixable issue in 1.8.9 which prevents Sponge from working with a number of mods.

Your choices here may be limited to asking Sponge kindly to update 1.8.9, or waiting for a 1.10.2 version of Galacticraft.

**Comment by radfast** [comment]
The Sponge guys have pretty much said they will accept a Sponge patch from me to fix this in 1.8.9 so I will be looking at doing that over the next few days.  I will post in this thread when it's ready for testing, but I'm not going to re-open this, because this is not a Galacticraft issue.

By the way you should be looking at our build 51 for 1.8.9 beta, it's better than build 45.  I'm not sure that there's public access to the beta but maybe you can get it from the same place you found build 45.
