### ISSUE TITLE
[1.8.9] Entity/Texture Rendering problem

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2492]
Missing texture on Buggy model.
![2560-04-04_20 43 14](https://cloud.githubusercontent.com/assets/6128413/24660446/c3655498-1979-11e7-8ed9-5adc922d4461.png)

~Astro Miner rendered too dark (Inactive).~
![2560-04-04_20 44 31](https://cloud.githubusercontent.com/assets/6128413/24660489/da006d46-1979-11e7-8981-a1652ad0db60.png)

**Comment by radfast** [comment]
Also missing / incorrect resource name for thermal armor textures?

     [Client thread/WARN]: Failed to load texture: galacticraftplanets:textures/misc/thermalPadding_T2_1.png
java.io.FileNotFoundException: galacticraftplanets:textures/misc/thermalPadding_T2_1.png
	at net.minecraft.client.resources.FallbackResourceManager.getResource(FallbackResourceManager.java:67) ~[FallbackResourceManager.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.getResource(SimpleReloadableResourceManager.java:64) ~[SimpleReloadableResourceManager.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.loadTexture(SimpleTexture.java:33) ~[SimpleTexture.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:67) [TextureManager.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:42) [TextureManager.class:?]
	at net.minecraft.client.renderer.entity.Render.bindTexture(Render.java:102) [Render.class:?]
	at micdoodle8.mods.galacticraft.core.client.render.entities.layer.LayerThermalPadding.renderLayerGC(LayerThermalPadding.java:87) [LayerThermalPadding.class:?]

**Comment by SteveKunG** [comment]
Yes, I can confirm. Affect with Tier 1/2 Thermal Armor and Frequency Module.

![2560-04-06_10 25 56](https://cloud.githubusercontent.com/assets/6128413/24737119/84a48f2e-1ab6-11e7-82e2-4a560c5c10b2.png)
![2560-04-06_10 29 35](https://cloud.githubusercontent.com/assets/6128413/24737121/84dc7ac4-1ab6-11e7-88bd-1efed025f18b.png)
![2560-04-06_10 30 11](https://cloud.githubusercontent.com/assets/6128413/24737120/84d73500-1ab6-11e7-9781-c089c6c5c87b.png)
