### ISSUE TITLE
[1.11.2] Workbench rendering bug + Crash

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2504]
When placing down the NASA Workbench i get this weird rendering, the fake blocks are still there.
![Renering Bug](http://i.imgur.com/eaSw0D1.png)

Also, when opening the workbench i get a client crash:
[Crash Log](https://pastebin.com/iP5sPSSA)

Mining the fake blocks makes the workbench disappear without returning the block.

Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

[ModList](https://pastebin.com/J7HsMHWQ)

**Comment by radfast** [comment]
The rendering is fixed in build 64, thank you.  The inventory / item crash I'm not sure, so leaving this open for now.

**Comment by ThomasAunvik** [comment]
The Crash is fixed but here we got an another issue:
When trying to unlock a new schematic and when you hover over the slot that you insert the schematic the 
game crashes.
[Crash Log](https://pastebin.com/PGMPknSP)
```
java.lang.NullPointerException: Rendering screen
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:777)
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiContainerGC.getTooltipOffset(GuiContainerGC.java:54)
	at micdoodle8.mods.galacticraft.core.client.gui.element.GuiElementInfoRegion.drawRegion(GuiElementInfoRegion.java:108)
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiContainerGC.func_73863_a(GuiContainerGC.java:31)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by radfast** [comment]
Ok, I think this issue can be closed then, as 2586 is still open and is more specific to the new issue.

Thanks for confirming that the original crash is now fixed in build 64.

**Comment by micdoodle8** [comment]
Tooltip crash should be fixed in the next build. Closing this as all issues mentioned here are fixed.
