### ISSUE TITLE
[1.11.2] Crashes in debug world/Block issues

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2511]
**Fluid Conduits & Walkway w/ fluid conduit:**
When placed down this exception happens and then crashes. Unable to rejoin to the world.

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.core.util.OxygenUtil.getAdjacentFluidConnections(OxygenUtil.java:472) ~[OxygenUtil.class:?]
	at micdoodle8.mods.galacticraft.core.util.OxygenUtil.getAdjacentFluidConnections(OxygenUtil.java:454) ~[OxygenUtil.class:?]
	at micdoodle8.mods.galacticraft.core.blocks.BlockTransmitter.func_176221_a(BlockTransmitter.java:211) ~[BlockTransmitter.class:?]
	at micdoodle8.mods.galacticraft.core.blocks.BlockFluidPipe.func_185496_a(BlockFluidPipe.java:130) ~[BlockFluidPipe.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:456) ~[atm$a.class:?]
	at net.minecraft.block.Block.func_180646_a(Block.java:466) ~[alu.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:446) ~[atm$a.class:?]
	at net.minecraft.pathfinding.PathWorldListener.func_184378_a(SourceFile:60) ~[wg.class:?]
	at net.minecraft.pathfinding.PathWorldListener.func_184376_a(SourceFile:25) ~[wg.class:?]
	at net.minecraft.world.World.func_184138_a(World.java:424) ~[ajs.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368) ~[ajs.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:886) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:165) ~[afj.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478) ~[lz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:685) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jm.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jm.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

[Crash Log](https://pastebin.com/c8PdqhDZ)

Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

**Comment by micdoodle8** [comment]
Thank you, this will be fixed in the next build.
