### ISSUE TITLE
[1.11.2] Shift clicking any items into any gc GUI crashes client

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2515]
**From a buggy:**

Just before the crash happens this exception seems to throw:
```
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[commons-lang3-3.3.2.jar:3.3.2]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[commons-lang3-3.3.2.jar:3.3.2]
	at net.minecraft.util.NonNullList.set(SourceFile:45) ~[dd.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:513) ~[aax.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[adl.class:?]
	at micdoodle8.mods.galacticraft.core.inventory.ContainerBuggy.func_82846_b(ContainerBuggy.java:84) ~[ContainerBuggy.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:237) ~[acl.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:548) ~[bnp.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632) ~[big.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391) ~[big.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542) ~[bho.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510) ~[bho.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695) ~[bes.class:?]
	... 9 more
```

[Crash Log](https://pastebin.com/9w3Vgt9Z)

**Ingot Compressor**

[Crash Log](https://pastebin.com/YDCZgC5m)

**GC Players Inventory**

[Crash Log](https://pastebin.com/PhU8Tj0P)

Note: Seems click shifting items in the GC guis are bad.

Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

**Comment by Bobynoby** [comment]
Thomas your on a roll! Good job this man deserves a metal from all this work haha

**Comment by micdoodle8** [comment]
Indeed he does :) Thanks again, fixed in the next build.

**Comment by ThomasAunvik** [comment]
**GC Inventory**
[Crash Log](https://pastebin.com/rkEusinJ)

```
java.lang.NullPointerException: Updating screen events
    at net.minecraft.inventory.Container.func_184996_a(Container.java:239)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:548)
    at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by ThomasAunvik** [comment]
**Oxygen Collector**
[Crash Log](https://pastebin.com/vXxnneru)

```
java.lang.NullPointerException: Updating screen events
    at net.minecraft.inventory.Container.func_184996_a(Container.java:239)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:548)
    at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by radfast** [comment]
Hi Thomas
I've tested this in 1.11.2 build 68 - Oxygen Collector and the main Galacticraft inventory - and it seems OK.  My guess is it's been fixed by one of the recent changes to containers.

If it occurs again, please do re-open this issue!
