### ISSUE TITLE
[1.11.2, 1.10.2] Build 57 is broken

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2526]
When creating a new world the server crashes:
[Crash Log](https://pastebin.com/NArKpt9h)
```
java.lang.NoSuchFieldError: xPosition
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:903)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.checkBlock(EventHandlerGC.java:611)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:521)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:428)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_EventHandlerGC_populate_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:662)
	at net.minecraft.world.gen.ChunkProviderOverworld.func_185931_b(ChunkProviderOverworld.java:491)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:106)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Thread.java:745)

```

Joining an another world gives out a crash:
[Crash Log](https://pastebin.com/8xT1kc67)

```
java.lang.NoSuchFieldError: xPosition
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:105)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by micdoodle8** [comment]
Thanks, fixed in the next build.
