### ISSUE TITLE
[1.11.2] Breaking Walkway (Aluminum Wire) crashes client

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2529]
[Crash Log](https://pastebin.com/HR9wnk7y)

Forge Version: 13.20.2279
Galacticraft Core: 4.0.0.58
Galacticraft-Planets: 4.0.0.58
Micdoodlecore: 4.0.0.58

First Exception Thrown
```
[11:09:22] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.api.vector.BlockVec3.<init>(BlockVec3.java:68) ~[BlockVec3.class:?]
	at micdoodle8.mods.galacticraft.core.energy.EnergyUtil.getAdjacentPowerConnections(EnergyUtil.java:53) ~[EnergyUtil.class:?]
	at micdoodle8.mods.galacticraft.planets.asteroids.blocks.BlockWalkway.func_176221_a(BlockWalkway.java:342) ~[BlockWalkway.class:?]
	at micdoodle8.mods.galacticraft.planets.asteroids.blocks.BlockWalkway.func_185496_a(BlockWalkway.java:90) ~[BlockWalkway.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:456) ~[atm$a.class:?]
	at net.minecraft.block.Block.func_180646_a(Block.java:466) ~[alu.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:446) ~[atm$a.class:?]
	at net.minecraft.pathfinding.PathWorldListener.func_184378_a(SourceFile:59) ~[wg.class:?]
	at net.minecraft.pathfinding.PathWorldListener.func_184376_a(SourceFile:25) ~[wg.class:?]
	at net.minecraft.world.World.func_184138_a(World.java:424) ~[ajs.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368) ~[ajs.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:353) ~[ajs.class:?]
	at net.minecraft.block.Block.removedByPlayer(Block.java:1127) ~[alu.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:274) ~[lz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180235_c(PlayerInteractionManager.java:268) ~[lz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:312) ~[lz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:157) ~[lz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:637) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[jd.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[jd.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

```

Second Exception Thrown
```
java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.api.vector.BlockVec3.<init>(BlockVec3.java:68) ~[BlockVec3.class:?]
	at micdoodle8.mods.galacticraft.core.energy.EnergyUtil.getAdjacentPowerConnections(EnergyUtil.java:53) ~[EnergyUtil.class:?]
	at micdoodle8.mods.galacticraft.planets.asteroids.blocks.BlockWalkway.func_176221_a(BlockWalkway.java:342) ~[BlockWalkway.class:?]
	at micdoodle8.mods.galacticraft.planets.asteroids.blocks.BlockWalkway.func_185496_a(BlockWalkway.java:90) ~[BlockWalkway.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:456) ~[atm$a.class:?]
	at net.minecraft.block.Block.func_180646_a(Block.java:466) ~[alu.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:446) ~[atm$a.class:?]
	at net.minecraft.pathfinding.PathWorldListener.func_184378_a(SourceFile:59) ~[wg.class:?]
	at net.minecraft.pathfinding.PathWorldListener.func_184376_a(SourceFile:25) ~[wg.class:?]
	at net.minecraft.world.World.func_184138_a(World.java:424) ~[ajs.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368) ~[ajs.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:353) ~[ajs.class:?]
	at net.minecraft.block.Block.removedByPlayer(Block.java:1127) ~[alu.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187103_a(PlayerControllerMP.java:172) ~[bnp.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_178891_a(PlayerControllerMP.java:70) ~[bnp.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:218) ~[bnp.class:?]
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1460) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2174) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

Quick Crash Log
```
java.lang.NullPointerException: Unexpected error
	at micdoodle8.mods.galacticraft.api.vector.BlockVec3.<init>(BlockVec3.java:68)
	at micdoodle8.mods.galacticraft.core.energy.EnergyUtil.getAdjacentPowerConnections(EnergyUtil.java:53)
	at micdoodle8.mods.galacticraft.planets.asteroids.blocks.BlockWalkway.func_176221_a(BlockWalkway.java:342)
	at micdoodle8.mods.galacticraft.planets.asteroids.blocks.BlockWalkway.func_185496_a(BlockWalkway.java:90)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:456)
	at net.minecraft.block.Block.func_180646_a(Block.java:466)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:446)
	at net.minecraft.pathfinding.PathWorldListener.func_184378_a(SourceFile:59)
	at net.minecraft.pathfinding.PathWorldListener.func_184376_a(SourceFile:25)
	at net.minecraft.world.World.func_184138_a(World.java:424)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368)
	at net.minecraft.world.World.func_180501_a(World.java:353)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1127)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187103_a(PlayerControllerMP.java:172)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_178891_a(PlayerControllerMP.java:70)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:218)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1460)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2174)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by radfast** [comment]
Tested, this is an issue in 1.10+ but not in 1.8.9.

**Comment by radfast** [comment]
Thank you, this is fixed from next build 61  (note: builds 59 and 60 made no update to 1.11.2)
