### ISSUE TITLE
[1.11.2] Already decorating! crash on moon in SSP

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2531]
Unable to join back to the world
[Crash Log](https://pastebin.com/D880RFmx)

Forge Version: 13.20.2279
Galacticraft Core: 4.0.0.58
Galacticraft-Planets: 4.0.0.58
Micdoodlecore: 4.0.0.58

```
java.lang.RuntimeException: Already decorating!!
    at micdoodle8.mods.galacticraft.core.world.gen.BiomeDecoratorMoon.func_180292_a(BiomeDecoratorMoon.java:42)
    at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:229)
    at micdoodle8.mods.galacticraft.core.world.gen.ChunkProviderMoon.func_185931_b(ChunkProviderMoon.java:292)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
    at net.minecraft.world.World.func_72964_e(World.java:303)
    at net.minecraft.world.World.func_175726_f(World.java:298)
    at net.minecraft.world.World.func_180495_p(World.java:903)
    at net.minecraft.world.World.func_190529_b(World.java:573)
    at net.minecraft.world.World.func_190522_c(World.java:471)
    at net.minecraft.world.World.markAndNotifyBlock(World.java:382)
    at net.minecraft.world.World.func_180501_a(World.java:353)
    at micdoodle8.mods.galacticraft.core.world.gen.BiomeDecoratorMoon.generateMoon(BiomeDecoratorMoon.java:91)
    at micdoodle8.mods.galacticraft.core.world.gen.BiomeDecoratorMoon.func_180292_a(BiomeDecoratorMoon.java:49)
    at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:229)
    at micdoodle8.mods.galacticraft.core.world.gen.ChunkProviderMoon.func_185931_b(ChunkProviderMoon.java:292)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by radfast** [comment]
It's connected with the Sapphire Ore.

Please, for now, disable sapphire ore generation like this in Galacticraft Core config.
>
     Disable Sapphire Ore Gen on Moon: true

That should mean you can load this world and test other stuff on the moon :D
