### ISSUE TITLE
[1.11.2] Placing down Telementry Unit crashes client

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2554]
Build 61

[Crash Log](https://pastebin.com/cKaAEW0e)

[Client Log w/Debug](https://pastebin.com/ipWB6Mj9)

Unable to join back to the world
```
java.lang.NullPointerException: Unexpected error
    at micdoodle8.mods.galacticraft.core.network.PacketSimple.handleClientSide(PacketSimple.java:758)
    at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.tick(GalacticraftPacketHandler.java:66)
    at micdoodle8.mods.galacticraft.core.tick.TickHandlerClient.onClientTick(TickHandlerClient.java:613)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_51_TickHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by radfast** [comment]
I can't reproduce in 1.10.2, so I'm assuming this is 1.11.2 only.
