### ISSUE TITLE
[1.8.9] N.A.S.A Workbench causes dedicated server to crash when pressing next/back.

### ISSUE THREAD

**Issue by NevCrow** [micdoodle8/Galacticraft#2557]
Using Version 61
https://fyfox.xyz/fy_server_forge.log

edit:
Clients get server has closed message

**Comment by radfast** [comment]
Thank you for beta testing.

I can fix this immediately, this will be in next build 62 which should be out either tonight or tomorrow.

**Comment by NevCrow** [comment]
I will test it at 10am today(GMT LONDON TIME)

**Comment by radfast** [comment]
hmm, this isn't so easy to fix as I thought.

Do you have the actual **crash-report** to show more details about this crash?

**Comment by NevCrow** [comment]
> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.61-BETA.jar)
  TransformerLoader (OpenComputers-MC1.8.9-1.6.2.12.jar)
  IC2core (industrialcraft-2-2.3.263-ex18.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/11/17 1:13 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at micdoodle8.mods.galacticraft.core.inventory.ContainerSchematicTier1Rocket.<init>(ContainerSchematicTier1Rocket.java:32)
	at micdoodle8.mods.galacticraft.core.schematic.SchematicRocketT1.getResultContainer(SchematicRocketT1.java:46)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getServerGuiElement(GuiHandler.java:143)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:244)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:80)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2305)
	at micdoodle8.mods.galacticraft.core.network.PacketSimple.handleServerSide(PacketSimple.java:879)
	at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.tick(GalacticraftPacketHandler.java:69)
	at micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onWorldTick(TickHandlerServer.java:638)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_378_TickHandlerServer_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:710)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 3.10.23-xxxx-grs-ipv6-64
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 929537912 bytes (886 MB) / 2043478016 bytes (1948 MB) up to 2075918336 bytes (1979 MB)
	JVM Flags: 5 total; -Xmx2048M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+AggressiveOpts -XX:MaxGCPauseMillis=30
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.2.12} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.8.9-3.0.13.jar) 
	UCHIJAAAA	ForgeEssentials{1.8.5} [Forge Essentials] (forgeessentials-1.8.9-1.8.5.103-server (1).jar) 
	UCHIJAAAA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJAAAA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJAAAA	IC2{2.3.263-ex18} [IndustrialCraft 2] (industrialcraft-2-2.3.263-ex18.jar) 
	UCHIJAAAA	GalacticraftCore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.8.9-4.0.0.61-BETA.jar) 
	UCHIJAAAA	GalacticraftPlanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.8.9-4.0.0.61-BETA.jar) 
	UCHIJAAAA	monev{1.0.5} [monev] (monev.jar) 
	UCHIJAAAA	nbtedit{$version} [NBTEdit] (NBTEdit-0.1.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.8.9-2.1.6 (1).jar) 
	UCHIJAAAA	OpenComputers{1.6.2.12} [OpenComputers] (OpenComputers-MC1.8.9-1.6.2.12.jar) 
	UCHIJAAAA	randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
	UCHIJAAAA	VeinMiner{0.35.2_1.8.9-748957c} [Vein Miner] (VeinMiner-1.8.9-0.35.2.569+748957c.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.35.2_1.8.9-748957c} [Mod Support] (VeinMiner-1.8.9-0.35.2.569+748957c.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.0.61-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TransformerLoader (OpenComputers-MC1.8.9-1.6.2.12.jar)
  li.cil.oc.common.asm.ClassTransformer
IC2core (industrialcraft-2-2.3.263-ex18.jar)
  
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
	ForgeEssentials: Running ForgeEssentials 1.8.5.103 (89f8710). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	Profiler Position: N/A (disabled)
	Player Count: 2 / 20; [GCEntityPlayerMP['Monty2001'/7702, l='yyyy', x=176.96, y=20.00, z=-379.81], GCEntityPlayerMP['SupermellGaming'/413037, l='yyyy', x=-114.59, y=75.00, z=27.43]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by radfast** [comment]
thank you
and yes, that does say 'Dedicated Server' at the end :)

I don't know if one of the other mods here is changing something - if you have a chance please can you also try without some of these other things, I have no clue which it could be.  IC2 should be OK, I've been testing all day with it.  Maybe try removing OpenComputers, ForgeEssentials and WorldEdit for a start, see

**Comment by radfast** [comment]
This will be fixed from [next build 69](https://ci.micdoodle8.com/job/Galacticraft-1.8/)

Thanks and sorry you've had to wait 8 days for a fix.
