### ISSUE TITLE
[1.11.2] GC Machines (w/fluid input) does not want to input fluid from Fluid Pipe

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2567]
List of Blocks that can access fluid from Fluid Pipe, but it does not:
- Oxygen Bubble Distributor
- Oxygen Sealer
- Oxygen Compressor

(I have not tested all machines (that does accept fluid))

For Example:
Oxygen Bubble Distrubutor:
![Imgur](http://i.imgur.com/Xu9AV76.png)
![Imgur](http://i.imgur.com/LKrn0Uk.png)

**Comment by dj3520** [comment]
If behavior is the same as it was in GC3 these machines will only accept oxygen _gas._

**Comment by MJRLegends** [comment]
Yeah use the gas pipes

**Comment by ThomasAunvik** [comment]
Ill try

**Comment by ThomasAunvik** [comment]
There are no Gas Pipes

**Comment by radfast** [comment]
it's a coding error in these machines.  The Fluid Pipes are new in GC4, the old Oxygen Pipes are gone.

**Comment by ThomasAunvik** [comment]
Also, there is no gas in minecraft. So Gas = Fluid

**Comment by ThomasAunvik** [comment]
Another issue, when right clicking the fluid pipe (just where the input/output is) with a standard hammer crashes the server. You can also get the Fluid Pipe Pull item with this command `/give username galacticraftcore:fluid_pipe_pull`

[Server Crash Log](https://pastebin.com/H2RUJYLt)
```
java.lang.NullPointerException: Ticking block entity
    at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygen.canDrain(TileEntityOxygen.java:410)
    at micdoodle8.mods.galacticraft.core.wrappers.FluidHandlerWrapper.drain(FluidHandlerWrapper.java:53)
    at micdoodle8.mods.galacticraft.core.tile.TileEntityFluidTransmitter.func_73660_a(TileEntityFluidTransmitter.java:128)
    at micdoodle8.mods.galacticraft.core.tile.TileEntityFluidPipe.func_73660_a(TileEntityFluidPipe.java:79)
    at net.minecraft.world.World.func_72939_s(World.java:1802)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by micdoodle8** [comment]
Both the emit functionality and crash will be fixed in the next build. Thanks!
