### ISSUE TITLE
[1.10.2] Random crash while flying away from machines on Moon

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2575]
I was simply flying away from an area with oxygen pipes/machines, and at about the same time that the chunks they were in would have unloaded, the game crashed.
I went back into that world, and tried to reproduce it, but I couldn't, so I can't be sure that unloading the chunks caused the crash.
The machines include:
- Oxygen Collector
- Oxygen Storage Module
- Oxygen Bubble Distributor
- Oxygen Compressor
- Energy Storage Cluster
- Advanced Solar Panel

Forge 12.18.3.2272
Galanticraft Build 63
Crash log (server side): https://ptpb.pw/bt8l

**Comment by radfast** [comment]
Thank you!!

This is exactly the type of issue I like.  Should be easy to resolve with this crash report

   java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at micdoodle8.mods.galacticraft.core.fluid.FluidNetwork.getAcceptors(FluidNetwork.java:438)
	at micdoodle8.mods.galacticraft.core.fluid.FluidNetwork.emitToAcceptors(FluidNetwork.java:210)
	at micdoodle8.mods.galacticraft.core.fluid.FluidNetwork.onUpdate(FluidNetwork.java:381)
	at micdoodle8.mods.galacticraft.core.fluid.FluidNetwork.tickEnd(FluidNetwork.java:292)
	at micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onServerTick(TickHandlerServer.java:447)

**Comment by radfast** [comment]
Thank you, this will be fiixed from build 64.
