### ISSUE TITLE
[1.11.2] Hovering over machine slots crashes client

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2586]
Hovering over a machine slot crashes client. Some inventories that are big enough does not crash the client.

Currently tested that do crash:
- Workbench Schematic Slot
- Oxygen Decompressor All Slots
- Gas Liquifier All Slots
- Water Electrolyzer All Slots
- Astro Miner Base Battery Slot

Conclusion: All machines with input slots crashes the client.

[Crash Log](https://pastebin.com/PGMPknSP)
```
java.lang.NullPointerException: Rendering screen
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:777)
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiContainerGC.getTooltipOffset(GuiContainerGC.java:54)
	at micdoodle8.mods.galacticraft.core.client.gui.element.GuiElementInfoRegion.drawRegion(GuiElementInfoRegion.java:108)
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiContainerGC.func_73863_a(GuiContainerGC.java:31)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by micdoodle8** [comment]
Fixed in the next build, thanks!
