### ISSUE TITLE
[1.8.9] Spawn Spider Queen crash the game

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2602]
`java.lang.RuntimeException: java.lang.ClassCastException: net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper cannot be cast to net.minecraftforge.client.model.obj.OBJModel
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.updateModels(RenderSpiderQueen.java:51)
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.doRender(RenderSpiderQueen.java:81)
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.doRender(RenderSpiderQueen.java:1)
	at net.minecraft.client.renderer.entity.RenderLiving.doRender(RenderLiving.java:16)
	at net.minecraft.client.renderer.entity.RenderManager.doRenderEntity(RenderManager.java:380)
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:337)
	at net.minecraft.client.renderer.entity.RenderManager.renderEntitySimple(RenderManager.java:304)
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:672)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1369)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1283)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1111)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1107)
	at net.minecraft.client.Minecraft.run(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
Caused by: java.lang.ClassCastException: net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper cannot be cast to net.minecraftforge.client.model.obj.OBJModel
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.updateModels(RenderSpiderQueen.java:43)
	... 25 more`

**Comment by radfast** [comment]
Caused by me in [this](https://github.com/micdoodle8/Galacticraft/commit/6c84a9076afc03634ecc8964f63aeb16b1fc3525) I think - the OBJ loader didn't like me removing the reference to ```web.mtl```

**Comment by radfast** [comment]
Fixed in build 69.

[Build 69 with Sponge compatibility](https://ci.micdoodle8.com/job/Galacticraft-1.10/) is now available.
