### ISSUE TITLE
[1.10.2] crash getting space station save data

### ISSUE THREAD

**Issue by AnarchySage** [micdoodle8/Galacticraft#2617]
`22:44:14] [Server thread/INFO]: Geizhals joined the game
[22:44:15] [Server thread/WARN]: Failed to handle packet for /ip:port
java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.core.dimension.SpaceStationWorldData.getMPSpaceStationData(SpaceStationWorldData.java:306) ~[SpaceStationWorldData.class:?]
	at micdoodle8.mods.galacticraft.core.dimension.SpaceStationWorldData.updateSSOwnership(SpaceStationWorldData.java:347) ~[SpaceStationWorldData.class:?]
	at micdoodle8.mods.galacticraft.core.dimension.SpaceStationWorldData.checkAllStations(SpaceStationWorldData.java:376) ~[SpaceStationWorldData.class:?]
	at micdoodle8.mods.galacticraft.core.network.ConnectionEvents.onPlayerLogin(ConnectionEvents.java:78) ~[ConnectionEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_702_ConnectionEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:565) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:228) ~[mp.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[22:44:20] [Server thread/INFO]: Geizhals lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[22:44:20] [Server thread/INFO]: Geizhals left the game`

Created a space station, any anyone who trys to login to server gets that(now i do since i disconnected)

**Comment by radfast** [comment]
Thanks for reporting, we will look at this as a priority.  I hope there will be a fix today.

**Comment by AnarchySage** [comment]
@radfast Any luck? I have found a bit of info which may help, the dimension it wont sync i belive to be space station. 


> forge tps
[17:07:46] [Server thread/INFO]: Dim -30 : Mean tick time: 0.564 ms. Mean TPS: 20.000
[17:07:46] [Server thread/INFO]: Dim -31 : Mean tick time: 0.176 ms. Mean TPS: 20.000
[17:07:46] [Server thread/INFO]: Dim -9999 : Mean tick time: 0.150 ms. Mean TPS: 20.000
[17:07:46] [Server thread/INFO]: Dim -343800852 : Mean tick time: 0.050 ms. Mean TPS: 20.000
[17:07:46] [Server thread/INFO]: Dim -28 : Mean tick time: 0.276 ms. Mean TPS: 20.000
[17:07:46] [Server thread/INFO]: Dim -29 : Mean tick time: 0.143 ms. Mean TPS: 20.000
[17:07:46] [Server thread/INFO]: Dim 0 : Mean tick time: 45.779 ms. Mean TPS: 20.000
[17:07:46] [Server thread/INFO]: Overall : Mean tick time: 48.475 ms. Mean TPS: 20.000
> cofh tps
[17:07:54] [Server thread/INFO]: Overall: 19.06 TPS/52.48MS (95%)
[17:07:54] [Server thread/INFO]: Overworld [0]: 20.00 TPS/49.97MS (100%)
[17:07:54] [Server thread/INFO]: Asteroids [-30]: 20.00 TPS/0.63MS (100%)
[17:07:54] [Server thread/INFO]: Venus [-31]: 20.00 TPS/0.19MS (100%)
[17:07:54] [Server thread/INFO]: ExtraUtils2_Quarry_Dim [-9999]: 20.00 TPS/0.15MS (100%)
[17:07:54] [Server thread/INFO]: Overworld [-343800852]: 20.00 TPS/0.12MS (100%)
[17:07:54] [Server thread/INFO]: Moon [-28]: 20.00 TPS/0.33MS (100%)
[17:07:54] [Server thread/INFO]: Mars [-29]: 20.00 TPS/0.12MS (100%)

**Comment by radfast** [comment]
I think the problem is you have a strange Overworld setup.  What is this?

> Overworld [-343800852]

Are you also using Sponge on your server, or something else which messes with the Overworld?

Galacticraft is actually just trying to get the Overworld save folder here, in the code which produced the error - because space stations orbit the Overworld!

**Comment by radfast** [comment]
Please provide **full details** of your setup: other mods, plugins, and configs.
A full ```fml-server-latest.log``` will probably cover it...

**Comment by AnarchySage** [comment]
http://pastebin.ubuntu.com/24426303/ The log file, core.conf from gc, no i am not using sponge, i didnt have that world Overworld [-343800852], until i made a space station from gc, i can boot the world without gc and see if it works later today(work now)

**Comment by radfast** [comment]
thanks, that's great

ok so it's us making world -343800852?  That's a problem!  switching this back to highest priority, sorry I thought you must be using a Multiworld system with a spawn world or something.

**Comment by AnarchySage** [comment]
Ok so i found this, https://www.reddit.com/r/feedthebeast/comments/59vnpt/randomthings_how_do_i_restart_spectre_room_for/

Yall arent creating it, but gc is attempting to sync it for some reason

**Comment by radfast** [comment]
thanks, I'll have to take a detailed look

Worst case, we can catch the crash and have it just continue, but in that case your Space Stations might not work correctly with Random Things installed.  I'm going to see if we can get both mods to work nicely together.

**Comment by AnarchySage** [comment]
I think i may not have explained, the two are unrelated, i thought i saw that dimension in regards to the error, i didnt(cant recreate the dim involded with error), however gc STILL crashes with that same error without randomthings.

**Comment by AnarchySage** [comment]
Why the can't reproduce? It's reproduceable lol. On amp create space station,  log out, log back in, crash happens.

**Comment by radfast** [comment]
"amp" is what?

The problem here is you have this huge modpack.  That's extremely hard for us to troubleshoot.  One of your other mods or configs has changed the dimension of the Overworld so it's not dimension 0.  I don't know which mod made this change.  I'm trying to figure out whether we can find some other way to workaround this problem.

**Comment by radfast** [comment]
and lol?
>
    [18:21:41] [Netty Epoll Server IO #0/INFO] [FML/]: Attempting connection with missing mods [Micdoodlecore, Dynmap, galacticraftplanets, galacticraftcore, ircbridge] at CLIENT

Looks like you then fixed it:
>
    [18:29:09] [Netty Epoll Server IO #0/INFO] [FML/]: Attempting connection with missing mods [Dynmap, ircbridge] at CLIENT

**Comment by radfast** [comment]
Next build 72 will have a workaround for this problem.   The build will probably come tomorrow.  In that build, if a similar problem is detected Galacticraft will leave a line like this in the log, around the time each player joins the server:

    No world for dimension 0?  That should be unpossible!  Please report at https://github.com/micdoodle8/Galacticraft/issues/2617

If you see that message in your log, please let me know.
If you don't see that message, then it means the problem is fully solved.

**Comment by radfast** [comment]
[Build 73](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available
