### ISSUE TITLE
[1.7.10] Build 487 crashes with Ticking block entity

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2622]
The build 487 crashes with Ticking block entity while the world chunks are still being loaded.

```
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced.func_145845_h(TileEntityAdvanced.java:63)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalElectrical.func_145845_h(TileBaseUniversalElectrical.java:338)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_145845_h(TileBaseElectricBlock.java:117)
	at micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityTelepadFake.func_145845_h(TileEntityTelepadFake.java:51)
```
Full log: https://gist.github.com/EzerArch/991818c1ee0facf2196c9e0b9ac2c95d

**Comment by radfast** [comment]
thanks, I'll look at getting a fix out ASAP

**Comment by radfast** [comment]
Thanks.  Please try out 488, that should be OK.  I hope...
