### ISSUE TITLE
Crashing when i place a launch controller then will not load world

### ISSUE THREAD

**Issue by Hexyman** [micdoodle8/Galacticraft#2629]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/22/17 4:31 PM
Description: Rendering screen

io.netty.channel.ChannelException: connection refused
	at io.netty.channel.local.LocalChannel$LocalUnsafe.connect(LocalChannel.java:361)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.connect(DefaultChannelPipeline.java:1008)
	at io.netty.channel.DefaultChannelHandlerContext.invokeConnect(DefaultChannelHandlerContext.java:494)
	at io.netty.channel.DefaultChannelHandlerContext.connect(DefaultChannelHandlerContext.java:479)
	at io.netty.channel.DefaultChannelHandlerContext.connect(DefaultChannelHandlerContext.java:464)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:847)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:198)
	at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:187)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at io.netty.channel.local.LocalChannel$LocalUnsafe.connect(LocalChannel.java:361)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.connect(DefaultChannelPipeline.java:1008)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
	Mouse location: Scaled: (177, 53). Absolute: (15, 284)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1067)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.2.0-42-generic
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 132840464 bytes (126 MB) / 336977920 bytes (321 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAAA	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJAAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.488.jar) 
	UCHIJAAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.485.jar) 
	UCHIJAAAAA	XaeroMinimap{1.12.7} [Xaero's Minimap] (Xaeros_Minimap_1.12.7_Forge_1.7.10.jar) 
	UCHIJAAAAA	XaeroWorldMap{1.8.1} [Xaero's World Map] (XaerosWorldMap_b1.8.1_Forge_1.7.10.jar) 
	GL info: ' Vendor: 'X.Org' Version: '3.0 Mesa 11.0.2' Renderer: 'Gallium 0.4 on AMD KAVERI (DRM 2.43.0, LLVM 3.6.2)'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Gallium 0.4 on AMD KAVERI (DRM 2.43.0, LLVM 3.6.2) GL version 3.0 Mesa 11.0.2, X.Org
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by micdoodle8** [comment]
Going to need the full log, there's no information about the source here.

**Comment by radfast** [comment]
**Possible cause: **  you don't have matching Galacticraft Core and Galacticraft Planets versions.

Your Galacticraft Planets is version 485.  Please update **both together** to the latest - that's now version 489 - and see if that fixes it.  :)
