### ISSUE TITLE
[1.11.2] Ingot Compressor - Ticking block entity error

### ISSUE THREAD

**Issue by DoomsDoorWay** [micdoodle8/Galacticraft#2638]
When placing the ingot compressor it creates a ticking block entity exception. For a bit more information if the forge option to remove any TileEntity that throws an error is enabled the ingot compressor is place-able but when you open its GUI its instantly closed. 

Galacticraft version is 1.11.2-4.0.0.71-BETA, tested with no other mods installed and this is the crash log.

> net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) ~[cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.core.tile.TileEntityIngotCompressor.canSmelt(TileEntityIngotCompressor.java:136) ~[TileEntityIngotCompressor.class:?]
	at micdoodle8.mods.galacticraft.core.tile.TileEntityIngotCompressor.func_73660_a(TileEntityIngotCompressor.java:62) ~[TileEntityIngotCompressor.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1802) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more

**Comment by radfast** [comment]
thanks for beta testing and for the clear issue report.

this is one we should be able to fix immediately :)

**Comment by radfast** [comment]
Thanks again.  Guess you're the first beta tester to place down an Ingot Compressor!

Fixed in next build 72, available later tonight if all goes well.

**Comment by DoomsDoorWay** [comment]
haha I had wondered about that so at first figured it must have been a mod incompatibility.

**Comment by radfast** [comment]
[Build 73](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available

**Comment by jjjworley** [comment]
I'm having the same issue first with 1.11.2-4.0.0.69 then after updating to 1.11.2-4.0.0.76. I was able to place the compressor and put two stacks of iron in, then it crashed. Need to use MCEdit to remove compressor before game will start again.
[crash-2017-04-28_06.01.17-server.txt](https://github.com/micdoodle8/Galacticraft/files/964215/crash-2017-04-28_06.01.17-server.txt)

**Comment by radfast** [comment]
hi jjjworley thanks for beta testing.  sorry that you've had crashes, looks like we didn't cover every possibility when I thought I fixed this.

This should be fixed properly from next build 77, probably available today/tomorrow.

**Comment by jjjworley** [comment]
Thank you for all of your hard work on this mod. I have so enjoyed this mod in the past, and I am thrilled to have it on 1.11.2 now.

**Comment by radfast** [comment]
:)

**Comment by radfast** [comment]
[Build 77 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)

**Comment by jjjworley** [comment]
Just to let you know, with build 77 the compressor and the electric compressor are working perfectly. :)

**Comment by radfast** [comment]
nice.  Thanks for confirming.  Please do let us know if you spot any other issues, we are aiming for a perfect player experience.
