### ISSUE TITLE
[1.10.2]: The game crashes when opening "Pre-Launch Checklist"

### ISSUE THREAD

**Issue by buithanh12072001** [micdoodle8/Galacticraft#2658]
When I open "Pre-Launch Checklist" item, the game crashed. Here is my crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.78-BETA.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/30/17 10:19 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Invalid hand null
	at net.minecraft.entity.EntityLivingBase.func_184586_b(EntityLivingBase.java:1487)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:188)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:155)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:273)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494)
	at micdoodle8.mods.galacticraft.core.items.ItemPreLaunchChecklist.func_77659_a(ItemPreLaunchChecklist.java:62)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:163)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.entity.EntityLivingBase.func_184586_b(EntityLivingBase.java:1487)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:188)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:155)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:273)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494)
	at micdoodle8.mods.galacticraft.core.items.ItemPreLaunchChecklist.func_77659_a(ItemPreLaunchChecklist.java:62)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:163)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['BTTgaming2001'/265, l='MpServer', x=140.50, y=73.06, z=260.50]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (176,64,248), Chunk: (at 0,4,8 in 11,15; contains blocks 176,0,240 to 191,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2163924 game time, 4104618 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 16 total; [GCEntityClientPlayerMP['BTTgaming2001'/265, l='MpServer', x=-29.90, y=63.00, z=623.13], EntityBat['Bat'/587, l='MpServer', x=131.57, y=40.10, z=266.75], EntityItemFrame['entity.ItemFrame.name'/109, l='MpServer', x=151.97, y=75.50, z=259.50], EntityItemFrame['entity.ItemFrame.name'/110, l='MpServer', x=151.97, y=76.50, z=259.50], EntityItemFrame['entity.ItemFrame.name'/111, l='MpServer', x=151.97, y=75.50, z=260.50], EntityItemFrame['entity.ItemFrame.name'/112, l='MpServer', x=151.97, y=76.50, z=261.50], EntityItemFrame['entity.ItemFrame.name'/113, l='MpServer', x=151.97, y=75.50, z=261.50], GCEntityClientPlayerMP['BTTgaming2001'/265, l='MpServer', x=140.50, y=73.06, z=260.50], EntityItemFrame['entity.ItemFrame.name'/114, l='MpServer', x=151.97, y=75.50, z=262.50], EntityItemFrame['entity.ItemFrame.name'/115, l='MpServer', x=151.97, y=76.50, z=262.50], EntityItemFrame['entity.ItemFrame.name'/116, l='MpServer', x=151.97, y=76.50, z=263.50], EntityItemFrame['entity.ItemFrame.name'/117, l='MpServer', x=151.97, y=76.50, z=264.50], EntityItemFrame['entity.ItemFrame.name'/118, l='MpServer', x=151.97, y=75.50, z=264.50], EntityBat['Bat'/278, l='MpServer', x=-33.25, y=16.10, z=633.55], EntityItemFrame['entity.ItemFrame.name'/119, l='MpServer', x=151.97, y=75.50, z=263.50], EntityItemFrame['entity.ItemFrame.name'/120, l='MpServer', x=151.97, y=76.50, z=260.50]]
	Retry entities: 6 total; [EntityBat['Bat'/278, l='MpServer', x=-33.25, y=16.10, z=633.55], EntitySheep['Sheep'/266, l='MpServer', x=-31.66, y=63.00, z=619.20], EntitySheep['Sheep'/267, l='MpServer', x=-30.56, y=63.00, z=614.35], EntityBat['Bat'/269, l='MpServer', x=-26.05, y=16.72, z=634.89], EntitySheep['Sheep'/270, l='MpServer', x=-26.61, y=62.01, z=626.85], EntitySheep['Sheep'/271, l='MpServer', x=-29.70, y=62.33, z=625.04]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 308754952 bytes (294 MB) / 1060372480 bytes (1011 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 16 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms1G -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 Optifine OptiFine_1.10.2_HD_U_D6 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.78-BETA.jar) 
	UCHIJAAAA	JEI{3.14.5.406} [Just Enough Items] (jei_1.10.2-3.14.5.406.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.78-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon HD 3200 Graphics'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2281
	LWJGL: 2.9.4
	OpenGL: ATI Radeon HD 3200 Graphics GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 1x AMD Sempron(tm) SI-42
	OptiFine Version: OptiFine_1.10.2_HD_U_D6
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.11672 Compatibility Profile Context
	OpenGlRenderer: ATI Radeon HD 3200 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 1

**Comment by booski2005** [comment]
I noticed that you are using Optifine. I would ask you to try without Optifine  but I tested it myself **without Optifine** and it still happened. It also happens in 1.11.2 in both game modes. I don't know if I added to the conversation as I'm not too big a programmer (more a try hard) so please tell me if I shouldn't reply like this.

**Comment by radfast** [comment]
@booski2005 all comments are welcome, especially to know if other players are also having the same issue or not

you're seeing the crash also, so that means probably everyone is seeing it.

I'm sure we can fix this today.  **Crashes** are usually easy to fix, because the crash report (usually) tells us precisely which line, out of our 300,000 lines of code (that's only Galacticraft), triggered the error.

**Comment by radfast** [comment]
@buithanh12072001 thanks for reporting this.

This crash is fixed in next build 79.  It will be available for download later today.

**Comment by radfast** [comment]
[Build 79](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43421) now available

**Comment by buithanh12072001** [comment]
Thank you :)
