### ISSUE TITLE
[Outdated BETA] You can't /summon Spider queen

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#2691]
When  you do /summon spiderqueen on any planet, the screen goes all blue then Minecraft crashes.
Here is the crash report:

[## Uploading crash-2017-05-06_17.16.16-client.txt…]()

**Comment by marcus8448** [comment]
Ok, here is the crash report because it didn't upload (Sorry):

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.66-BETA.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 06/05/17 5:16 PM
Description: Rendering entity in world

java.lang.RuntimeException: net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model galacticraftplanets:web.obj with loader INSTANCE, skipping
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.updateModels(RenderSpiderQueen.java:50)
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.doRender(RenderSpiderQueen.java:79)
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.func_76986_a(RenderSpiderQueen.java:25)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:624)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model galacticraftplanets:web.obj with loader INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153)
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.updateModels(RenderSpiderQueen.java:42)
	... 17 more
Caused by: net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Error loading model previously: galacticraftplanets:models/web.obj
	at net.minecraftforge.client.model.obj.OBJLoader.loadModel(OBJLoader.java:103)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149)
	... 18 more
Caused by: java.lang.RuntimeException: OBJLoader.Parser: Exception parsing line #1115: `f 349/1/1 2/2/1 3/3/1`
	at net.minecraftforge.client.model.obj.OBJModel$Parser.parse(OBJModel.java:376)
	at net.minecraftforge.client.model.obj.OBJLoader.loadModel(OBJLoader.java:91)
	... 19 more
Caused by: java.lang.NullPointerException
	at net.minecraftforge.client.model.obj.OBJModel$Material.access$100(OBJModel.java:594)
	at net.minecraftforge.client.model.obj.OBJModel$Parser.parse(OBJModel.java:312)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.updateModels(RenderSpiderQueen.java:50)
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.doRender(RenderSpiderQueen.java:79)
	at micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen.func_76986_a(RenderSpiderQueen.java:25)

-- Entity being rendered --
Details:
	Entity Type: galacticraftplanets.spider_queen (micdoodle8.mods.galacticraft.planets.venus.entities.EntitySpiderQueen)
	Entity ID: 4897
	Entity Name: Spider Queen
	Entity's Exact location: 185.73, 69.00, 234.80
	Entity's Block location: World: (185,69,234), Chunk: (at 9,4,10 in 11,14; contains blocks 176,0,224 to 191,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: micdoodle8.mods.galacticraft.planets.venus.client.render.entity.RenderSpiderQueen@50e77b47
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 0.112351656
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:624)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['marcus8448'/675, l='MpServer', x=185.73, y=69.00, z=234.80]]
	Chunk stats: MultiplayerChunkCache: 430, 430
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (192,64,248), Chunk: (at 0,4,8 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 449 game time, 449 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 72 total; [EntityPig['Pig'/22, l='MpServer', x=149.76, y=69.00, z=239.56], EntityPig['Pig'/23, l='MpServer', x=161.72, y=67.00, z=225.64], EntityPig['Pig'/24, l='MpServer', x=160.70, y=67.00, z=227.78], EntityPig['Pig'/25, l='MpServer', x=172.18, y=68.00, z=233.46], EntityChicken['Chicken'/38, l='MpServer', x=194.50, y=68.00, z=164.78], EntityChicken['Chicken'/39, l='MpServer', x=190.50, y=63.00, z=175.50], EntityChicken['Chicken'/40, l='MpServer', x=189.50, y=63.00, z=177.50], EntityChicken['Chicken'/41, l='MpServer', x=192.50, y=66.00, z=175.50], EntityChicken['Chicken'/42, l='MpServer', x=200.18, y=70.00, z=203.61], EntityChicken['Chicken'/43, l='MpServer', x=196.50, y=70.00, z=204.50], EntityChicken['Chicken'/44, l='MpServer', x=182.22, y=66.00, z=204.22], EntityChicken['Chicken'/45, l='MpServer', x=186.62, y=67.00, z=203.89], EntityPig['Pig'/58, l='MpServer', x=262.50, y=78.00, z=300.50], EntityPig['Pig'/59, l='MpServer', x=263.50, y=77.00, z=296.50], EntityPig['Pig'/60, l='MpServer', x=261.50, y=79.00, z=301.50], EntityPig['Pig'/61, l='MpServer', x=262.50, y=78.00, z=301.50], EntitySkeleton['Skeleton'/4327, l='MpServer', x=252.76, y=23.00, z=271.50], EntitySkeleton['Skeleton'/4346, l='MpServer', x=209.23, y=57.00, z=276.52], EntitySpider['Spider'/4347, l='MpServer', x=207.40, y=57.00, z=276.40], EntitySpider['Spider'/4466, l='MpServer', x=226.50, y=53.00, z=233.50], EntitySkeleton['Skeleton'/4468, l='MpServer', x=221.75, y=53.00, z=236.49], EntityBat['Bat'/4509, l='MpServer', x=205.51, y=17.25, z=276.30], EntityBat['Bat'/4510, l='MpServer', x=204.15, y=16.40, z=273.42], EntityBat['Bat'/4511, l='MpServer', x=205.17, y=15.73, z=274.31], EntityBat['Bat'/4512, l='MpServer', x=210.45, y=16.03, z=270.60], EntityBat['Bat'/4513, l='MpServer', x=260.43, y=42.93, z=301.52], EntitySkeleton['Skeleton'/4517, l='MpServer', x=250.50, y=53.00, z=248.50], EntityCreeper['Creeper'/4519, l='MpServer', x=251.50, y=42.00, z=278.50], EntitySpider['Spider'/4581, l='MpServer', x=163.50, y=12.00, z=171.50], EntityZombie['Zombie'/4624, l='MpServer', x=220.50, y=11.00, z=185.50], EntityZombie['Zombie'/4625, l='MpServer', x=221.50, y=11.00, z=184.50], EntitySkeleton['Skeleton'/4634, l='MpServer', x=207.53, y=38.00, z=306.79], EntityZombie['Zombie'/4637, l='MpServer', x=235.50, y=19.00, z=257.50], EntityZombie['Zombie'/4638, l='MpServer', x=234.50, y=19.00, z=257.50], EntityCreeper['Creeper'/4662, l='MpServer', x=260.50, y=45.00, z=243.50], EntityCreeper['Creeper'/4667, l='MpServer', x=144.50, y=18.00, z=314.50], EntityCreeper['Creeper'/4675, l='MpServer', x=222.50, y=26.00, z=261.50], EntitySkeleton['Skeleton'/4693, l='MpServer', x=233.50, y=56.00, z=229.50], EntityCreeper['Creeper'/4702, l='MpServer', x=184.50, y=51.00, z=300.50], EntityCreeper['Creeper'/4703, l='MpServer', x=183.50, y=51.00, z=301.50], EntityCreeper['Creeper'/4704, l='MpServer', x=184.50, y=51.00, z=299.50], EntitySkeleton['Skeleton'/4727, l='MpServer', x=187.50, y=51.00, z=297.50], EntitySkeleton['Skeleton'/4728, l='MpServer', x=187.50, y=51.00, z=295.50], EntitySkeleton['Skeleton'/4729, l='MpServer', x=190.50, y=51.00, z=294.50], EntitySkeleton['Skeleton'/4730, l='MpServer', x=191.50, y=51.00, z=293.50], EntitySkeleton['Skeleton'/4766, l='MpServer', x=228.50, y=53.00, z=233.50], EntityCreeper['Creeper'/4799, l='MpServer', x=171.50, y=41.00, z=297.50], EntitySkeleton['Skeleton'/4819, l='MpServer', x=265.50, y=46.00, z=250.50], EntitySkeleton['Skeleton'/4827, l='MpServer', x=263.50, y=57.00, z=236.50], EntityCreeper['Creeper'/4854, l='MpServer', x=170.50, y=16.00, z=297.50], EntityCreeper['Creeper'/4855, l='MpServer', x=172.50, y=16.00, z=292.50], EntityCreeper['Creeper'/4856, l='MpServer', x=172.50, y=16.00, z=292.50], EntityCreeper['Creeper'/4857, l='MpServer', x=174.50, y=16.00, z=292.50], EntityWitch['Witch'/4859, l='MpServer', x=195.50, y=26.00, z=293.50], EntitySkeleton['Skeleton'/4865, l='MpServer', x=158.50, y=19.00, z=303.50], EntityCreeper['Creeper'/4866, l='MpServer', x=159.50, y=19.00, z=304.50], EntityCreeper['Creeper'/4867, l='MpServer', x=160.50, y=19.00, z=303.50], EntityZombie['Zombie'/4868, l='MpServer', x=170.50, y=13.00, z=220.50], EntitySpider['Spider'/4874, l='MpServer', x=227.50, y=53.00, z=230.50], EntityItem['item.item.seedtomate'/4892, l='MpServer', x=136.54, y=65.00, z=241.13], EntityItem['item.item.seeds'/4893, l='MpServer', x=136.19, y=68.00, z=240.82], EntitySpiderQueen['Spider Queen'/4897, l='MpServer', x=185.73, y=69.00, z=234.80], GCEntityClientPlayerMP['marcus8448'/675, l='MpServer', x=185.73, y=69.00, z=234.80], EntitySquid['Squid'/2188, l='MpServer', x=133.72, y=51.94, z=296.31], EntitySquid['Squid'/2189, l='MpServer', x=136.23, y=50.83, z=288.07], EntitySquid['Squid'/2190, l='MpServer', x=138.96, y=50.78, z=299.00], EntitySquid['Squid'/2191, l='MpServer', x=141.60, y=50.55, z=296.85], EntitySquid['Squid'/2199, l='MpServer', x=126.23, y=58.46, z=193.77], EntitySquid['Squid'/2203, l='MpServer', x=126.31, y=61.23, z=280.35], EntitySquid['Squid'/2209, l='MpServer', x=126.65, y=60.81, z=276.82], EntityItem['item.item.guideBook'/3719, l='MpServer', x=187.34, y=70.00, z=241.66], EntityZombie['Zombie'/3735, l='MpServer', x=212.50, y=38.00, z=311.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 560387672 bytes (534 MB) / 1304174592 bytes (1243 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2239 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2239.jar) 
	UCHIJAAAA	Forge{12.18.3.2239} [Minecraft Forge] (forge-1.10.2-12.18.3.2239.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	backpack{3.0.1} [Backpack] (Backpacks-Mod-1.10.2.jar) 
	UCHIJAAAA	cofhcore{4.1.1} [CoFH Core] (CoFHCore-1.10.2-4.1.1.156-universal.jar) 
	UCHIJAAAA	torohealthmod{1.10.2-7} [ToroHealth Damage Indicators] (damage-indicators-mod-by-torocraft-1.10.2.jar) 
	UCHIJAAAA	emeraldobsidianmod{1.5} [Emerald & Obsidian tools/armor mod] (emeraldobsidianmod-1.5.1-1.10.jar) 
	UCHIJAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.66-BETA.jar) 
	UCHIJAAAA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.66-BETA.jar) 
	UCHIJAAAA	guideBook{1.6.1} [Guide Book] (Guide-Book-Mod-1.10.2.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.12.801} [Iron Chest] (ironchest-1.10.2-7.0.12.801.jar) 
	UCHIJAAAA	JEI{3.14.7.416} [Just Enough Items] (Just-Enough-Items-Mod-1.10.2.jar) 
	UCHIJAAAA	LotsOfFood{1.12.0} [Lots of Food] (Lots of Food-1.10.2.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.10.2.jar) 
	UCHIJAAAA	simplyjetpacks{2.1.1.47} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.1.1.47.jar) 
	UCHIJAAAA	switchbow{1.0} [Switch-Bow] (Switch-Bow-Mod-1.10.2.jar) 
	UCHIJAAAA	thermalfoundation{2.0.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.5.81-universal.jar) 
	UCHIJAAAA	XaeroMinimap{1.12.6} [Xaero's Minimap] (Xaeros-Minimap-Mod-1.10.2.jar) 
	UCHIJAAAA	xlfoodmod{1.10.2-0.5.0} [XL Food Mod] (XL Food Mod-1.10.2-0.5.0.zip) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.66-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.65' Renderer: 'GeForce GT 540M/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2239
	LWJGL: 2.9.4
	OpenGL: GeForce GT 540M/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz

**Comment by SteveKunG** [comment]
Please use Galacticraft Build 84 or above, Should fix this.
https://ci.micdoodle8.com/job/Galacticraft-1.10/84/

**Comment by radfast** [comment]
Thanks @SteveKunG  :)
