### ISSUE TITLE
[1.11.2] build 86 startup crash

### ISSUE THREAD

**Issue by Timsuper** [micdoodle8/Galacticraft#2702]
GC build 86 is crashing Minecraft. I used the Technic Launcher with Forge for 1.11.2 preinstalled.
I tested build 85 and the game crashes the same way. Build 61 (for example) works fine under the same circumstances. But that's not all. The game worked some way before (build 86) by giving me the error in the picture below. Here the log:

```
[20:05:56] [Client thread/INFO]: Setting user: Timsuper2
[20:05:59] [Client thread/INFO]: LWJGL Version: 2.9.4
[20:06:00] [Client thread/INFO]: [STDOUT]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.86-BETA.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/10/17 8:06 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1672686080 bytes (1595 MB) / 2058354688 bytes (1963 MB) up to 2058354688 bytes (1963 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.86-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.165.1' Renderer: 'Radeon (TM) RX 480 Graphics'
[20:06:03] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core
[20:06:03] [Sound Library Loader/INFO]: Starting up SoundSystem...
[20:06:03] [Thread-8/INFO]: Initializing LWJGL OpenAL
[20:06:03] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[20:06:04] [Thread-8/INFO]: OpenAL initialized.
[20:06:04] [Sound Library Loader/INFO]: Sound engine started
[20:06:06] [Client thread/INFO]: Created: 16x16 textures-atlas
[20:06:06] [Client thread/INFO]: [STDERR]: Potential problem: Galacticraft did not complete injection of bytecode into: bqe (4 / 6)
[20:06:07] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1138) ~[bqe.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: cah
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:228) ~[Restriction.class:?]
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:500) ~[VersionRange.class:?]
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106) ~[GuiModsMissing.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1111) ~[bqe.class:?]
	... 9 more
```

![unbenannt](https://cloud.githubusercontent.com/assets/18632345/25914166/9d93cb5e-35bd-11e7-801c-7218faaf028b.JPG)

**Comment by radfast** [comment]
Please post your full latest log.

Which Forge version are you using?  You might be able to fix this just by updating Forge to any version since 2228.  Let us know if that fixes it for you!

If that doesn't fix it, please separate out these two issues (the crash and the loading screen) and for each one, tell us which is the **last** version of Galacticraft which did **not** have the problem.

**Comment by radfast** [comment]
Is [this](https://www.technicpack.net/modpack/minecraft-1112-forge.964429) what you're using?

**Comment by Timsuper** [comment]
Yep. Aww I just promised on there things, that they are up to date, but no. I'm very sorry.

**Comment by radfast** [comment]
Please post link to the Technic pack you used, so that we can maybe warn other people too...

Generally **modpacks are out of date**.  I've noticed most modpack makers make a modpack, upload it somewhere, then go to the beach or switch to playing League of Legends or something...

**Comment by Timsuper** [comment]
It was this pack: [https://www.technicpack.net/modpack/minecraft-1112-forge.964429](url)
