### ISSUE TITLE
[1.8.9] JEI java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2740]
Using latest 1.8.9 JEI
Galacticraft Build 99

> [00:52:42] [Client thread/ERROR] [JEI]: Couldn't get ItemModel for Galacticraft Planets itemStack 1xgalacticraftplanets:sulphuric_acid@0
java.lang.AbstractMethodError: micdoodle8.mods.galacticraft.planets.venus.VenusModuleClient$$Lambda$43/1360870920.func_178113_a(Lnet/minecraft/item/ItemStack;)Lnet/minecraft/client/resources/model/ModelResourceLocation;
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:49) ~[bfo.class:?]
	at mezz.jei.ItemFilter$ItemStackChecker.isItemStackHiddenByMissingModel(ItemFilter.java:176) [ItemFilter$ItemStackChecker.class:?]
	at mezz.jei.ItemFilter$ItemStackChecker.isItemStackHidden(ItemFilter.java:162) [ItemFilter$ItemStackChecker.class:?]
	at mezz.jei.ItemFilter.createBaseList(ItemFilter.java:83) [ItemFilter.class:?]
	at mezz.jei.ItemFilter.access$100(ItemFilter.java:28) [ItemFilter.class:?]
	at mezz.jei.ItemFilter$ItemFilterCacheLoader.load(ItemFilter.java:122) [ItemFilter$ItemFilterCacheLoader.class:?]
	at mezz.jei.ItemFilter$ItemFilterCacheLoader.load(ItemFilter.java:112) [ItemFilter$ItemFilterCacheLoader.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [guava-17.0.jar:?]
	at mezz.jei.ItemFilter.<init>(ItemFilter.java:41) [ItemFilter.class:?]
	at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:195) [ProxyCommonClient.class:?]
	at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:131) [ProxyCommonClient.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_156_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1122) [adm.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:197) [bdb.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2318) [ave.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2239) [ave.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:251) [bcy.class:?]
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:76) [gt.class:?]
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13) [gt.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by radfast** [comment]
Same issue as [this](http://www.minecraftforge.net/forum/topic/33822-solved-18-strange-abstractmethoderror-crash-with-lambda/)

**Comment by radfast** [comment]
@SteveKunG https://github.com/micdoodle8/Galacticraft/commit/372d1ee12c01e44b7c430ec7f69c5f5983c6b752 should fix this.  The issue does not occur in a **de-obfuscated** environment.  If you have a chance to test this in an obfuscated build, it would be good to know that it's OK.

**Comment by SteveKunG** [comment]
Thanks, Can you make GC build 100 for testing this?

**Comment by radfast** [comment]
Not ready to make build 100 yet, the changes in master are not yet merged to 1.10 and 1.11 and tested there.

Can you create your own test build using gradle?

**Comment by SteveKunG** [comment]
Can confirm it fixed.

**Comment by radfast** [comment]
great news, thank you
