### ISSUE TITLE
Galacticraft 1.10.2-4.0.0.102 render entities error + Multiplayer landing issue

### ISSUE THREAD

**Issue by sintaxcz** [micdoodle8/Galacticraft#2775]
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at micdoodle8.mods.galacticraft.core.client.render.entities.RenderEvolvedEnderman.doRender(RenderEvolvedEnderman.java:41)
	at micdoodle8.mods.galacticraft.core.client.render.entities.RenderEvolvedEnderman.func_76986_a(RenderEvolvedEnderman.java:17)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:398)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:375)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:812)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1749)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1574)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1347)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at micdoodle8.mods.galacticraft.core.client.render.entities.RenderEvolvedEnderman.doRender(RenderEvolvedEnderman.java:41)
	at micdoodle8.mods.galacticraft.core.client.render.entities.RenderEvolvedEnderman.func_76986_a(RenderEvolvedEnderman.java:17)

-- Entity being rendered --
Details:
	Entity Type: galacticraftcore.evolved_enderman (micdoodle8.mods.galacticraft.core.entities.EntityEvolvedEnderman)
	Entity ID: 1962
	Entity Name: Evolved Enderman
	Entity's Exact location: 861.50, 58.00, 1324.50
	Entity's Block location: World: (861,58,1324), Chunk: (at 13,3,12 in 53,82; contains blocks 848,0,1312 to 863,255,1327), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: micdoodle8.mods.galacticraft.core.client.render.entities.RenderEvolvedEnderman@141cf214
	Location: -33.00,-12.90,19.00 - World: (-33,-13,19), Chunk: (at 15,-1,3 in -3,1; contains blocks -48,0,16 to -33,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 115.656044
	Delta: 0.6579544
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:398)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:375)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:812)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1749)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1574)

This happen every time when i try to start game when im on moon or land on moon

+ I have issue on multiplayer server every time when some one launch rocket and select galacticraft planet he is teleported to galacticraft dimension and falling like player on planet and cant build etc. and after reconnect they spawn in landing module (baloons etc.) and sucesfully land (that is for version 100 and 102 but with 102 theyr client crash becouse of render bug)

**Comment by radfast** [comment]
Thanks for reporting, we should be able to fix the crash later today, I'll post in this thread when an update is available.

The lander spawning we can also investigate, is it a Sponge server?

**Comment by sintaxcz** [comment]
yes its a sponge server

**Comment by radfast** [comment]
The rendering crash issue is fixed next build, available later tonight.  I'm looking at the lander spawning also.  Hope to get both issues at once ...

**Comment by radfast** [comment]
The landing module spawning should be **improved** in build 103.

I'm not sure if the landing module is perfect yet, but please let us know how it goes on your server.  Any serious problem should be fixable if a player quits and relogs (it's currently not possible to quit if the player is stuck in the intermediate "One giant leap" screen - in that case the server can use the /kick command).

What I'm currently seeing in 1.10.2:

* the landing module sometimes spawns slowly, leaving the player in the intermediate screen for 5 seconds or so
* do a same-dimension launch and landing, with the player launching far from the landing site (so that the landing site chunks are unloaded at launch) - landing module sometimes spawns **very** slowly, needing 30 seconds to 1 minute to appear - sometimes the player will "fall" to the ground during this waiting time but it's not a true landing and the player can't break blocks, until after he lands properly

These problems are seen only in the [1.10.2] version, the [1.8.9] version is working perfectly ...

**Comment by radfast** [comment]
Build 104 now available with the fixes talked about here.
