### ISSUE TITLE
Crash while starting game

### ISSUE THREAD

**Issue by OmegaRogue** [micdoodle8/Galacticraft#2816]
[crash-2017-06-08_12.18.14-client.txt](https://github.com/micdoodle8/Galacticraft/files/1060775/crash-2017-06-08_12.18.14-client.txt)
log part (was 14 times in the log):
`[12:14:20] [Client thread/WARN]: ****************************************
[12:14:20] [Client thread/WARN]: * A broken ore dictionary registration with name ingotCopper has occurred. It adds an item (type: class micdoodle8.mods.galacticraft.core.items.ItemBasic) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Galacticraft Core report it to them!
[12:14:20] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[12:14:20] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[12:14:20] [Client thread/WARN]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:240)
[12:14:20] [Client thread/WARN]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
[12:14:20] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:14:20] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)...
[12:14:20] [Client thread/WARN]: ****************************************`

**Comment by radfast** [comment]
Please provide either the crash report or the full log.

What you've posted is a standard and uninteresting warning message in logs, 99.9% chance that has no connection with any crash.  (I'm a bit surprised to see that warning message, are you using the latest Galacticraft version?)

**Comment by OmegaRogue** [comment]
this probably hasnt caused the crash, but i found the log part while searching the log for the cause and i have 1.7-3.0.12.375 so not the lastest at all

**Comment by radfast** [comment]
If you update Galacticraft to the latest build 500 or 501, that logging should be gone.  You'll also get 2 years worth of other improvements ... ... and updating Galacticraft should never break compatibility with other stuff.  (Unlike other mods, we don't increase our requirements or force users to update other stuff).

If you're playing a modpack, please request the modpack creator to update the Galacticraft version, it's unacceptable to be still distributing such an old version of our mod.

Sounds like you have an EnderIO crash, so I'm closing this issue.
