### ISSUE TITLE
Right-clicking nitrogen canister crashes.

### ISSUE THREAD

**Issue by SixtyFourWarrior** [micdoodle8/Galacticraft#2827]
Title explains all. Using GC Build 107

Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.11.2-Latest.jar)
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.107.jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.2.0.216-universal.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 6/11/17 3:55 PM
XRay version: 48
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at micdoodle8.mods.galacticraft.planets.asteroids.items.ItemCanisterLiquidNitrogen.func_77659_a(ItemCanisterLiquidNitrogen.java:113)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:196)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:496)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:72)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1539)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at micdoodle8.mods.galacticraft.planets.asteroids.items.ItemCanisterLiquidNitrogen.func_77659_a(ItemCanisterLiquidNitrogen.java:113)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:196)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:496)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:72)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1539)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['WelshRabbit'/130, l='MpServer', x=-2158.30, y=31.00, z=195.66]]
	Chunk stats: MultiplayerChunkCache: 600, 600
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1996,4,199), Chunk: (at 4,0,7 in -125,12; contains blocks -2000,0,192 to -1985,255,207), Region: (-4,0; contains chunks -128,0 to -97,31, blocks -2048,0,0 to -1537,255,511)
	Level time: 53659 game time, 1140 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntityItem['item.tile.unlit_torch_lit'/4395267, l='MpServer', x=-2146.51, y=31.00, z=211.13], EntityItem['item.tile.unlit_torch_lit'/4395266, l='MpServer', x=-2118.45, y=31.00, z=212.88], EntityItem['item.tile.unlit_torch_lit'/4395265, l='MpServer', x=-2125.16, y=31.00, z=212.88], EntityItem['item.tile.unlit_torch_lit'/4395268, l='MpServer', x=-2157.88, y=31.00, z=198.71], GCEntityClientPlayerMP['WelshRabbit'/130, l='MpServer', x=-2158.30, y=31.00, z=195.66]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 482338608 bytes (459 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 529, tallocated: 10051
	FML: Minecraft 1.11.2 MCP 9.38 Powered by Forge 13.20.0.2303 Optifine OptiFine_1.11.2_HD_U_C1 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2303.jar) 
	UCHIJAAAA	forge{13.20.0.2303} [Minecraft Forge] (forge-1.11.2-13.20.0.2303.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-Latest.jar) 
	UCHIJAAAA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-Latest.jar) 
	UCHIJAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.107.jar) 
	UCHIJAAAA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.107.jar) 
	UCHIJAAAA	jei{4.3.5.277} [Just Enough Items] (jei_1.11.2-4.3.5.277.jar) 
	UCHIJAAAA	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.2.0.216-universal.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.11.2-Latest.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.107.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
NEICorePlugin (NotEnoughItems-1.11.2-2.2.0.216-universal.jar)
  codechicken.nei.asm.NEITransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon HD 4300/4500 Series'
	nei Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2303
	LWJGL: 2.9.4
	OpenGL: ATI Radeon HD 4300/4500 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: A Random Texture Pack.zip (incompatible)
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q8400 @ 2.66GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_C1
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.11672 Compatibility Profile Context
	OpenGlRenderer: ATI Radeon HD 4300/4500 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by radfast** [comment]
Thank you for reporting.

This will be fixed in our next build 108 as soon as we can get that out, see #2794

**Comment by SixtyFourWarrior** [comment]
Ah yes we figured it out together, didn't see Seba reported that, thanks!
