### ISSUE TITLE
Galactic Craft

### ISSUE THREAD

**Issue by heypops3** [micdoodle8/Galacticraft#2833]
Im hosting a Modded 1.7.10 Minecraft server. I logged off inside of my space station and other player can still connect but when I connect the server crashes with this error

java.lang.NullPointerException: Exception ticking world
	at micdoodle8.mods.galacticraft.core.dimension.WorldProviderOrbit.checkSS(WorldProviderOrbit.java:1144)
	at micdoodle8.mods.galacticraft.core.dimension.WorldProviderOrbit.readFromNBT(WorldProviderOrbit.java:1394)
	at micdoodle8.mods.galacticraft.core.dimension.WorldProviderOrbit.updateWeather(WorldProviderOrbit.java:252)
	at net.minecraft.world.World.func_72979_l(World.java:2692)
	at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:979)
	at net.minecraft.world.World.func_72835_b(World.java:2669)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:137)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Help!

**Comment by radfast** [comment]
Please specify the exact Galacticraft version and other mods installed - best way is to paste a copy of the server's latest log.

**Comment by heypops3** [comment]
Sorry I just had to delete the space space station from the forge folder and it worked

**Comment by radfast** [comment]
OK.  I'm not sure why this happened, maybe somehow a bad save of that dimension.

Any more problems, please re-open.  Everything is supposed to be working correctly in 1.7.10, it's been stable for a while now.
