### ISSUE TITLE
[1.10.2] Crashed with Arclamp

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2876]
In my development test I just place 3 block of Arclamp.

`net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:688) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:537) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

`Caused by: java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.core.tile.TileEntityArclamp.lightArea(TileEntityArclamp.java:400) ~[TileEntityArclamp.class:?]
	at micdoodle8.mods.galacticraft.core.tile.TileEntityArclamp.update(TileEntityArclamp.java:155) ~[TileEntityArclamp.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1952) ~[World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:647) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:784) ~[MinecraftServer.class:?]
	... 4 more`

**Comment by radfast** [comment]
That commit should fix it - please re-open if it still crashes.
