### ISSUE TITLE
[1.7.10] ClassCastException while fast breaking double treasury chests

### ISSUE THREAD

**Issue by Ghostlyr** [micdoodle8/Galacticraft#2881]
Occurs randomly during breaking and placing treasury chests. Unfortunately, did not find any specific conditions to reproduce it.

```
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to micdoodle8.mods.galacticraft.planets.mars.blocks.BlockTier2TreasureChest
	at micdoodle8.mods.galacticraft.planets.mars.client.render.tile.TileEntityTreasureChestRenderer.renderGCTileEntityTreasureChestAt(TileEntityTreasureChestRenderer.java:41)
	at micdoodle8.mods.galacticraft.planets.mars.client.render.tile.TileEntityTreasureChestRenderer.func_147500_a(TileEntityTreasureChestRenderer.java:152)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:766)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

GalacticraftCore-1.7-3.0.12.501
Galacticraft-Planets-1.7-3.0.12.501
MicdoodleCore-1.7-3.0.12.501
MC 1.7.10 Forge 1614
No addons installed

**Comment by radfast** [comment]
Thanks for reporting, we should be able to fix this.  For now, be careful around your double treasure chests!

**Comment by radfast** [comment]
Fixed in build 504, for anyone who is still watching this.  (Also fixed in all Galacticraft 4 versions...)
