### ISSUE TITLE
[1.8.9] Deconstructor crash the game

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2886]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 10/7/2560, 10:18 น.
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.toItemStackList(TileEntityDeconstructor.java:387)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.getIngredients(TileEntityDeconstructor.java:293)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.getSalvageable(TileEntityDeconstructor.java:220)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.deconstruct(TileEntityDeconstructor.java:185)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.update(TileEntityDeconstructor.java:152)
	at net.minecraft.world.World.updateEntities(World.java:1860)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:560)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:777)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.toItemStackList(TileEntityDeconstructor.java:387)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.getIngredients(TileEntityDeconstructor.java:293)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.getSalvageable(TileEntityDeconstructor.java:220)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.deconstruct(TileEntityDeconstructor.java:185)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor.update(TileEntityDeconstructor.java:152)

-- Block entity being ticked --
Details:
	Name: GC Deconstructor // micdoodle8.mods.galacticraft.core.tile.TileEntityDeconstructor
	Block type: ID #236 (tile.machine2 // micdoodle8.mods.galacticraft.core.blocks.BlockMachine2)
	Block data value: 13 / 0xD / 0b1101
	Block location: World: (-98,56,-426), Chunk: (at 14,3,6 in -7,-27; contains blocks -112,0,-432 to -97,255,-417), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #236 (tile.machine2 // micdoodle8.mods.galacticraft.core.blocks.BlockMachine2)
	Actual block data value: 13 / 0xD / 0b1101
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1860)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:560)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [GCEntityPlayerMP['SteveKunG'/0, l='New World', x=-99.26, y=56.00, z=-425.36]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 1165177511073120542
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,3*minecraft:stone,52*minecraft:sandstone;2;
	Level spawn location: -93.00,4.00,-419.00 - World: (-93,4,-419), Chunk: (at 3,0,13 in -6,-27; contains blocks -96,0,-432 to -81,255,-417), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1286 game time, 1286 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 63813 (now: false), thunder time: 165473 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:777)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1188612216 bytes (1133 MB) / 2095185920 bytes (1998 MB) up to 2095185920 bytes (1998 MB)
	JVM Flags: 3 total; -Xincgc -Xmx2048M -Xms2048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8.9-11.15.1.2318-1.8.9-PROJECT(1.8.9).jar) 
	UCHIJAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forgeSrc-1.8.9-11.15.1.2318-1.8.9-PROJECT(1.8.9).jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	GalacticraftCore{4.0.0} [Galacticraft Core] (bin) 
	UCHIJAAAA	GalacticraftPlanets{4.0.0} [Galacticraft Planets] (bin) 
	UCHIJAAAA	indicatorutils{2.1.2} [Indicator Utils] (bin) 
	UCHIJAAAA	moreplanets{2.0.5} [More Planets] (bin) 
	UCHIJAAAA	JEI{2.28.9.177} [Just Enough Items] (jei_1.8.9-2.28.9.177.jar) 
	UCHIJAAAA	NBTEdit{1.8.9-2.0.0} [In-game NBTEdit] (NBTEdit-deobf-1.8.9-2.0.0.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (unknown)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['SteveKunG'/0, l='New World', x=-99.26, y=56.00, z=-425.36]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by radfast** [comment]
Which block / item did you use as input for the Deconstructor?

**Comment by SteveKunG** [comment]
Tier 3 Rocket / meta 0

**Comment by radfast** [comment]
That's strange, I tested with all the rockets...

**Comment by radfast** [comment]
OK the issue was already fixed in 1.10 and 1.11 but I forgot to fix 1.8.9.  Now included in next build 113.  I hope this didn't affect too many people - probably most are downloading 1.10 or 1.11.
