### ISSUE TITLE
Friend unable to connect to server when Galacticraft is installed.

### ISSUE THREAD

**Issue by Zucchini101** [micdoodle8/Galacticraft#2911]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)
Whenever we try to install galacticraft on our private server one of my friends gets a 'Fatal error, the connection was terminated' This is what he gets inside the console (using the Twitch Launcher) It's a server of 5 people and we all get on the server fine with the mod, except our one friend. We'd like to be able to play all together with the galacticraft mod so hopefully you could help us. Thank you.

Minecraft version: 1.7.10
Galacticraft version:1.7-3.0.12.501
Forge version: 1.7.10-10.13.4.1614

Single player (SSP) or Multiplayer (SMP)? Multiplayer

Galacticraft add-ons and other mods installed?
Using the Trollcraft modpack with added mods: Buildcraft, Aether II, and Galacticraft
Please provide screenshots / crash report / log as needed.

There was a critical exception handling a packet on channel FORGE
java.lang.NullPointerException
at net.minecraftforge.fluids.FluidRegistry.loadFluidDefaults(FluidRegistry.java:117)
at net.minecraftforge.fluids.FluidRegistry.initFluidIDs(FluidRegistry.java:82)
at net.minecraftforge.common.network.FluidIdRegistryMessageHandler.channelRead0(FluidIdRegistryMessageHandler.java:15)
at net.minecraftforge.common.network.FluidIdRegistryMessageHandler.channelRead0(FluidIdRegistryMessageHandler.java:11)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMe

**Comment by TheQuadShot** [comment]
What does the server console say when he tried to connect? In most cases that I've run into is that that player has a mod not on the server or is missing a mod that the server has. This could be just a version mismatch. If the player that can't connect can run his game in SSP then it's definitely a mod mismatch. The easy fix is to send him a copy of your mod folder.

**Comment by Zucchini101** [comment]
My friend managed to fix the issue on his own but thank you for the help anyway! <3

**Comment by MJRLegends** [comment]
@Zucchini101 If this was a one time, user only issue i think it would be best to close this issue. But if its something others might have it might benefit players if the issue was posted here so later players dont need to look far for a fix :D

**Comment by radfast** [comment]
I don't see any Galacticraft issue here.

The likely cause of the error was different mod versions of a mod / some mods between client and server.
