### ISSUE TITLE
[Terrain Control mod] place any objects/blocks on Moon with right-click not saved after logout

### ISSUE THREAD

**Issue by chezpaul** [micdoodle8/Galacticraft#2935]
Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.114
Forge version: 12.18.3.2316

Single player (SSP) or Multiplayer (SMP)? Multiplayer

Mods used: appliedenergistics2-core, ivtoolkit, Micdoodlecore, NotEnoughItems, OpenComputers|Core, , ae2stuff, animania, appliedenergistics2, arsmagica2, AnimationAPI, Baubles, bdlib, bedbugs, BiblioCraft, biomebundle, BiomesOPlenty, bookshelf, Botania, bottledmilk, cfm, Chameleon, ChickenChunks, chisel, CodeChickenCore, CodeChickenLib, ccl-entityhook, cofhcore, PTRModelLib, props, eplus, endercore, EnderIO, EnderStorage, EnderZoo, energyconverters, extrautils2, fluxnetworks, forestry, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, galacticraftplanets, galacticraftcore, gendustry, geographicraft, GraveStone, hammercore, Waila, immersiveengineering, imc, IC2, ironbackpacks, ironchest, JEI, jeibees, malisiscore, malisisdoors, mantle, mcmultipart, Mekanism, MekanismGenerators, MekanismTools, mercurius_updater, testdummy, Morpheus, MrTJPCoreMod, mysticalagriculture, natura, neid, notenoughwands, OpenComputers, openterraingenerator, p455w0rdslib, getalltheseeds, harvestcraft, plustic, pressure, projectred-core, projectred-integration, projectred-transmission, projectred-illumination, projectred-expansion, projectred-transportation, railcraft, reccomplex, redstonearsenal, roguelike, simplecorn, solarfluxreborn, sonarcore, special_ai, StorageDrawers, tconstruct, thermaldynamics, thermalexpansion, thermalfoundation, Translocator, unidict, wailaplugins, wanionlib, weaponcaseloot, wct, worldcontrol, worldedit, wrcbe, xtones

I will build a base, add all kinds of items. Solar energy, energy storage, Aluminum wires etc, fuel loader.
Fuel loader won't drain fuel tanks inserted or see battery in it. Energy storage device won't let me click on it to open gui, Solar panels don't ever see the sun. Items will duplicate within my inventory. Whatever I just placed down will re appear in my inv within a minute. 
Then if I log out and then back in, all items and blocks are gone. I can only see where I have dug into the ground, nothing else. Launching pad gone etc...

If I click on launcher to access my chests, once opened my inventory will be different from when it was closed. All my armor also got duplicated.

Here's my server [log](https://pastebin.com/wq0ryDVA):

**Comment by MJRLegends** [comment]
Ok from your log i see terraincontrol spamming errors all other your console, this is why as its rejecting and cancelling the right click event

`[12:03:48] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@73cce088:
java.lang.NullPointerException
    at com.khorn.terraincontrol.forge.events.RightClickBlockListener.onRightClickBlock(RightClickBlockListener.java:24) ~[RightClickBlockListener.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_507_RightClickBlockListener_onRightClickBlock_RightClickBlock.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026) [ForgeHooks.class:?]
    at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:435) [lv.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) [me.class:?]
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [jj.class:?]
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [jj.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

**Comment by chezpaul** [comment]
Cool, thanks for the response.
I just talked to the Terrain Control dens and they say it's a known bug already fixed for the next release. So that's great.  ;-)
Thanks

**Comment by PG85** [comment]
This will be fixed for OTG 1.10.2 v 22 / OTG 1.11.2 v7 (should be this week). Thanks for reporting this!

**Comment by Mooglemuffins** [comment]
[I'm glad I wasn't the only one experiencing this](https://github.com/micdoodle8/Galacticraft/issues/2926)

**Comment by PG85** [comment]
Here's a link to a dev version with the fix: https://cdn.discordapp.com/attachments/307111022257373185/342455263594283018/OpenTerrainGenerator-1.10.2_-_Rocket_Fuel_Edition_v4.jar

It's a dev version, it should be alright but just to be sure it can't hurt to back up your world.
