### ISSUE TITLE
[with IC2] Cannot Pump Oil

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [micdoodle8/Galacticraft#2973]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: GalacticraftCore-1.10.2-4.0.0.117
IC2 Version : industrialcraft-2-2.6.252-ex110  and  industrialcraft-2-2.6.254-ex110
Forge version: 1.10.2-12.18.3.2422

Single player (SSP) or Multiplayer (SMP)?  SSP

World crashes with tesselating block error when trying to pump galacticraft oil with IC2 Pump. 
Log appears to point at GC Oil missing properties that the pump needs.  It also cannot be pumped by Extra Utilities node with Pump upgrade, also leading me to believe its a GC Oil issue.  
Both collection methods seem to work correctly on all other fluids.
Please let me know if this is fixable.  Thank You.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.254-ex110.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.117.jar)
  SimpleCore (SimpleQuarry-1.10.2_1.0.2.jar)
  PlayerAPIPlugin (PlayerAPI-1.10.2-1.1.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.308-universal.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 9/5/17 1:45 PM
Description: Tesselating block in world

java.lang.IllegalArgumentException: Cannot get property MaterialProperty{name=material, clazz=class ic2.core.block.state.MaterialProperty$WrappedMaterial, values=[ic2.core.block.state.MaterialProperty$WrappedMaterial@360ba44f, ic2.core.block.state.MaterialProperty$WrappedMaterial@443fae4a, ic2.core.block.state.MaterialProperty$WrappedMaterial@56f4226]} as it does not exist in ExtendedBlockState{block=galacticraftcore:crude_oil_still, properties=[level]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at ic2.core.block.BlockTileEntity.func_149688_o(BlockTileEntity.java:428)
	at micdoodle8.mods.galacticraft.core.blocks.BlockFluidGC.getFluidHeightForRender(BlockFluidGC.java:195)
	at micdoodle8.mods.galacticraft.core.blocks.BlockFluidGC.getExtendedState(BlockFluidGC.java:139)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at gcewing.sg.BaseAORenderingManager$CustomBlockRendererDispatcher.func_175018_a(BaseAORenderingManager.java:85)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:171)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:952)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by radfast** [comment]
thanks for reporting, we'll take a look

**Comment by TheQuadShot** [comment]
Sorry if this is a dumb question, but I thought liquids animated and weren't a tessellating block, What am I missing? Thanks in advance.

**Comment by radfast** [comment]
Liquids are a block, but the render is custom.  First the surface height of the liquid can be from 1-8 depending on how it has flowed from a source block.  Second, the texture is animated - a few other blocks have animated textures.

"Tesselating" is part of the render engine in the Minecraft client.

The issue here appears to be an interaction between what IC2 expects from a fluid block and GC's implementation of a fluid block.  I will need to look at IC2 code to understand the issue (and that's always a pain, because IC2 is a closed-source mod).

**Comment by MachiavelliSeraphim** [comment]
Sorry for the trouble.
Why cant everything be easy... lol.
________________________________

**Comment by TheQuadShot** [comment]
@radfast Thanks for the brief explanation. I miss understood "tesselating" I guess I was thinking of mosaics and assumed it was how it displayed repeating patterns, like chisel n' bits tiles. btw do you know of any flow chart's or something like it on how the engine works? I've not had any luck finding something like that.

**Comment by radfast** [comment]
Should be fixed in next build 119.

@TheQuadShot to understand how the engine works, I really recommend http://greyminecraftcoder.blogspot.co.uk/ - it's well written and useful.

**Comment by MachiavelliSeraphim** [comment]
Thank you guys!
