### ISSUE TITLE
Galacticraft loading world now crashes game?

### ISSUE THREAD

**Issue by GFrE420** [micdoodle8/Galacticraft#2981]
I've been playing one world for a few weeks without problems, and I got pretty far. Today, all of the sudden, my world will either instantly crash upon loading or will stay on "loading world" forever. Is there anything I can do? Here's the crash report:

Minecraft version:1.11.2
Galacticraft version: Galacticraft 4, 1.11.2
Forge version:1.11.2

Single player

Galacticraft and Just enough items

---- Minecraft Crash Report ----

WARNING: coremods are present:
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.117 (1).jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 9/17/17 4:10 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 3
at java.util.Arrays$ArrayList.get(Arrays.java:3841)
at net.minecraft.util.NonNullList.get(SourceFile:40)
at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.canProcess(TileEntityElectricFurnace.java:163)
at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.shouldUseEnergy(TileEntityElectricFurnace.java:342)
at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.shouldPullEnergy(TileBaseElectricBlock.java:42)
at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_73660_a(TileBaseElectricBlock.java:102)
at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.func_73660_a(TileEntityElectricFurnace.java:95)
at net.minecraft.world.World.func_72939_s(World.java:1802)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
at java.util.Arrays$ArrayList.get(Arrays.java:3841)
at net.minecraft.util.NonNullList.get(SourceFile:40)
at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.canProcess(TileEntityElectricFurnace.java:163)
at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.shouldUseEnergy(TileEntityElectricFurnace.java:342)
at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.shouldPullEnergy(TileBaseElectricBlock.java:42)
at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_73660_a(TileBaseElectricBlock.java:102)
at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.func_73660_a(TileEntityElectricFurnace.java:95)

-- Block entity being ticked --
Details:
Name: minecraft:gc electric furnace // micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace
Block type: ID #276 (tile.machine_tiered // micdoodle8.mods.galacticraft.core.blocks.BlockMachineTiered)
Block data value: 13 / 0xD / 0b1101
Block location: World: (304,63,278), Chunk: (at 0,3,6 in 19,17; contains blocks 304,0,272 to 319,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Actual block type: ID #276 (tile.machine_tiered // micdoodle8.mods.galacticraft.core.blocks.BlockMachineTiered)
Actual block data value: 13 / 0xD / 0b1101
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1802)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
Level name: End me
All players: 0 total; []
Chunk stats: ServerChunkCache: 625 Drop: 0
Level seed: 7999988012284393947
Level generator: ID 00 - default, ver 1. Features enabled: true
Level generator options:
Level spawn location: World: (208,64,252), Chunk: (at 0,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 3531494 game time, 1344823 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 115550 (now: false), thunder time: 145952 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
Minecraft Version: 1.11.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 317385608 bytes (302 MB) / 847810560 bytes (808 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
FML: MCP 9.38 Powered by Forge 13.20.1.2454 9 mods loaded, 9 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar)
UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2454.jar)
UCHIJAAAA	forge{13.20.1.2454} [Minecraft Forge] (forge-1.11.2-13.20.1.2454.jar)
UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar)
UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar)
UCHIJAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.117 (2).jar)
UCHIJAAAA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.117.jar)
UCHIJAAAA	jei{4.5.0.294} [Just Enough Items] (jei_1.11.2-4.5.0.294.jar)
Loaded coremods (and transformers):
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.117 (1).jar)
micdoodle8.mods.miccore.MicdoodleTransformer
GL info: ERROR RuntimeException: No OpenGL context found in the current thread.
Profiler Position: N/A (disabled)
Player Count: 0 / 8; []
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by GFrE420** [comment]
I figured it out. To anyone who may have this problem, I was able to fix it by using MCedit to delete an arc furnace i'd built, and it worked. If you have an arc furnace and your game starts crashing, try deleting it.
