### ISSUE TITLE
Players disconnect with Internal Server Error when encountering water on the Moon

### ISSUE THREAD

**Issue by TiranDirth** [micdoodle8/Galacticraft#2994]
Minecraft version: 1.7.10
Galacticraft version: 3.0.12.502
Forge version: 10.13.4.1614

Single player (SSP) or Multiplayer (SMP)? SMP

Galacticraft add-ons and other mods installed? Galaxy Space 1.1.5

Please provide screenshots / crash report / log as needed.

Log from the server side:

`[01:27:21] [Server thread/INFO]: TiranDirth joined the game
[01:27:21] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[01:27:21] [Server thread/INFO] [Waila]: Player GCEntityPlayerMP['TiranDirth'/3948805, l='AFBCraft', x=-790.58, y=67.33, z=-159.59] connected. Sending ping
[01:27:21] [Server thread/INFO] [Mekanism]: Sent config to 'TiranDirth.'
[01:27:24] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent@7f06591b:
java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.util.WorldUtil.getProviderForDimensionClient(I)Lnet/minecraft/world/WorldProvider;
        at galaxyspace.SolarSystem.core.events.GSEventHandler.freezeBlocks(Unknown Source) ~[GSEventHandler.class:?]
        at galaxyspace.SolarSystem.core.events.GSEventHandler.onEntityUpdate(Unknown Source) ~[GSEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_405_GSEventHandler_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287) [ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071h(EntityLivingBase.java:1560) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071h(EntityPlayer.java:288) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) [nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) [jd.class:?]
at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) [jf.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[01:27:24] [Server thread/ERROR] [FML]: Index: 12 Listeners:
[01:27:24] [Server thread/ERROR] [FML]: 0: NORMAL
[01:27:24] [Server thread/ERROR] [FML]: 1: ASM: baubles.common.event.EventHandlerEntity@644d419d playerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 2: ASM: vazkii.botania.common.item.equipment.bauble.ItemTravelBelt@7ae01e0f updatePlayerStepStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 3: ASM: vazkii.botania.common.item.equipment.bauble.ItemFlightTiara@5adc1dea updatePlayerFlyStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 4: ASM: vazkii.botania.common.brew.potion.PotionFeatherfeet@1881a3bc onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 5: ASM: vazkii.botania.common.brew.potion.PotionAllure@479aac7b onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 6: ASM: com.rwtema.extrautils.item.ItemAngelRing$EventHandlerRing@16c1b36f entTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 7: ASM: Reika.ChromatiCraft.ChromaticEventManager@4f47766a sinkingEnchantment(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 8: ASM: Reika.ChromatiCraft.ChromaticEventManager@4f47766a checkRainbowForest(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 9: ASM: Reika.ChromatiCraft.ChromaticEventManager@4f47766a stopSomeTicks(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 10: ASM: crazypants.enderio.machine.spawner.BlockPoweredSpawner@3e2a7bd2 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 11: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@7bdc742e entityLivingEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 12: ASM: galaxyspace.SolarSystem.core.events.GSEventHandler@257a35e8 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 13: ASM: vazkii.botania.common.core.handler.SheddingHandler@526cef98 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 14: ASM: twilightforest.TFEventListener@7b0b1c88 livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)Z
[01:27:24] [Server thread/ERROR] [FML]: 15: ASM: com.carpentersblocks.util.handler.EventHandler@7a952a6b onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 16: ASM: com.rwtema.extrautils.EventHandlerServer@528127c7 updateEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 17: ASM: com.rwtema.extrautils.EventHandlerSiege@5af55f73 Siege(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 18: ASM: Reika.ChromatiCraft.Auxiliary.Ability.AbilityHelper@7d6728e8 addPoint(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 19: ASM: galaxyspace.SolarSystem.core.achievements.AchEvent@498755e7 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 20: ASM: com.emoniph.witchery.infusion.Infusion$EventHooks@7eabbb6e onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 21: ASM: com.emoniph.witchery.common.GenericEvents@5126b3b2 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/ERROR] [FML]: 22: ASM: com.emoniph.witchery.brewing.potions.WitcheryPotions$EventHooks@1db91e55 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[01:27:24] [Server thread/WARN]: Failed to handle packet for /109.148.157.81:61373
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.util.WorldUtil.getProviderForDimensionClient(I)Lnet/minecraft/world/WorldProvider;
        at galaxyspace.SolarSystem.core.events.GSEventHandler.freezeBlocks(Unknown Source) ~[GSEventHandler.class:?]
        at galaxyspace.SolarSystem.core.events.GSEventHandler.onEntityUpdate(Unknown Source) ~[GSEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_405_GSEventHandler_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071h(EntityLivingBase.java:1560) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071h(EntityPlayer.java:288) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
        ... 10 more
[01:27:24] [Server thread/INFO]: TiranDirth lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[01:27:24] [Server thread/INFO]: TiranDirth left the game`

The server continues to run just fine for everyone but the affected player.

Happens both with player-placed water and naturally generating water in villages, both work perfectly fine in SSP but cause the issue in SMP. Tested with multiple clients with the same issue seen.

I suspect this to be something to do with Galaxy Space freezing water to ice, but I figured it can't hurt to post here.

Modlist:
Another One Bites the Dust
AE2
Baubles
Bibliocraft
Botania
Buildcraft
Carpenters Blocks
Chisel 2
Chromaticraft
CodeChickenCore
Damage Indicators
Dragon API
Ender IO
EnderCore
Extra Cells 2
Extra Utilities
ExtraTiC
Forestry
Forge Microblocks
Galacticraft Core
Galacticraft Planets
GalaxySpace
GeoStrata
Harcore Ender Expansion
Hats
iChunUtil
Iguana Tinker Tweaks
INpureCore
Inventory Tweaks
JourneyMap
Mantle
Mekanism
Mekanism Generators
Mekanism Tools
Metallurgy 4
Micdoodle8 Core
MineTweaker 3
MineTweakerRecipeMaker
Mod Tweaker 2
Morpheus
MrTJPCore
Natura
NEI
OpenBlocks
OpenMods
OpenModsCore
ProjectRed Core
Railcraft
The Twilight Forest
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Tinkers' Construct
Waila
Waila Harvestability
Witchery

**Comment by marcus8448** [comment]
Yeah... I think this is galaxy space not Galacticraft

**Comment by TiranDirth** [comment]
That's what I figured from the error, but these things are not always clear cut so I thought it best to check here too.

**Comment by TheQuadShot** [comment]
Do you have Headcrumbs installed? Or a mod that names mob's/npc's? I've seen this error
"Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent@7f06591b:" When a mob spawns and doesn't get a name or the name is "null".

**Comment by TiranDirth** [comment]
I don't believe so. I've not installed anything that intentionally does that and haven't seen any instances of that.

Edited in a modlist to the OP.

**Comment by TiranDirth** [comment]
It was Galaxy Space, issue fixed with an update there so I'll close this.
