### ISSUE TITLE
[1.11.2] java.lang.ArrayIndexOutOfBoundsException: 4

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [micdoodle8/Galacticraft#2997]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.11.2
Galacticraft version: 117
Forge version: 2376

Single player (SSP) or Multiplayer (SMP)? Multi

Galacticraft add-ons and other mods installed? Extra Planets

Please provide screenshots / crash report / log as needed.

```
java.lang.ArrayIndexOutOfBoundsException: 4
    at micdoodle8.mods.galacticraft.core.network.PacketSimple.handleClientSide(PacketSimple.java:329)
    at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.tick(GalacticraftPacketHandler.java:65)
    at micdoodle8.mods.galacticraft.core.tick.TickHandlerClient.onClientTick(TickHandlerClient.java:639)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1106_TickHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Arkyo** [comment]
/dimensiontp from SS to Overworld , server error:

```
[22:52:43] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at mcp.mobius.waila.network.MessageRequestEntity$Handler$1.run(MessageRequestEntity.java:68) ~[MessageRequestEntity$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by radfast** [comment]
First crash report is likely caused by having **different Galacticraft versions on client and server**.  Please tell us the exact Galacticraft version you have on your client and on your server.

If it's not that, it could be caused by Extra Planets mod.  Please test without Extra Planets.  It would also be useful to know what you were trying to do when the bug happened.

Second crash report appears to be a bug in WAILA not Galacticraft.  Do you even need to have WAILA on your server?

**Comment by radfast** [comment]
Updated my post ^^^^^^^^^^^^^^.  @MJRLegends have you come across this elsewhere?

**Comment by MJRLegends** [comment]
@radfast Nope sorry never seen this before

**Comment by radfast** [comment]
Closing due to **no response** from original poster.

@Pythonic-Rainbow if you can answer some of my questions above ^^^^^ I can maybe do more here.

**Comment by Pythonic-Rainbow** [comment]
I have removed thiis modpack , so I can't test it out
and I've forgot whether have I removed WAILA from server

**Comment by Sirse** [comment]
Seems like that problem occurs when station name contains "?" charter
