### ISSUE TITLE
Crash while using Arc Furnaces

### ISSUE THREAD

**Issue by BlitzAce71** [micdoodle8/Galacticraft#3028]
@radfast This is the crash from the arc furnace I mentioned over in issue 3004.

Minecraft version: 1.11.2
Galacticraft version: 1.11.2-4.0.0.117
Forge version: 1.11.2-13.20.0.2315

Single player (SSP) or Multiplayer (SMP)? SMP

Galacticraft add-ons and other mods installed?
minecraft{1.11.2} [Minecraft] (minecraft.jar)
mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2315-universal.jar)
forge{13.20.0.2315} [Minecraft Forge] (forge-1.11.2-13.20.0.2315-universal.jar)
Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar)
animania{1.0.4.7} [Animania] (animania-1.11.2-1.0.4.7.jar)
biomesoplenty{6.2.0.2254} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.2.0.2254-universal.jar)
craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar)
dimensionrules{1.1} [Dimension Rules] (DimensionRules-MC1.11-1.1.jar)
galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.117.jar)
galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.117.jar)
extraplanets{0.3.8} [Extra Planets] (ExtraPlanets-0.3.8.jar)
zerocore{1.11.2-0.1.0.6} [Zero CORE] (zerocore-1.11.2-0.1.0.6.jar)
bigreactors{1.11.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.30.jar)
inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar)
ironchest{1.11.2-7.0.25.815} [Iron Chest] (ironchest-1.11.2-7.0.25.815.jar)
jei{4.5.0.294} [Just Enough Items] (jei_1.11.2-4.5.0.294.jar)
journeymap{1.11.2-5.5.0} [JourneyMap] (journeymap-1.11.2-5.5.0.jar)

Please provide screenshots / crash report / log as needed.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  LoadingPlugin (DimensionRules-MC1.11-1.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.117.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 11/4/17 12:15 PM
Description: Ticking player

java.lang.ArrayIndexOutOfBoundsException: 3
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory.func_70301_a(TileBaseElectricBlockWithInventory.java:48)
	at net.minecraft.inventory.Slot.func_75211_c(Slot.java:60)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:75)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:1724)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory.func_70301_a(TileBaseElectricBlockWithInventory.java:48)
	at net.minecraft.inventory.Slot.func_75211_c(Slot.java:60)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:75)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Player being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 20461
	Entity Name: phonk99
	Entity's Exact location: 513.42, 96.00, -1705.07
	Entity's Block location: World: (513,96,-1706), Chunk: (at 1,6,6 in 32,-107; contains blocks 512,0,-1712 to 527,255,-1697), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
	Entity's Momentum: 0.00, -0.02, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:1724)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: aaaaaaaaagh
	All players: 1 total; [GCEntityPlayerMP['phonk99'/20461, l='aaaaaaaaagh', x=513.42, y=96.00, z=-1705.07]]
	Chunk stats: ServerChunkCache: 451 Drop: 0
	Level seed: -9134626163274414725
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.9.33-mod-std-ipv6-64
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 134084536 bytes (127 MB) / 1383596032 bytes (1319 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xms256M -Xmx2048M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.38 Powered by Forge 13.20.0.2315 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2315-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2315} [Minecraft Forge] (forge-1.11.2-13.20.0.2315-universal.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	animania{1.0.4.7} [Animania] (animania-1.11.2-1.0.4.7.jar) 
	UCHIJAAAA	biomesoplenty{6.2.0.2254} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.2.0.2254-universal.jar) 
	UCHIJAAAA	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
	UCHIJAAAA	dimensionrules{1.1} [Dimension Rules] (DimensionRules-MC1.11-1.1.jar) 
	UCHIJAAAA	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.117.jar) 
	UCHIJAAAA	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.117.jar) 
	UCHIJAAAA	extraplanets{0.3.8} [Extra Planets] (ExtraPlanets-0.3.8.jar) 
	UCHIJAAAA	zerocore{1.11.2-0.1.0.6} [Zero CORE] (zerocore-1.11.2-0.1.0.6.jar) 
	UCHIJAAAA	bigreactors{1.11.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.30.jar) 
	UCHIJAAAA	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.25.815} [Iron Chest] (ironchest-1.11.2-7.0.25.815.jar) 
	UCHIJAAAA	jei{4.5.0.294} [Just Enough Items] (jei_1.11.2-4.5.0.294.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.5.0} [JourneyMap] (journeymap-1.11.2-5.5.0.jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (DimensionRules-MC1.11-1.1.jar)
  lumien.dimensionrules.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.117.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 100; [GCEntityPlayerMP['phonk99'/20461, l='aaaaaaaaagh', x=513.42, y=96.00, z=-1705.07]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MJRLegends** [comment]
This was a ExtraPlanets issue a few months back, update your ExtraPlanets version your 6+ versions out of date

**Comment by MJRLegends** [comment]
Please update your Galacticraft and ExtraPlanets both are out of date
