### ISSUE TITLE
Crash API

### ISSUE THREAD

**Issue by MagTemTenebrius** [micdoodle8/Galacticraft#3060]
https://www.micdoodle8.com/mods/galacticraft/downloads/dev

Minecraft version: 1.7.10
Galacticraft version:
Forge version: 1.7-3.0.12.501

At start

dev + api

`cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/EntityEvolvedZombie
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:522)
	at net.minecraft.client.Minecraft.run(Minecraft.java:942)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/EntityEvolvedZombie
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 12 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.core.entities.EntityEvolvedZombie
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/entity/IEntityBreathable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.api.entity.IEntityBreathable
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more`

I installed api and dev, but crash occurs at start. Help, pls...

**Comment by MJRLegends** [comment]
Are you trying to play with the mod or develop something in another mod with the api?

**Comment by MagTemTenebrius** [comment]
I want to empty src  addon to the GC, put dev versions in the mod and API in the library elipse

**Comment by MJRLegends** [comment]
Ok you need to download all 4 jars from https://www.micdoodle8.com/mods/galacticraft/downloads/dev and put them as a external jar file, from that i can see it seems you are missing one of the jars

**Comment by MagTemTenebrius** [comment]
![default](https://user-images.githubusercontent.com/28220793/33774122-0aaf2e50-dc5c-11e7-8cf0-1d699d659490.png)
Like everything added .-.

**Comment by MJRLegends** [comment]
You dont need them in your mods folder, you only need to put all 4 as a external jar library file in your project

**Comment by MagTemTenebrius** [comment]
Oy, ok

**Comment by MagTemTenebrius** [comment]
Yes, everything works. Thank you. Silly mistake :slightly_smiling_face:

**Comment by MJRLegends** [comment]
No problem

**Comment by altrisi** [comment]
If everything works, why you don't close the issue?
