### ISSUE TITLE
Galacticraft crashes on rendering screen.

### ISSUE THREAD

**Issue by St4tch** [micdoodle8/Galacticraft#3071]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.106
Forge version: 1.10.2-12.18.1.2075

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed? Only Galacticraft core, planets, and micdoodlecore.

Please provide screenshots / crash report / log as needed.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.106.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 12/30/17 12:24 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: bxl
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraftforge.fml.client.GuiModsMissing
	Mouse location: Scaled: (0, 239). Absolute: (0, 0)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4017583000 bytes (3831 MB) / 4281597952 bytes (4083 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 7 total; -Xmx4G -Xms4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2075 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2075.jar) 
	U	Forge{12.18.1.2075} [Minecraft Forge] (forge-1.10.2-12.18.1.2075.jar) 
	U	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	U	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.106.jar) 
	U	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.106.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.106.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GT 740/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.1.2075
	LWJGL: 2.9.4
	OpenGL: GeForce GT 740/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz

**Comment by St4tch** [comment]
Fixed, was using an old version of forge. Sorry about that.

**Comment by MJRLegends** [comment]
Your Galacticraft is out of date too

**Comment by radfast** [comment]
hey @St4tch thanks for confirming the issue is fixed
