### ISSUE TITLE
[1.10.2] Already decorating, crash on mars in SMP

### ISSUE THREAD

**Issue by sdjnmxd** [micdoodle8/Galacticraft#3077]
Minecraft version: `1.10.2`
Galacticraft version: `4.0.0.119`
Forge version: `12.18.3.2477`
Add-ons: 
- `ExtraPlanets-0.8.5`

Other mods: 
- `Applied Energistics 2`
- `ExtraCells`
- `ThermalDynamics`
- `ThermalExpansion`
- `ThermalFoundation`
- `Bamboo`
- `Carpenter's Blocks`
- `MrCrayfish's Furniture Mod`
- `Chameleon`
- `Chisel`
- `CustomNPC`
- `...many of mods`

if u need more information, please comment to me, thank you 🐰 

crash-report:
[https://pastebin.com/9kxBm3ZX](https://pastebin.com/9kxBm3ZX)

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  JechCore (JustEnoughCharacters-1.12.0-2.2.0.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.119.jar)
  SpongeCoremod (forge-1.10.2-12.18.3.2477-universal.jar)
  CreativePatchingLoader (CreativeCore v1.7.3 mc1.10.2.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.11.2-0.7.3-Anarchy.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  FarseekCoreMod (Farseek-1.9.4-2.2.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 1/4/18 1:51 PM
Description: Exception ticking world

java.lang.RuntimeException: Already decorating!!
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:32)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:343)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_185931_b(ChunkProviderSpace.java:357)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3111)
	at net.minecraft.world.World.func_175666_e(World.java:3758)
	at net.minecraft.world.World.func_175690_a(World.java:2466)
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:2268)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:2121)
	at org.spongepowered.common.event.tracking.CauseTracker.setBlockState(CauseTracker.java:488)
	at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2705)
	at micdoodle8.mods.galacticraft.planets.mars.world.gen.WorldGenEggs.func_180709_b(WorldGenEggs.java:37)
	at micdoodle8.mods.galacticraft.planets.mars.EventHandlerMars.onPlanetDecorated(EventHandlerMars.java:151)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_EventHandlerMars_onPlanetDecorated_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:43)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:343)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_185931_b(ChunkProviderSpace.java:357)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zpp000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:32)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:343)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_185931_b(ChunkProviderSpace.java:357)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3111)
	at net.minecraft.world.World.func_175666_e(World.java:3758)
	at net.minecraft.world.World.func_175690_a(World.java:2466)
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:2268)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:2121)
	at org.spongepowered.common.event.tracking.CauseTracker.setBlockState(CauseTracker.java:488)
	at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2705)
	at micdoodle8.mods.galacticraft.planets.mars.world.gen.WorldGenEggs.func_180709_b(WorldGenEggs.java:37)
	at micdoodle8.mods.galacticraft.planets.mars.EventHandlerMars.onPlanetDecorated(EventHandlerMars.java:151)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_EventHandlerMars_onPlanetDecorated_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:43)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:343)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_185931_b(ChunkProviderSpace.java:357)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zpp000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: DIM-29
	All players: 1 total; [GCEntityPlayerMP['saya'/567037, l='DIM-29', x=912.62, y=98.00, z=-2049.48]]
	Chunk stats: ServerChunkCache: 2098 Drop: 0
	Level seed: 2870968080628784946
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (0,76,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1168694 game time, 1200730 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- Sponge CauseTracker --
Details:
	Cause Stack: /*****************************************************************/
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION} */
/*     Context:                                                  */
/*     - Name: World                                             */
/*       Object: WorldServer{LevelName=DIM-29, DimensionId=-29, DimensionType=galacticraftplanets:mars} */
/*     - Name: CapturedBlocks                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}              */
/*     - Name: CapturedEntities                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}            */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION} */
/*     Context:                                                  */
/*     - Name: CapturedBlocks                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}              */
/*     - Name: CapturedEntities                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}            */
/*     - Name: World                                             */
/*       Object: WorldServer{LevelName=DIM-29, DimensionId=-29, DimensionType=galacticraftplanets:mars} */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION} */
/*     Context:                                                  */
/*     - Name: World                                             */
/*       Object: WorldServer{LevelName=DIM-29, DimensionId=-29, DimensionType=galacticraftplanets:mars} */
/*     - Name: CapturedBlocks                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}              */
/*     - Name: CapturedEntities                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}            */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION} */
/*     Context:                                                  */
/*     - Name: CapturedBlocks                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}              */
/*     - Name: CapturedEntities                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}            */
/*     - Name: World                                             */
/*       Object: WorldServer{LevelName=DIM-29, DimensionId=-29, DimensionType=galacticraftplanets:mars} */
/*****************************************************************/

Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zhp000(MinecraftServer.java:3953)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.10.0-693.2.2.el7.x86_64
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4296530496 bytes (4097 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 11 total; -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms6G -Xmx6G -XX:hashCode=5
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2477 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2477-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2477} [Minecraft Forge] (forge-1.10.2-12.18.3.2477-universal.jar) 
	UCHIJAAAA	spongeapi{5.2.0-SNAPSHOT-c675e80} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2477-5.2.0-BETA-2777} [SpongeForge] (forge-1.10.2-12.18.3.2477-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	jecharacters{1.12.0-2.2.0} [Just Enough Characters] (JustEnoughCharacters-1.12.0-2.2.0.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJAAAA	actionbroadcaster{0.7.1} [ActionBroadcaster] (ActionBroadcaster.jar) 
	UCHIJAAAA	adminshop{1.8.2} [AdminShop] (AdminShop-1.10.2-1.8.2-universal.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	appleskin{1.0.9} [AppleSkin] (AppleSkin-mc1.10.2-1.0.9.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UCHIJAAAA	architecturecraft{1.7.3} [ArchitectureCraft] (ArchitectureCraft-1.7.3-mc1.10.2.jar) 
	UCHIJAAAA	bamboomod{Minecraft1.10.2 var3.0.0.12.2} [bamboomod] (Bamboo-3.0.0.12.2.jar) 
	UCHIJAAAA	kaiscommons{0.10.2} [KaisCommons] (KaisCommons-0.10.2.jar) 
	UCHIJAAAA	betteritemrestrict{0.9.6} [BetterItemRestrict] (BetterItemRestrict-0.9.6.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJAAAA	chattimestamp{1.0.0} [ChatTimestamp] (chattimestamp-1.10.2-1.0.0.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.1.1.39} [Chisel] (Chisel-MC1.10.2-0.1.1.39.jar) 
	UCHIJAAAA	chiselsandbits{12.16} [Chisels & Bits] (chiselsandbits-12.16.jar) 
	UCHIJAAAA	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHIJAAAA	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.7.3 mc1.10.2.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(21jul17).jar) 
	UCHIJAAAA	Dynmap{2.4-8} [Dynmap] (Dynmap-2.4-forge-1.10.2.jar) 
	UCHIJAAAA	economylite{2.12.0} [EconomyLite] (EconomyLite-5.0.0-2.12.0.jar) 
	UCHIJAAAA	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UCHIJAAAA	extracells{1.10.2-2.4.2aNIGHTLY} [Extra Cells 2] (ExtraCells-1.10.2-2.4.2aNIGHTLY.jar) 
	UCHIJAAAA	galacticraftcore{4.0.1.119} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.119.jar) 
	UCHIJAAAA	galacticraftplanets{4.0.1.119} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.119.jar) 
	UCHIJAAAA	extraplanets{0.8.5} [Extra Planets] (ExtraPlanets-0.8.5.jar) 
	UCHIJAAAA	farseek{2.2} [Farseek] (Farseek-1.9.4-2.2.jar) 
	UCHIJAAAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJAAAA	FireGayForge{2.3} [FireGay] (FireGayForge-2.3.jar) 
	UCHIJAAAA	firegay{2.0} [firegay] (FireGayForge-2.3.jar) 
	UCHIJAAAA	rmcaserver{2.3} [rmcaserver] (FireGayForge-2.3.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (FoamFix-1.11.2-0.7.3-Anarchy.jar) 
	UCHIJAAAA	geographicraft{0.8.8} [GeographiCraft] (GeographiCraft-1.9-1.11-0.8.9.jar) 
	UCHIJAAAA	grapplemod{1.10.2-v10} [Grappling hook mod] (grapplemod-1.10.2-v10.jar) 
	UCHIJAAAA	graves{1.10.2-b29-universal} [Graves Mod] (Graves-1.10.2-b29-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHIJAAAA	latch{0.4.3} [Latch] (Latch-0.4.3-S5.2.0.jar) 
	UCHIJAAAA	luckperms{3.0.14} [LuckPerms] (LuckPerms-Sponge-3.0.14.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	nbtedit{$version} [NBTEdit] (NBTEdit-0.3.jar) 
	UCHIJAAAA	nucleus{1.1.8-LTS-S6.0} [Nucleus] (Nucleus-1.1.8-LTS-S6.0-MC1.11.2-plugin.jar) 
	UCHIJAAAA	opframe{0.1} [OnlinePictureFrame] (OnlinePicFrame v1.3.3 mc1.10.2.zip) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	payday{1.1.0} [PayDay] (PayDay-1.1.0.jar) 
	UCHIJAAAA	prism{3.0.0} [Prism] (Prism-3.0.0-beta2-45-gfbbeb2b-all.jar) 
	UCHIJAAAA	prismplus{1.0.0} [PrismPlus] (PrismPlus-1.0.0.jar) 
	UCHIJAAAA	pjc{0.1.5} [ProjectCore for SpongeAPI 5.x] (projectcore-5.2.0-0.1.5.jar) 
	UCHIJAAAA	pjw{0.11.6} [ProjectWorlds for SpongeAPI 5.x] (projectworlds-5.2.0-0.11.6.jar) 
	UCHIJAAAA	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHIJAAAA	SaltMod{1.8.d} [Salty Mod] (SaltyMod-1.10.2-1.8.d.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UCHIJAAAA	streams{0.4} [Streams] (Streams-1.9.4-0.4.jar) 
	UCHIJAAAA	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.1.10} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.10.28-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.0.11} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.11.19-universal.jar) 
	UCHIJAAAA	thutcore{3.21.0} [Thut Core] (thutcore-3.21.0.jar) 
	UCHIJAAAA	thuttech{@VERSION@} [Thut's Tech] (thuttech-4.0.13.jar) 
	UCHIJAAAA	bspkrsCore{at_0.9} [bspkrsCore] (Treecapitator-1.10.2-at_0.9.jar) 
	UCHIJAAAA	Treecapitator{at_0.9} [Treecapitator] (Treecapitator-1.10.2-at_0.9.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	Loaded coremods (and transformers): 
JechCore (JustEnoughCharacters-1.12.0-2.2.0.jar)
  me.towdium.jecharacters.core.ClassTransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.119.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SpongeCoremod (forge-1.10.2-12.18.3.2477-universal.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
CreativePatchingLoader (CreativeCore v1.7.3 mc1.10.2.jar)
  
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  codechicken.nei.asm.NEITransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.11.2-0.7.3-Anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
FarseekCoreMod (Farseek-1.9.4-2.2.jar)
  farseek.core.FarseekClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	AE2 Integration: IC2:OFF, RF:OFF, RFItem:OFF, Waila:ON, THE_ONE_PROBE:OFF
	Profiler Position: N/A (disabled)
	Player Count: 8 / 93; [GCEntityPlayerMP['icefox'/272135, l='world', x=1375.70, y=75.29, z=-879.70], GCEntityPlayerMP['bangbang93'/318933, l='mine', x=173.95, y=109.00, z=204.76], GCEntityPlayerMP['chEN'/502325, l='world', x=547.58, y=28.00, z=-1201.62], GCEntityPlayerMP['xiaoma'/533070, l='world', x=553.70, y=74.00, z=-269.30], GCEntityPlayerMP['AnnKang'/511958, l='world', x=132.27, y=66.00, z=-432.67], GCEntityPlayerMP['Bond_Girl'/383171, l='mine', x=-7027.17, y=64.00, z=-19894.64], GCEntityPlayerMP['saya'/567037, l='DIM-29', x=912.62, y=98.00, z=-2049.48], GCEntityPlayerMP['stray'/582920, l='world', x=1067.70, y=64.00, z=94.46]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by TheQuadShot** [comment]
I'd start with updating to the latest build (1.10.2-4.0.0.120).
https://micdoodle8.com/mods/galacticraft/downloads
I know there are/where some issues with Sponge so make sure your running the latest version(.2793) there as well.
https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2

**Comment by radfast** [comment]
Thanks for reporting, we'll take a look - seems to be associated with the Mars worldgen for Slimeling Eggs.

Until we find a solution, I hope that you're still able to play your world (maybe best to avoid travelling to Mars).

**Comment by sdjnmxd** [comment]
thank you all, i will update mod & sponge to the latest

In fact, this problem has been encountered many times, almost every time will lead to the mars world break. When a player on mars enter the server, the server will crash again

so when this happens, i will remove the mars world and let the server regenerate the world. this will solve the problem for the time being.

**Comment by radfast** [comment]
please keep open, this issue needs further investigation by me or one of the other developers

**Comment by MJRLegends** [comment]
Can confirm this is a issue got the same issue on my server, my crash log if this helps https://pastebin.com/TUVU5VHu

**Comment by MJRLegends** [comment]
@radfast any chance this can be looked at for build 121 or disabled for build 121 :D

**Comment by radfast** [comment]
Should be able to fix this for 121 - I'm planning on releasing 121 in the next couple of days.

**Comment by MJRLegends** [comment]
Sounds good :D @radfast

**Comment by radfast** [comment]
Hopefully that will have fixed it.  Please test 121 and let me know if the problem recurs.

**Comment by radfast** [comment]
121 now available to download

**Comment by MJRLegends** [comment]
Nice thank you
