### ISSUE TITLE
Crash relating to Venus - Sponge Server

### ISSUE THREAD

**Issue by Noobcrafteryt** [micdoodle8/Galacticraft#3147]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 1.10.2
Forge version: 2281

Single player (SSP) or Multiplayer (SMP)? SERVER smp

Galacticraft add-ons and other mods installed?
no Galacticraft addons YET
OTHER MODS:
 Abyssal Craft
Bookshelf
Classic Combat
Decocraft
Mo' Creatures
Enchanting Plus
Extra Utilities 2
Galacticraft
Hats
Hopper Ducts
JEI
JurassiCraft
MCA (Minecraft Comes Alive)
MetaMorph
Mr. Crayfishes Furniture (MCF)
**ON SPONGE SERVER**

Please provide screenshots / crash report / log as needed.
[14:10:19] [Server thread/ERROR]: Encountered an unexpected exceptionnet.minecraft.util.ReportedException: Ticking block entity at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/planets/venus/dimension/WorldProviderVenus at micdoodle8.mods.galacticraft.core.tile.TileEntitySolar.func_73660_a(TileEntitySolar.java:189) ~[TileEntitySolar.class:?] at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:229) ~[TrackingUtil.class:1.10.2-2281-5.2.0-BETA-2610] at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2831) ~[ls.class:?] at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zkc000(WorldServer.java:2818) ~[ls.class:?] at net.minecraft.world.World.func_72939_s(World.java:6076) ~[aid.class:?] at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185) ~[ls.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?] ... 4 moreCaused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.planets.venus.dimension.WorldProviderVenus at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141] at micdoodle8.mods.galacticraft.core.tile.TileEntitySolar.func_73660_a(TileEntitySolar.java:189) ~[TileEntitySolar.class:?] at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:229) ~[TrackingUtil.class:1.10.2-2281-5.2.0-BETA-2610] at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2831) ~[ls.class:?] at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zkc000(WorldServer.java:2818) ~[ls.class:?] at net.minecraft.world.World.func_72939_s(World.java:6076) ~[aid.class:?] at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185) ~[ls.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?] ... 4 moreCaused by: java.lang.NullPointerException[14:10:19] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/servers/mine12804/./crash-reports/crash-2018-02-03_14.10.19-server.txt

**Comment by Noobcrafteryt** [comment]
UPDATE: Crashes when trying to place basic solar panel too

**Comment by radfast** [comment]
>      Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.planets.venus.dimension.WorldProviderVenus at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) 

>     Caused by: java.lang.NullPointerException


Please can you post the **full crash report** - that one cuts off just at the relevant parts.

This appears to be a Sponge bug connected with our ```WorldProviderVenus```, not a bug in the Solar Panel _per se_.

I can't tell more without seeing the full crash report.

**However: ** Galacticraft 1.10.2 is stable with Sponge, so it could be either (a) something changed in a recent Sponge version or (b) one of the other mods - I don't know them all and I wouldn't like to guess which one it can be, except that I know Mo'Creatures can cause problems generally.

If possible please try:

* backup your world fully

* play the same world with only Galacticraft (and MicdoodleCore) and Sponge in the mods folder

* if that's OK, play the same world with Galacticraft, Sponge + half your mods placed back into the mods folder - and all the clientside mods like NEI, Optifine, Minimap should all be OK.

(Personally I would just make a subfolder in the mods folder and slide the unused mods into that.)

**Comment by Noobcrafteryt** [comment]
Ok, sorry for the late response, been an extremely busy week. I ran a test sponge server on local. 2281 (forge) with matching Sponge 2281. Only Galacticraft installed in mods and it still crashes both server and client.

[latest.log](https://github.com/micdoodle8/Galacticraft/files/1712460/latest.log)
[fml-server-latest.log](https://github.com/micdoodle8/Galacticraft/files/1712461/fml-server-latest.log)
[fml-junk-earlystartup.log](https://github.com/micdoodle8/Galacticraft/files/1712462/fml-junk-earlystartup.log)

Those are the three logs. I have.

Again the only installed mods are: 
Galacticraft Core- 1.10.2- 4.0.1.132
MicdoodleCore- 1.10.2- 4.0.1.132
Sponge- 1.10.2 - 2281 -5.2.0 BETA 2610

And again that's with Forge 2281

**Comment by Noobcrafteryt** [comment]
> I want you to be going back to Venus with the same solar panel

I just noticed this part. I NEVER went to Venus. I was live and had just made the basic panel and placed it in the main world. Nothing else I've placed yet has had an issue. So far I've placed compressor, circuit fabricator and coal generators along with aluminum wiring to link them to the generator. They are in a cave (home) and the solar panel was on top of a mountain.

**Comment by radfast** [comment]
OK the issue here is simply this: you didn't install **Galacticraft-Planets** yet.  Download build 132 of that from our Download site, add to your mods folder and all should be OK.

**BUT** it is our intention that GalacticraftCore should be able to run standalone without Galacticraft-Planets, so thank you for this issue report, these are things we need to fix.

**Comment by Noobcrafteryt** [comment]
Oh wow, I feel like a derp. I played with 1.7.10 before and don't remember needing planets, even when I when to other planets... but that was over a year ago xD. Thanks brother appreciate the help, love the mod too btw.

**Comment by hYdos** [comment]
i got this error but i got galacticraft planets installed any help?

**Comment by hYdos** [comment]
here is the crash
`14.03 20:08:05 [Server] Server thread/ERROR [minecraft/MinecraftServer]: Encountered an unexpected exception
14.03 20:08:05 [Server] INFO net.minecraft.util.ReportedException: Exception ticking world entities
14.03 20:08:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
14.03 20:08:05 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
14.03 20:08:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
14.03 20:08:05 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
14.03 20:08:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
14.03 20:08:05 [Server] INFO Caused by: java.lang.ClassCastException: micdoodle8.mods.galacticraft.planets.venus.tile.SolarModuleNetwork cannot be cast to micdoodle8.mods.galacticraft.api.transmission.grid.IElectricityNetwork
14.03 20:08:05 [Server] INFO at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseConductor.getNetwork(TileBaseConductor.java:71) ~[TileBaseConductor.class:?]
14.03 20:08:05 [Server] INFO at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseConductor.getNetwork(TileBaseConductor.java:26) ~[TileBaseConductor.class:?]
14.03 20:08:05 [Server] INFO at micdoodle8.mods.galacticraft.planets.venus.tile.SolarModuleNetwork.refreshWithChecks(SolarModuleNetwork.java:84) ~[SolarModuleNetwork.class:?]
14.03 20:08:05 [Server] INFO at micdoodle8.mods.galacticraft.planets.venus.tile.SolarModuleNetwork.split(SolarModuleNetwork.java:248) ~[SolarModuleNetwork.class:?]
14.03 20:08:05 [Server] INFO at micdoodle8.mods.galacticraft.planets.venus.tile.SolarModuleNetwork.split(SolarModuleNetwork.java:26) ~[SolarModuleNetwork.class:?]
14.03 20:08:05 [Server] INFO at micdoodle8.mods.galacticraft.planets.venus.tile.TileEntitySolarTransmitter.func_145843_s(TileEntitySolarTransmitter.java:37) ~[TileEntitySolarTransmitter.class:?]
14.03 20:08:05 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:832) ~[axw.class:?]
14.03 20:08:05 [Server] INFO at net.minecraft.world.World.func_72939_s(World.java:1891) ~[amu.class:?]
14.03 20:08:05 [Server] INFO at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
14.03 20:08:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
14.03 20:08:05 [Server] INFO ... 4 more`
