### ISSUE TITLE
Crash log from CreativeTabGC.displayAllRelevantItems uses printStackTrace()

### ISSUE THREAD

**Issue by mezz** [micdoodle8/Galacticraft#3155]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.128
Forge version: 1.12.2-14.23.1.2608

Single player (SSP) or Multiplayer (SMP)?
Both

Galacticraft add-ons and other mods installed?
extraplanets, JEI

Please provide screenshots / crash report / log as needed.
Snippet of log:
```
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: com.google.common.collect.Ordering$IncomparableValueException: Cannot compare value: Item:(com.mjr.extraplanets.items.ItemBasicBattery@3b0da7cf),Meta:(100)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.collect.ExplicitOrdering.rank(ExplicitOrdering.java:45)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.collect.ExplicitOrdering.compare(ExplicitOrdering.java:39)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.collect.ByFunctionOrdering.compare(ByFunctionOrdering.java:43)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.TimSort.binarySort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.TimSort.sort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.Arrays.sort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.List.sort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.util.Collections.sort(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at micdoodle8.mods.galacticraft.core.util.CreativeTabGC.func_78018_a(CreativeTabGC.java:50)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory.create(ItemStackListFactory.java:47)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.plugins.vanilla.VanillaPlugin.registerIngredients(VanillaPlugin.java:96)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.startup.JeiStarter.registerIngredients(JeiStarter.java:129)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:46)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:118)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:728)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:33:51] [main/INFO] [STDERR/jei]: [micdoodle8.mods.galacticraft.core.util.CreativeTabGC:func_78018_a:53]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Full log: https://gist.github.com/Vitali8/676abb0da286b78631fca17743e8eb57

### Report:

I saw this crashing in a report given to me for an unrelated issue. I realize this is mainly a extraplanets issue (reported here: https://github.com/MJRLegends/ExtraPlanets/issues/237) but please use a log4j log and do not use printStackTrace. If you add an exception as the last parameter in a log4j log call, it will print the stack trace more nicely instead of to stdout:
https://github.com/micdoodle8/Galacticraft/blob/ee0b9ac667b477623a53236d2b63fb95e56ac1f0/src/main/java/micdoodle8/mods/galacticraft/core/util/CreativeTabGC.java#L53
can be
```java
logger.error("Crashed while sorting creative tab.", e);
```

**Comment by MJRLegends** [comment]
Fixed players just need to update

**Comment by radfast** [comment]
>  com.mjr.extraplanets.items.ItemBasicBattery

**Comment by MJRLegends** [comment]
@radfast yeah as said above it was fixed days ago and is in the latest version

**Comment by MJRLegends** [comment]
It was because https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/energy/item/ItemElectricBase.java contains a hardcoded check for GC tab in subItems method? Shouldnt this base class be generalized

**Comment by radfast** [comment]
@MJRLegends  if you create a subclass of ```ItemElectricBase``` which is displayed on a different Creative tab, you can override ```getSubItems()``` surely?  So this shouldn't be a problem.

The hardcoded check is needed in Minecraft 1.12.  See also https://github.com/micdoodle8/Galacticraft/commit/44af55cddde9bd428f5c5399153d6525f565dd2c

**Comment by MJRLegends** [comment]
Yeah thats what i did to fix it
