### ISSUE TITLE
[1.12.2] soft crash when "launching" to a planet from planet menu

### ISSUE THREAD

**Issue by seeker2921** [micdoodle8/Galacticraft#3165]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.132
Forge version: 14.23.2.2612

Single player (SSP) or Multiplayer (SMP)? Multiplayer

Galacticraft add-ons and other mods installed?
Journey map.
Please provide screenshots / crash report / log as needed.
after launching a rocket and entering the select a planet GUI, when you choose your destination (any) and the screen goes to "Taking on small step" it freezes. The server reports a logout.

here is the relevant server log when it happens:
Server thread/FATAL
 
02/08/2018 21:38:50

21:38:50

Error executing task

Console
 
02/08/2018 21:38:50

21:38:50

java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_161]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_161]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
at codechicken.nei.network.NEIServerPacketHandler.sendLoginState(NEIServerPacketHandler.java:250) ~[NEIServerPacketHandler.class:?]
at codechicken.nei.network.NEIServerPacketHandler.handlePacket(NEIServerPacketHandler.java:66) ~[NEIServerPacketHandler.class:?]
at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:135) ~[PacketCustom$ServerInboundHandler.class:?]
at codechicken.lib.packet.PacketCustom$ServerInboundHandler.lambda$handle$0(PacketCustom.java:133) ~[PacketCustom$ServerInboundHandler.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 5 more

Server thread/WARN
 
02/08/2018 21:38:50

21:38:50

handleDisconnection() called twice

**Comment by MJRLegends** [comment]
Already been reported please check #3157

**Comment by radfast** [comment]
not sure that this is the same crash @MJRLegends ... could be, could be not!

@seeker2921  please try two things and see if the same crash happens

1.   Give your Minecraft game much more memory, like at least 1G or 2G more, in the JVM +xmx memory setting (or you can install Foamfix mod on the client, or both)

2    Try the same setup without **JourneyMap**

Generally please give us a full modlist and your JVM settings.

**Comment by radfast** [comment]
Looking again at this log, it is **NEI** crashing.  Please also try your same setup without NEI, and see if it still crashes.

**Comment by radfast** [comment]
ok further thoughts, I think this is a Java memory issue - the player client version of Minecraft is running out of memory.

Vanilla Minecraft client includes this code:

    public void freeMemory()
    {
            memoryReserve = new byte[0];
            this.renderGlobal.deleteAllDisplayLists();
            System.gc();
            this.loadWorld(null);
            System.gc();
    }

The ```.loadWorld(null)``` can make the ```java.util.concurrent.ExecutionException``` crash reported in the first post.

**Comment by radfast** [comment]
Good news, I've found and fixed the problem.  A new build 133 will be available later today.

**Comment by radfast** [comment]
Build 133 is now available from the download site.  Also has a new feature: **Hydraulic Platform**
