### ISSUE TITLE
Worldgen conflict with Dungeons2

### ISSUE THREAD

**Issue by Teibidh** [micdoodle8/Galacticraft#3200]
Error is definitely repeatable. What I'm not sure about is whether any dungeons2 generations are completing successfully, hard to tell what "successful" might mean in terms of block placement, etc. but I believe this pops every time a dungeon generation is triggered. Posted on Dungeons2 tracker as well as I have no idea which mod is "responsible."

https://github.com/gottsch/gottsch-minecraft-Dungeons2/issues/10

MC 1.12.2
MicdoodleCore-1.12.2-4.0.1.139
GalacticraftCore-1.12.2-4.0.1.139
GottschCore-mc1.12.2-f14.23.1.2555-v1.2.0
Dungeons2-mc1.12.2-f14.23.1.2555-v1.3.2
forge-1.12.2-14.23.2.2619-universal

at com.someguyssoftware.dungeons2.worldgen.DungeonsWorldGen.generate(DungeonsWorldGen.java:240)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:183)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:977)
	at pregenerator.impl.processor.ChunkFile.populate(ChunkFile.java:86)
	at pregenerator.impl.processor.ChunkFile$ChunkFileEntry.process(ChunkFile.java:250)
	at pregenerator.impl.processor.ChunkProcessor.onServerTickEvent(ChunkProcessor.java:97)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_381_ChunkProcessor_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by radfast** [comment]
It's not a Galacticraft issue, I think.  That is just a "hook" the same as what Forge provides.
Probably your log has a line like this also:

>    Error in another mod's worldgen.  This is NOT a Galacticraft bug.

I will close this now, but we can re-open it if there is a reason to think it is Galacticraft-related.
