### ISSUE TITLE
Crash With Actually Additions

### ISSUE THREAD

**Issue by Pet9948** [micdoodle8/Galacticraft#3249]
Crash between Actually Additions and Galacticraft. Help. 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-78-core.jar)
  CTMCorePlugin (GL_3_CTM-MC1.12-0.2.3.12.jar)
  Inventory Tweaks Coremod (FIX_InventoryTweaks-1.64-dev.jar)
  SoundFixPatchingLoader (SOUND_AmbientSounds_v2.2.3_mc1.12.2.jar)
  MicdoodlePlugin (GL_1_MicdoodleCore-1.12.2-4.0.1.155.jar)
  BetterFontsCore (GUI_HD_TTFR-1.12.1-1.9.1.jar)
  LoadingPlugin (FIX_ChunkAnimator-MC1.12-1.2.jar)
  LoadingPlugin (LIB_ResourceLoader-MC1.12.1-1.5.3.jar)
  LucraftForgeLoading (LIB_LucraftCore-1.12-1.2.3.jar)
  ShetiPhian-ASM (LIB_shetiphiancore-1.12.0-3.5.6.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/15/18 4:04 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Core (galacticraftcore)
Caused by: java.lang.NullPointerException
	at de.ellpeck.actuallyadditions.mod.misc.apiimpl.MethodHandler.addCrusherRecipes(MethodHandler.java:273)
	at de.ellpeck.actuallyadditions.api.ActuallyAdditionsAPI.addCrusherRecipes(ActuallyAdditionsAPI.java:144)
	at micdoodle8.mods.galacticraft.core.recipe.CompatModuleActuallyAdditions.addRecipes(CompatModuleActuallyAdditions.java:16)
	at micdoodle8.mods.galacticraft.core.recipe.RecipeManagerGC.loadCompatibilityRecipes(RecipeManagerGC.java:77)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.postInit(GalacticraftCore.java:410)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:725)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1912182952 bytes (1823 MB) / 4691329024 bytes (4474 MB) up to 7478968320 bytes (7132 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2627 Optifine OptiFine_1.12.2_HD_U_C9 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                      | Source                                               | Signature                                |
	|:----- |:-------------------- |:---------------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| UCHIJ | minecraft            | 1.12.2                       | minecraft.jar                                        | None                                     |
	| UCHIJ | mcp                  | 9.42                         | minecraft.jar                                        | None                                     |
	| UCHIJ | FML                  | 8.0.99.99                    | forge-1.12.2-14.23.2.2627-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | forge                | 14.23.2.2627                 | forge-1.12.2-14.23.2.2627-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | micdoodlecore        |                              | minecraft.jar                                        | None                                     |
	| UCHIJ | betterfonts          | 1.9.1                        | minecraft.jar                                        | None                                     |
	| UCHIJ | biomesoplenty        | 7.0.1.2325                   | BIOM_BiomesOPlenty-1.12.2-7.0.1.2325-universal.jar   | None                                     |
	| UCHIJ | shetiphiancore       | 3.5.6                        | LIB_shetiphiancore-1.12.0-3.5.6.jar                  | None                                     |
	| UCHIJ | terraqueous          | 1.4.11                       | BIOM_terraqueous-1.12.0-1.4.11.jar                   | None                                     |
	| UCHIJ | bibliocraft          | 2.4.3                        | DECORE_1_BiblioCraft[v2.4.3][MC1.12.0].jar           | None                                     |
	| UCHIJ | crafttweaker         | 4.1.6                        | FIX_CraftTweaker2-1.12-4.1.6.jar                     | None                                     |
	| UCHIJ | cookingforblockheads | 6.3.17                       | DECORE_CookingForBlockheads_1.12.1-6.3.17.jar        | None                                     |
	| UCHIJ | codechickenlib       | 3.1.6.339                    | LIB_CodeChickenLib-1.12.2-3.1.6.339-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | chickenchunks        | 2.4.1.71                     | FIX_ChickenChunks-1.12.2-2.4.1.71-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | chunkanimator        | 1.2                          | FIX_ChunkAnimator-MC1.12-1.2.jar                     | None                                     |
	| UCHIJ | ctgui                | 1.0.0                        | FIX_CraftTweaker2-1.12-4.1.6.jar                     | None                                     |
	| UCHIJ | mtlib                | 3.0.4                        | LIB_MTLib-3.0.4.jar                                  | None                                     |
	| UCHIJ | modtweaker           | 4.0.8                        | FIX_modtweaker-4.0.8.jar                             | None                                     |
	| UCHIJ | jei                  | 4.8.5.159                    | GUI_1_jei_1.12.2-4.8.5.159.jar                       | None                                     |
	| UCHIJ | crafttweakerjei      | 2.0.0                        | FIX_CraftTweaker2-1.12-4.1.6.jar                     | None                                     |
	| UCHIJ | inventorytweaks      | 1.64-dev+release.110.b4fac73 | FIX_InventoryTweaks-1.64-dev.jar                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJ | mousetweaks          | 2.8                          | FIX_MouseTweaks-2.8-mc1.12.1.jar                     | None                                     |
	| UCHIJ | reap                 | 1.5.0                        | FIX_reap-1.5.0.jar                                   | None                                     |
	| UCHIJ | ic2                  | 2.8.16-ex112                 | GL_2_industrialcraft-2-2.8.16-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJ | ctm                  | MC1.12-0.2.3.12              | GL_3_CTM-MC1.12-0.2.3.12.jar                         | None                                     |
	| UCHIJ | chisel               | MC1.12.2-0.2.0.31            | GL_3_Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCHIJ | mantle               | 1.12-1.3.1.21                | LIB_Mantle-1.12-1.3.1.21.jar                         | None                                     |
	| UCHIJ | tconstruct           | 1.12.2-2.9.1.65              | GL_TConstruct-1.12.2-2.9.1.65.jar                    | None                                     |
	| UCHIE | galacticraftcore     | 4.0.1.155                    | GL_1_GalacticraftCore-1.12.2-4.0.1.155.jar           | None                                     |
	| UCHIE | galacticraftplanets  | 4.0.1.155                    | GL_1_Galacticraft-Planets-1.12.2-4.0.1.155.jar       | None                                     |
	| UCHIJ | mjrlegendslib        | 1.12.2-1.1.3                 | GL_1_MJRLegendsLib-1.12.2-1.1.3.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIE | extraplanets         | 1.12.2-0.2.9                 | GL_1_ExtraPlanets-1.12.2-0.2.9.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJ | extrautils2          | 1.0                          | GL_2_extrautils2-1.12-1.7.4.jar                      | None                                     |
	| UCHIJ | lucraftcore          | 1.12-1.2.3                   | LIB_LucraftCore-1.12-1.2.3.jar                       | None                                     |
	| UCHIJ | heroesexpansion      | Beta-1.12-1.1.0              | GL_4_HeroesExpansion-Beta-1.12-1.1.0.jar             | None                                     |
	| UCHIJ | speedsterheroes      | 1.12-1.2.1                   | GL_4_SpeedsterHeroes-1.12-1.2.1.jar                  | None                                     |
	| UCHIJ | redstoneflux         | 2.0.1                        | LIB_RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJ | cofhcore             | 4.3.10                       | LIB_CoFHCore-1.12.2-4.3.10.5-universal.jar           | None                                     |
	| UCHIJ | cofhworld            | 1.1.1                        | LIB_CoFHWorld-1.12.2-1.1.1.12-universal.jar          | None                                     |
	| UCHIJ | thermalfoundation    | 2.3.10                       | GL_5_ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UCHIJ | brandonscore         | 2.4.0                        | LIB_BrandonsCore-1.12-2.4.0.152-universal.jar        | None                                     |
	| UCHIJ | draconicevolution    | 2.3.10                       | MAG_Draconic-Evolution-1.12-2.3.10.284-universal.jar | None                                     |
	| UCHIJ | thermalexpansion     | 5.3.10                       | GL_5_ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
	| UCHIJ | redstonearsenal      | 2.3.10                       | GL_5_RedstoneArsenal-1.12.2-2.3.10.4-universal.jar   | None                                     |
	| UCHIJ | thermalcultivation   | 0.1.5                        | GL_5_ThermalCultivation-1.12.2-0.1.5.3-universal.jar | None                                     |
	| UCHIJ | actuallyadditions    | 1.12.2-r132                  | GL_ActuallyAdditions-1.12.2-r132.jar                 | None                                     |
	| UCHIJ | appliedenergistics2  | rv5-stable-10                | GL_appliedenergistics2-rv5-stable-10.jar             | None                                     |
	| UCHIJ | immersiveengineering | 0.12-78                      | GL_ImmersiveEngineering-0.12-78.jar                  | None                                     |
	| UCHIJ | jeiintegration       | 1.5.1.36                     | GUI_1_jeiintegration_1.12.2-1.5.1.36.jar             | None                                     |
	| UCHIJ | chameleon            | 1.12-4.1.3                   | LIB_Chameleon-1.12-4.1.3.jar                         | None                                     |
	| UCHIJ | resourceloader       | 1.5.3                        | LIB_ResourceLoader-MC1.12.1-1.5.3.jar                | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJ | journeymap           | 1.12.2-5.5.2                 | MAP_journeymap-1.12.2-5.5.2.jar                      | None                                     |
	| UCHIJ | nei                  | 2.4.1                        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | ironchest            | 1.12.2-7.0.40.824            | PACK_ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCHIJ | lootbags             | 2.5.4b                       | PACK_LootBags-1.12.2-2.5.4b.jar                      | None                                     |
	| UCHIJ | storagedrawers       | 1.12-5.2.5                   | PACK_StorageDrawers-1.12.2-5.3.5.jar                 | None                                     |
	| UCHIJ | ambientsounds        | 2.0.0                        | SOUND_AmbientSounds_v2.2.3_mc1.12.2.jar              | None                                     |
	| UCHIJ | millenaire           | Millénaire 6.2.0-beta.14     | VILLAGE_millenaire-6.2.0-beta.14.jar                 | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-0.12-78-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (GL_3_CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Inventory Tweaks Coremod (FIX_InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
SoundFixPatchingLoader (SOUND_AmbientSounds_v2.2.3_mc1.12.2.jar)
  com.creativemd.ambientsounds.soundfix.SoundFixTransformer
MicdoodlePlugin (GL_1_MicdoodleCore-1.12.2-4.0.1.155.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
BetterFontsCore (GUI_HD_TTFR-1.12.1-1.9.1.jar)
  cubex2.ttfr.BFClassTransformer
LoadingPlugin (FIX_ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
LoadingPlugin (LIB_ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
LucraftForgeLoading (LIB_LucraftCore-1.12-1.2.3.jar)
  lucraft.mods.lucraftcore.access.LucraftClassTransformer
ShetiPhian-ASM (LIB_shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.69' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	AE2 Version: stable rv5-stable-10 for Forge 14.23.1.2554
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 385.69
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 20
```

**Comment by radfast** [comment]
Thanks for reporting.  Fixed in our next build 156 - should be available to download in around 10-15 minutes.

**Comment by Pet9948** [comment]
Thank you so much. Fixed!
