### ISSUE TITLE
Meteor Ticking Entity NullPointerException

### ISSUE THREAD

**Issue by Gregorsharpe** [micdoodle8/Galacticraft#3254]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.156
Dedicated SMP server

Relevant addons and mods:
Extra Planets (1.12.2-0.2.9)
A handful of tech mods including the Thermal Expansion suite, OpenComputers, Refined Storage, etc.

--------------------------------------------------------------------------------------------------------

A few minutes after making our server's first Mars landing the server crashed with a meteor null pointer exception. I've included the stack trace below, and have linked the full server crash log on pastebin. Please don't hesitate to ask if I've missed any required information!

```
java.lang.NullPointerException: Ticking entity
	at micdoodle8.mods.galacticraft.core.entities.EntityMeteor.onImpact(EntityMeteor.java:140)
	at micdoodle8.mods.galacticraft.core.entities.EntityMeteor.func_70071_h_(EntityMeteor.java:116)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

Link to the full server crash report:
`https://pastebin.com/QWEDw5LW`

Cheers, you have quite the fun mod here!

**Comment by radfast** [comment]
Thanks for reporting, I'm looking at this now.

BTW this also confirms that I can close #2885 because this can only happen because a meteor spawned on Mars ... :)

**Comment by radfast** [comment]
Thanks again.  Will be fixed in next build 158, available later today.

**Comment by radfast** [comment]
Build 158 is now available.

If you have any more issues, please do let us know.
