### ISSUE TITLE
[1.12.2] Game Crash After Placing Solar Panel.

### ISSUE THREAD

**Issue by tyabus** [micdoodle8/Galacticraft#3264]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2 
Galacticraft version: 1.12.2-4.0.1.163

Multiplayer.

Galacticraft add-ons and other mods installed?
addon: Galacticraft-Planets 1.12.2-4.0.1.163
other mods:
Applied Energistics 2
BrandonsCore
CodeChickenLib
CoFHWorld
CoFHCore
Crafting Nether Star
Draconic Evolution
Extreme Reactors
mccray furniture
Redstone Flux
Thermal Foundation
Thermal Dynamics
Thermal Expansion
Toro Health
Twilight Forest
zerocore
latest.log, crash part.
[21:07:41] [main/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Cannot get property MaterialProperty{name=material, clazz=class ic2.core.block.state.MaterialProperty$WrappedMaterial, values=[ic2.core.block.state.MaterialProperty$WrappedMaterial@1198b3be, ic2.core.block.state.MaterialProperty$WrappedMaterial@2d137b6c, ic2.core.block.state.MaterialProperty$WrappedMaterial@670075f2]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209) ~[awu$a.class:?]
	at ic2.core.block.BlockTileEntity.func_149688_o(BlockTileEntity.java:444) ~[BlockTileEntity.class:?]
	at micdoodle8.mods.galacticraft.core.blocks.BlockSolar.func_176198_a(BlockSolar.java:105) ~[BlockSolar.class:?]
	at net.minecraft.world.World.func_190527_a(World.java:3178) ~[amu.class:?]
	at net.minecraft.item.ItemBlock.func_179222_a(ItemBlock.java:127) ~[ahb.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:431) ~[bsa.class:?]
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96) ~[PlayerControllerOF.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by tyabus** [comment]
[latest.log](https://github.com/micdoodle8/Galacticraft/files/1833858/latest.log)
full log.

**Comment by radfast** [comment]
Thank you for reporting.  This issue should be fixed from next build 164.

**Comment by radfast** [comment]
Build 4.0.1.164 now available.

**Comment by tyabus** [comment]
Okay, let me check

**Comment by tyabus** [comment]
Issue Solved. Not crashing.

**Comment by radfast** [comment]
good job, thanks for confirming
