### ISSUE TITLE
Server log error message related with advancements and "goggles"

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3273]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.163

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP on localhost Forge server.

Galacticraft add-ons and other mods installed?
BuildCraft, MrCrayfish Furniture, ChickenChunks, EnderStorage, CodeChickenCore, JEI+NEI, Optifine

Please provide screenshots / crash report / log as needed.

I just found this in the server log while it was starting up:
`[17:20:39] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement buildcraftcore:goggles
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'buildcraftcore:goggles'
	at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
	at net.minecraft.advancements.DisplayInfo.func_193221_a(DisplayInfo.java:133) ~[r.class:?]
	at net.minecraft.advancements.DisplayInfo.func_192294_a(DisplayInfo.java:111) ~[r.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:202) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1342) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1324) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1298) [ForgeHooks.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`
It seems to be related with advancements and "goggles". Might be related with the Sensor Glasses. Does not cause any issues but just curious what this is.

**Comment by radfast** [comment]
`buildcraftcore:goggles`

Nothing to do with us.  That's a Buildcraft item.  Obviously.

Why are you reporting this to us, and where is your issue report on the Buildcraft github?
