### ISSUE TITLE
JEI

### ISSUE THREAD

**Issue by AlexRover** [micdoodle8/Galacticraft#3348]
And what about this?
[crash-2018-04-16_00.22.56-client.txt](https://github.com/micdoodle8/Galacticraft/files/1913112/crash-2018-04-16_00.22.56-client.txt)

**Comment by MJRLegends** [comment]
Your crash problem here isnt related to Galacticraft in anyway

**Comment by AlexRover** [comment]
I do not understand anything about this, but without galacticraft everything is working. Tell me what's causing the accident, that I could tell the culprit

**Comment by AlexRover** [comment]
How hard it is to live without knowing English, I figured out, this is the problem of the smithy, well ender io

**Comment by kouwei32** [comment]
From what I'm seeing, the crash is caused by some sort of electricity conversion error between GalactiCraft and EnderIO, while loading JEI. Pretty weird.

**Comment by radfast** [comment]
>   some sort of electricity conversion error between GalactiCraft and EnderIO

wtf?  you are inventing this, Galacticraft electricity is not referenced in that error report

>
     Caused by: java.lang.NullPointerException
	at crazypants.enderio.base.power.forge.InternalPoweredItemWrapper$PoweredItemCapabilityProvider.getCapability(InternalPoweredItemWrapper.java:27)
	at crazypants.enderio.base.power.ItemPowerCapabilityBackend.getCapability(ItemPowerCapabilityBackend.java:41)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.item.ItemStack.getCapability(ItemStack.java:1169)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory$FluidSubtypeInterpreter.apply(ItemStackListFactory.java:151)
	at mezz.jei.api.ISubtypeRegistry$ISubtypeInterpreter.getSubtypeInfo(ISubtypeRegistry.java:87)
	at mezz.jei.runtime.SubtypeRegistry.getSubtypeInfo(SubtypeRegistry.java:50)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:386)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:363)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:42)

This is an internal EnderIO crash pure and simple.  Please report to them.

>    but without galacticraft everything is working

This is hard to believe.  If we are making a difference it must be because EnderIO behaves differently if Galacticraft is loaded, I cannot imagine why.
