### ISSUE TITLE
Error when loading up a world

### ISSUE THREAD

**Issue by trunkyredstone** [micdoodle8/Galacticraft#3356]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.8.9
Galacticraft version: 4.0.1.169

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed?
-Computercraft
-Just Enough Items
-Buildcraft
-PlayerAPI

Please provide screenshots / crash report / log as needed.

Crash Report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.1.169.jar)
  PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 4/22/18 5:33 PM
Description: Unexpected error

com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at net.minecraft.client.resources.SkinManager.func_152788_a(SourceFile:126)
	at micdoodle8.mods.galacticraft.core.tick.TickHandlerClient.onClientTick(TickHandlerClient.java:370)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_124_TickHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1624)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:33)
Caused by: java.lang.NullPointerException
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.isWhitelistedDomain(YggdrasilMinecraftSessionService.java:210)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:149)
	at net.minecraft.client.resources.SkinManager$1.load(SourceFile:47)
	at net.minecraft.client.resources.SkinManager$1.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at net.minecraft.client.resources.SkinManager.func_152788_a(SourceFile:126)
	at micdoodle8.mods.galacticraft.core.tick.TickHandlerClient.onClientTick(TickHandlerClient.java:370)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_124_TickHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['unknownuser'/1374, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 124.00,64.00,252.00 - World: (124,64,252), Chunk: (at 12,4,12 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['unknownuser'/1374, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:33)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 405707056 bytes (386 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 3, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	PlayerAPI{1.0} [Player API] (minecraft.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.7} [BuildCraft] (buildcraft-mod-1.8.9.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.2.7} [BC Silicon] (buildcraft-mod-1.8.9.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.7} [BC Transport] (buildcraft-mod-1.8.9.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.7} [BC Builders] (buildcraft-mod-1.8.9.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.7} [BC Energy] (buildcraft-mod-1.8.9.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.2.7} [BC Robotics] (buildcraft-mod-1.8.9.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.7} [BC Factory] (buildcraft-mod-1.8.9.jar) 
	UCHIJAAAA	ComputerCraft{1.79} [ComputerCraft] (computercraft.jar) 
	UCHIJAAAA	GalacticraftCore{4.0.1.169} [Galacticraft Core] (GalacticraftCore-1.8.9-4.0.1.169.jar) 
	UCHIJAAAA	GalacticraftPlanets{4.0.1.169} [Galacticraft Planets] (Galacticraft-Planets-1.8.9-4.0.1.169.jar) 
	UCHIJAAAA	JEI{2.28.9.176} [Just Enough Items] (jei_1.8.9-2.28.9.176.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.1.169.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  api.player.forge.PlayerAPITransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.99' Renderer: 'Quadro 1000M/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: Quadro 1000M/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.99, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: TEAVSRP2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz

Help is needed! Thanks!

**Comment by radfast** [comment]
It's a vanilla bug - you can see people reporting this a few times on MinecraftForum, and at [this Spigot page](https://hub.spigotmc.org/jira/si/jira.issueviews:issue-html/SPIGOT-1506/SPIGOT-1506.html) - where people probably actually know what they are talking about - you can see the final post says there is a Mojang issue open for this.

(I couldn't find the Mojang issue - maybe MC-120163 but I'm not sure.)

Some forum posters have suggested switch off your antivirus (especially if you use Avast).

If that doesn't fix it, you might need to update your whole modpack to 1.10.2 or later.
