### ISSUE TITLE
[1.10.2] Crash while shift-clicking enderio silicone into CircuitFabricator

### ISSUE THREAD

**Issue by 7eggert** [micdoodle8/Galacticraft#3358]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 4.0.1.174
extraplanets{1.10.2-1.0.5}
EnderIO{1.10.2-3.1.183}

Single player (SSP),

Galacticraft add-ons and other mods installed? A lot, all included in crash report

java.lang.NullPointerException: Updating screen events
        at micdoodle8.mods.galacticraft.core.inventory.ContainerCircuitFabricator.mergeEven(ContainerCircuitFabricator.java:198)
        at micdoodle8.mods.galacticraft.core.inventory.ContainerCircuitFabricator.func_82846_b(ContainerCircuitFabricator.java:130)
        at net.minecraft.inventory.Container.func_184996_a(Container.java:258)

Thread: Client thread
Stacktrace:
        at micdoodle8.mods.galacticraft.core.inventory.ContainerCircuitFabricator.mergeEven(ContainerCircuitFabricator.java:198)
        at micdoodle8.mods.galacticraft.core.inventory.ContainerCircuitFabricator.func_82846_b(ContainerCircuitFabricator.java:130)
        at net.minecraft.inventory.Container.func_184996_a(Container.java:258)

(crashlog will be appended later because github has javascript issues)

**Comment by 7eggert** [comment]
[crash-2018-04-23_01.54.20-client.txt](https://github.com/micdoodle8/Galacticraft/files/1936265/crash-2018-04-23_01.54.20-client.txt)

**Comment by TheQuadShot** [comment]
Dupe https://github.com/micdoodle8/Galacticraft/issues/3353
Please search the database before you file, also make sure to do a search using "is:issue" ONLY, it will show all bugs instead of just open ones (some are fixed, just not propagated to download page)

**Comment by radfast** [comment]
fixed next build 175, which will be released some time in the coming week

I think the crash occurs when you shift-click with **any empty silicon slot** in the Circuit Fabricator.

It's an issue in build 174 version for MC 1.10.2 only, it won't occur in 1.11.2 and 1.12.2 versions which is why we didn't pick it up sooner.

**Comment by 7eggert** [comment]
Did search as described, but obviously not with correct keywords. Thanks for the good work.
