### ISSUE TITLE
Crash when entering minecraft with galacticraft and galacticraft planets

### ISSUE THREAD

**Issue by levilips123** [micdoodle8/Galacticraft#3361]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:Galacticraft-Mod-1.12.2-latest

Single player (SSP)
singleplayer
Galacticraft add-ons and other mods installed?
galacticraft planets 1.12.2-latest
Please provide screenshots / crash report / log as needed.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 4/23/18 4:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Planets (galacticraftplanets)
Caused by: java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.util.ConfigManagerCore.cleanConfig(Lnet/minecraftforge/common/config/Configuration;Ljava/util/Map;)V
	at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.configSyncEnd(GalacticraftPlanets.java:172)
	at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.preInit(GalacticraftPlanets.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 142001344 bytes (135 MB) / 351920128 bytes (335 MB) up to 1593049088 bytes (1519 MB)
	JVM Flags: 5 total; -Xmx1532M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                                    | Signature                                |
	|:----- |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| UCH   | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| UCH   | FML                 | 8.0.99.99    | forge-1.12.2-14.23.3.2655.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.3.2655 | forge-1.12.2-14.23.3.2655.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| UCH   | galacticraftcore    | 4.0.1.121    | Galacticraft-Mod-1.12.2.jar               | None                                     |
	| UCE   | galacticraftplanets | 4.0.1.174    | Galacticraft-Planets-1.12.2-4.0.1.174.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4590' Renderer: 'Intel(R) HD Graphics 620'

**Comment by TheQuadShot** [comment]
Your not running the same versions of GC modules, they should all have the same version number, and your core is build 121, and your planets is .174. So download the correct ones from here:
https://micdoodle8.com/mods/galacticraft/downloads

**Comment by MJRLegends** [comment]
Looks like they were download from a site like 9minecraft too which you should never download from

**Comment by radfast** [comment]
Galacticraft-Mod-1.12.2.jar

is not our file.  Get the proper one from the link **TheQuadShot** gave you.
