### ISSUE TITLE
Crash upon loading the second inventory screen

### ISSUE THREAD

**Issue by UrHeadset** [micdoodle8/Galacticraft#3410]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:
1.12.2
Galacticraft version:
every version I tried (the oldest on the download page and the newest)

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single
Galacticraft add-ons and other mods installed?
Yes, Codechickenlib, Forgemultipart, immersive engineering, immersiverailroading, micdoodlecore, MJRlegendslib, NGTlib, RealTrainMod, signpost, TrackAPI, WR-CBE

Please provide screenshots / crash report / log as needed.
Nothing avalable, it just shuts minecraft down, I got a report once, it crashed whilst rendering an sertain item, in the compas thing it also crashes.

**Comment by marcus8448** [comment]
I think this is a conflict with another mod, I can open the tab just fine...
If the game is crashing you should have a crash report...

On windows crash reports are kept in `%APPDATA%/.minecraft/crash-reports`
On Mac crash reports are kept in `~/Library/Application Support/minecraft`

**Comment by UrHeadset** [comment]
Here it is, the full crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-81.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.176.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 5/20/18 10:20 PM
Description: Rendering item

java.lang.IllegalAccessError: tried to access method javax.vecmath.Matrix3d.compute_svd([D[D[D)V from class javax.vecmath.Matrix4f
	at javax.vecmath.Matrix4f.getScaleRotate(Matrix4f.java:3239)
	at javax.vecmath.Matrix4f.setRotation(Matrix4f.java:3049)
	at micdoodle8.mods.galacticraft.planets.asteroids.client.render.item.ItemModelAstroMiner.getTransformForPerspective(ItemModelAstroMiner.java:32)
	at micdoodle8.mods.galacticraft.core.wrappers.ModelTransformWrapper.handlePerspective(ModelTransformWrapper.java:63)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:422)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:302)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:342)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:217)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:202)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at javax.vecmath.Matrix4f.getScaleRotate(Matrix4f.java:3239)
	at javax.vecmath.Matrix4f.setRotation(Matrix4f.java:3049)
	at micdoodle8.mods.galacticraft.planets.asteroids.client.render.item.ItemModelAstroMiner.getTransformForPerspective(ItemModelAstroMiner.java:32)
	at micdoodle8.mods.galacticraft.core.wrappers.ModelTransformWrapper.handlePerspective(ModelTransformWrapper.java:63)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:422)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:302)

-- Item being rendered --
Details:
	Item Type: micdoodle8.mods.galacticraft.planets.asteroids.items.ItemAstroMiner@72d699a9
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:342)

-- Item being rendered --
Details:
	Item Type: micdoodle8.mods.galacticraft.planets.asteroids.items.ItemAstroMiner@72d699a9
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:217)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:202)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (302, 11). Absolute: (605, 456)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Mart_The_Dragon'/30, l='MpServer', x=682.71, y=72.12, z=871.96]]
	Chunk stats: MultiplayerChunkCache: 729, 729
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,63,0), Chunk: (at 0,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 217582
