### ISSUE TITLE
Galacticraft planets causing crash SSp

### ISSUE THREAD

**Issue by phelpsor** [micdoodle8/Galacticraft#3477]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:1.12.2
crash report:---- Minecraft Crash Report ----
 
WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
Contact their authors BEFORE contacting forge
 
// Oops.
 
Time: 7/15/18 4:26 PM
XRay version: 58
Description: There was a severe problem during mod loading that has caused the game to fail
 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Planets (galacticraftplanets)
Caused by: java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.util.ConfigManagerCore.cleanConfig(Lnet/minecraftforge/common/config/Configuration;Ljava/util/Map;)V
    at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.configSyncEnd(GalacticraftPlanets.java:172)
    at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.preInit(GalacticraftPlanets.java:80)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:637)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- System Details --
Details:
    Minecraft Version: 1.12.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 256033856 bytes (244 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.42 Powered by Forge 14.23.3.2669 15 mods loaded, 15 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 
    | State | ID                  | Version         | Source                                  | Signature                                |
    |:----- |:------------------- |:--------------- |:--------------------------------------- |:---------------------------------------- |
    | UCH   | minecraft           | 1.12.2          | minecraft.jar                           | None                                     |
    | UCH   | mcp                 | 9.42            | minecraft.jar                           | None                                     |
    | UCH   | FML                 | 8.0.99.99       | forge-1.12.2-14.23.3.2669.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
    | UCH   | forge               | 14.23.3.2669    | forge-1.12.2-14.23.3.2669.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
    | UCH   | micdoodlecore       |                 | minecraft.jar                           | None                                     |
    | UCH   | codechickenlib      | 3.1.6.339       | CodeChickenLib-1.12.2.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
    | UCH   | galacticraftcore    | 4.0.1.121       | Galacticraft-Mod-1.12.2.jar             | None                                     |
    | UCE   | galacticraftplanets | 4.0.1.181       | Galacticraft-Planets-Mod-1.12.2.jar     | None                                     |
    | UCH   | ichunutil           | 7.1.4           | iChun-Util-Mod-1.12.2.jar               | None                                     |
    | UCH   | jei                 | 4.9.1.168       | jei_1.12.2-4.9.1.168.jar                | None                                     |
    | UCH   | mantle              | 1.12-1.3.2.24   | Mantle-Mod-1.12.2.jar                   | None                                     |
    | UCH   | morph               | 7.1.0           | Morphing-Mod-1.12.2.jar                 | None                                     |
    | UCH   | nei                 | 2.4.1           | Not-Enough-Items-1.12.2-Recommended.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
    | UCH   | projecte            | 1.12-PE1.1.0    | ProjectE-Mod-1.12.1.jar                 | None                                     |
    | UCH   | tconstruct          | 1.12.2-2.9.0.55 | Tinkers-Construct-Mod-1.12.2.jar        | None                                     |
 
    Loaded coremods (and transformers):
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.11' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses:
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)

**Comment by marcus8448** [comment]
You seem to have downloaded the mod from a site that reposts/steals mods (9minecraft I think). Please re-download Galacticraft from the official downloads page: https://micdoodle8.com/mods/galacticraft/downloads . Checkout http://stopmodreposts.org/ and #3430 for more information.

**Comment by phelpsor** [comment]
redownloading galacticraft core, galacticraft planets and micdoodlecore from the official site fixed the problem.
thanks

**Comment by Littlecat8845** [comment]
This didnt work for me and I have the same issue
