### ISSUE TITLE
Issues with Xaerosmap. What mod causes this timeout?

### ISSUE THREAD

**Issue by TheRealDadbeard** [micdoodle8/Galacticraft#3498]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

Galacticraft add-ons and other mods installed?

Please provide screenshots / crash report / log as needed.
`[04:29:08] [main/INFO]: Synced client config with server config.
[04:29:08] [Thread-19/INFO]: [xaero.map.MapLoader:loadBlockColourFromTexture:743]: Block file not found: minecraft:air
[04:29:09] [Thread-26/INFO]: Galacticraft remote version found: 4.0.1
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:464]: Region failed to load: -8_22 1
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 9
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.asteroids.blocks.BlockWalkway$EnumWalkwayType.byMetadata(BlockWalkway.java:67)
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.asteroids.blocks.BlockWalkway.func_176203_a(BlockWalkway.java:371)
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at net.minecraft.block.Block.func_176220_d(Block.java:2714)
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.Misc.getStateById(Misc.java:22)
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadPixel(MapSaveLoad.java:774)
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadRegion(MapSaveLoad.java:440)
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.run(MapSaveLoad.java:600)
[04:29:09] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at java.lang.Thread.run(Thread.java:745)
[04:29:11] [main/INFO]: Loaded 802 advancements
[04:29:11] [main/INFO]: Creating default SeasonInfo for dimension overworld
[04:29:14] [main/INFO]: Facade Accessor: cofh.core.render.IBlockAppearance
[04:29:14] [main/INFO]: Facade Accessor: team.chisel.ctm.api.IFacade
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:464]: Region failed to load: -7_21 1
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 3
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars$EnumMachineType.byMetadata(BlockMachineMars.java:81)
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.func_176203_a(BlockMachineMars.java:330)
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at net.minecraft.block.Block.func_176220_d(Block.java:2714)
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.Misc.getStateById(Misc.java:22)
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadPixel(MapSaveLoad.java:774)
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadRegion(MapSaveLoad.java:440)
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.run(MapSaveLoad.java:600)
[04:29:14] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at java.lang.Thread.run(Thread.java:745)
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:464]: Region failed to load: -8_21 1
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 3
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars$EnumMachineType.byMetadata(BlockMachineMars.java:81)
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.func_176203_a(BlockMachineMars.java:330)
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at net.minecraft.block.Block.func_176220_d(Block.java:2714)
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.Misc.getStateById(Misc.java:22)
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadPixel(MapSaveLoad.java:774)
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadRegion(MapSaveLoad.java:440)
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.run(MapSaveLoad.java:600)
[04:29:18] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at java.lang.Thread.run(Thread.java:745)
[04:29:18] [Thread-19/INFO]: [xaero.map.MapLoader:loadBlockColourFromTexture:743]: Block file not found: mekanism:transmitter
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:464]: Region failed to load: -6_20 1
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 3
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars$EnumMachineType.byMetadata(BlockMachineMars.java:81)
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.func_176203_a(BlockMachineMars.java:330)
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at net.minecraft.block.Block.func_176220_d(Block.java:2714)
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.Misc.getStateById(Misc.java:22)
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadPixel(MapSaveLoad.java:774)
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadRegion(MapSaveLoad.java:440)
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.run(MapSaveLoad.java:600)
[04:29:26] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at java.lang.Thread.run(Thread.java:745)
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:464]: Region failed to load: -7_20 1
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 3
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars$EnumMachineType.byMetadata(BlockMachineMars.java:81)
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.func_176203_a(BlockMachineMars.java:330)
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at net.minecraft.block.Block.func_176220_d(Block.java:2714)
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.Misc.getStateById(Misc.java:22)
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadPixel(MapSaveLoad.java:774)
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadRegion(MapSaveLoad.java:440)
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.run(MapSaveLoad.java:600)
[04:29:35] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at java.lang.Thread.run(Thread.java:745)
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:464]: Region failed to load: -8_20 1
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 3
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars$EnumMachineType.byMetadata(BlockMachineMars.java:81)
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.func_176203_a(BlockMachineMars.java:330)
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at net.minecraft.block.Block.func_176220_d(Block.java:2714)
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.Misc.getStateById(Misc.java:22)
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadPixel(MapSaveLoad.java:774)
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadRegion(MapSaveLoad.java:440)
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.run(MapSaveLoad.java:600)
[04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at java.lang.Thread.run(Thread.java:745)
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:464]: Region failed to load: -5_20 1
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 3
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars$EnumMachineType.byMetadata(BlockMachineMars.java:81)
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.func_176203_a(BlockMachineMars.java:330)
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at net.minecraft.block.Block.func_176220_d(Block.java:2714)
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.Misc.getStateById(Misc.java:22)
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadPixel(MapSaveLoad.java:774)
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadRegion(MapSaveLoad.java:440)
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.run(MapSaveLoad.java:600)
[04:29:49] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at java.lang.Thread.run(Thread.java:745)
[04:29:52] [Netty Client IO #1/ERROR]: NetworkDispatcher exception
java.io.IOException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_51]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_51]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_51]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_51]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_51]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[04:29:52] [Netty Client IO #1/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[04:29:52] [Netty Client IO #1/INFO]: Unregistered Dimension: -30
[04:29:52] [Netty Client IO #1/INFO]: Unregistered Dimension: -29
[04:29:52] [Netty Client IO #1/INFO]: Unregistered Dimension: -31
[04:29:52] [Netty Client IO #1/INFO]: Unregistered Dimension: -28
[04:29:53] [main/INFO]: JEI search tree manager injection complete!
[04:29:54] [main/INFO]: Applying holder lookups
[04:29:54] [main/INFO]: Holder lookups applied
[04:29:54] [main/INFO]: VoiceServer: Stopping client connection...
[04:29:54] [main/INFO]: Reloaded config.`

**Comment by radfast** [comment]
I don't know about the Netty timeout, that can be any mod.  The only way to figure it out is to try removing mods, maybe using a [binary search](https://wiki.micdoodle8.com/wiki/Common_Problems#Mod_conflicts:_Binary_Seach_method)

Separately, I am seeing this error in your logs, this implies a corrupted map at that position, you may be able to fix it by breaking the block and replacing it if you can figure out which block is the cause.  BlockMachineMars can be a few different things, most likely a Cryogenic Chamber.

    [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 3 [04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars$EnumMachineType.byMetadata(BlockMachineMars.java:81) [04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: at micdoodle8.mods.galacticraft.planets.mars.blocks.BlockMachineMars.func_176203_a(BlockMachineMars.java:330) [04:29:42] [Thread-19/INFO]: [xaero.map.MapSaveLoad:loadRegion:465]: at
