### ISSUE TITLE
Crash on Minecraft loader: End of phase 2 / 7

### ISSUE THREAD

**Issue by BadLucKWyvern** [micdoodle8/Galacticraft#3511]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.11.2
Galacticraft version: Galacticraft 1.11.2-4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? Single

Galacticraft add-ons and other mods installed? ExtraPlanets, MorePlanets, MorePlanetsExtra

Please provide screenshots / crash report / log as needed.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.11.2-4.0.jar)
  Better mobGriefing GameRule Core (bettermobgriefinggamerule-1.11.2-5.0.0.jar)
  LoadingPlugin (Quark-r1.2-93b.jar)
  IC2core (industrialcraft-2-2.7.81-ex111.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.2.5.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.9.jar)
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.1.181 (1).jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.2.2-70.jar)
  MDECore-Core (mdecore-1.11-1.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  MalisisSwitchesPlugin (malisisswitches-1.11.2-4.1.0.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.328-universal.jar)
  DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  BaseMetals (BaseMetals-1.11.2-2.5.0-beta4.113.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  llibrary (llibrary-1.7.11-1.11.2.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-2.0.0.388.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 8/17/18 11:27 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:456)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:834)
	at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:225)
	at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:205)
	at micdoodle8.mods.galacticraft.core.GCBlocks.registerBlock(GCBlocks.java:352)
	at micdoodle8.mods.galacticraft.core.blocks.BlockGrating.createForgeFluidVersion(BlockGrating.java:134)
	at micdoodle8.mods.galacticraft.core.blocks.BlockGrating.remapForgeVariants(BlockGrating.java:146)
	at micdoodle8.mods.galacticraft.core.TransformerHooks.preInitFinal(TransformerHooks.java:629)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:652)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:276)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:456)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:834)
	at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:225)
	at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:205)
	at micdoodle8.mods.galacticraft.core.GCBlocks.registerBlock(GCBlocks.java:352)
	at micdoodle8.mods.galacticraft.core.blocks.BlockGrating.createForgeFluidVersion(BlockGrating.java:134)
	at micdoodle8.mods.galacticraft.core.blocks.BlockGrating.remapForgeVariants(BlockGrating.java:146)
	at micdoodle8.mods.galacticraft.core.TransformerHooks.preInitFinal(TransformerHooks.java:629)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:652)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:276)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MJRLegends** [comment]
@BadLucKWyvern You dont have a bug here, your issue is you have to many blocks being registered use the JustEnoughIDs mod to expand this limit

**Comment by BadLucKWyvern** [comment]
Ah ok, thank you ! Ill be able to put more mods again :D
Btw ive got, a question, ive got, a bug (not with your mod) but i usually face mobs with NaN/max HP ... how can i kill them ? (some are tamed units so i can't make em despawning)
Is there a command to kill those fake death mobs ? :/

**Comment by MJRLegends** [comment]
Idk sorry

**Comment by BadLucKWyvern** [comment]
then you can close the thread, thanks for the help :)

**Comment by MJRLegends** [comment]
I cant close it but you can

**Comment by radfast** [comment]
Thanks @MJRLegends for helping out.
