### ISSUE TITLE
MicDoodle's Core Problem

### ISSUE THREAD

**Issue by Niilyx** [micdoodle8/Galacticraft#3521]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181
MicDoodle's Core version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? opened to premium

Galacticraft add-ons and other mods installed? Yes, a lot of other mods.

Please provide screenshots / crash report / log as needed.

The MicDoodle's Core not compatible??? I choose the right version...

MultiMC version: 0.6.2-1222

Minecraft folder is:
C:/Users/naitm/Desktop/MultiMC/instances/1.12.2 LAN Alex/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_181, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/naitm/Desktop/MultiMC/instances/1.12.2 LAN Alex/natives

Libraries:
  C:/Users/naitm/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/mojang/realms/1.9.8/realms-1.9.8.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.10.2-12.18.3.2422/forge-1.10.2-12.18.3.2422-universal.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/naitm/Desktop/MultiMC/instances/1.12.2 LAN Alex/.minecraft/bin/minecraft.jar

Native libraries:
  C:/Users/naitm/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/naitm/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  appliedenergistics2-rv5-stable-11
  BrandonsCore-1.12.2-2.4.4.173-universal
  buildcraft-7.99.18
  Chisel-MC1.12.2-0.2.1.34
  CodeChickenLib-1.12.2-3.2.1.351-universal
  CoFHCore-1.12.2-4.5.3.20-universal
  CoFHWorld-1.12.2-1.2.0.5-universal
  CTM-MC1.12.2-0.3.2.18
  Draconic-Evolution-1.12.2-2.3.13.306-universal
  EnderCore-1.12.2-0.5.37
  EnderIO-1.12.2-5.0.31
  ForgeMultipart-1.12.2-2.5.0.71-universal
  GalacticraftCore-1.12.2-4.0.1.181
  Galacticraft-Planets-1.12.2-4.0.1.181
  iChunUtil-1.12.2-7.1.4
  ImmersiveEngineering-0.12-85
  jei_1.12.2-4.11.0.212
  mcjtylib-1.12-3.0.4
  Mekanism-1.12.2-9.4.13.349
  MekanismGenerators-1.12.2-9.4.13.349
  MekanismTools-1.12.2-9.4.13.349
  MicdoodleCore-1.12.2-4.0.1.181
  Morphing-Mod-1.12.2
  NotEnoughItems-1.12.2-2.4.1.238-universal
  OptiFine_1.12.2_HD_U_E2
  orespawn-1.7.10-20.3
  Pixelmon-1.12.2-6.3.4-universal
  PortalGun-1.12.2-7.0.2
  rafradek_tf2_weapons-1.12.2-1.3.8.2
  RedstoneFlux-1.12-2.0.2.3-universal
  rftools-1.12-7.55
  rftoolsctrl-1.12-1.9.1
  SimplyJetpacks2-1.12.2-2.2.7.45
  StorageDrawers-1.12.2-5.3.7
  ThermalDynamics-1.12.2-2.5.1.14-universal
  ThermalExpansion-1.12.2-5.5.0.29-universal
  ThermalFoundation-1.12.2-2.5.0.19-universal
  ThermalInnovation-1.12.2-0.3.0.7-universal

Jar Mods:
  Mekanism-1.7.10-8.1.9.265 (02a8b75d-05fd-4ff8-a385-9bf5254e36cf.jar)
  MekanismGenerators-1.7.10-8.1.9.265 (86579ce7-37f3-4ff7-9883-21a44475fd8e.jar)
  MekanismTools-1.7.10-8.1.9.265 (deadf562-ccd8-471e-8e0d-02e927134b48.jar)

Params:
  --username  --version MultiMC5 --gameDir C:/Users/naitm/Desktop/MultiMC/instances/1.12.2 LAN Alex/.minecraft --assetsDir C:/Users/naitm/Desktop/MultiMC/assets --assetIndex 1.10 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx2304m, -Duser.language=en]

Minecraft process ID: 14880

Using onesix launcher.

2018-09-18 19:11:16,028 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-09-18 19:11:16,028 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[19:11:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:11:16] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:11:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:11:16] [main/INFO] [FML]: Forge Mod Loader version 12.18.3.2422 for Minecraft 1.10.2 loading
[19:11:16] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_181, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_181
[19:11:16] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[19:11:16] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2018-09-18 19:11:16,340 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-09-18 19:11:16,356 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-09-18 19:11:16,356 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[19:11:16] [main/ERROR] [FML]: The coremod com.enderio.core.common.transform.EnderCorePlugin is requesting minecraft version 1.12.2 and minecraft is 1.10.2. It will be ignored.
[19:11:16] [main/WARN] [FML]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:11:16] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:11:16] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E2.jar
[19:11:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:11:16] [main/INFO] [LaunchWrapper]: Loading tweak class name codechicken.asm.internal.Tweaker
[19:11:16] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[19:11:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:11:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:11:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:11:16] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[19:11:16] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[19:11:16] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[19:11:16] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[19:11:16] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\naitm\Desktop\MultiMC\instances\1.12.2 LAN Alex\.minecraft\mods\OptiFine_1.12.2_HD_U_E2.jar
[19:11:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:11:18] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:11:18] [main/ERROR] [FML]: The minecraft jar file:/C:/Users/naitm/Desktop/MultiMC/instances/1.12.2%20LAN%20Alex/.minecraft/bin/minecraft.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
[19:11:18] [main/ERROR] [FML]: FML has been ordered to ignore the invalid or missing minecraft certificate. This is very likely to cause a problem!
[19:11:18] [main/ERROR] [FML]: Technical information: ClientBrandRetriever was at jar:file:/C:/Users/naitm/Desktop/MultiMC/instances/1.12.2%20LAN%20Alex/.minecraft/bin/minecraft.jar!/net/minecraft/client/ClientBrandRetriever.class, there were 0 certificates for it
[19:11:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:11:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:11:18] [main/INFO] [STDERR]: [micdoodle8.mods.miccore.MicdoodlePlugin:versionCheck:52]: This version of MicdoodleCore does not support minecraft version 1.10.2
[19:11:59] [main/ERROR] [LaunchWrapper]: Unable to launch
net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49) ~[forge-1.10.2-12.18.3.2422-universal.jar:?]
	at java.lang.SecurityManager.checkExit(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Runtime.exit(Unknown Source) ~[?:1.8.0_181]
	at java.lang.System.exit(Unknown Source) ~[?:1.8.0_181]
	at micdoodle8.mods.miccore.MicdoodlePlugin.versionCheck(MicdoodlePlugin.java:77) ~[MicdoodleCore-1.12.2-4.0.1.181.jar:?]
	at micdoodle8.mods.miccore.MicdoodlePlugin.getASMTransformerClass(MicdoodlePlugin.java:84) ~[MicdoodleCore-1.12.2-4.0.1.181.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:130) ~[forge-1.10.2-12.18.3.2422-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.exit(Unknown Source)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.exit(Unknown Source)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:12:00] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[19:12:00] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[19:12:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:12:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:12:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[19:12:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[19:12:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[19:12:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.

And i get this!

**Comment by TheQuadShot** [comment]
file:/C:/Users/naitm/Desktop/MultiMC/instances/1.12.2%20LAN%20Alex/.minecraft/bin/minecraft.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!

Are you running a legal copy of Minecraft!?

**Comment by Niilyx** [comment]
> file:/C:/Users/naitm/Desktop/MultiMC/instances/1.12.2%20LAN%20Alex/.minecraft/bin/minecraft.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
> 
> Are you running a legal copy of Minecraft!?

Definitely, its premium

**Comment by Niilyx** [comment]
Wrong Manip :/

**Comment by marcus8448** [comment]
Why is the Minecraft jarfile inside `.minecraft/bin/ as normally its inside `.minecraft/versions/` or `.minecraft/libraries/net/minecraftforge/forge/xxxx` (for forge)

**Comment by Niilyx** [comment]
Forget it , i just reinstalled the multimc instance and bam it worked so... Thank you anyway
