### ISSUE TITLE
Client crash when leaving atmosphere of Overworld.

### ISSUE THREAD

**Issue by mando222** [micdoodle8/Galacticraft#3534]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

Galacticraft add-ons and other mods installed?
Yes and yes full list in crash link. https://paste.dimdev.org/eboqariqak.mccrash

Please provide screenshots / crash report / log as needed.
Same as above.
https://paste.dimdev.org/eboqariqak.mccrash

**Comment by mando222** [comment]
To be clear only the client crashes. The server freaks out a bit but recovers without anything serious.

Also if you want to reproduce the Modpack we are using is on the twitch launcher if that would help you.

**Comment by radfast** [comment]
This appears to be an ExtraPlanets issue.  From our side we can fix it so it doesn't crash here, but even after that it may not behave as expected - if there are continuing problems please report to ExtraPlanets.

**Comment by MJRLegends** [comment]
I believe this to be a galaxy space related thing, as it only seems to happen when Galaxy Space is used for ExtraPlanets and GC but GC and ExtraPlanets are fine

**Comment by MJRLegends** [comment]
See https://github.com/MJRLegends/ExtraPlanets/issues/355

**Comment by MJRLegends** [comment]
@radfast & @BlesseNtumble ok so thanks for your fix for this, but im aware it doesnt stop the crash the issue seems to be

the Celestial Body is returning a null value from celestialBodyTicks hash map, also i tested this without my custom galaxy map off and Galaxyspaces one off too and still the crash here is the crash log. Any ideas? 
```
java.lang.NullPointerException: Rendering screen
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1319)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.drawCircles(GuiCelestialSelection.java:2292)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.drawScreen(GuiCelestialSelection.java:1197)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1177)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1208)
	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)
```

**Comment by MJRLegends** [comment]
Seems adding the following to GuiCelestialSelection#initGUI Method fixing the issue, which means the getCelestialBodyPosition is erroring on getting stars location. This is a GC bug :D @radfast 

```
		for (SolarSystem star : GalaxyRegistry.getRegisteredSolarSystems().values()) {
			this.celestialBodyTicks.put(star.getMainStar(), 0);
		}
```

I since i override this method in my custom gui for other reasons, i have added the above to ExtraPlanets version of initGUI  to fix this in the meantime :D

**Comment by MJRLegends** [comment]
Since i wanna be done with this, For my ExtraPlanets & Planet Progressions mod i have added 


```
		for (SolarSystem star : GalaxyRegistry.getRegisteredSolarSystems().values()) {
			this.celestialBodyTicks.put(star.getMainStar(), 0);
		}
```
to my overrided version of GuiCelestialSelection#initGUI method in my custom gui which i already have for other reasons, 

and i have added for ExtraPlanets
```
	protected Vector3f getCelestialBodyPosition(CelestialBody cBody)
    {
    	if(this.celestialBodyTicks.get(cBody) == null)
    		return new Vector3f(0.0F, 0.0F, 0.0F);
		return super.getCelestialBodyPosition(cBody);
    }
``` to solve the galaxy map issues with Galaxy Space registering non reachable planets correctly
