### ISSUE TITLE
Celestial Map Broken/Can't see information on most planets or moons/Can't launch to said planets or moons

### ISSUE THREAD

**Issue by Machu297** [micdoodle8/Galacticraft#3596]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.184

Multiplayer (SMP)
Extra Planets Ver: 0.4.6
This is what the map looks like for most of the planets on the map (Broken map (#1))
![broken map](https://user-images.githubusercontent.com/33404970/50731987-70ce8680-1136-11e9-9a19-23ec021fe1a4.png)

This is what the map is supposed to look like (Example from same broken map(#2))
![correct map](https://user-images.githubusercontent.com/33404970/50731989-880d7400-1136-11e9-858f-7f4a0fb70cca.png)

Modlist can be found on this site: https://www.technicpack.net/modpack/reprise-of-the-fallen-v1.1195046/mods

**Comment by MJRLegends** [comment]
Please can you post your client logs

**Comment by Machu297** [comment]
Logs have been posted below the modlist site.

**Comment by MJRLegends** [comment]
```
[11:24:12] [main/ERROR] [Galacticraft]: (The problem is likely caused by a dimension ID conflict.  Check configs for dimension clashes.  You can also try disabling Mars space station in configs.)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: java.lang.IllegalArgumentException: Could not get provider type for dimension -19, does not exist
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:164)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:325)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.getProviderForDimensionClient(WorldUtil.java:352)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.drawCustomButtons(CustomCelestialSelection.java:247)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.drawButtons(CustomCelestialSelection.java:437)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73863_a(GuiCelestialSelection.java:1225)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.func_73863_a(CustomCelestialSelection.java:983)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3941)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[11:24:12] [main/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection:func_73863_a:1233]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by MJRLegends** [comment]
Im going to crash the game if this error happens in extraplanets, i think as im kinda bored of these crash log and people not checking the log for possible errors

**Comment by spylor** [comment]
One of my players reported the same issue yesterday but I haven't been able to confirm it yet. I do not use extraplanets.

**Comment by spylor** [comment]
I think in my case it's probably sponge related as I see in other issue.

**Comment by micdoodle8** [comment]
So it seems to be related to Sponge, as I can't recreate it in vanilla and you're both using Sponge. Did either of you notice it break after updating Galacticraft or Sponge? E.g. was it working in X version?

**Comment by spylor** [comment]
I installed both at the same time. I have removed sponge again for now.

**Comment by Machu297** [comment]
As far as I know, nothing was updated before the issue started. The issue began, and due to this, the server's Extra Planets was updated. Also as a side note, the bug does not happen in singleplayer.

**Comment by rzfoxtrot** [comment]
I have the same issue and looking for solution.  On my server i cant launch to the moon or other planet and map looks the same. In single player everything is ok. I also have installed sponge on server.

**Comment by rzfoxtrot** [comment]
https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.12.2-2768-7.1.5-RC3522/spongeforge-1.12.2-2768-7.1.5-RC3522.jar

This version of sponge resolved issue, i cant fly to the mon now. But map still does not work
