### ISSUE TITLE
Crashing on Difficulty change

### ISSUE THREAD

**Issue by MarcMallo** [micdoodle8/Galacticraft#3606]
So basically, everytime I try to change the difficulty in our world, the game crashes, but it only does it when I'm in a different dimension like for example, the moon. Help would be much appreciated! Details are below. 

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Single Player opened to LAN

No add-ons 

Here comes the crashlog: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 1/11/19 9:43 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:335)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:202)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:335)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:202)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)

-- Affected level --
Details:
	Level name: Mar an Dusy an Ni Gay AND DEEGO
	All players: 1 total; [GCEntityPlayerMP['Marc_mallow'/390, l='Mar an Dusy an Ni Gay AND DEEGO', x=-15.06, y=72.80, z=261.53]]
	Chunk stats: ServerChunkCache: 729 Drop: 0
	Level seed: -1543664993
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3397411424 bytes (3240 MB) / 4697620480 bytes (4480 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_E3 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                                        | Signature                                |
	|:--------- |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |              | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | obfuscate           | 0.2.5        | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | biomesoplenty       | 7.0.1.2399   | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
	| UCHIJAAAA | cfm                 | 5.4.1        | cfm-5.4.1-mc1.12.2.jar                        | None                                     |
	| UCHIJAAAA | chesttransporter    | 2.8.8        | ChestTransporter-1.12.2-2.8.8.jar             | None                                     |
	| UCHIJAAAA | chiselsandbits      | 14.20        | chiselsandbits-14.20.jar                      | None                                     |
	| UCHIJAAAA | craftablemobs       | 1.0.0        | craftablemobs-1.0.0.jar                       | None                                     |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.181    | GalacticraftCore-1.12.2-4.0.1.181.jar         | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.181    | Galacticraft-Planets-1.12.2-4.0.1.181.jar     | None                                     |
	| UCHIJAAAA | jei                 | 4.13.1.225   | jei_1.12.2-4.13.1.225.jar                     | None                                     |
	| UCHIJAAAA | malisiscore         | 1.12.2-6.4.0 | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCHIJAAAA | malisisdoors        | 1.12.2-7.3.0 | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UCHIJAAAA | harvestcraft        | 1.12.2zb     | Pam's+HarvestCraft+1.12.2zb.jar               | None                                     |
	| UCHIJAAAA | ropebridge          | 2.0.5        | ropebridge-1.12-2.0.7.jar                     | None                                     |
	| UCHIJAAAA | treechopper         | 1.2.4        | Tree-Chopper-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | vehicle             | 0.35.0       | vehicle-0.35.0-mc1.12.2.jar                   | None                                     |
	| UCHIJAAAA | worldedit           | 6.1.8        | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| UCHIJAAAA | xaerominimap        | 1.15         | Xaeros_Minimap_FP1.15_Forge_1.12.jar          | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['Marc_mallow'/390, l='Mar an Dusy an Ni Gay AND DEEGO', x=-15.06, y=72.80, z=261.53]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 13
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 417.35
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by micdoodle8** [comment]
I'm not seeing anything that makes me think this is Galacticraft, but I could be wrong. Can you upload the full latest.log to pastebin.com?
