### ISSUE TITLE
Issue Running with Vivecraft

### ISSUE THREAD

**Issue by deGaus93** [micdoodle8/Galacticraft#3618]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Any Galacticraft add-ons installed? Core, Galacticraft, Planets

Crash occurs when creating a world.

Please provide screenshots / crash report / log / full modlist as needed

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.0.20.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 1/19/19 6:42 PM
Description: Starting integrated server

java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/player/GCEntityPlayerMP
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:61)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:3141)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:523)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.mouseDown(GuiScreen.java:868)
	at com.mtbs3d.minecrift.gameplay.screenhandlers.GuiHandler.processBindingsGui(GuiHandler.java:210)
	at com.mtbs3d.minecrift.provider.MCOpenVR.processBindings(MCOpenVR.java:1265)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2494)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1607)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:656)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:61)

-- Starting integrated server --
Details:
	Level ID: New World
	Level Name: New World
Stacktrace:
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:3141)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:523)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.mouseDown(GuiScreen.java:868)
	at com.mtbs3d.minecrift.gameplay.screenhandlers.GuiHandler.processBindingsGui(GuiHandler.java:210)
	at com.mtbs3d.minecrift.provider.MCOpenVR.processBindings(MCOpenVR.java:1265)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2494)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1607)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:656)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1644179264 bytes (1568 MB) / 4234149888 bytes (4038 MB) up to 4234149888 bytes (4038 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_E3 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                          | Signature                                |
	|:------ |:------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2796.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2796             | forge-1.12.2-14.23.5.2796.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |                          | minecraft.jar                                   | None                                     |
	| LCHIJA | opencomputers|core  | 1.7.0.20                 | minecraft.jar                                   | None                                     |
	| LCHIJA | mercurius_updater   | 1.0                      | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| LCHIJA | astralsorcery       | 1.8.5                    | astralsorcery-1.12.2-1.8.5.jar                  | None                                     |
	| LCHIJA | autoreglib          | 1.3-15                   | AutoRegLib-1.3-15.jar                           | None                                     |
	| LCHIJA | baubles             | 1.5.1                    | Baubles-1.12-1.5.1.jar                          | None                                     |
	| LCHIJA | bibliocraft         | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| LCHIJA | jei                 | 4.14.4.259               | jei_1.12.2-4.14.4.259.jar                       | None                                     |
	| LCHIJA | forestry            | 5.7.0.214                | forestry_1.12.2-5.7.0.214.jar                   | None                                     |
	| LCHIJA | binniecore          | unspecified              | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| LCHIJA | binniedesign        | 1.0                      | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| LCHIJA | genetics            | 2.5.0.106                | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| LCHIJA | botany              | 2.5.0.106                | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| LCHIJA | extrabees           | 2.5.0.106                | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| LCHIJA | extratrees          | 2.5.0.106                | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| LCHIJA | botania             | r1.10-350                | Botania r1.10-350.jar                           | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.15                  | buildcraft-7.99.15.jar                          | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.15                  | buildcraft-7.99.15.jar                          | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.15                  | buildcraft-7.99.15.jar                          | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.15                  | buildcraft-7.99.15.jar                          | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.15                  | buildcraft-7.99.15.jar                          | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.15                  | buildcraft-7.99.15.jar                          | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.15                  | buildcraft-7.99.15.jar                          | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.15                  | buildcraft-7.99.15.jar                          | None                                     |
	| LCHIJA | chunkpregenerator   | 1.8                      | Chunk+Pregenerator+V1.12-1.8.1.jar              | None                                     |
	| LCHIJA | codechickenlib      | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux        | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore            | 4.6.1                    | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| LCHIJA | cofhworld           | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | ptrmodellib         | 1.0.0                    | Decocraft-2.5.4_1.12.2.jar                      | None                                     |
	| LCHIJA | props               | 2.5.4                    | Decocraft-2.5.4_1.12.2.jar                      | None                                     |
	| LCHIJA | densemetals         | 1.0.2                    | densemetals-1.12.2-1.0.2.jar                    | None                                     |
	| LCHIJA | mantle              | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| LCHIJA | extrautils2         | 1.0                      | extrautils2-1.12-1.6.8.jar                      | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.1.181                | GalacticraftCore-1.12.2-4.0.1.181.jar           | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.1.181                | Galacticraft-Planets-1.12.2-4.0.1.181.jar       | None                                     |
	| LCHIJA | ichunutil           | 7.1.3                    | iChunUtil-1.12.2-7.1.3.jar                      | None                                     |
	| LCHIJA | hats                | 7.0.0                    | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| LCHIJA | waila               | 1.8.23                   | Hwyla-1.8.23-B38_1.12.jar                       | None                                     |
	| LCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest           | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| LCHIJA | mekanism            | 1.12.2-9.4.3.330         | Mekanism-1.12.2-9.4.3.330.jar                   | None                                     |
	| LCHIJA | mekanismgenerators  | 9.4.3                    | MekanismGenerators-1.12.2-9.4.3.330.jar         | None                                     |
	| LCHIJA | mekanismtools       | 9.4.3                    | MekanismTools-1.12.2-9.4.3.330.jar              | None                                     |
	| LCHIJA | morebees            | 1.12.2-1.4.4             | morebees-1.12.2-1.4.4.jar                       | None                                     |
	| LCHIJA | nei                 | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | opencomputers       | 1.7.0.20                 | OpenComputers-MC1.12.1-1.7.0.20.jar             | None                                     |
	| LCHIJA | ocsensors           | 1.0.0                    | ocsensors-1.0.2-b12.jar                         | None                                     |
	| LCHIJA | clayspawn           | 1.12a                    | Pam's+ClaySpawn+1.12a.jar                       | None                                     |
	| LCHIJA | getalltheseeds      | 1.12a                    | Pam's+Get+all+the+Seeds!+1.12a.jar              | None                                     |
	| LCHIJA | harvestcraft        | 1.12.2q                  | Pam's+HarvestCraft+1.12.2q.jar                  | None                                     |
	| LCHIJA | projecte            | 1.12-PE1.1.0             | ProjectE-1.12-PE1.1.0.jar                       | None                                     |
	| LCHIJA | reforged            | 0.7.5                    | Reforged-0.7.5-1.12+.jar                        | None                                     |
	| LCHIJA | ruins               | 16.9                     | Ruins-1.12.1.jar                                | None                                     |
	| LCHIJA | thermalfoundation   | 2.6.1                    | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion    | 5.5.2                    | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics     | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | treechopper         | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
	| LCHIJA | twilightforest      | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| LCHIJA | waystones           | 4.0.17                   | Waystones_1.12.1-4.0.17.jar                     | None                                     |
	| LCHIJA | weeeflowers         | 1.12.2b                  | Weee!+Flowers+1.12.2b (1).jar                   | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
TransformerLoader (OpenComputers-MC1.12.1-1.7.0.20.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.71' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: vivecraft-1.12.2-jrbudda-7-r12-forge
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vivecraft,fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 417.71
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by tbnboy815** [comment]
Also happens when I am just running with galacticraft 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190 (1).jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 1/19/19 7:34 PM
Description: Starting integrated server

java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/player/GCEntityPlayerMP
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:61)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:3141)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:523)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:653)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:610)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2453)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1607)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:656)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:61)

-- Starting integrated server --
Details:
	Level ID: New World---
	Level Name: New World
Stacktrace:
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:3141)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:523)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:653)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:610)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2453)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1607)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:656)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7889768568 bytes (7524 MB) / 8549040128 bytes (8153 MB) up to 8549040128 bytes (8153 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -Xms8G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_E3 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                        | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2796.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2796 | forge-1.12.2-14.23.5.2796.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                                 | None                                     |
	| LCHIJA | mercurius_updater   | 1.0          | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.190    | GalacticraftCore-1.12.2-4.0.2.190 (1).jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.190    | Galacticraft-Planets-1.12.2-4.0.2.190 (1).jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190 (1).jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.71' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	Launched Version: vivecraft-1.12.2-jrbudda-7-r12-forge
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vivecraft,fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 417.71
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by 0x8080** [comment]
Same issue here
