### ISSUE TITLE
Solar Array Modules crash the game.

### ISSUE THREAD

**Issue by Xtreme533** [micdoodle8/Galacticraft#3646]
I've hooked up about 150 Solar Array Modules or so (can't check as the world is inaccesible) to a controller, which provides power to Arc Furnaces throughout Sealed Aluminum Wire blocks. After leaving the world and restarting the game, the world will crash upon entering, although there is a chance that it will let you in. Upon that, the game seems stable.
EDIT: I finally got to hop on after 3 tries, will provide a screenshot of the setup.

Minecraft version: 1.12.2
Forge version: 14.23.5.2814
Galacticraft version: 4.0.2.190

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single player world, multiplayer untested.

Any Galacticraft add-ons installed? please list all
None

Please provide screenshots / crash report / log / full modlist as needed
I'm only using the GalactiCraft mods, no addons or other mods.
Crash log: AMDescription: Exception ticking world entities java.lang.ClassCastException: micdoodle8.mods.galacticraft.planets.venus.tile.SolarModuleNetwork cannot be cast to micdoodle8.mods.galacticraft.api.transmission.grid.IElectricityNetwork at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseConductor.getNetwork(TileBaseConductor.java:71 at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseConductor.getNetwork(TileBaseConductor.java:26 at micdoodle8.mods.galacticraft.planets.venus.tile.SolarModuleNetwork.refreshWithChecks(SolarModuleNetwork.java:84)
at micdoodle8.mods.galacticraft.planets.venus.tile.SolarModuleNetwork.split(SolarModuleNetwork.java:248 at micdoodle8.mods.galacticraft.planets.venus.tile.SolarModuleNetwork.split(SolarModuleNetwork.java:26) at micdoodle8.mods.galacticraft.planets.venus.tile.TileEntitySolarTransmitter.func_145843_s(TileEntitySolarTransmitter.java:37)
at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:832)
at net.minecraft.world.World.func_72939_s(World.java:1891)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:745)

![2019-03-09_10 13 43](https://user-images.githubusercontent.com/19747005/54069082-10ea7e00-4254-11e9-8fa5-e045fa6f76b7.png)

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

The mods are from official source.

**Comment by MJRLegends** [comment]
Already posted #3641

**Comment by Xtreme533** [comment]
> Already posted #3641

That issue addresses placing/removing the modules though, while here the game seemingly crashes for what you could call no reason, as nothing happens to the blocks themselves...

**Comment by MJRLegends** [comment]
Still same crash issue

**Comment by micdoodle8** [comment]
Should be fixed in the next build. Thanks.
