### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by nallack** [micdoodle8/Galacticraft#3682]
Getting crashes flying around in creative. It looks like sponge events may be involved so gonna try determining if it's a conflict with sponge or one if its plugins.

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

Any Galacticraft add-ons installed? please list all:
* galacticraftcore
* galacticraftplanets

Please provide screenshots / crash report / log / full modlist as needed:

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  SpongeCoremod (spongeforge-1.12.2-2768-7.1.5.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 4/28/19 7:55 PM
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:643)
	at org.spongepowered.common.event.tracking.PhaseStack.checkForRunaways(PhaseStack.java:141)
	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:250)
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:581)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:748)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:697)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:386)
	at net.minecraft.world.World.redirect$onCallEntityUpdate$zmc000(World.java:5725)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:6099)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:643)
	at org.spongepowered.common.event.tracking.PhaseStack.checkForRunaways(PhaseStack.java:141)
	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:250)
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:581)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:748)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:697)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:386)
	at net.minecraft.world.World.redirect$onCallEntityUpdate$zmc000(World.java:5725)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP)
	Entity ID: 3338
	Entity Name: Nallack
	Entity's Exact location: 86.33, 85.00, 150.22
	Entity's Block location: World: (86,85,150), Chunk: (at 6,5,6 in 5,9; contains blocks 80,0,144 to 95,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:6099)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Nallack'/3338, l='MpServer', x=86.33, y=85.00, z=150.22]]
	Chunk stats: MultiplayerChunkCache: 399, 399
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (32,64,256), Chunk: (at 0,4,0 in 2,16; contains blocks 32,0,256 to 47,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 24235 game time, 34764 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 94 total; [EntitySkeleton['Skeleton'/3592, l='MpServer', x=86.50, y=43.00, z=152.50], EntityZombie['Zombie'/3849, l='MpServer', x=98.50, y=29.00, z=197.50], EntitySkeleton['Skeleton'/2571, l='MpServer', x=32.72, y=64.00, z=208.55], EntitySheep['Sheep'/3346, l='MpServer', x=101.50, y=64.00, z=127.50], EntitySheep['Sheep'/21, l='MpServer', x=35.01, y=63.00, z=204.43], EntitySheep['Sheep'/22, l='MpServer', x=31.73, y=64.00, z=203.80], EntitySheep['Sheep'/3350, l='MpServer', x=95.50, y=63.00, z=100.50], EntitySheep['Sheep'/23, l='MpServer', x=22.52, y=64.00, z=196.77], EntitySheep['Sheep'/3351, l='MpServer', x=88.50, y=65.00, z=101.50], EntitySheep['Sheep'/24, l='MpServer', x=25.78, y=64.00, z=195.71], EntitySheep['Sheep'/3352, l='MpServer', x=91.50, y=64.00, z=99.50], EntitySheep['Sheep'/25, l='MpServer', x=42.50, y=130.00, z=137.50], EntitySheep['Sheep'/3353, l='MpServer', x=93.50, y=64.00, z=99.50], EntitySheep['Sheep'/26, l='MpServer', x=41.50, y=121.00, z=136.50], EntitySkeleton['Skeleton'/3866, l='MpServer', x=19.50, y=78.00, z=163.50], EntityCreeper['Creeper'/4122, l='MpServer', x=70.50, y=42.00, z=146.50], EntitySheep['Sheep'/27, l='MpServer', x=41.50, y=121.00, z=136.50], EntitySheep['Sheep'/28, l='MpServer', x=40.50, y=120.00, z=136.50], EntitySpider['Spider'/2590, l='MpServer', x=86.50, y=69.00, z=218.50], EntityCreeper['Creeper'/2591, l='MpServer', x=88.50, y=69.00, z=215.50], EntitySheep['Sheep'/33, l='MpServer', x=70.73, y=73.00, z=137.50], EntitySheep['Sheep'/34, l='MpServer', x=81.41, y=71.00, z=122.82], EntitySheep['Sheep'/35, l='MpServer', x=84.74, y=70.00, z=135.20], EntitySheep['Sheep'/36, l='MpServer', x=85.26, y=70.00, z=132.51], EntityRabbit['Rabbit'/37, l='MpServer', x=73.50, y=69.00, z=222.50], EntityZombie['Zombie'/4133, l='MpServer', x=125.50, y=37.00, z=200.50], EntityRabbit['Rabbit'/38, l='MpServer', x=73.50, y=69.00, z=222.50], EntityRabbit['Rabbit'/39, l='MpServer', x=75.50, y=69.00, z=221.50], EntitySheep['Sheep'/44, l='MpServer', x=102.50, y=64.00, z=129.50], EntitySheep['Sheep'/45, l='MpServer', x=103.50, y=63.00, z=131.50], EntitySheep['Sheep'/46, l='MpServer', x=83.73, y=70.00, z=141.51], EntityCreeper['Creeper'/2609, l='MpServer', x=84.50, y=69.00, z=211.50], EntityCreeper['Creeper'/2610, l='MpServer', x=83.50, y=69.00, z=211.50], EntitySpider['Spider'/2611, l='MpServer', x=88.50, y=69.00, z=213.50], EntityZombie['Zombie'/2868, l='MpServer', x=83.50, y=51.00, z=205.50], EntitySpider['Spider'/2612, l='MpServer', x=84.50, y=69.00, z=215.50], EntityZombie['Zombie'/3636, l='MpServer', x=60.50, y=59.00, z=207.50], EntitySheep['Sheep'/52, l='MpServer', x=113.50, y=63.00, z=132.50], EntitySkeleton['Skeleton'/2613, l='MpServer', x=77.50, y=50.00, z=204.50], EntitySheep['Sheep'/67, l='MpServer', x=146.50, y=76.00, z=138.50], EntitySheep['Sheep'/68, l='MpServer', x=147.50, y=77.00, z=141.50], EntitySheep['Sheep'/69, l='MpServer', x=147.50, y=77.00, z=139.50], EntitySheep['Sheep'/70, l='MpServer', x=147.50, y=77.00, z=137.50], EntitySheep['Sheep'/71, l='MpServer', x=141.50, y=74.00, z=139.50], EntitySheep['Sheep'/72, l='MpServer', x=142.50, y=74.00, z=139.50], EntitySheep['Sheep'/73, l='MpServer', x=142.50, y=74.00, z=142.50], EntitySheep['Sheep'/74, l='MpServer', x=145.50, y=75.00, z=140.50], EntitySkeleton['Skeleton'/2636, l='MpServer', x=33.50, y=66.00, z=213.21], EntityZombie['Zombie'/3917, l='MpServer', x=87.50, y=36.00, z=101.50], EntityZombie['Zombie'/3918, l='MpServer', x=85.50, y=36.00, z=103.50], EntitySheep['Sheep'/79, l='MpServer', x=157.50, y=69.00, z=179.50], EntityEnderman['Enderman'/3919, l='MpServer', x=86.50, y=36.00, z=102.50], EntityItem['item.tile.mushroom'/2384, l='MpServer', x=90.88, y=33.00, z=158.65], EntitySheep['Sheep'/80, l='MpServer', x=153.50, y=70.00, z=176.50], EntitySheep['Sheep'/81, l='MpServer', x=157.50, y=70.00, z=175.50], EntityCreeper['Creeper'/3921, l='MpServer', x=142.50, y=23.00, z=206.50], EntitySheep['Sheep'/82, l='MpServer', x=159.50, y=69.00, z=175.50], EntitySkeleton['Skeleton'/3926, l='MpServer', x=38.50, y=20.00, z=134.50], EntitySkeleton['Skeleton'/3674, l='MpServer', x=20.50, y=49.00, z=214.50], EntitySkeleton['Skeleton'/3419, l='MpServer', x=40.50, y=25.00, z=213.50], EntityCreeper['Creeper'/3675, l='MpServer', x=56.50, y=21.00, z=156.50], EntityWitch['Witch'/3931, l='MpServer', x=95.50, y=40.00, z=163.50], EntityWitch['Witch'/3933, l='MpServer', x=91.12, y=39.00, z=161.47], EntityZombieVillager['Zombie Villager'/3934, l='MpServer', x=91.81, y=41.00, z=164.47], EntitySkeleton['Skeleton'/3938, l='MpServer', x=78.50, y=41.00, z=150.50], EntitySpider['Spider'/3431, l='MpServer', x=90.50, y=50.00, z=200.50], EntitySpider['Spider'/3687, l='MpServer', x=19.50, y=49.00, z=212.50], EntitySkeleton['Skeleton'/3691, l='MpServer', x=47.50, y=21.00, z=149.50], EntityCreeper['Creeper'/3693, l='MpServer', x=6.50, y=46.00, z=228.50], EntityZombie['Zombie'/3964, l='MpServer', x=51.50, y=22.00, z=176.50], EntityZombie['Zombie'/3709, l='MpServer', x=25.50, y=24.00, z=185.50], EntityCreeper['Creeper'/3971, l='MpServer', x=89.50, y=39.00, z=159.50], EntityItem['item.item.rustic.tomato_seeds'/3975, l='MpServer', x=136.22, y=63.00, z=86.38], GCEntityClientPlayerMP['Nallack'/3338, l='MpServer', x=86.33, y=85.00, z=150.22], EntitySkeleton['Skeleton'/3983, l='MpServer', x=87.50, y=43.00, z=148.50], EntitySpider['Spider'/3732, l='MpServer', x=68.50, y=51.00, z=168.50], EntityZombie['Zombie'/3479, l='MpServer', x=78.50, y=50.00, z=203.50], EntityZombie['Zombie'/3753, l='MpServer', x=44.50, y=22.00, z=153.50], EntityCreeper['Creeper'/3761, l='MpServer', x=36.11, y=72.00, z=168.46], EntitySkeleton['Skeleton'/3762, l='MpServer', x=54.50, y=57.00, z=211.50], EntitySkeleton['Skeleton'/4020, l='MpServer', x=94.50, y=40.00, z=143.50], EntityZombie['Zombie'/3776, l='MpServer', x=71.50, y=41.00, z=149.50], EntityCreeper['Creeper'/3525, l='MpServer', x=25.50, y=71.00, z=166.50], EntityZombie['Zombie'/4037, l='MpServer', x=105.50, y=35.00, z=201.50], EntityCreeper['Creeper'/3526, l='MpServer', x=19.56, y=74.00, z=167.85], EntityZombie['Zombie'/4041, l='MpServer', x=56.50, y=46.00, z=162.50], EntitySkeleton['Skeleton'/3541, l='MpServer', x=70.50, y=57.00, z=217.50], EntitySkeleton['Skeleton'/3800, l='MpServer', x=26.50, y=93.00, z=160.50], EntityCreeper['Creeper'/3547, l='MpServer', x=24.50, y=76.00, z=159.50], EntityCreeper['Creeper'/4064, l='MpServer', x=94.50, y=55.00, z=192.50], EntityZombie['Zombie'/3810, l='MpServer', x=91.50, y=50.00, z=196.50], EntitySpider['Spider'/3315, l='MpServer', x=99.50, y=36.00, z=207.50], EntityCreeper['Creeper'/3832, l='MpServer', x=26.50, y=26.00, z=111.50], EntityZombie['Zombie'/3326, l='MpServer', x=111.50, y=44.00, z=204.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2148165208 bytes (2048 MB) / 4060086272 bytes (3872 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 9, tcache: 71, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version           | Source                                            | Signature                                |
	|:------ |:------------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                 | 1.12.2            | minecraft.jar                                     | None                                     |
	| UCHIJA | mcp                       | 9.42              | minecraft.jar                                     | None                                     |
	| UCHIJA | FML                       | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                     | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | micdoodlecore             |                   | minecraft.jar                                     | None                                     |
	| UCHIJA | spongeapi                 | 7.1.0-366290f8    | spongeforge-1.12.2-2768-7.1.5.jar                 | None                                     |
	| UCHIJA | sponge                    | 1.12.2-7.1.5      | spongeforge-1.12.2-2768-7.1.5.jar                 | None                                     |
	| UCHIJA | spongeforge               | 1.12.2-2768-7.1.5 | spongeforge-1.12.2-2768-7.1.5.jar                 | None                                     |
	| UCHIJA | opencomputers|core        | 1.7.4.153         | minecraft.jar                                     | None                                     |
	| UCHIJA | appliedenergistics2       | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJA | baubles                   | 1.5.2             | Baubles-1.12-1.5.2.jar                            | None                                     |
	| UCHIJA | ic2                       | 2.8.109-ex112     | industrialcraft-2-2.8.109-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJA | jei                       | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| UCHIJA | forestry                  | 5.8.2.387         | forestry_1.12.2-5.8.2.387.jar                     | None                                     |
	| UCHIJA | binniecore                | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| UCHIJA | binniedesign              | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| UCHIJA | genetics                  | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| UCHIJA | botany                    | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| UCHIJA | extrabees                 | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| UCHIJA | extratrees                | 2.5.1.188         | binnie-mods-1.12.2-2.5.1.188.jar                  | None                                     |
	| UCHIJA | codechickenlib            | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | chickenchunks             | 2.4.1.73          | ChickenChunks-1.12.2-2.4.1.73-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | computercraft             | 1.80pr1           | ComputerCraft1.80pr1.jar                          | None                                     |
	| UCHIJA | discordchat               | 2.3.0             | DiscordChat-1.12.2-2.3.0.jar                      | None                                     |
	| UCHIJA | forgemultipartcbe         | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | microblockcbe             | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| UCHIJA | minecraftmultipartcbe     | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| UCHIJA | galacticraftcore          | 4.0.2.210         | GalacticraftCore-1.12.2-4.0.2.210.jar             | None                                     |
	| UCHIJA | galacticraftplanets       | 4.0.2.210         | Galacticraft-Planets-1.12.2-4.0.2.210.jar         | None                                     |
	| UCHIJA | gravisuite                | 3.1.0             | Gravitation+Suite-3.1.0.jar                       | None                                     |
	| UCHIJA | magicbees                 | 1.0               | MagicBees-1.12.2-3.1.10.jar                       | None                                     |
	| UCHIJA | mcmultipart               | 2.5.3             | MCMultiPart-2.5.3.jar                             | None                                     |
	| UCHIJA | mjrlegendslib             | 1.12.2-1.1.8      | MJRLegendsLib-1.12.2-1.1.8.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJA | mrtjpcore                 | 2.1.3.35          | MrTJPCore-1.12.2-2.1.3.35-universal.jar           | None                                     |
	| UCHIJA | nei                       | 2.4.2             | NotEnoughItems-1.12.2-2.4.2.240-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | opencomputers             | 1.7.4.153         | OpenComputers-MC1.12.2-1.7.4.153.jar              | None                                     |
	| UCHIJA | projectred-core           | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-Base.jar               | None                                     |
	| UCHIJA | projectred-integration    | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| UCHIJA | projectred-transmission   | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| UCHIJA | projectred-fabrication    | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-fabrication.jar        | None                                     |
	| UCHIJA | projectred-illumination   | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-lighting.jar           | None                                     |
	| UCHIJA | projectred-expansion      | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
	| UCHIJA | projectred-relocation     | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
	| UCHIJA | projectred-transportation | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
	| UCHIJA | projectred-exploration    | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-world.jar              | None                                     |
	| UCHIJA | rustic                    | 1.1.0             | rustic-1.1.0.jar                                  | None                                     |
	| UCHIJA | thaumcraft                | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
	| UCHIJA | rusticthaumaturgy         | 4.4a              | Rustic+Thaumaturgy-4.4a.jar                       | None                                     |
	| UCHIJA | thaumcomp                 | 0.4.4             | ThaumicComputers-MC1.12.2-0.4.4.jar               | None                                     |
	| UCHIJA | thaumicjei                | 1.5.8             | ThaumicJEI-1.12.2-1.5.8-26.jar                    | None                                     |
	| UCHIJA | thaumicenergistics        | 2.2.1             | thaumicenergistics-2.2.1.jar                      | None                                     |
	| UCHIJA | thaumicterminal           | 1.0.12            | ThaumicTerminal-1.0.12.jar                        | None                                     |
	| UCHIJA | worldedit                 | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
SpongeCoremod (spongeforge-1.12.2-2768-7.1.5.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 425.31' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 425.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,sponge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 425.31
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by nallack** [comment]
This happens when opening inventory, crashes seem to indicates it's sponge..
