### ISSUE TITLE
Fallen meteror 212 build.

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#3730]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2-212

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?: SSP

Any Galacticraft add-ons installed? please list all
- dev build GC4

Please provide screenshots / crash report / log / full modlist as needed
```
[00:20:50] [Server thread/ERROR] [FML]: A TileEntity type micdoodle8.mods.galacticraft.core.tile.TileEntityFallenMeteor has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException: null
	at net.minecraft.inventory.ItemStackHelper.saveAllItems(ItemStackHelper.java:30) ~[ItemStackHelper.class:?]
	at net.minecraft.inventory.ItemStackHelper.saveAllItems(ItemStackHelper.java:23) ~[ItemStackHelper.class:?]
	at micdoodle8.mods.galacticraft.core.tile.TileEntityInventory.writeToNBT(TileEntityInventory.java:77) ~[TileEntityInventory.class:?]
	at micdoodle8.mods.galacticraft.core.tile.TileEntityFallenMeteor.writeToNBT(TileEntityFallenMeteor.java:80) ~[TileEntityFallenMeteor.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeChunkToNBT(AnvilChunkLoader.java:414) [AnvilChunkLoader.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.saveChunk(AnvilChunkLoader.java:185) [AnvilChunkLoader.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.saveChunkData(ChunkProviderServer.java:214) [ChunkProviderServer.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java:242) [ChunkProviderServer.class:?]
	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1061) [WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:468) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:274) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:766) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

**Comment by micdoodle8** [comment]
Thanks, hope I got all the errors this time.
