### ISSUE TITLE
Bytecode injection incomplete at pl (2/4) runs into server crash

### ISSUE THREAD

**Issue by Nick-77ab2** [micdoodle8/Galacticraft#3752]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.190

Server-Kettle (this problem had not occurred without kettle, so probable cause?)

GC addon->Galacticraft Tweaker

Log only as crash-report was not generated:

[11:23:47] [main/INFO] [STDERR]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1741]: Potential problem: Galacticraft did not complete injection of bytecode into: pl (2 / 4)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: java.lang.reflect.InvocationTargetException
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:73)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:37)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at java.lang.Class.getMethod0(Unknown Source)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at java.lang.Class.getMethod(Unknown Source)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:23:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	... 6 more
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@6be422da from coremod AppleCore
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 15 more
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: java.lang.RuntimeException: EntityPlayer.addExhaustion call pattern (index=1) not found in net/minecraft/entity/player/EntityPlayer.func_70664_aZ
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at squeek.applecore.asm.module.ModuleExhaustingActions.patchSimpleAddExhaustionCall(ModuleExhaustingActions.java:129)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at squeek.applecore.asm.module.ModuleExhaustingActions.transform(ModuleExhaustingActions.java:30)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:42)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
[11:23:47] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	... 17 more

**I'm unsure what is fully at fault here, but when switching to a kettle server the incomplete bytecode injection is new.
edit: There's a possibility that it's applecore, but idk how switching to a different type of server can cause the mod to do that.**

**After trying a different version of the Server type, I found that the bytecode error persists, however it continues a bit before crashing again with the same error.**

[12:13:59] [main/INFO] [STDERR]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1741]: Potential problem: Galacticraft did not complete injection of bytecode into: pl (2 / 4)
[12:13:59] [main/INFO] [Quark ASM]: Transforming net.minecraft.entity.Entity
[12:13:59] [main/INFO] [Quark ASM]: Applying Transformation to method (Names [move, func_70091_d] Descriptor (Lnet/minecraft/entity/MoverType;DDD)V)
[12:13:59] [main/INFO] [Quark ASM]: Located Method, patching...
[12:13:59] [main/INFO] [Quark ASM]: Located patch target node INVOKEVIRTUAL net/minecraft/entity/Entity.func_184231_a (DZLnet/minecraft/block/state/IBlockState;Lnet/minecraft/util/math/BlockPos;)V
[12:13:59] [main/INFO] [Quark ASM]: Patch result: true
[12:13:59] [main/INFO] [Quark ASM]: Located Method, patching...
[12:13:59] [main/INFO] [Quark ASM]: Located patch target node INVOKEVIRTUAL net/minecraft/entity/Entity.func_145775_I ()V
[12:13:59] [main/INFO] [Quark ASM]: Patch result: true
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: java.lang.reflect.InvocationTargetException
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at java.lang.reflect.Method.invoke(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:73)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:37)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.getDeclaredMethods0(Native Method)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.privateGetMethodRecursive(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.getMethod0(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.getMethod(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: ... 6 more
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at java.lang.ClassLoader.loadClass(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at java.lang.ClassLoader.loadClass(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: ... 13 more
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@43cf5bff from coremod AppleCore
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: ... 15 more
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: java.lang.RuntimeException: EntityPlayer.addExhaustion call pattern (index=1) not found in net/minecraft/entity/player/EntityPlayer.func_70664_aZ
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: at squeek.applecore.asm.module.ModuleExhaustingActions.patchSimpleAddExhaustionCall(ModuleExhaustingActions.java:129)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: at squeek.applecore.asm.module.ModuleExhaustingActions.transform(ModuleExhaustingActions.java:30)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:42)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: ... 17 more

**Comment by Nick-77ab2** [comment]
There's a possibility that it's applecore, but idk how switching to a different type of server can cause the mod to do that.

**Comment by Nick-77ab2** [comment]
After trying a different version of the Server type, I found that the issue is definitely not caused by Galacticraft. Any help would be appreciated, but this thread can be closed as far as i know.

**Comment by MJRLegends** [comment]
Looks like your crash issues are with applecore too

**Comment by Nick-77ab2** [comment]
yea, i've been testing with other versions of kettle and the issue persists, but in different areas. I'll be filing an issue with them to see if they know what's going on

**Comment by MJRLegends** [comment]
Sounds like a kettle issue tbh

**Comment by Nick-77ab2** [comment]
It should be, if anything. They are in unstable right now, so I guess it would be expected.

**Comment by micdoodle8** [comment]
It looks like kettle and applecore are incompatible at the moment. Applecore is trying to modify the jump method of EntityPlayer and can't find a place to do it with Kettle installed.

I'd be surprised if this still crashes with Galacticraft removed, but if you want to test that I'll leave this open for a little while.

**Comment by Nick-77ab2** [comment]
Yes, sorry for the late response. I'll be checking that today, but I'm certain it has nothing to do with your mod and that kettle's issue with applecore is what caused the injection to fail. I'll get back to you as soon as i check.

**Comment by Nick-77ab2** [comment]
I can't actually run the pack without the mods in it, so I really can't check. However, I'm pretty certain that your mods have nothing to do with it. Thanks again for the help, I'll close the issue.
