### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by ZerqPlayz** [micdoodle8/Galacticraft#3757]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?

Any Galacticraft add-ons installed? please list all

Please provide screenshots / crash report / log / full modlist as needed

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

my game crashed for no reason while I was putting the electric arc furnace, I tried to enter the world again it still crashed

here is the crash report:
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.215.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 8/7/19 9:18 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.canProcess(TileEntityElectricFurnace.java:151)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.shouldUseEnergy(TileEntityElectricFurnace.java:336)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.shouldPullEnergy(TileBaseElectricBlock.java:47)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_73660_a(TileBaseElectricBlock.java:107)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.func_73660_a(TileEntityElectricFurnace.java:96)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.canProcess(TileEntityElectricFurnace.java:151)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.shouldUseEnergy(TileEntityElectricFurnace.java:336)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.shouldPullEnergy(TileBaseElectricBlock.java:47)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_73660_a(TileBaseElectricBlock.java:107)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace.func_73660_a(TileEntityElectricFurnace.java:96)

-- Block entity being ticked --
Details:
	Name: minecraft:gc electric furnace // micdoodle8.mods.galacticraft.core.tile.TileEntityElectricFurnace
	Block type: ID #294 (tile.machine_tiered // micdoodle8.mods.galacticraft.core.blocks.BlockMachineTiered // galacticraftcore:machine_tiered)
	Block data value: 12 / 0xC / 0b1100
	Block location: World: (-115,63,1690), Chunk: (at 13,3,10 in -8,105; contains blocks -128,0,1680 to -113,255,1695), Region: (-1,3; contains chunks -32,96 to -1,127, blocks -512,0,1536 to -1,255,2047)
	Actual block type: ID #294 (tile.machine_tiered // micdoodle8.mods.galacticraft.core.blocks.BlockMachineTiered // galacticraftcore:machine_tiered)
	Actual block data value: 12 / 0xC / 0b1100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: GalacticCraft Survival
	All players: 1 total; [GCEntityPlayerMP['ZerqPlayz'/96, l='GalacticCraft Survival', x=-114.82, y=63.00, z=1688.59]]
	Chunk stats: ServerChunkCache: 739 Drop: 0
	Level seed: -8030369116538831293
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-196,64,248), Chunk: (at 12,4,8 in -13,15; contains blocks -208,0,240 to -193,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1396883 game time, 1734449 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 34110 (now: false), thunder time: 136739 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 210127408 bytes (200 MB) / 666624000 bytes (635 MB) up to 7177764864 bytes (6845 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx6858M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                    | Signature                                |
	|:------ |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.211    | GalacticraftCore-1.12.2-4.0.2.215.jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.211    | Galacticraft-Planets-1.12.2-4.0.2.215.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.215.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['ZerqPlayz'/96, l='GalacticCraft Survival', x=-114.82, y=63.00, z=1688.59]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ZerqPlayz** [comment]
By the way, I am using the latest version of galacticraft

**Comment by MJRLegends** [comment]
Galacticraft version 215 isnt the latest at all 226 is.

**Comment by MJRLegends** [comment]
And updating to 226 will fix your issue

**Comment by ZerqPlayz** [comment]
ok thanks, but how?

**Comment by ZerqPlayz** [comment]
thanks

**Comment by MJRLegends** [comment]
Please close issue
