### ISSUE TITLE
Random crash after few seconds after loading a world

### ISSUE THREAD

**Issue by DudeimShrek** [micdoodle8/Galacticraft#3765]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10
Galacticraft version: 1.7-3.0.12.504

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP
Any Galacticraft add-ons installed? please list all
I installed Galaxy Space, but after the crash i deleted it and reinstalled Galacticraft alone, it didn't work.
Please provide screenshots / crash report / log / full modlist as needed

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 3
	at micdoodle8.mods.galacticraft.core.blocks.BlockLandingPad.func_149691_a(BlockLandingPad.java:74)
	at net.minecraft.block.Block.func_149673_e(Block.java:556)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9472)
	at net.minecraft.client.renderer.RenderBlocks.func_147736_d(RenderBlocks.java:6672)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4788)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:327)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:325)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2382)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1388)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by radfast** [comment]
The problem here is caused by you adding mods and then deleting mods (GalaxySpace) in an existing world.  You are not supposed to change mods after you started the world.  If you change mods, it can cause problems like this.

The problem here is that a GalaxySpace type of landing pad has been left in the world, even after you deleted the GalaxySpace mod.

You need to delete your world and start a new world.

Alternatively (if you know how) find the one chunk containing this landing pad and delete that chunk.
