### ISSUE TITLE
Telepad Caused Game Crash

### ISSUE THREAD

**Issue by Dopamaniac** [micdoodle8/Galacticraft#3768]
Minecraft version: 1.12.2
Galacticraft version: 4.0

SSP opened to LAN 

The Planets Addon

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 8/21/19 4:56 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.inventory.ItemStackHelper.func_191281_a(SourceFile:34)
	at net.minecraft.inventory.ItemStackHelper.func_191282_a(SourceFile:29)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityInventory.func_189515_b(TileEntityInventory.java:77)
	at micdoodle8.mods.galacticraft.core.energy.tile.EnergyStorageTile.func_189515_b(EnergyStorageTile.java:41)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalElectrical.func_189515_b(TileBaseUniversalElectrical.java:184)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_189515_b(TileBaseElectricBlock.java:153)
	at micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityTelepadFake.func_189515_b(TileEntityTelepadFake.java:138)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_189517_E_(TileBaseElectricBlock.java:162)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.inventory.ItemStackHelper.func_191281_a(SourceFile:34)
	at net.minecraft.inventory.ItemStackHelper.func_191282_a(SourceFile:29)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityInventory.func_189515_b(TileEntityInventory.java:77)
	at micdoodle8.mods.galacticraft.core.energy.tile.EnergyStorageTile.func_189515_b(EnergyStorageTile.java:41)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalElectrical.func_189515_b(TileBaseUniversalElectrical.java:184)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_189515_b(TileBaseElectricBlock.java:153)
	at micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityTelepadFake.func_189515_b(TileEntityTelepadFake.java:138)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_189517_E_(TileBaseElectricBlock.java:162)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: GalacticCraft
	All players: 1 total; [GCEntityPlayerMP['Player'/127, l='GalacticCraft', x=117.50, y=900.00, z=404.50]]
	Chunk stats: ServerChunkCache: 127 Drop: 0
	Level seed: 3033512181861716165
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 646369112 bytes (616 MB) / 1174405120 bytes (1120 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2795 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                | Signature                                |
	|:------ |:------------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                         | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                         | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2795.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2795 | forge-1.12.2-14.23.5.2795.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                         | None                                     |
	| LCHIJA | codechickenlib      | 3.2.2.353    | CodeChickenLib-1.12.2.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | galacticraftcore    | 4.0.2.231    | GalacticraftCore-1.12.2-4.0.2.231.jar | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.220    | Galacticraft-Planets-Mod-1.12.2.jar   | None                                     |
	| LCHIJA | jei                 | 4.15.0.268   | jei_1.12.2-4.15.0.268.jar             | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['Player'/127, l='GalacticCraft', x=117.50, y=900.00, z=404.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

Hello! When I attempted to use a telepad on the Moon, my game crashed, with a Exception Ticking World error, attempting to load the save caused a crash with the same error. I think if I were able to remove only Telepads from my version of the mod, I could get back into my save.

**Comment by marcus8448** [comment]
From the looks of your filenames, you seem to have downloaded Galacticraft Planets and MicdoodleCore from a illegal/non-official webpage, for example: "9minecraft". Chances are, the error you have posted will be solved by re-downloading Galacticraft from [the official site](https://micdoodle8.com/mods/galacticraft/downloads). Please checkout the organization [Stop Mod Reposts](https://stopmodreposts.org) for more info about these sites.
