### ISSUE TITLE
ClassNotFoundException: org.( ... ).world.gen.IMixinChunkProviderServer

### ISSUE THREAD

**Issue by electron93** [micdoodle8/Galacticraft#3788]
- Minecraft version: **1.12.2**
 - Forge version: **14.23.5.2838** (or **14.23.5.2846** on the test server)
 - Galacticraft version: **1.12.2-4.0.2.235**
 - **SpongeForge** version: **1.12.2-2838-7.1.7-RC3908**
 - Java version: **1.8.0_222/64-bit**

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? **Multiplayer**

Each time the server starts, it displays this error in the console.

**Error log:**

```
[00:23:34] [Server thread/INFO] [Galacticraft]: Galacticraft: activating IndustrialCraft2 compatibility features.
[00:23:34] [Server thread/INFO] [Galacticraft]: Galacticraft: activating BuildCraft Transport (Pipes) compatibility features.
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]: java.lang.ClassNotFoundException: org.spongepowered.common.interfaces.world.gen.IMixinChunkProviderServer
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at java.lang.Class.forName0(Native Method)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at java.lang.Class.forName(Class.java:264)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at micdoodle8.mods.galacticraft.core.util.CompatibilityManager.checkForCompatibleMods(CompatibilityManager.java:226)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at micdoodle8.mods.galacticraft.core.GalacticraftCore.postInit(GalacticraftCore.java:417)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at java.lang.reflect.Method.invoke(Method.java:498)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at java.lang.reflect.Method.invoke(Method.java:498)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at java.lang.reflect.Method.invoke(Method.java:498)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[00:23:34] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.util.CompatibilityManager:checkForCompatibleMods:229]:     at java.lang.Thread.run(Thread.java:748)
[00:23:34] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.NullPointerException
```

**Comment by radfast** [comment]
Thanks very much for reporting.  This will not be harming your server, the only issue it causes is that Galacticraft's AstroMiner may not be able to keep chunk loaded in the region where it is working (if no player is nearby).

Looks like Sponge changed the name of part of their code in a recent update, we'll find and fix it so we are compatible with all versions of Sponge.

Once again, don't worry about this too much, your players should still be able to play Galacticraft fine on your server.

**Comment by radfast** [comment]
Please try [new Galacticraft build 237](https://micdoodle8.com/mods/galacticraft/downloads) - that should fix this and hopefully not produce any new errors ... please let us know if it works.

To test it, try taking a rocket to the Moon or any other planet, or, for a full test, try setting an AstroMiner moving and then taking the player far away (more than 80 blocks), return to the AstroMiner after 10 minutes and see if it mined anything.

Would be good to know this is working OK for you.

---

@SteveKunG @BlesseNtumble @MJRLegends there is a breaking change here if you are currently using `CompatibilityManager.forceLoadChunksEnd()` in your mod, this now needs to be given a parameter which was the previous value.

**Comment by electron93** [comment]
@radfast yep, the error is gone.

Tested Astro Miner as you suggested, works.

<details><summary>Screenshots</summary><p>

![2019-09-10_14 29 14](https://user-images.githubusercontent.com/1076914/64610344-b505db00-d3d7-11e9-921a-533b8c7b0948.png)
![2019-09-10_14 30 16](https://user-images.githubusercontent.com/1076914/64610350-b8996200-d3d7-11e9-9cb7-9318852e162e.png)
![2019-09-10_14 30 50](https://user-images.githubusercontent.com/1076914/64610357-bafbbc00-d3d7-11e9-905e-42d18621b337.png)
![2019-09-10_15 03 35](https://user-images.githubusercontent.com/1076914/64612363-44ad8880-d3dc-11e9-83e8-5f695de56339.png)
![2019-09-10_14 49 31](https://user-images.githubusercontent.com/1076914/64618367-cb686280-d3e8-11e9-9f7f-836d7f62e36b.png)
![2019-09-10_14 44 22](https://user-images.githubusercontent.com/1076914/64612086-9efa1980-d3db-11e9-9212-2dc128e3a061.png)
</p></details>

**Comment by radfast** [comment]
nice, thank you for confirming!  and thanks for great screenshots - shows how rare the metal and cheese ores are on the Moon.

**Comment by MJRLegends** [comment]
@radfast thanks for the head up ping about the change
