### ISSUE TITLE
[1.12.2] Rendering crash with CodeChickenLib and heavy wires

### ISSUE THREAD

**Issue by AugiteSoul** [micdoodle8/Galacticraft#3797]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.237

Single player.
No addons installed.

Looking at a specific wire in my base makes the game crash - other minor rendering errors appear with the other heavy wires and arc lamps.

https://paste.ee/p/C57GI

**Comment by radfast** [comment]
This crash is in **MatterOverdrive** mod, not Galacticraft.

See these lines in the crash report:

    Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.isOutsideBuildHeight(World.java:225) ~[amu.class:?]
	at net.minecraft.world.World.getTileEntity(World.java:2384) ~[amu.class:?]
	at matteroverdrive.tile.TileEntityBoundingBox.getOwnerTile(TileEntityBoundingBox.java:118) ~[TileEntityBoundingBox.class:?]
	at matteroverdrive.tile.TileEntityBoundingBox.hasCapability(TileEntityBoundingBox.java:153) ~[TileEntityBoundingBox.class:?]

If reporting to the MatterOverdrive mod author, it may help to say that the calling code is this:

    tileEntity.hasCapability(net.minecraftforge.energy.CapabilityEnergy.ENERGY, sideFrom)

Obviously, that's very standard code.   There will be a Galacticraft tile - an aluminium wire - on the `sideFrom` side of the MatterOverdrive tile.

If you can figure out **which** MatterOverdrive tile your Aluminium Wire is connected to, from the wire coordinates (x:251, y:73, z:296) I'm sure that will be a big help to the MatterOverdrive devs.
