### ISSUE TITLE
EnergyUtil:initialiseIC2Methods Detects Ic2Classic as normal IC2

### ISSUE THREAD

**Issue by clienthax** [micdoodle8/Galacticraft#3800]
Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.224

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Sponge - SMP

Any Galacticraft add-ons installed? please list all
Galacticraft-Planets

Please provide screenshots / crash report / log / full modlist as needed

IC2Classic+1.12-1.5.4.4.jar

```
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: java.lang.ClassNotFoundException: ic2.core.energy.Tile
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at java.lang.Class.forName0(Native Method)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at java.lang.Class.forName(Class.java:264)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at micdoodle8.mods.galacticraft.core.energy.EnergyUtil.initialiseIC2Methods(EnergyUtil.java:702)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at micdoodle8.mods.galacticraft.core.energy.EnergyUtil.<clinit>(EnergyUtil.java:70)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalElectricalSource.getCapability(TileBaseUniversalElectricalSource.java:268)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.base.power.PowerHandlerUtil.getPowerInterface(PowerHandlerUtil.java:19)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.conduits.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:478)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.conduits.conduit.power.PowerConduitNetwork.addConduit(PowerConduitNetwork.java:62)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.conduits.conduit.power.PowerConduitNetwork.addConduit(PowerConduitNetwork.java:22)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.conduits.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:91)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.conduits.conduit.AbstractConduitNetwork.init(AbstractConduitNetwork.java:64)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.conduits.conduit.power.PowerConduitNetwork.init(PowerConduitNetwork.java:36)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.base.conduit.ConduitUtil.ensureValidNetwork(ConduitUtil.java:68)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.conduits.conduit.AbstractConduit.updateNetwork(AbstractConduit.java:462)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.conduits.conduit.AbstractConduit.updateEntity(AbstractConduit.java:397)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at crazypants.enderio.conduits.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:343)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:47)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4728)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlg000(WorldServer.java:4712)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at net.minecraft.world.World.func_72939_s(World.java:1835)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3930)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[micdoodle8.mods.galacticraft.core.energy.EnergyUtil:initialiseIC2Methods:757]: 	at net.minecraft.server.MinecraftServer.run(
```

**Comment by radfast** [comment]
Hopefully sorted in next build 238, please re-open if further issues.
