### ISSUE TITLE
Galacticraft wont start with GalaxySpace 

### ISSUE THREAD

**Issue by younox** [micdoodle8/Galacticraft#3811]
Minecraft version:1.12.2
Galacticraft version:4.0.2.237

Single Player and Multiplayer (Forge Server)

---------------------------------------------------------------------------------------------------------
Short:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GalaxySpace (galaxyspace)
----------------------------------------------------------------------------------------------------------
Full:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.237.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 10/13/19 10:54 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GalaxySpace (galaxyspace)
Caused by: java.lang.NoClassDefFoundError: galaxyspace/systems/SolarSystem/planets/mercury/dimension/WorldProviderMercury
	at galaxyspace.systems.SolarSystem.SolarSystemBodies.preInit(SolarSystemBodies.java:170)
	at galaxyspace.GalaxySpace.preInit(GalaxySpace.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: galaxyspace.systems.SolarSystem.planets.mercury.dimension.WorldProviderMercury
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: asmodeuscore/core/astronomy/dimension/IProviderFreeze
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more
Caused by: java.lang.ClassNotFoundException: asmodeuscore.core.astronomy.dimension.IProviderFreeze
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 492342080 bytes (469 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2781 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version             | Source                                        | Signature                                |
	|:----- |:------------------- |:------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2              | minecraft.jar                                 | None                                     |
	| LCH   | mcp                 | 9.42                | minecraft.jar                                 | None                                     |
	| LCH   | FML                 | 8.0.99.99           | forge-1.12.2-14.23.5.2781.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2781        | forge-1.12.2-14.23.5.2781.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore       |                     | minecraft.jar                                 | None                                     |
	| LCH   | bspkrscore          | 7.6.0.1             | [1.12]bspkrsCore-universal-7.6.0.1.jar        | None                                     |
	| LCH   | treecapitator       | 1.43.0              | [1.12]TreeCapitator-client-1.43.0.jar         | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.55       | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCH   | jei                 | 4.15.0.268          | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.12.0.157   | TConstruct-1.12.2-2.12.0.157.jar              | None                                     |
	| LCH   | galacticraftcore    | 4.0.2.237           | GalacticraftCore-1.12.2-4.0.2.237.jar         | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.237           | Galacticraft-Planets-1.12.2-4.0.2.237.jar     | None                                     |
	| LCH   | asmodeuscore        | 0.0.10              | AsmodeusCore-1.12.2-0.0.10.jar                | None                                     |
	| LCH   | ichunutil           | 7.2.2               | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | backtools           | 7.0.0               | Back-Tools-Mod-1.12.2.jar                     | None                                     |
	| LCH   | backpack            | 3.0.2               | backpack-3.0.2-1.12.2.jar                     | None                                     |
	| LCH   | betterstorage       | 3.0.0.2             | Better-Storage-Too-Mod-1.12.2.jar             | None                                     |
	| LCH   | bibliocraft         | 2.4.5               | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| LCH   | bookshelf           | 2.3.585             | Bookshelf-1.12.2-2.3.585.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | chococraft          | 0.9.1.52            | chococraft_1.12.1-0.9.1.52.jar                | None                                     |
	| LCH   | codechickenlib      | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | eplus               | 5.0.176             | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | extrabows           | v1.12.2 b6          | Extra-Bows-Mod-1.12.2.jar                     | None                                     |
	| LCE   | galaxyspace         | 2.0.3               | GalaxySpace-1.12.2-2.0.3+STABLE.jar           | None                                     |
	| LC    | placebo             | 1.6.0               | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LC    | hexxitgear          | 2.8.0               | Hexxit+Gear-1.12.2-2.8.0.jar                  | None                                     |
	| LC    | infernalmobs        | 1.7.6               | Infernal-Mobs-Mod-1.12.2.jar                  | None                                     |
	| LC    | lunatriuscore       | 1.2.0.42            | LunatriusCore-1.12.2.jar                      | None                                     |
	| LC    | lycanitesmobs       | 2.0.0.8 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.0.8.jar              | None                                     |
	| LC    | moreoverlays        | 1.15.1              | moreoverlays-1.15.1-mc1.12.2.jar              | None                                     |
	| LC    | nei                 | 2.4.3               | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | pcb                 | 1.5.0               | portablecraftbench-1.12.2-1.5.1.jar           | None                                     |
	| LC    | schematica          | 1.8.0.169           | Schematica-Mod-1.12.2.jar                     | None                                     |
	| LC    | spartanshields      | 1.5.4               | Spartan-Shields-Mod-1.12.2.jar                | None                                     |
	| LC    | xaerominimap        | 1.17.7              | Xaeros-Minimap-Mod-1.12.2.jar                 | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.237.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.35' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
----------------------------------------------------------------------------------------------------------
It starts but it crashes afterwards in the Forge loading screen.
Yes I downloaded from the official site.

**Comment by Gandalf360one** [comment]
Upate your GalaxySpace version (1.12.2-2.0.3) to the newest (1.12.2-2.0.10):
https://www.curseforge.com/minecraft/mc-mods/galaxy-space-addon-for-galacticraft/files

**Comment by younox** [comment]
If I use 2.0.10 it wont even open my Map

**Comment by MJRLegends** [comment]
Then report it to galaxyspace not here

**Comment by radfast** [comment]
I just spotted this in the crash report, should have seen it before:

    Caused by: java.lang.ClassNotFoundException: asmodeuscore.core.astronomy.dimension.IProviderFreeze

Looks like you need to update your asmodeuscore [to version 0.0.11](https://www.curseforge.com/minecraft/mc-mods/asmodeuscore/files).  asmodeuscore is a needed part of the GalaxySpace mod.

**Comment by pirdyBirdy** [comment]
> Upate your GalaxySpace version (1.12.2-2.0.3) to the newest (1.12.2-2.0.10): https://www.curseforge.com/minecraft/mc-mods/galaxy-space-addon-for-galacticraft/files

I did this and I still get the crash
