### ISSUE TITLE
Galactic Planets keeps crashing

### ISSUE THREAD

**Issue by Galacticfish** [micdoodle8/Galacticraft#3814]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2

SSP
Galactic Craft core
Forger(1.12.2)
MicdoodleCore

Downloaded from the correct website

Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/25/19 6:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Planets (galacticraftplanets)
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/planets/venus/tile/TileEntityCrashedProbe
	at micdoodle8.mods.galacticraft.planets.venus.VenusBlocks.initBlocks(VenusBlocks.java:37)
	at micdoodle8.mods.galacticraft.planets.venus.VenusModule.preInit(VenusModule.java:111)
	at micdoodle8.mods.galacticraft.planets.PlanetsProxy.preInit(PlanetsProxy.java:22)
	at micdoodle8.mods.galacticraft.planets.PlanetsProxyClient.preInit(PlanetsProxyClient.java:30)
	at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.preInit(GalacticraftPlanets.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.planets.venus.tile.TileEntityCrashedProbe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/tile/TileEntityInventory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.core.tile.TileEntityInventory
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 51 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 921117920 bytes (878 MB) / 1845493760 bytes (1760 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                            | Signature                                |
	|:----- |:------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                                     | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore       |                   | minecraft.jar                                     | None                                     |
	| LCH   | orbis-lib           | 0.2.0             | orbis-lib-1.12.2-0.2.0+build121.jar               | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | aether              | 0.2.5             | aether_ii-1.12.2-0.2.5+build121-universal.jar     | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | any_dimension_mod   | 1.3.4             | any_dimension_mod_v1.3.4.jar                      | None                                     |
	| LCH   | aquaculture         | 1.6.8             | Aquaculture-1.12.2-1.6.8.jar                      | None                                     |
	| LCH   | biomesoplenty       | 7.0.1.2439        | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar     | None                                     |
	| LCH   | better_diving       | 1.3.91            | BetterDiving-1.12.2-1.3.91.jar                    | None                                     |
	| LCH   | bibliocraft         | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCH   | chameleon           | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCH   | clumps              | 3.1.2             | Clumps-3.1.2.jar                                  | None                                     |
	| LCH   | codechickenlib      | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | controlling         | 3.0.7             | Controlling-3.0.7.jar                             | None                                     |
	| LCH   | coralreef           | 2.0               | CoralReef-2.5-1.12.2.jar                          | None                                     |
	| LCH   | ctm                 | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
	| LCH   | cucumber            | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                         | None                                     |
	| LCH   | cxlibrary           | 1.6.1             | cxlibrary-1.12.1-1.6.1.jar                        | None                                     |
	| LCH   | llibrary            | 1.7.19            | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | dragonmounts        | 1.12.2-1.6.2      | DragonMounts2-1.12.2-1.6.2.jar                    | None                                     |
	| LCH   | mocreatures         | 12.0.5            | DrZharks+MoCreatures+Mod-12.0.5.jar               | None                                     |
	| LCH   | exoticbirds         | 1.0               | Exotic Birds 1.12.2-2.2.1.jar                     | None                                     |
	| LCH   | jei                 | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCH   | twilightforest      | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar                  | None                                     |
	| LCH   | extrautils2         | 1.0               | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LCH   | familiarfauna       | 1.0.11            | FamiliarFauna-1.12.2-1.0.11.jar                   | None                                     |
	| LCH   | fastleafdecay       | v14               | FastLeafDecay-v14.jar                             | None                                     |
	| LCH   | forestry            | 5.8.1.322         | forestry_1.12.2-5.8.1.322.jar                     | None                                     |
	| LCH   | cfm                 | 6.3.0             | furniture-6.3.0-1.12.2.jar                        | None                                     |
	| LCH   | galacticraftcore    | 4.0.1.181         | Galacticraft-Mod-1.12.2.jar                       | None                                     |
	| LCE   | galacticraftplanets | 4.0.2.238         | Galacticraft-Planets-1.12.2-4.0.2.238.jar         | None                                     |
	| LC    | gravestone          | 1.10.1            | gravestone-1.10.1.jar                             | None                                     |
	| LC    | iceandfire          | 1.7.1             | iceandfire-1.7.1-1.12.2.jar                       | None                                     |
	| LC    | ichunutil           | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | inventorypets       | 2.0.1             | inventorypets-1.12-2.0.1.jar                      | None                                     |
	| LC    | ironbackpacks       | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| LC    | journeymap          | 1.12.2-5.5.4      | journeymap-1.12.2-5.5.4.jar                       | None                                     |
	| LC    | jaff                | 1.7_for_1.12      | Just-a-Few-Fish-Mod-1.12.jar                      | None                                     |
	| LC    | lex                 | 1.0.8             | LibEx-1.12.2-1.0.8.jar                            | None                                     |
	| LC    | mca                 | 6.0.0             | MCA-1.12.2-6.0.0-universal.jar                    | None                                     |
	| LC    | mjrlegendslib       | 1.12.2-1.1.8      | MJRLegendsLib-1.12.2-1.1.8.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LC    | morefurnaces        | 1.10.5            | MoreFurnaces-1.12.2-1.10.6.jar                    | None                                     |
	| LC    | mo_swords           | v5                | moSwords-1.12.2v5.jar                             | None                                     |
	| LC    | nex                 | 2.0.8             | NetherEx-1.12.2-2.0.8.jar                         | None                                     |
	| LC    | nei                 | 2.4.2             | NotEnoughItems-1.12.2-2.4.2.240-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | corerm              | 1.3.3             | RikMuldsCore_1.3.3.jar                            | None                                     |
	| LC    | roguelike           | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LC    | storagedrawers      | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
	| LC    | camping             | 2.4.3             | TheCampingMod_2.4.3.jar                           | None                                     |
	| LC    | theoneprobe         | 1.4.28            | theoneprobe-1.12-1.4.28.jar                       | None                                     |
	| LC    | torohealthmod       | 1.12.2-11         | torohealth-1.12.2-11.jar                          | None                                     |
	| LC    | undergroundbiomes   | 1.3.6             | UndergroundBiomesConstructs-1.12-1.3.6.jar        | None                                     |
	| LC    | veinminer           | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LC    | veinminermodsupport | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LC    | worldedit           | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LC    | zoocraftdiscoveries | 1.0               | Zoocraft Discoveries 1.12.2-1.3.0.jar             | None                                     |
	| LC    | phosphor-lighting   | 1.12.2-0.2.6      | phosphor-1.12.2-0.2.6+build50.jar                 | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

**Comment by marcus8448** [comment]
From the looks of your filenames, you seem to have downloaded Galacticraft's files from a _illegal_ website, for example: "9minecraft". Chances are, the error you have posted will be solved by replacing your current Galacticraft files with ones from [the official site](https://micdoodle8.com/mods/galacticraft/downloads). Please checkout the organization [Stop Mod Reposts](https://stopmodreposts.org) for more info about these sites.

**Comment by radfast** [comment]
thank you marcus8448, great info :)
