### ISSUE TITLE
LucraftCore/HeroesExpansion issue - game crashes on load

### ISSUE THREAD

**Issue by ConnorSimp** [micdoodle8/Galacticraft#3819]
Something to do with oxygen?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  Regeneration (Regeneration-1.12.2-2.0.2.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  craftfallessentials (CraftfallEssentials-1.12.2-1.2.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  pymtech (PymTech-1.12.2-1.0.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.8.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 11/3/19 7:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/event/oxygen/GCCoreOxygenSuffocationEvent$Pre
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/event/oxygen/GCCoreOxygenSuffocationEvent$Pre
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.api.event.oxygen.GCCoreOxygenSuffocationEvent$Pre
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 676872936 bytes (645 MB) / 1293942784 bytes (1234 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version           | Source                                    | Signature                                |
	|:----- |:-------------------- |:----------------- |:----------------------------------------- |:---------------------------------------- |
	| LC    | minecraft            | 1.12.2            | minecraft.jar                             | None                                     |
	| LC    | mcp                  | 9.42              | minecraft.jar                             | None                                     |
	| LC    | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | micdoodlecore        |                   | minecraft.jar                             | None                                     |
	| LC    | jei                  | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                 | None                                     |
	| LC    | quark                | r1.6-177          | Quark-r1.6-177.jar                        | None                                     |
	| LC    | autoreglib           | 1.3-32            | AutoRegLib-1.3-32.jar                     | None                                     |
	| LC    | chiselsandbits       | 14.33             | chiselsandbits-14.33.jar                  | None                                     |
	| LC    | ftblib               | 5.4.3.141         | FTBLib-5.4.3.141.jar                      | None                                     |
	| LC    | ftbutilities         | 5.4.0.108         | FTBUtilities-5.4.0.108.jar                | None                                     |
	| LE    | lucraftcore          | 1.12.2-2.4.8      | LucraftCore-1.12.2-2.4.8.jar              | None                                     |
	| L     | heroesexpansion      | 1.12.2-1.3.5      | HeroesExpansion-1.12.2-1.3.5.jar          | None                                     |
	| L     | craftfallessentials  | 1.2.2             | CraftfallEssentials-1.12.2-1.2.2.jar      | None                                     |
	| L     | ctm                  | MC1.12.2-1.0.0.29 | CTM-MC1.12.2-1.0.0.29.jar                 | None                                     |
	| L     | custommainmenu       | 2.0.9             | CustomMainMenu-MC1.12.2-2.0.9.jar         | None                                     |
	| L     | customnpcs           | 1.12              | CustomNPCs_1.12.2-(01Oct19).jar           | None                                     |
	| L     | galacticraftcore     | 4.0.2.238         | GalacticraftCore-1.12.2-4.0.2.238.jar     | None                                     |
	| L     | galacticraftplanets  | 4.0.2.238         | Galacticraft-Planets-1.12.2-4.0.2.238.jar | None                                     |
	| L     | pymtech              | 1.12.2-1.0.2      | PymTech-1.12.2-1.0.2.jar                  | None                                     |
	| L     | regeneration         | 2.0.2             | Regeneration-1.12.2-2.0.2.jar             | None                                     |
	| L     | resourceloader       | 1.5.3             | ResourceLoader-MC1.12.1-1.5.3.jar         | None                                     |
	| L     | roguelike            | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar        | None                                     |
	| L     | star-tech            | 1.1.1             | star-tech-1.1.1.jar                       | None                                     |
	| L     | the-fifth-world      | 0.5               | the-fifth-world-0.5.jar                   | None                                     |
	| L     | immersiveengineering | 0.12-92           | ImmersiveEngineering-0.12-92.jar          | None                                     |
	| L     | weeping-angels       | 1.12.2-39         | weeping-angels-39.jar                     | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Regeneration (Regeneration-1.12.2-2.0.2.jar)
  me.swirtzly.regeneration.asm.RegenClassTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
craftfallessentials (CraftfallEssentials-1.12.2-1.2.2.jar)
  com.hydrosimp.craftfallessentials.core.CEClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
pymtech (PymTech-1.12.2-1.0.2.jar)
  lucraft.mods.pymtech.core.PymTechClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.8.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.08' Renderer: 'GeForce GTX 1070/PCIe/SSE2'

**Comment by marcus8448** [comment]
Bug with LucraftCore/HeroesExpansion see #3705 .

**Comment by radfast** [comment]
Thanks @marcus8448 , I was going to say I thought we saw this issue before :)

**Comment by ConnorSimp** [comment]
It appears to be something to do with Oxygen. With HE we cancel the oxygen suffocation event from GC if you have the GOT powers

**Comment by radfast** [comment]
hey @ConnorSimp  thanks for looking in

OK I re-opened this for more investigation.

Can you point me to the event cancellation code so I can take a closer look?

Our event is [here](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/event/oxygen/GCCoreOxygenSuffocationEvent.java#L32)

**Comment by ConnorSimp** [comment]
It's alright man. Thanks for offering anyway! It's mostly something on our end (I'm not actually a developer. I just do sounds and ideas and such)

**Comment by radfast** [comment]
OK, I'll close this again and flag "Not a Galacticraft issue" for now.

If you or one of the HE developers wants me to re-open this, please just comment here and I'll see it (you can comment on a closed issue).  Or start a new issue or pull request.

**Comment by ConnorSimp** [comment]
Will do man! Thanks again :D
