### ISSUE TITLE
ic2 + Galacticraft: java.lang.IllegalStateException: invalid load state: 2

### ISSUE THREAD

**Issue by electron93** [micdoodle8/Galacticraft#3825]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.238
IndustrialCraft 2 version: 2.8.187-ex112

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP, **Sponge**

```
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]: java.lang.reflect.InvocationTargetException
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at java.lang.reflect.Method.invoke(Method.java:498)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed.onTick(TileCableIC2Sealed.java:75)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at ic2.core.TickHandler.processUpdates(TickHandler.java:148)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at ic2.core.TickHandler.onWorldTick(TickHandler.java:35)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1252)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1202)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at java.lang.Thread.run(Thread.java:748)
[STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.IllegalStateException: invalid load state: 2
[STDERR]: [java.lang.Throwable:printStackTrace:635]:    at ic2.core.block.TileEntityBlock.onLoaded(TileEntityBlock.java:183)
[STDERR]: [java.lang.Throwable:printStackTrace:635]:    at ic2.core.block.wiring.TileEntityCable.onLoaded(TileEntityCable.java:142)
[STDERR]: [java.lang.Throwable:printStackTrace:635]:    ... 16 more
```

**Comment by MJRLegends** [comment]
You just need to update Galacticraft

**Comment by electron93** [comment]
@MJRLegends updated Galacticraft, it did not help.

**Comment by MJRLegends** [comment]
Is the error the same? As i know they did some ic2 changes recently very similar to this error shown above

**Comment by electron93** [comment]
Yes, exactly the same.

```
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]: java.lang.reflect.InvocationTargetException
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at java.lang.reflect.Method.invoke(Method.java:498)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed.onTick(TileCableIC2Sealed.java:75)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at ic2.core.TickHandler.processUpdates(TickHandler.java:148)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at ic2.core.TickHandler.onWorldTick(TickHandler.java:35)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1252)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1202)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at java.lang.Thread.run(Thread.java:748)
[STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.IllegalStateException: invalid load state: 2
[STDERR]: [java.lang.Throwable:printStackTrace:635]:    at ic2.core.block.TileEntityBlock.onLoaded(TileEntityBlock.java:183)
[STDERR]: [java.lang.Throwable:printStackTrace:635]:    at ic2.core.block.wiring.TileEntityCable.onLoaded(TileEntityCable.java:142)
[STDERR]: [java.lang.Throwable:printStackTrace:635]:    ... 17 more
```

Code that throws an exception (`ic2.core.block.TileEntityBlock`):
![2019-11-13_20-17-54](https://user-images.githubusercontent.com/1076914/68790049-a6e26e00-0657-11ea-9bdf-357f5858be62.png)

![2019-11-13_20-54-35](https://user-images.githubusercontent.com/1076914/68790165-d5f8df80-0657-11ea-95be-91d3057445f5.png)

**Comment by electron93** [comment]
@MJRLegends and after upgrading to build 238, I get errors every time the server starts:

```
[TIME] [Server thread/INFO] [FML]: Holder lookups applied
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/refinery: Task Advancement{parentId=galacticraftcore:galacticraft/oil, display=net.minecraft.advancements.DisplayInfo@223099a, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={refinery=net.minecraft.advancements.Criterion@2aca3c7d}, requirements=[[refinery]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/spin_thruster: Task Advancement{parentId=galacticraftcore:galacticraft/create_space_station, display=net.minecraft.advancements.DisplayInfo@28f8ffee, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={spin_thruster=net.minecraft.advancements.Criterion@53aa1758}, requirements=[[spin_thruster]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/rocket_fuel: Task Advancement{parentId=galacticraftcore:galacticraft/refinery, display=net.minecraft.advancements.DisplayInfo@64beb2d1, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={fuel_bucket=net.minecraft.advancements.Criterion@672d79c9}, requirements=[[fuel_bucket]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/moon: Task Advancement{parentId=galacticraftcore:galacticraft/launch_rocket, display=net.minecraft.advancements.DisplayInfo@7c09409a, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={traveled_to_moon=net.minecraft.advancements.Criterion@70669de3}, requirements=[[traveled_to_moon]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/key_t1: Task Advancement{parentId=galacticraftcore:galacticraft/moon_dungeon, display=net.minecraft.advancements.DisplayInfo@6f8c8a31, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={got_key=net.minecraft.advancements.Criterion@2bc19ba6}, requirements=[[got_key]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/moon_buggy_schematic: Task Advancement{parentId=galacticraftcore:galacticraft/key_t1, display=net.minecraft.advancements.DisplayInfo@422fa896, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={got_schematic=net.minecraft.advancements.Criterion@651407de}, requirements=[[got_schematic]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/moon_buggy: Task Advancement{parentId=galacticraftcore:galacticraft/moon_buggy_schematic, display=net.minecraft.advancements.DisplayInfo@e114bf5, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={got_buggy=net.minecraft.advancements.Criterion@4b7e871e}, requirements=[[got_buggy]]}
[TIME] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 554 advancements
[TIME] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 8 advancement trees
...
[TIME] [Server thread/INFO] [Sponge]: Loading world [world_name] (minecraft:overworld/0)
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/refinery: Task Advancement{parentId=galacticraftcore:galacticraft/oil, display=net.minecraft.advancements.DisplayInfo@bf27e9b, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={refinery=net.minecraft.advancements.Criterion@5a28fdf7}, requirements=[[refinery]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/spin_thruster: Task Advancement{parentId=galacticraftcore:galacticraft/create_space_station, display=net.minecraft.advancements.DisplayInfo@5d4f8a0e, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={spin_thruster=net.minecraft.advancements.Criterion@40151315}, requirements=[[spin_thruster]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/rocket_fuel: Task Advancement{parentId=galacticraftcore:galacticraft/refinery, display=net.minecraft.advancements.DisplayInfo@71db4e4c, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={fuel_bucket=net.minecraft.advancements.Criterion@19be66d9}, requirements=[[fuel_bucket]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/moon: Task Advancement{parentId=galacticraftcore:galacticraft/launch_rocket, display=net.minecraft.advancements.DisplayInfo@37574f1c, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={traveled_to_moon=net.minecraft.advancements.Criterion@5d356f81}, requirements=[[traveled_to_moon]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/key_t1: Task Advancement{parentId=galacticraftcore:galacticraft/moon_dungeon, display=net.minecraft.advancements.DisplayInfo@678d653, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={got_key=net.minecraft.advancements.Criterion@7047e87a}, requirements=[[got_key]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/moon_buggy_schematic: Task Advancement{parentId=galacticraftcore:galacticraft/key_t1, display=net.minecraft.advancements.DisplayInfo@41350e85, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={got_schematic=net.minecraft.advancements.Criterion@efe2ae1}, requirements=[[got_schematic]]}
[TIME] [Server thread/ERROR] [minecraft/AdvancementList]: Couldn't load advancement galacticraftcore:galacticraft/moon_buggy: Task Advancement{parentId=galacticraftcore:galacticraft/moon_buggy_schematic, display=net.minecraft.advancements.DisplayInfo@415fae69, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={got_buggy=net.minecraft.advancements.Criterion@3e092d81}, requirements=[[got_buggy]]}
[TIME] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 554 advancements
...
```

**Comment by radfast** [comment]
Thanks for reporting.  Since I aim to have 100% compatibility with IC2 I'll treat this as priority.

Please let me know **exactly which IC2 version you are using**  - it's fairly confusing with IndustrialCraft, IC2 Classic, etc.

**Comment by electron93** [comment]
@radfast I'm using IndustrialCraft 2 v2.8.187-ex112.

**Comment by radfast** [comment]
Thank you again for reporting.  This issue is fixed in the latest Galacticraft build 243.
[Temporary download link](https://ci.micdoodle8.com/job/Galacticraft-1.12/243/)  -  hopefully this will soon be on the main downloads page too.

**Comment by electron93** [comment]
@radfast Updated to version 4.0.2.243, the same exceptions appear. Sorry for the late feedback.

<details>
<summary>Exception</summary>

```
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]: java.lang.reflect.InvocationTargetException
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at java.lang.reflect.Method.invoke(Method.java:498)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed.onTick(TileCableIC2Sealed.java:75)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at ic2.core.TickHandler.processUpdates(TickHandler.java:148)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at ic2.core.TickHandler.onWorldTick(TickHandler.java:35)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1253)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1203)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[STDERR]: [micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed:onTick:79]:         at java.lang.Thread.run(Thread.java:748)
[STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.IllegalStateException: invalid load state: 2
[STDERR]: [java.lang.Throwable:printStackTrace:635]:    at ic2.core.block.TileEntityBlock.onLoaded(TileEntityBlock.java:183)
[STDERR]: [java.lang.Throwable:printStackTrace:635]:    at ic2.core.block.wiring.TileEntityCable.onLoaded(TileEntityCable.java:142)
[STDERR]: [java.lang.Throwable:printStackTrace:635]:    ... 17 more
```

```
> sponge mods ic2
[Server thread/INFO] [minecraft/DedicatedServer]: IndustrialCraft 2 v2.8.187-ex112
> sponge mods galacticraftcore
[Server thread/INFO] [minecraft/DedicatedServer]: Galacticraft Core v4.0.2.243
```
</details>
