### ISSUE TITLE
Game crash upon launch 

### ISSUE THREAD

**Issue by CarltonPBanks** [micdoodle8/Galacticraft#3842]
Minecraft version: 1.6.4 
Galacticraft Version: Galacticraft-1.6.4-2.0.14.1098

Crashes upon launch. (intended for smp tho)
(Galacticraft gotten from site (latest))

So me and a few friends decided to make a new modded server w galacticraft included in some of the downloads, and whenever I launch a "loaderexception" error message pops up.
It only occurs when the galacticraft mods/core are in the folder, excluding it allows the game to launch and run smoothly, no issues.
PepeHands

Full crash report 

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/6/19 7:21 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:700)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:249)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ExceptionInInitializerError
	at micdoodle8.mods.galacticraft.core.client.ClientProxyCore.registerHandlers(ClientProxyCore.java:262)
	at micdoodle8.mods.galacticraft.core.client.ClientProxyCore.init(ClientProxyCore.java:213)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.init(GalacticraftCore.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:699)
	... 10 more
Caused by: java.lang.NumberFormatException: For input string: "minecraft"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at micdoodle8.mods.galacticraft.core.tick.GCCoreTickHandlerClient.<clinit>(GCCoreTickHandlerClient.java:95)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 443499864 bytes (422 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.50.1,345 Minecraft Forge 9.11.1.1345 Optifine OptiFine_1.6.4_HD_U_C8 40 mods loaded, 40 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{6.4.50.1,345} [Forge Mod Loader] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{9.11.1.1345} [Minecraft Forge] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NotEnoughItems{1.6.1.9} [Not Enough Items] (NotEnoughItems-1.6.4-1.6.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	bspkrsCore{v5.3(1.6.4)} [bspkrsCore] (1.6.4bspkrsCorev5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized
	TreeCapitator{Forge 1.6.4.r06} [Treecapitator] (1.6.4TreeCapitator.Forge.1.6.4.r06.Universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArchimedesShipsMod{1.6.2 v1.4.4} [Archimedes' Ships] (ArchimedesShipsMod1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized
	Artifice{1.6.4R1.1.3} [Artifice] (Artifice-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArtificeCompat|EE3{1.6.4R1.1.3} [Artifice Compat: EE3] (Artifice-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArtificeCompat|Forestry{1.6.4R1.1.3} [Artifice Compat: Forestry] (Artifice-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArtificeCompat|Vanilla{1.6.4R1.1.3} [Artifice Compat: Vanilla] (Artifice-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArtificeCompat|MFR{1.6.4R1.1.3} [Artifice Compat: MFR] (Artifice-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Core{4.2.1} [BuildCraft] (BuildCraftMod1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArtificeCompat|Buildcraft{1.6.4R1.1.3} [Artifice Compat: Buildcraft] (Artifice-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArtificeCompat|ForgeMicroblock{1.6.4R1.1.3} [Artifice Compat: ForgeMicroblock] (Artifice-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArtificeCompat|Thaumcraft{1.6.4R1.1.3} [Artifice Compat: Thaumcraft] (Artifice-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	IC2{2.0.397-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AtomicScience{1.0.0} [Atomic Science] (Atomic_Science_v1.0.0.145.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Builders{4.2.1} [BC Builders] (BuildCraftMod1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Energy{4.2.1} [BC Energy] (BuildCraftMod1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Factory{4.2.1} [BC Factory] (BuildCraftMod1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Transport{4.2.1} [BC Transport] (BuildCraftMod1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Silicon{4.2.1} [BC Silicon] (BuildCraftMod1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BCTools{1.4-a-15} [Buildcraft Tools] (bcTools-v1.4-a-15.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BiomesOPlenty{1.1.1} [Biomes O' Plenty] (BiomesOPlenty-universal-1.6.4-1.1.1.48.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CakeIsALie{1.6.2} [CakeIsALie Mod] (CakeIsALie_mod_1-6-21.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized
	ChickenShed{1.1.2} [Chicken Shed] (ChickenShed-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized
	DamageIndicatorsMod{2.9.2.4} [Damage Indicators] (Damage-Indicators-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized
	GalacticraftCore{2.0.14} [Galacticraft Core] (Galacticraft-1.6.4-2.0.14.1098.jar) Unloaded->Constructed->Pre-initialized->Errored
	GalacticraftMars{2.0.14} [Galacticraft Mars] (Galacticraft-Planets-1.6.4-2.0.14.1098.jar) Unloaded->Constructed->Pre-initialized->Errored
	Hats{2.1.8} [Hats] (Hats2.1.8.zip) Unloaded->Constructed->Pre-initialized->Initialized
	cfm{3.3.2} [§6MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Mystcraft{0.10.13.01} [Mystcraft] (mystcraft-uni-1.6.4-0.10.13.01.zip) Unloaded->Constructed->Pre-initialized->Initialized
	mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap] (ReisMinimap1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized
	DarrenPR_RottenFleshToLeather{1.0.0} [Rotten Flesh to Leather] (RottenFleshToLeather_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized
	TConstruct{1.6.4_1.4.6d1} [Tinkers' Construct] (TConstructMod1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR] (TConstructMod1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	tuxweapons{0.6} [TuxWeapons] (TuxWeapons-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized

All mods in folder ss

![image](https://user-images.githubusercontent.com/58601586/70339131-55e12680-185f-11ea-97d7-35378aaa398d.png)

Please and thanks o/

**Comment by MJRLegends** [comment]
MC 1.6.4 is years and years old, and no longer supported

**Comment by MJRLegends** [comment]
Double of #2281 also

**Comment by CarltonPBanks** [comment]
> MC 1.6.4 is years and years old, and no longer supported

Thanks ig
