### ISSUE TITLE
Exceptions thrown by BlockGrating when dummied galacticraftcore:grating registries are removed

### ISSUE THREAD

**Issue by database64128** [micdoodle8/Galacticraft#3862]
Minecraft version: 1.12.2
Galacticraft version: 239
Forge 2847
SpongeForge 7.1.7 RC3928

Any Galacticraft add-ons installed? please list all
Extra Planets

Some galacticraftcore:grating block registries are dummied in level.dat. If I remove these dummied registries, when a player joins the server, the mod keeps throwing exceptions:
```
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: java.lang.Exception: Stack trace
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at micdoodle8.mods.galacticraft.core.blocks.BlockGrating.func_180660_a(BlockGrating.java:255)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.block.Block.getDrops(Block.java:1320)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.block.Block.getDrops(Block.java:1300)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at mekanism.common.util.MinerUtils.getDrops(MinerUtils.java:97)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:240)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4728)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlh000(WorldServer.java:4712)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.world.World.func_72939_s(World.java:1838)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3930)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[05:18:51] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:1336]: 	at java.lang.Thread.run(Thread.java:748)
```
![image](https://user-images.githubusercontent.com/18757988/72201084-5e92d100-348b-11ea-9a92-792813f9068f.png)

The issue seems to be caused by https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockGrating.java where each exception was made to print a stack trace when thrown.

Also I don't understand the whole idea of BlockGrating. It seems to be a waste of block IDs. And yes, I know about NotEnoughIDs. But I don't want to use it because it could potentially break the compatibility with newer versions of Minecraft.

**Comment by radfast** [comment]
Maybe don't remove the registries then?
