### ISSUE TITLE
Moon problem (ExtraPlanets Moons too)

### ISSUE THREAD

**Issue by bartcreator** [micdoodle8/Galacticraft#3896]
Dear micdoodle8. I have a issue with moons and i think i know what is it, ID conflict, but i dont know how to solve it.

PS. Writing "Moon Problem" I mean "I cant go to Earth's Moon in 1, 2 and 3 tier rocket
and other moons from ExtraPlanets". 

PPS: More planets dont work, for sure Venus

MC version: 1.12.2

Forge: 14.23.5.2847

GC version: GalacticraftCore-1.12.2-4.0.2.243

Addons: ExtraPlanets-1.12.2-0.6.2
 
Game: Multiplayer (Aternos), Singleplayer

Side issue: During start i cant see darkness of space (normal day) and sometimes buged fly into space (Delayed space map loading).

Mod list:

[1.12]bspkrsCore-universal-7.6.0.1
[1.12]TreeCapitator-client-1.43.0
BetterFoliage-MC1.12-2.3.1
betternether-0.1.8.6
BiomesOPlenty-1.12.2-7.0.1.2444-universal
ChocolateQuestRepoured-1.12.2-1.5.2A
CodeChickenLib-1.12.2-3.2.3.358-universal
CoralReef-2.5-1.12.2
CustomMobSpawner-3.11.5
DrZharks MoCreatures Mod-12.0.5
DynamicLights-1.12.2
ExtraPlanets-1.12.2-0.6.2
Forgelin-1.8.4
furniture-6.3.1-1.12.2
GalacticraftCore-1.12.2-4.0.2.243
Galacticraft-Planets-1.12.2-4.0.2.243
gravestone-1.10.3
guns-0.15.3-1.12.2
inventorypets-1.12-2.0.3
InventoryTweaks-1.64%2Bdev.150
jei_1.12.2-4.15.0.293
journeymap-1.12.2-5.5.6
MicdoodleCore-1.12.2-4.0.2.243
MJRLegendsLib-1.12.2-1.1.9
NotEnoughItems-1.12.2-2.4.3.245-universal
obfuscate-0.2.6-1.12.2
OptiFine_1.12.2_HD_U_F5
Pam's HarvestCraft 1.12.2z
Reforged-0.7.5-1.12+
RoguelikeDungeons-1.12.2-1.8.0
tlskincape1.12.2-1.4
TravellersBackpack-1.12.2-1.0.20.20
twilightforest-1.12.2-3.10.1013-universal
 
[latest.log](https://github.com/micdoodle8/Galacticraft/files/4261798/latest.log)

**Comment by radfast** [comment]
Here is the problem in the log.  I do not know the cause (yet) ...   We will investigate some more.

To get the game working for now, you could try removing **ExtraPlanets**.

    java.lang.IndexOutOfBoundsException: Index: 48, Size: 48
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at micdoodle8.mods.galacticraft.api.GalacticraftRegistry.getDimensionTypeID(GalacticraftRegistry.java:311)
	at micdoodle8.mods.galacticraft.core.util.WorldUtil.registerPlanetClient(WorldUtil.java:630)
	at micdoodle8.mods.galacticraft.core.util.WorldUtil.decodePlanetsListClient(WorldUtil.java:1255)
	at micdoodle8.mods.galacticraft.core.network.ConnectionPacket.handle(ConnectionPacket.java:44)
	at micdoodle8.mods.galacticraft.core.network.ConnectionPacket.onFMLProxyPacketData(ConnectionPacket.java:152)
	at micdoodle8.mods.galacticraft.core.network.ConnectionPacket.onPacketData(ConnectionPacket.java:132)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_271_ConnectionPacket_onPacketData_ClientCustomPacketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:130)
	at net.minecraftforge.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:51)
	at net.minecraftforge.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:39)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274)
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:99)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)

**Comment by bartcreator** [comment]
> Here is the problem in the log. I do not know the cause (yet) ... We will investigate some more.
> 
> To get the game working for now, you could try removing **ExtraPlanets**.
> 
> ```
> java.lang.IndexOutOfBoundsException: Index: 48, Size: 48
> at java.util.ArrayList.rangeCheck(Unknown Source)
> at java.util.ArrayList.get(Unknown Source)
> at micdoodle8.mods.galacticraft.api.GalacticraftRegistry.getDimensionTypeID(GalacticraftRegistry.java:311)
> at micdoodle8.mods.galacticraft.core.util.WorldUtil.registerPlanetClient(WorldUtil.java:630)
> at micdoodle8.mods.galacticraft.core.util.WorldUtil.decodePlanetsListClient(WorldUtil.java:1255)
> at micdoodle8.mods.galacticraft.core.network.ConnectionPacket.handle(ConnectionPacket.java:44)
> at micdoodle8.mods.galacticraft.core.network.ConnectionPacket.onFMLProxyPacketData(ConnectionPacket.java:152)
> at micdoodle8.mods.galacticraft.core.network.ConnectionPacket.onPacketData(ConnectionPacket.java:132)
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_271_ConnectionPacket_onPacketData_ClientCustomPacketEvent.invoke(.dynamic)
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> at net.minecraftforge.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:130)
> at net.minecraftforge.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:51)
> at net.minecraftforge.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:39)
> at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
> at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274)
> at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:99)
> at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
> at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
> ```

I know what was a problem. For some reason Galacticraft and ExtraPlanets were interfering with Mo'Creatures and CustomMobSpawner. I turned off these mods and everything si ok now. Is there any way to make them work together?

**Comment by MJRLegends** [comment]
Probably dimension id conflicts so best to check their configs

**Comment by MJRLegends** [comment]
DrZharks MoCreatures Mod uses -17 dimension id, Uranus from ExtraPlanets also does it seems it causes weird conflict issues probably due to DrZharks MoCreatures Mod side.

Issue also caused by this https://github.com/MJRLegends/ExtraPlanets/issues/531

Solution: Change Dimension ID in config
