### ISSUE TITLE
Issue With Start up

### ISSUE THREAD

**Issue by TheOnlySmeme** [micdoodle8/Galacticraft#3906]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? please list all

Please provide screenshots / crash report / log / full modlist as needed

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244 (1).jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 3/15/20 1:29 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: Two space station types registered with the same home planet ID: -31
	at micdoodle8.mods.galacticraft.api.GalacticraftRegistry.registerSpaceStation(GalacticraftRegistry.java:213)
	at com.mjr.extraplanets.util.GCRecipeUtilities.addSpaceStationRecipe(GCRecipeUtilities.java:15)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.registerSatellitesRecipes(ExtraPlanets_Recipes.java:331)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.initOther(ExtraPlanets_Recipes.java:33)
	at com.mjr.extraplanets.ExtraPlanets.init(ExtraPlanets.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1934287264 bytes (1844 MB) / 2998403072 bytes (2859 MB) up to 7525629952 bytes (7177 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8073m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                                    | Signature                                |
	|:----- |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHI  | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| LCHI  | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCHI  | forge               | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCHI  | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| LCHI  | galacticraftcore    | 4.0.2.244    | GalacticraftCore-1.12.2-4.0.2.244.jar     | None                                     |
	| LCHI  | galacticraftplanets | 4.0.2.244    | Galacticraft-Planets-1.12.2-4.0.2.244.jar | None                                     |
	| LCHI  | asmodeuscore        | 0.0.12       | AsmodeusCore-1.12.2-0.0.12.jar            | None                                     |
	| LCHI  | buildcraftlib       | 7.99.24.5    | buildcraft-all-7.99.24.5.jar              | None                                     |
	| LCHI  | buildcraftcore      | 7.99.24.5    | buildcraft-all-7.99.24.5.jar              | None                                     |
	| LCHI  | buildcraftbuilders  | 7.99.24.5    | buildcraft-all-7.99.24.5.jar              | None                                     |
	| LCHI  | buildcrafttransport | 7.99.24.5    | buildcraft-all-7.99.24.5.jar              | None                                     |
	| LCHI  | buildcraftsilicon   | 7.99.24.5    | buildcraft-all-7.99.24.5.jar              | None                                     |
	| LCHI  | buildcraftcompat    | 7.99.24.5    | buildcraft-all-7.99.24.5.jar              | None                                     |
	| LCHI  | buildcraftenergy    | 7.99.24.5    | buildcraft-all-7.99.24.5.jar              | None                                     |
	| LCHI  | buildcraftfactory   | 7.99.24.5    | buildcraft-all-7.99.24.5.jar              | None                                     |
	| LCHI  | buildcraftrobotics  | 7.99.24.5    | buildcraft-all-7.99.24.5.jar              | None                                     |
	| LCHI  | mjrlegendslib       | 1.12.2-1.1.9 | MJRLegendsLib-1.12.2-1.1.9.jar            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHE  | extraplanets        | 1.12.2-0.6.1 | ExtraPlanets-1.12.2-0.6.1.jar             | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | galaxyspace         | 2.0.11       | GalaxySpace-1.12.2-2.0.11.jar             | None                                     |
	| LCH   | waila               | 1.8.26       | Hwyla-1.8.26-B41_1.12.2.jar               | None                                     |
	| LCH   | journeymap          | 1.12.2-5.7.0 | journeymap-1.12.2-5.7.0.jar               | None                                     |
	| LCH   | moreplanets         | 2.0.22       | More-Planets-1.12.2-2.0.22-GC238.jar      | b3468b224a74e296555ad7efeb35f482e6f445de |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244 (1).jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.59' Renderer: 'GeForce GTX 1660/PCIe/SSE2'

**Comment by MJRLegends** [comment]
Follow all three steps on here for Galaxyspace https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

**Comment by MJRLegends** [comment]
And you might aswell do it for more planet also to get some small fixes done there too

**Comment by TheOnlySmeme** [comment]
Ok thanks I'll write back if it doesn't work

**Comment by MJRLegends** [comment]
You should be good provided you follow all 3 steps :P

**Comment by TheOnlySmeme** [comment]
Ye it worked thanks mate
