### ISSUE TITLE
NullPointerException when placing any of IC2-compatible sealable cable blocks

### ISSUE THREAD

**Issue by Feliksas** [micdoodle8/Galacticraft#3922]
Minecraft version: 1.12.2, Forge 1.12.2-14.23.5.2847-universal
Galacticraft version: 1.12.2-4.0.2.244

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP, Texkit 3 modpack

Any Galacticraft add-ons installed? please list all
Galacticraft-Planets-1.12.2-4.0.2.244.

This occurs when placing blocks #7789/2, #7789/3, #7789/0 and #7789/5 (at least), corresponding IC2 cables do not connect to those.

IC2 version: IC2Classic+1.12-1.5.4.5

[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]: java.lang.NullPointerException
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed.func_180633_a(BlockEnclosed.java:434)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:186)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at micdoodle8.mods.galacticraft.core.items.ItemBlockEnclosed.func_180614_a(ItemBlockEnclosed.java:112)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:481)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.util.Util.func_181617_a(SourceFile:529)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[13:24:24] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.blocks.BlockEnclosed:func_180633_a:438]:   at java.lang.Thread.run(Thread.java:748)

**Comment by radfast** [comment]
Thank you for reporting.  I guess something changed in IC2, we'll get onto this.

**Comment by Prurite** [comment]
Similar issue here. When I put an Aluminum Wire next to an IC2 Storage Box NullPointerExceptions just spam my log to 400MB with 170,0000 errors, ~180 per sec, before I notify that!

Here's 1 section of the error log:
```
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: java.lang.NullPointerException
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at micdoodle8.mods.galacticraft.core.energy.EnergyUtil.getAdjacentPowerConnections(EnergyUtil.java:232)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at micdoodle8.mods.galacticraft.core.blocks.BlockTransmitter.func_176221_a(BlockTransmitter.java:214)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at micdoodle8.mods.galacticraft.core.blocks.BlockAluminumWire.func_185496_a(BlockAluminumWire.java:221)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:468)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.block.Block.func_180636_a(Block.java:631)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:473)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.world.World.func_147447_a(World.java:1087)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.entity.Entity.func_174822_a(Entity.java:1586)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:491)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1718)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:07:55] [Client thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.energy.EnergyUtil:getAdjacentPowerConnections:254]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Prurite** [comment]
@radfast Rechecked and it looks like it's a new NullPointer issue about compatibility with IC2? Shall I open a new issue for this?

**Comment by radfast** [comment]
No it's OK - no need for a new issue.   This issue is fine.  The IC2 version number is enough, now I can test this for myself.

**Comment by micdoodle8** [comment]
Should be fixed in the latest build, thanks!
