### ISSUE TITLE
Players disconnect with Internal Server Error when going on the Moon

### ISSUE THREAD

**Issue by Creiziol** [micdoodle8/Galacticraft#3945]
I am playing on my presonal modpack and when i went to the space i am disconected form server and 
i can't do anything 
Modlist:

AsmodeusCore | graciaplus9 | AsmodeusCore-1.12.2-0.0.13.jar |  
  | Astral Sorcery | HellFirePvP | astralsorcery-1.12.2-1.10.23.jar |  
  | Baubles | Azanor13 | Baubles-1.12-1.5.2.jar |  
  | Better Builder's Wands | Portablejim | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar |  
  | BetterFps | Guichaguri | BetterFps-1.4.8.jar |  
  | Biomes O' Plenty | Forstride | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar |  
  | Carry On | Tschipp | CarryOn MC1.12.2 v1.12.3.jar |  
  | Chameleon | Texelsaur | Chameleon-1.12-4.1.3.jar |  
  | Chisel | tterrag1098 | Chisel-MC1.12.2-1.0.2.45.jar |  
  | CodeChicken Lib 1.8.+ | covers1624 | CodeChickenLib-1.12.2-3.2.3.358-universal.jar |  
  | ConnectedTexturesMod | tterrag1098 | CTM-MC1.12.2-1.0.2.31.jar |  
  | Cooking for Blockheads | BlayTheNinth | CookingForBlockheads_1.12.2-6.5.0.jar |  
  | CraftTweaker | Jaredlll08 | CraftTweaker2-1.12-4.1.20.562.jar |  
  | Ender IO | CrazyPants_MC | EnderIO-1.12.2-5.1.55.jar |  
  | Ender Storage 1.8.+ | covers1624 | EnderStorage-1.12.2-2.4.6.137-universal.jar |  
  | EnderCore | tterrag1098 | EnderCore-1.12.2-0.5.73.jar |  
  | Extra Utilities | RWTema | extrautils2-1.12-1.9.9.jar |  
  | FoamFix​ | asiekierka | foamfix-0.10.10-1.12.2.jar |  
  | Galacticraft Tweaker | MJRLegends | GalacticraftTweaker-1.12.2-1.0.3.jar |  
  | Hwyla | TehNut | Hwyla-1.8.26-B41_1.12.2.jar |  
  | Immersive Engineering | BluSunrize | ImmersiveEngineering-0.12-92.jar |  
  | Industrial Craft | sfPlayer1 | industrialcraft-2-2.8.170-ex112.jar |  
  | Iron Backpacks | gr8pefish | IronBackpacks-1.12.2-3.0.8-12.jar |  
  | Iron Chests | ProgWML6 | ironchest-1.12.2-7.0.72.847.jar |  
  | JourneyMap | techbrew | journeymap-1.12.2-5.7.1.jar |  
  | Just Enough Items (JEI) | mezz | jei_1.12.2-4.15.0.291.jar |  
  | Logistics Pipes | mc_rs485 | logisticspipes-0.10.2.218.jar |  
  | Mantle | mDiyo | Mantle-1.12-1.3.3.55.jar |  
  | Mekanism | bradyaidanc | Mekanism-1.12.2-9.8.3.390.jar |  
  | Mekanism Generators | bradyaidanc | MekanismGenerators-1.12.2-9.8.3.390.jar |  
  | Mekanism Tools | bradyaidanc | MekanismTools-1.12.2-9.8.3.390.jar |  
  | Morpheus | Quetzi | Morpheus-1.12.2-3.5.106.jar |  
  | OpenBlocks | OpenMods | OpenBlocks-1.12.2-1.8.1.jar |  
  | OpenBlocks Elevator | vsngarcia | ElevatorMod-1.12.2-1.3.14.jar |  
  | OpenModsLib | OpenMods | OpenModsLib-1.12.2-0.12.2.jar |  
  | Patchouli | Vazkii | Patchouli-1.0-20.jar |  
  | Shadowfacts' Forgelin | ShadowfactsDev | Forgelin-1.8.4.jar |  
  | Storage Drawers | Texelsaur | StorageDrawers-1.12.2-5.4.1.jar |  
  | The Twilight Forest | Benimatic | twilightforest-1.12.2-3.10.1013-universal.jar |  
  | Tinker I/O | GKBm2011 | tinker_io-1.12.2-rw2.8.1a.jar |  
  | Tinkers Construct | mDiyo | TConstruct-1.12.2-2.13.0.183.jar |  
  | Wawla - What Are We Looking At | DarkhaxDev | Wawla-1.12.2-2.6.275.jar |  
  | YUNG's Better Caves | YUNGNICKYOUNG | bettercaves-1.12.2-2.0.jar

**Comment by micdoodle8** [comment]
We're going to need the internal server error to be able to help you. Do you have access to it?

**Comment by Creiziol** [comment]
were i can find it on serwer

**Comment by Creiziol** [comment]
After i clicking launch minecraft dissconects me from server but it's showing prepare for landing or taking one big leap

**Comment by Creiziol** [comment]
![image](https://user-images.githubusercontent.com/47253474/79957027-487caf80-8481-11ea-8f68-3eb8f43d302a.png)

**Comment by Creiziol** [comment]
Ther is export package from twich 
[Njalepszy Pack #2 fixed-1.0.2.zip](https://github.com/micdoodle8/Galacticraft/files/4514659/Njalepszy.Pack.2.fixed-1.0.2.zip)

**Comment by dj3520** [comment]
The file that is needed will be on the server in the logs folder.

**Comment by Creiziol** [comment]
[latest.log](https://github.com/micdoodle8/Galacticraft/files/4521493/latest.log)

**Comment by Creiziol** [comment]
[Netty Server IO #1/ERROR]: There was a critical exception handling a packet on channel asmodeuscore
java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.wrappers.ScheduledDimensionChange.<init>(Lnet/minecraft/entity/player/EntityPlayerMP;Ljava/lang/String;)V
	at asmodeuscore.core.network.packet.ACPacketSimple.handleServerSide(ACPacketSimple.java:280) ~[ACPacketSimple.class:?]
	at asmodeuscore.core.network.packet.AsmodeusPacketHandler.channelRead0(AsmodeusPacketHandler.java:28) ~[AsmodeusPacketHandler.class:?]
	at asmodeuscore.core.network.packet.AsmodeusPacketHandler.channelRead0(AsmodeusPacketHandler.java:13) ~[AsmodeusPacketHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:99) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147) [gw.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49) [gw.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleServerSideCustomPacket(NetworkDispatcher.java:452) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:264) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:443) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.local.LocalChannel.access$500(LocalChannel.java:49) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:397) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by micdoodle8** [comment]
Can you try using an old build (specifically build 244) of Galacticraft and see if that fixes the issue? Please report back, this is just for testing purposes.

**Comment by radfast** [comment]
Why is this:

    asmodeuscore.core.network.packet.ACPacketSimple.handleServerSide(ACPacketSimple.java:280) 

calling Galacticraft code at all, I don't get it?
