### ISSUE TITLE
Moon blocks not loading, and spawned in a wall at first.

### ISSUE THREAD

**Issue by Nozfera** [micdoodle8/Galacticraft#3972]
Hey, so today my friend and I had finally been able to get to the moon. However we seemed to have gotten there only to get out and appear to be stuck in a wall. We couldn't see anything other than mobs floating around us. We kept dying so I put us both into creative mode to try and figure out what was going on. I threw a bomb and it blew the invisible chunks around us up to be able to move around. Then random chunks would load in. I included a screenshot of that. Any help with this would be greatly appreciated. Thank you.

REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:

 1.12.2

Galacticraft version ("latest" is not a valid option):

 .277, I just looked to make sure and realized there is a newer version available, .277 was the latest when I created the server. I just tested it in single player and it worked fine. I'd like to avoid changing the server one to the new version as to not lose our world that we've spent a lot of time playing on. If anyone cant see what I'm doing wrong then I will do it.

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

It is a MP server, using GG Servers hosting.

Any Galacticraft add-ons installed? Please list all of them: 

I am not using any additional Galacticraft add-ons I believe. However, I am using these Mods in conjunction with Galacticraft. BuildCraft, Extra-Utilities, Mantle, and Tinkers Construct.

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site: This is the most I could pull from the server console that it would let me

14.05 20:19:43 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
14.05 20:19:43 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
14.05 20:19:43 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
14.05 20:19:43 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
14.05 20:19:43 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
14.05 20:19:43 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at java.lang.Thread.run(Thread.java:748)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: java.lang.NullPointerException
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.updateControllerSettings(EntityAutoRocket.java:595)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:454)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:177)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.core.entities.EntityTier1Rocket.func_70071_h_(EntityTier1Rocket.java:67)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.World.func_72866_a(World.java:1996)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.World.func_72870_g(World.java:1958)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.World.func_72939_s(World.java:1762)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
14.05 20:19:44 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at java.lang.Thread.run(Thread.java:748)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: java.lang.NullPointerException
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.updateControllerSettings(EntityAutoRocket.java:595)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:454)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:177)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.core.entities.EntityTier1Rocket.func_70071_h_(EntityTier1Rocket.java:67)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.World.func_72866_a(World.java:1996)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.World.func_72870_g(World.java:1958)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.World.func_72939_s(World.java:1762)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
14.05 20:19:45 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at java.lang.Thread.run(Thread.java:748)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: java.lang.NullPointerException
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.updateControllerSettings(EntityAutoRocket.java:595)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:454)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:177)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at micdoodle8.mods.galacticraft.core.entities.EntityTier1Rocket.func_70071_h_(EntityTier1Rocket.java:67)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.World.func_72866_a(World.java:1996)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.World.func_72870_g(World.java:1958)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.World.func_72939_s(World.java:1762)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
14.05 20:19:46 [Server] Server thread/INFO [STDERR]: [micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket:updateControllerSettings:640]: 	at java.lang.Thread.run(Thread.java:748)
14.05 20:21:49 [Server] Server thread/INFO [Galacticraft]: Found matching world (-28) for name: -28
14.05 20:21:49 [Server] Server thread/INFO [Galacticraft]: Server attempting to transfer player Mr_Diggity to dimension -28
14.05 20:21:49 [Server] Server thread/INFO Mr_Diggity has completed the challenge [The Moon!]
14.05 20:22:36 [Server] Server thread/INFO Mr_Diggity suffocated in a wall
14.05 20:23:00 [Multicraft] Auto-saving world...
14.05 20:23:00 [Server] Server thread/INFO Saving is already turned on
14.05 20:23:00 [Server] Server thread/INFO Saving...
14.05 20:23:00 [Server] Server thread/INFO [Server] World saved.
14.05 20:23:38 [Server] Server thread/INFO [Mr_Diggity: This is Mission Control, say again please? (To abandon mission, type /gchouston again to confirm.)]
14.05 20:23:44 [Server] Server thread/INFO [Galacticraft]: Server attempting to transfer player Mr_Diggity to dimension 0
14.05 20:23:44 [Server] Server thread/INFO [Mr_Diggity: OK, stand by, Mr_Diggity, teleporting to Overworld home position.]
14.05 20:31:51 [Server] Server thread/INFO Set MrDQ's game mode to Creative Mode
14.05 20:33:02 [Multicraft] Auto-saving world...
14.05 20:33:02 [Server] Server thread/INFO Saving is already turned on
14.05 20:33:02 [Server] Server thread/INFO Saving...
14.05 20:33:02 [Server] Server thread/INFO [Server] World saved.
14.05 20:36:26 [Server] Server thread/INFO Set Mr_Diggity's game mode to Creative Mode
14.05 20:37:45 [Server] Server thread/INFO Mr_Diggity has reached the goal [Buggy]
14.05 20:39:05 [Server] Netty Epoll Server IO #4/INFO [FML]: Disconnecting Player: This server has mods that require FML/Forge to be installed on the client: [BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, Extra Utilities 2, Galacticraft Core, Mantle, Tinkers' Construct]
14.05 20:40:05 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 4625ms behind, skipping 92 tick(s)
14.05 20:41:55 [Server] Server thread/INFO [Galacticraft]: Found matching world (-28) for name: -28
14.05 20:41:55 [Server] Server thread/INFO [Galacticraft]: Server attempting to transfer player Mr_Diggity to dimension -28
14.05 20:41:57 [Server] Server thread/INFO [Galacticraft]: Found matching world (-28) for name: -28
14.05 20:41:57 [Server] Server thread/INFO [Galacticraft]: Server attempting to transfer player MrDQ to dimension -28
14.05 20:43:04 [Multicraft] Auto-saving world...
14.05 20:43:04 [Server] Server thread/INFO Saving is already turned on
14.05 20:43:04 [Server] Server thread/INFO Saving...
14.05 20:43:05 [Server] Server thread/INFO [Server] World saved.
14.05 20:43:45 [Disconnect] User MrDQ has disconnected, reason: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
14.05 20:43:45 [Server] Server thread/INFO MrDQ left the game
14.05 20:44:30 [Server] User Authenticator #82/INFO UUID of player MrDQ is cc443e9e-86e1-440d-987d-9e5e5ec30ad1
14.05 20:44:30 [Server] Netty Epoll Server IO #5/INFO [FML]: Client protocol version 2
14.05 20:44:30 [Server] Netty Epoll Server IO #5/INFO [FML]: Client attempting to join with 20 mods : minecraft@1.12.2,tconstruct@1.12.2-2.12.0.115,galacticraftcore@4.0.2.277,buildcraftlib@7.99.24.1,mercurius_updater@1.0,FML@8.0.99.99,buildcraftsilicon@7.99.24.1,buildcraftcompat@7.99.24.1,buildcraftenergy@7.99.24.1,buildcrafttransport@7.99.24.1,galacticraftplanets@4.0.2.277,micdoodlecore@,forge@14.23.5.2847,extrautils2@1.0,mantle@1.12-1.3.3.55,buildcraftbuilders@7.99.24.1,mcp@9.42,buildcraftcore@7.99.24.1,buildcraftrobotics@7.99.24.1,buildcraftfactory@7.99.24.1
14.05 20:44:31 [Server] Server thread/INFO [FML]: [Server thread] Server side modded connection established
14.05 20:44:31 [Connect] User MrDQ, IP 73.144.126.34
14.05 20:44:31 [Server] Server thread/INFO MrDQ joined the game
14.05 20:44:31 [Multicraft] MrDQ ran command Message of the Day
14.05 20:45:08 [Server] Server thread/WARN [FML]: Galacticraft Core loaded a new chunk [-123, 37] in dimension -28 (moon.moon) while populating chunk [-124, 37], causing cascading worldgen lag.
14.05 20:45:08 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
14.05 20:45:08 [Server] Server thread/WARN [FML]: Galacticraft Core loaded a new chunk [-122, 37] in dimension -28 (moon.moon) while populating chunk [-123, 37], causing cascading worldgen lag.
14.05 20:45:08 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
14.05 20:45:08 [Server] Server thread/WARN [FML]: Galacticraft Core loaded a new chunk [-122, 36] in dimension -28 (moon.moon) while populating chunk [-123, 37], causing cascading worldgen lag.
14.05 20:45:08 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
14.05 20:45:08 [Server] Server thread/WARN [FML]: Galacticraft Core loaded a new chunk [-123, 36] in dimension -28 (moon.moon) while populating chunk [-124, 37], causing cascading worldgen lag.
14.05 20:45:08 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
14.05 20:47:31 [Server] Server thread/INFO Teleported MrDQ to Mr_Diggity
14.05 20:47:31 [Server] Server thread/WARN MrDQ moved too quickly! -20.675017514200363,9.96843719697808,-13.751464492677655
14.05 20:47:41 [Server] Server thread/WARN [FML]: Galacticraft Core loaded a new chunk [-121, 35] in dimension -28 (moon.moon) while populating chunk [-120, 35], causing cascading worldgen lag.
14.05 20:47:41 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
14.05 20:47:41 [Server] Server thread/WARN [FML]: Galacticraft Core loaded a new chunk [-122, 35] in dimension -28 (moon.moon) while populating chunk [-120, 35], causing cascading worldgen lag.
14.05 20:47:41 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
14.05 20:47:41 [Server] Server thread/WARN [FML]: Galacticraft Core loaded a new chunk [-119, 34] in dimension -28 (moon.moon) while populating chunk [-119, 35], causing cascading worldgen lag.
14.05 20:47:41 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
14.05 20:53:07 [Multicraft] Auto-saving world...
14.05 20:53:07 [Server] Server thread/INFO Saving is already turned on
14.05 20:53:07 [Server] Server thread/INFO Saving...
14.05 20:53:07 [Server] Server thread/INFO [Server] World saved.

Please provide screenshots / videos / full modlist as needed

BuildCraft, Extra-Utilities, Mantle, and Tinkers Construct.

![My Mods](https://user-images.githubusercontent.com/65377109/82001095-4c3ac680-9628-11ea-9281-f326cc9c17a7.png)

![Server Mods](https://user-images.githubusercontent.com/65377109/82001113-58bf1f00-9628-11ea-8f36-2c8c4d69adda.png)

![2020-05-14_20 59 52](https://user-images.githubusercontent.com/65377109/82001133-683e6800-9628-11ea-90d8-cf610c4c60d6.png)

Please state the site that you downloaded Galacticraft from:

https://micdoodle8.com/mods/galacticraft/downloads

**Comment by MJRLegends** [comment]
All your mods that are in the format XXXX-Mod-1.12.2 are all downloaded from a site that doesnt care about copyright and are promoting old versions download your mods from curseforge not a site that is doing illegal copyright infringement such as 9minecraft

**Comment by MJRLegends** [comment]
This could be part of your issue your having here
