### ISSUE TITLE
TileEntitySolar causes excessive chunkloading

### ISSUE THREAD

**Issue by clienthax** [micdoodle8/Galacticraft#3992]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option): GalacticraftCore-1.12.2-4.0.2.244.jar

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)? Sponge MP

Any Galacticraft add-ons installed? Please list all of them: Galacticraft-Planets-1.12.2-4.0.2.244.jar

It seems there is no loaded check when the tile checks if the sky is clear, so if a solar panel is on the edge of a loaded chunk, but the block check extends into an unloaded chunk, will cause the tile to excessively load the chunk just for it to be unloaded again.

```
Chunks loaded 3823   [-]
	at org.spongepowered.common.util.SpongeHooks.logStack(SpongeHooks.java:107) [SpongeHooks.class:1.12.2-2838-7.2.2-RC0]
	at org.spongepowered.common.util.SpongeHooks.logChunkLoad(SpongeHooks.java:206) [SpongeHooks.class:1.12.2-2838-7.2.2-RC0]
	at net.minecraft.world.chunk.Chunk.handler$zma000$impl$UpdateNeighborsOnLoad(Chunk.java:3551) [axw.class:?]
	at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:863) [axw.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.redirect$zmd000$impl$ProvideChunkForced(ChunkProviderServer.java:1642) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.world.World.getChunk(World.java:310) [amu.class:?]
	at micdoodle8.mods.galacticraft.api.vector.BlockVec3.getBlockState(BlockVec3.java:136) [BlockVec3.class:?]
	at micdoodle8.mods.galacticraft.core.tile.TileEntitySolar.update(TileEntitySolar.java:164) [TileEntitySolar.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237) [!!!!!!!spongeforge-1.12.2-2838-7.2.2-RC0--haxy.jar:1.12.2-2838-7.2.2-RC0]
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4726) [oo.class:?]
	at net.minecraft.world.WorldServer.redirect$zlj000$onUpdateTileEntities(WorldServer.java:4710) [oo.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1838) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:3928) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by MJRLegends** [comment]
Please test with latest Galacticraft

**Comment by clienthax** [comment]
> Please test with latest Galacticraft

Not sure why that would make any difference when that code hasn't been touched since 2019, baring import cleanup.

**Comment by MJRLegends** [comment]
It makes a difference tbh

**Comment by clienthax** [comment]
> It makes a difference tbh

I highly doubt it does in this case, BlockVec3 hasn't been touched since 2017, and TileEntitySolar since 2019, I get wanting to test bugs on the latest version, but its fairly obvious this wont make any difference here.

Similar patch made by me to a mod doing the same thing if you want to check https://github.com/P3pp3rF1y/Reliquary/pull/433/files
