### ISSUE TITLE
TileBaseElectricBlockWithInventory: method <init>()V not found

### ISSUE THREAD

**Issue by Dreamcastering** [micdoodle8/Galacticraft#3998]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.280

Single player (SP)

Galacticraft add-on with version i got:
GalacticraftTweaker-1.12.2-1.0.3
GalacticTweaks-1.12.2-0.0.2-[13]
SpaceAmbient-1.12.2-0.0.1
spacecraftx-1.12.2-1.0.35
More-Planets-1.12.2-2.0.24-GC251
MorePlanetsExtras-1.12.2-1.0

I downloaded Galacticraft from [Micdoodle8](http://micdoodle8.com)
I downloaded the add-on from [Twitch](https://www.twitch.tv/)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280 (1).jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 6/9/20 5:41 PM
Description: Initializing game

java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory: method <init>()V not found
	at fr.militario.spacex.tiles.TileEntityOxygenLoader.<init>(TileEntityOxygenLoader.java:54)
	at fr.militario.spacex.blocks.BlockOxygenLoader.createTileEntity(BlockOxygenLoader.java:55)
	at fr.militario.spacex.items.ItemBlockDesc.func_77624_a(ItemBlockDesc.java:86)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$2614/1797707876.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$2637/1524030567.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-----------------------------------------------------------------------------------------------
if mod list needed plz tell me

**Comment by MJRLegends** [comment]
spacecraftx-1.12.2-1.0.35 needs updating for Galacticraft changes

**Comment by Dreamcastering** [comment]
ok thx for the info
