### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Wountie** [micdoodle8/Galacticraft#4009]
Hello, so i want to start minecraft with these mods but it keeps crashing when its not even on the main screen :/.
I don't know what to do so please help me.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280 (2).jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 6/28/20 4:13 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
	at com.mjr.extraplanets.util.GCRecipeUtilities.addSpaceStationRecipe(GCRecipeUtilities.java:20)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.registerSatellitesRecipes(ExtraPlanets_Recipes.java:331)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.initOther(ExtraPlanets_Recipes.java:33)
	at com.mjr.extraplanets.ExtraPlanets.init(ExtraPlanets.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 366000704 bytes (349 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                     | Source                                    | Signature                                |
	|:----- |:------------------- |:--------------------------- |:----------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft           | 1.12.2                      | minecraft.jar                             | None                                     |
	| LCHI  | mcp                 | 9.42                        | minecraft.jar                             | None                                     |
	| LCHI  | FML                 | 8.0.99.99                   | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCHI  | forge               | 14.23.5.2847                | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCHI  | micdoodlecore       |                             | minecraft.jar                             | None                                     |
	| LCHI  | ambience            | GRADLE:VERSION-GRADLE:BUILD | Ambience+1.1-10.jar                       | None                                     |
	| LCHI  | galacticraftcore    | 4.0.2.280                   | GalacticraftCore-1.12.2-4.0.2.280.jar     | None                                     |
	| LCHI  | galacticraftplanets | 4.0.2.280                   | Galacticraft-Planets-1.12.2-4.0.2.280.jar | None                                     |
	| LCHI  | asmodeuscore        | 0.0.15                      | AsmodeusCore-1.12.2-0.0.15.jar            | None                                     |
	| LCHI  | buildcraftlib       | 7.99.24.6                   | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCHI  | buildcraftcore      | 7.99.24.6                   | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCHI  | buildcraftbuilders  | 7.99.24.6                   | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCHI  | buildcrafttransport | 7.99.24.6                   | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCHI  | buildcraftsilicon   | 7.99.24.6                   | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCHI  | buildcraftcompat    | 7.99.24.6                   | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCHI  | buildcraftenergy    | 7.99.24.6                   | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCHI  | buildcraftfactory   | 7.99.24.6                   | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCHI  | buildcraftrobotics  | 7.99.24.6                   | buildcraft-all-7.99.24.6.jar              | None                                     |
	| LCHI  | mjrlegendslib       | 1.12.2-1.1.9                | MJRLegendsLib-1.12.2-1.1.9.jar            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHE  | extraplanets        | 1.12.2-0.6.4                | ExtraPlanets-1.12.2-0.6.4.jar             | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | galaxyspace         | 2.0.11                      | GalaxySpace-1.12.2-2.0.11.jar             | None                                     |
	| LCH   | journeymap          | 1.12.2-5.7.1                | journeymap-1.12.2-5.7.1.jar               | None                                     |
	| LCH   | moreplanets         | 2.0.24                      | More-Planets-1.12.2-2.0.24-GC251.jar      | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCH   | uteamcore           | 2.2.5.147                   | u_team_core-1.12.2-2.2.5.147.jar          | None                                     |
	| LCH   | musicplayer         | 2.0.8.77                    | music_player-1.12.2-2.0.8.77.jar          | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280 (2).jar)
  micdoodle8.mods.miccore.MicdoodleTransformer

**Comment by MJRLegends** [comment]
Says the crash cause and fix in crash log

Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

**Comment by Wountie** [comment]
> Says the crash cause and fix in crash log
> 
> Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

thnx ill try it :)
