### ISSUE TITLE
Minecraft went Crash Bandicoot on me. :(

### ISSUE THREAD

**Issue by joey-lg** [micdoodle8/Galacticraft#4010]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:
Galacticraft version ("latest" is not a valid option):

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? Please list all of them:

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  FMLModule (mdxlib-3.0.0.26.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 6/30/20 3:03 PM
Description: Initializing game

java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory: method <init>()V not found
	at fr.militario.spacex.tiles.TileEntityOxygenLoader.<init>(TileEntityOxygenLoader.java:54)
	at fr.militario.spacex.blocks.BlockOxygenLoader.createTileEntity(BlockOxygenLoader.java:55)
	at fr.militario.spacex.items.ItemBlockDesc.func_77624_a(ItemBlockDesc.java:86)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$339/1958633370.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$344/254213829.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at fr.militario.spacex.tiles.TileEntityOxygenLoader.<init>(TileEntityOxygenLoader.java:54)
	at fr.militario.spacex.blocks.BlockOxygenLoader.createTileEntity(BlockOxygenLoader.java:55)
	at fr.militario.spacex.items.ItemBlockDesc.func_77624_a(ItemBlockDesc.java:86)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$339/1958633370.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$344/254213829.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 640938976 bytes (611 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                    | Signature                                |
	|:----- |:------------------- |:----------------- |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2            | minecraft.jar                             | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                             | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCH   | forge               | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCH   | micdoodlecore       |                   | minecraft.jar                             | None                                     |
	| LCH   | securitycraft       | v1.8.18.2         | [1.12.2]+SecurityCraft+v1.8.18.2.jar      | None                                     |
	| LCH   | mdxlib              | 3.0.0.26          | mdxlib-3.0.0.26.jar                       | None                                     |
	| LCH   | avp                 | 6.0.0.60          | aliensvspredator-6.0.0.60.jar             | None                                     |
	| LCH   | galacticraftcore    | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar     | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.280         | Galacticraft-Planets-1.12.2-4.0.2.280.jar | None                                     |
	| LCH   | mjrlegendslib       | 1.12.2-1.1.9      | MJRLegendsLib-1.12.2-1.1.9.jar            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | spacecraftx         | 1.0.35            | spacecraftx-1.12.2-1.0.35.jar             | None                                     |
	| LCH   | extraplanets        | 1.12.2-0.6.4      | ExtraPlanets-1.12.2-0.6.4.jar             | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | hbm                 | hbm-1.3.3A-1.12.2 | hbm-1.3.3a.jar                            | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
FMLModule (mdxlib-3.0.0.26.jar)
  com.asx.mdx.AccessTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Please provide screenshots / videos / full modlist as needed
![Capture1](https://user-images.githubusercontent.com/62820134/86166936-a19d3b00-bae3-11ea-8f6c-44ed4146afe0.PNG)

Please state the site that you dowdnloaded Galacticraft from:
Official download from mcdoodle site.

**Comment by MJRLegends** [comment]
Spacecraftx mod needs updating for Galacticraft new versions
