### ISSUE TITLE
Compatibility with chicken libcore and middoodle core problem

### ISSUE THREAD

**Issue by Onilinkblue** [micdoodle8/Galacticraft#4017]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:
Galacticraft version ("latest" is not a valid option):

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? Please list all of them:

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:

Please provide screenshots / videos / full modlist as needed

Please state the site that you downloaded Galacticraft from: https://micdoodle8.com/mods/galacticraft/downloads

Crash report : ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/7/20 9:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 662175928 bytes (631 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                             | Signature                                |
	|:----- |:------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                                      | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCH   | forge               | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCH   | micdoodlecore       |                   | minecraft.jar                                      | None                                     |
	| LCE   | codechickenlib      | 3.2.3.357         | CodeChickenLib-1.12.2-3.2.3.357-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux        | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LC    | brandonscore        | 2.4.18            | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
	| LC    | cofhcore            | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LC    | cofhworld           | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LC    | thermalfoundation   | 2.6.7             | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LC    | draconicevolution   | 2.3.25            | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
	| LC    | cfm                 | 6.3.1             | furniture-6.3.1-1.12.2.jar                         | None                                     |
	| LC    | mantle              | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LC    | jei                 | 4.15.0.297        | jei_1.12.2-4.15.0.297.jar                          | None                                     |
	| LC    | tconstruct          | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LC    | galacticraftcore    | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar              | None                                     |
	| LC    | galacticraftplanets | 4.0.2.280         | Galacticraft-Planets-1.12.2-4.0.2.280.jar          | None                                     |
	| LC    | geneticsreborn      | 1.28              | geneticsreborn-1.12-1.28.jar                       | None                                     |
	| LC    | minions             | 2.0.3             | Minions-1.12.2.jar                                 | None                                     |
	| LC    | statues             | 0.8.9.2           | statues-1.12.X-0.8.9.2.jar                         | None                                     |
	| LC    | thermalexpansion    | 5.5.7             | ThermalExpansion-1.12.2-5.5.7.1-universal (1).jar  | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 9200/integrated/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

I can't get chicken libcore with micdoodlecore together in my mod file.

**Comment by dj3520** [comment]
Not a GC issue. Your CodeChicken Lib configuration is invalid.
