### ISSUE TITLE
the crash report about ic2 on server

### ISSUE THREAD

**Issue by StarskyXIII** [micdoodle8/Galacticraft#4061]
When I put ic2 in my server,server will be crash
sorry my bad English.

This is my  crash report

---- Mohist Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
Contact their authors BEFORE contacting forge

Time: 2020/9/21 上午 2:32
Description: 處理「server tick loop」時出現異常

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Core (galacticraftcore)
Caused by: java.lang.NoClassDefFoundError: micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed
	at micdoodle8.mods.galacticraft.core.GCBlocks.initBlocks(GCBlocks.java:154)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:632)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:215)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:132)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:632)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:102)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:329)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:171)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593)
	at java.lang.Thread.run(Thread.java:823)
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.core.energy.tile.TileCableIC2Sealed
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	... 38 more
Caused by: java.lang.VerifyError: JVMVRFY007 final 方法置換；類別=micdoodle8/mods/galacticraft/core/energy/tile/TileCableIC2Sealed，方法=func_145829_t()V，PC=0
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Mohist version: 1.12.2-36
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_265, Eclipse OpenJ9
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200728_776 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01), Eclipse OpenJ9
	Memory: 3123888320 bytes (2979 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 11 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-openj9\jre\bin\compressedrefs\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xmx4096M -Xms4096M -Xss512K -Xaggressive -Xalwaysclassgc -XcompilationThreads4 -Xconmeter:dynamic -Xshareclasses
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport: craftbukkit not runs

	FML: MCP 9.42 Powered by Forge 14.23.5.2854 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version       | Source                                    | Signature                                |
	|:----- |:------------------- |:------------- |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2        | minecraft.jar                             | None                                     |
	| LCH   | mcp                 | 9.42          | minecraft.jar                             | None                                     |
	| LCH   | mohist              | 1.12.2-36     | mohist.jar                                | None                                     |
	| LCH   | FML                 | 8.0.99.99     | mohist-1.12.2-36-server.jar               | None                                     |
	| LCH   | forge               | 14.23.5.2854  | mohist-1.12.2-36-server.jar               | None                                     |
	| LCH   | micdoodlecore       |               | minecraft.jar                             | None                                     |
	| LCH   | ic2                 | 2.8.220-ex112 | industrialcraft-2-2.8.220-ex112.jar       | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCE   | galacticraftcore    | 4.0.2.280     | GalacticraftCore-1.12.2-4.0.2.280.jar     | None                                     |
	| LC    | galacticraftplanets | 4.0.2.280     | Galacticraft-Planets-1.12.2-4.0.2.280.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'Mohist'
	Type: Dedicated Server (map_server.txt)

**Comment by dj3520** [comment]
Mohist looks like a Thermos/Kettle/Cauldron/MCPC+successor.
