### ISSUE TITLE
Galacticraft crashes game when going to space, corrupts world

### ISSUE THREAD

**Issue by C7R15** [micdoodle8/Galacticraft#4073]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option): 4.0.2.255

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)? LAN
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? Please list all of them: Extra Planets, Galacticraft Planets

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MineFactoryReloaded Core (MineFactoryReloaded-core-1.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.255.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 10/30/20 11:16 AM
Description: Rendering screen

java.lang.NoSuchFieldError: ticksSinceSelectionF
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.drawCustomButtons(CustomCelestialSelection.java:431)
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.drawButtons(CustomCelestialSelection.java:473)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73863_a(GuiCelestialSelection.java:1212)
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.func_73863_a(CustomCelestialSelection.java:1026)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Please provide screenshots / videos / full modlist as needed
[Twitch 2020-10-30 11-35-32.zip](https://github.com/micdoodle8/Galacticraft/files/5466064/Twitch.2020-10-30.11-35-32.zip)

Please state the site that you downloaded Galacticraft from: Micdoodle

**Comment by C7R15** [comment]
I updated, still didn't work, and then reinstalled and still crashes and corrupts the world. I tried updating all mods in my pack and forge, and then reinstalling again. not sure if it works this time, haven't tried it yet

**Comment by C7R15** [comment]
Not sure what fixed it, but it works now. Thank you
