### ISSUE TITLE
game crashes when in survival on space station 

### ISSUE THREAD

**Issue by Lex101YT** [micdoodle8/Galacticraft#4086]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_21.19.0_Forge_1.12.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 1/8/22 8:15 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at asmodeuscore.core.event.AsmodeusEvent.doRadiatoinForEntity(AsmodeusEvent.java:243)
	at asmodeuscore.core.event.AsmodeusEvent.onEntityUpdate(AsmodeusEvent.java:155)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_134_AsmodeusEvent_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at asmodeuscore.core.event.AsmodeusEvent.doRadiatoinForEntity(AsmodeusEvent.java:243)
	at asmodeuscore.core.event.AsmodeusEvent.onEntityUpdate(AsmodeusEvent.java:155)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_134_AsmodeusEvent_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 546
	Entity Name: Lex101YT
	Entity's Exact location: 0.50, 65.00, 0.50
	Entity's Block location: World: (0,65,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@48414d0e
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 902342136 bytes (860 MB) / 1811939328 bytes (1728 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version        | Source                                        | Signature                                |
	|:------ |:-------------------- |:-------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2         | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                  | 9.42           | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99      | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2855   | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore        |                | minecraft.jar                                 | None                                     |
	| LCHIJA | xaerominimap_core    | 1.12.2-1.0     | minecraft.jar                                 | None                                     |
	| LCHIJA | galacticraftcore     | 4.0.2.280      | GalacticraftCore-1.12.2-4.0.2.280.jar         | None                                     |
	| LCHIJA | galacticraftplanets  | 4.0.2.280      | Galacticraft-Planets-1.12.2-4.0.2.280.jar     | None                                     |
	| LCHIJA | asmodeuscore         | 0.0.28         | AsmodeusCore-1.12.2-0.0.28.jar                | None                                     |
	| LCHIJA | biomesoplenty        | 7.0.1.2444     | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCHIJA | codechickenlib       | 3.2.3.358      | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | extendedrenderer     | v1.0           | coroutil-1.12.1-1.2.37.jar                    | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.37  | coroutil-1.12.1-1.2.37.jar                    | None                                     |
	| LCHIJA | configmod            | v1.0           | coroutil-1.12.1-1.2.37.jar                    | None                                     |
	| LCHIJA | damageindicatorsmod  | 1.0            | Damage-Indicators-Mod-1.12.2.jar              | None                                     |
	| LCHIJA | sereneseasons        | 1.2.18         | SereneSeasons-1.12.2-1.2.18-universal.jar     | None                                     |
	| LCHIJA | orelib               | 3.6.0.1        | OreLib-1_12_2.jar                             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround            | 3.6.1.0        | DynamicSurroundings-1.12.2-3.6.1.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | jei                  | 4.16.1.302     | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LCHIJA | weather2             | 1.12.1-2.6.12  | weather2-1.12.1-2.6.12.jar                    | None                                     |
	| LCHIJA | worldedit            | 6.1.8          | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| LCHIJA | xaerominimap         | 21.19.0        | Xaeros_Minimap_21.19.0_Forge_1.12.jar         | None                                     |
	| LCHIJA | zombieawareness      | 1.12.1-1.11.16 | zombieawareness-1.12.1-1.11.16.jar            | None                                     |
	| LCHIJA | immersiveengineering | 0.12-92        | ImmersiveEngineering-0.12-92.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_21.19.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['Lex101YT'/546, l='New World', x=0.50, y=65.00, z=0.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by TheQuadShot** [comment]
To me it looks like you're missing the Galaxy Space mod, since the mod that is causing the crash is asmodeuscore which is the core mod for Galaxy Space, and I don't see it listed in your mod load list.

**Comment by ROMVoid95** [comment]
@Lex101YT remove AsmodeusCore or add GalaxySpace. Closing as this is not an issue with Galacticraft
