### ISSUE TITLE
Crash with Animated Player mod and Animated API

### ISSUE THREAD

**Issue by crunkazcanbe** [micdoodle8/Galacticraft#461]
I am using version 2.0.13.1080 of Galacticraft with the last Animated player v1.3.0 mod made for 1.6.4 and Anamated API v1.1.2 and ImprovedFirstPerson 1.6.4 r1 version for 1.6.4 This crash happens as soon as I load a world.

java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.client.render.entities.GCCoreRenderPlayer cannot be cast to thehippomaster.AnimatedPlayer.client.RenderPlayer
    at kes5219.improvedfirstperson.hooks.AnimatedPlayerCamera.doAnimatedPlayerTransforms(AnimatedPlayerCamera.java:12)
    at kes5219.improvedfirstperson.hooks.AfterCameraTransformation.afterCameraTransform(AfterCameraTransformation.java:124)
    at net.minecraft.client.renderer.EntityRenderer.func_78479_a(EntityRenderer.java:725)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1452)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1119)
    at net.minecraft.src.EntityRendererProxy.func_78480_b(EntityRendererProxy.java:39)
    at weather2.weathersystem.EntityRendererProxyWeather2Mini.func_78480_b(EntityRendererProxyWeather2Mini.java:52)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by potatom4n** [comment]
i dont use galacticraft i have 12GB of ram and it crashes

**Comment by potatom4n** [comment]
it crashes at step 5

**Comment by MJRLegends** [comment]
Unless its a issue in MC 1.7.10 we won't be able to help you. MC 1.6.4 is very old and unsupported
