### ISSUE TITLE
[1.7] Incomplete code injection + crash

### ISSUE THREAD

**Issue by ghost** [micdoodle8/Galacticraft#887]
This is on  3.0.1 build 170

First we have this.

```
Potential problem: Galacticraft did not complete injection of bytecode into: oi (4 / 6)
Galacticraft successfully injected bytecode into: sv (1 / 1)
Potential problem: Galacticraft did not complete injection of bytecode into: sa (0 / 1)
Galacticraft successfully injected bytecode into: xk (1 / 1)
```

Then, sometimes we have this crash during runtime

```
[14:37:44 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:932) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:422) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:803) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.lang.IllegalArgumentException
        at net.minecraft.util.WeightedRandom.func_76273_a(WeightedRandom.java:28) ~[qv.class:?]
        at net.minecraft.util.WeightedRandom.func_76271_a(WeightedRandom.java:60) ~[qv.class:?]
        at net.minecraft.world.WorldServer.func_73057_a(WorldServer.java:305) ~[mt.class:?]
        at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:185) ~[aho.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:247) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:916) ~[MinecraftServer.class:?]
        ... 4 more
[14:37:44 ERROR]:       Cause of unexpected exception was
java.lang.IllegalArgumentException
        at net.minecraft.util.WeightedRandom.func_76273_a(WeightedRandom.java:28) ~[qv.class:?]
        at net.minecraft.util.WeightedRandom.func_76271_a(WeightedRandom.java:60) ~[qv.class:?]
        at net.minecraft.world.WorldServer.func_73057_a(WorldServer.java:305) ~[mt.class:?]
        at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:185) ~[aho.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:247) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:916) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:422) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:803) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
```

**Comment by trismegistis** [comment]
Hi Kerai, was wondering if you ever indentified the cause of your crashes. My server is doing this same crash, but not in a galacticraft planet, in the overworld, and always at a very specific chunk..
