### ISSUE TITLE
Crash when Loading up World

### ISSUE THREAD

**Issue by foreverblu** [micdoodle8/Galacticraft#952]
---- Minecraft Crash Report ----
// Oops.

Time: 14-9-3 下午5:28
Description: Starting integrated server

java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/player/GCEntityPlayerMP
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:52)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2079)
    at cpw.mods.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:669)
    at net.minecraft.client.gui.GuiSelectWorld.func_146615_e(GuiSelectWorld.java:183)
    at net.minecraft.client.gui.GuiSelectWorld$List.func_148144_a(GuiSelectWorld.java:257)
    at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:209)
    at net.minecraft.client.gui.GuiSelectWorld.func_73863_a(GuiSelectWorld.java:216)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 17 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at micdoodle8.mods.miccore.MicdoodleTransformer.startInjection(MicdoodleTransformer.java:1722)
    at micdoodle8.mods.miccore.MicdoodleTransformer.transformCustomAnnotations(MicdoodleTransformer.java:865)
    at micdoodle8.mods.miccore.MicdoodleTransformer.transform(MicdoodleTransformer.java:284)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174)
    ... 19 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:52)

-- Starting integrated server --
Details:
    Level ID: Stuffz
    Level Name: Stuffz
Stacktrace:
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2079)
    at cpw.mods.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:669)
    at net.minecraft.client.gui.GuiSelectWorld.func_146615_e(GuiSelectWorld.java:183)
    at net.minecraft.client.gui.GuiSelectWorld$List.func_148144_a(GuiSelectWorld.java:257)
    at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:209)
    at net.minecraft.client.gui.GuiSelectWorld.func_73863_a(GuiSelectWorld.java:216)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.GuiMainMenu
    Mouse location: Scaled: (191, 98). Absolute: (573, 604)
    Screen size: Scaled: (480, 300). Absolute: (1440, 900). Scale factor of 3
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 154270808 bytes (147 MB) / 268713984 bytes (256 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.18.1180 Minecraft Forge 10.13.0.1180 5 mods loaded, 5 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.18.1180} [Forge Mod Loader](forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.0.1180} [Minecraft Forge](forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.1.7} [Baubles](Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.7.10-Forge10.13.0.1180
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [faithful32packOptiFine.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (16)
```

**Comment by PamonhaAp** [comment]
what was the problem ?
