### ISSUE TITLE
CRash it can be by any other mods but how i can fix it?

### ISSUE THREAD

**Issue by Dokman** [micdoodle8/Galacticraft#958]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 06/09/14 12:32
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: glass_pane
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: glass_pane
    at micdoodle8.mods.galacticraft.core.util.ConfigManagerCore.syncConfig(ConfigManagerCore.java:168)
    at micdoodle8.mods.galacticraft.core.util.ConfigManagerCore.initialize(ConfigManagerCore.java:99)
    at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:113)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_05, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 127925408 bytes (121 MB) / 314580992 bytes (300 MB) up to 6429081600 bytes (6131 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.25.1208 Minecraft Forge 10.13.0.1208 Optifine OptiFine_1.7.10_HD_U_A4 20 mods loaded, 20 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.25.1208} [Forge Mod Loader](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.0.1208} [Minecraft Forge](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.3.25} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.51} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.51-universal.jar) Unloaded->Constructed->Pre-initialized
    advancedgenetics{1.5.7} [Advanced Genetics](advancedgenetics-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    Aquaculture{1.2.3} [Aquaculture](Aquaculture-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.7.5} [BiblioCraft](BiblioCraft[v1.7.5][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    AWWayofTime{v1.2.0Beta18} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.2.0Beta18%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    bunkermod{1.1} [Bunker Mod](Bunker-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Chimneys{1.7.2} [Chimneys](Chimneys-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    dextend{1.0.0} [D-Extend](dextend-1.0.0.jar) Unloaded->Constructed->Pre-initialized
    DragonMounts{r39} [Dragon Mounts](Dragon-Mounts-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    evilcraft{0.5.2b} [EvilCraft](EvilCraft-1.7.10-0.5.2b.jar) Unloaded->Constructed->Pre-initialized
    GalacticraftCore{3.0.1} [Galacticraft Core](GalacticraftCore-Dev-BETA-1.7-3.0.1.8.jar) Unloaded->Constructed->Errored
    GalacticraftMars{3.0.1} [Galacticraft Planets](Galacticraft-Planets-Dev-BETA-1.7-3.0.1.8.jar) Unloaded->Constructed->Errored
    Kradxns Minimap{2.0} [Minimap](Kradxn-X-ray-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.7} [Baubles](Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.0.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    voxelmap{1.7.10} [VoxelMap No Radar](voxelmapNoRadar-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized

**Comment by trismegistis** [comment]
Hi.. theres a crash fix in a dev build that isnt in the latest.. how can I get the latest dev build not in dev format?
